### ISSUE TITLE
Why does the FeedForward have three linear layer?

### ISSUE THREAD

**Issue by CarkusL** [facebookresearch/llama#1004]
I find that the FFN implementation has three linear layers.

https://github.com/facebookresearch/llama/blob/ef351e9cd9496c579bf9f2bb036ef11bdc5ca3d2/llama/model.py#L337-L345

But in the paper "Attention Is All You Need", FFN only has two linear layer. 
![image](https://github.com/facebookresearch/llama/assets/23131205/062e641e-1df7-4375-b088-f95e4d97b59b)

**Comment by wjwzju** [comment]
Because llama uses SwiGLU instead of relu。SwiGLU(x,W,V,b,c) = Swish(xW+b) ⊗ (xV+c)

**Comment by CarkusL** [comment]
> Because llama uses SwiGLU instead of relu。SwiGLU(x,W,V,b,c) = Swish(xW+b) ⊗ (xV+c)

thank you.
