### ISSUE TITLE
OSError: Not found: "./llama-2-7b-chat/tokenizer.model": Too many levels of symbolic links Error #40

### ISSUE THREAD

**Issue by jiazi1** [facebookresearch/llama#1008]
When following the https://ai.meta.com/blog/5-steps-to-getting-started-with-llama-2/ and running step 2
`python $TRANSFORM --input_dir ./llama-2-7b-chat --model_size 7B --output_dir ./llama-2-7b-chat-hf`

Got the error 
** OSError: Not found: "./llama-2-7b-chat/tokenizer.model": Too many levels of symbolic links Error #40 **

How to fix it?

**Comment by fbnav** [comment]
It looks like the tokenizer.model file could not be found in the directory `./llama-2-7b-chat`. Could you confirm if you were able to run `ln -h ./tokenizer.model ./llama-2-7b-chat/tokenizer.model` to create the link to the tokenizer? 

If you tried that and still got this error,  could you try removing the symbolic link and copying the tokenizer.model file directly into the `./llama-2-7b-chat` directory by running `cp tokenizer.model ./llama-2-7b-chat/tokenizer.model` and re-running the command?

**Comment by purejomo** [comment]
if tokenizer.model is not created, in dir "./llama-2-7b-chat/tokenizer.model"
could you let me know how to fix it?

**Comment by purejomo** [comment]
`ln -h ./tokenizer.model ./llama-2-7b-chat/tokenizer.model`
is not working, 
`ln -h` is not proper command
so I used `ln -s  ./tokenizer.model ./llama-2-7b-chat/tokenizer.model`
Is this the reason why I encountered this error "OSError: Not found: "./llama-2-7b-chat/tokenizer.model": Too many levels of symbolic links Error #40"
