### ISSUE TITLE
HTTP request sent, awaiting response... 403 Forbidden

### ISSUE THREAD

**Issue by a2012456373** [facebookresearch/llama#102]
I accidentally deleted the tokenizer.model when I started download.sh. When I repeated the download, it had already been 403 forbidden, so it could not be downloaded (maybe the download link can only be executed twice). Could you please send the tokenizer.model file separately?

**Comment by Inserian** [comment]
The link is valid for 7 days with unlimited executions. I would just delete and re-do.

**Comment by a2012456373** [comment]
The first two download executions were fine, and the third time 403 forbidden appeared

**Comment by Inserian** [comment]
That sounds like just an error with how the link is input in the download.sh
The weights link should be fine, just check your brackets and values. If it still gives you the same issue, contact llama and have them send you a new link.

**Comment by a2012456373** [comment]
I think the problem is link, because I downloaded the same download.sh for the first time without any problem, and also for the second time. All my files were downloaded, but I accidentally ran download.sh again, overwriting the files I downloaded before. And because the HTTP request sent, awaiting response... 403 Forbidden causes that the overwritten files are empty. The three download.sh runs were completely unmodified, except that the first and second runs were on two different computers.
![image](https://user-images.githubusercontent.com/76865636/222938215-eac0015b-5507-41f0-9eb6-8aec639a6421.png)

**Comment by a2012456373** [comment]
@Inserian  The problem has been solved.

**Comment by a2012456373** [comment]
@Nicole-Yi You can download the leaked file on huggingface

**Comment by Nicole-Yi** [comment]
@a2012456373 is that still alive? Thanks a lot!

**Comment by Nicole-Yi** [comment]
@a2012456373, if there exists the link?
