### ISSUE TITLE
Can not submit a requst.

### ISSUE THREAD

**Issue by richardlzluo** [facebookresearch/llama#1037]
I am submitting a request to download the model. But as I click the "Accept and Continue" button, it says "There was an error submitting your email address.". I tried several email addresses, including my Gmail and university mail, and the results were the same. 

So I just can't submit the request. Does anyone have the same issue as me?

**Comment by edwardqin-creator** [comment]
How did you solve it? I met the same situation.

**Comment by richardlzluo** [comment]
Are you using a proxy. I finally solve it after I turn off my proxy setting.
