### ISSUE TITLE
Is there a possibilty to offload the model to ram?

### ISSUE THREAD

**Issue by CyberTimon** [facebookresearch/llama#108]
Hello!
I really want to test out the 7b model. Is there any option to offload it to ram?
My GPU is a rtx 3070ti with 8gb vram and I have 32gb ram.
With KoboldAi I was able to run GPT J 6b by splitting half to ram. Is or will this be possible for these kind of models or just load it in ram? I know it will be slow but I have no problem with this
Thanks

**Comment by MiuGod0126** [comment]
Hello, I tried using the paddle framework for cpu inference, however it takes 20 minutes. To save memory, I divided all the weights into separate Numpy files and loaded each one into the model one at a time.  I hope this helps.  [ppllama](https://github.com/MiuGod0126/ppllama)

**Comment by CyberTimon** [comment]
Thank you very much! Did I read correctly that I have to wait 20 minute for inference?

**Comment by CyberTimon** [comment]
Splitting half on gpu and other half on ram doesn't work? Because GPT J was quite fast. (1-2 tokens / sec)

**Comment by gmorenz** [comment]
Yes, here's my fork where I did this https://github.com/gmorenz/llama/tree/gpu_offload

**Comment by iaalm** [comment]
I tested 7B model with batch size 2 and it takes 15-17GB of GPU memory. The `example.py` use a much larger batch size and may need 40GB GPU memory.

**Comment by CyberTimon** [comment]
Closing as text generation webui does all of this and even gpt q 4bit
