### ISSUE TITLE
I got the access but have no clue how to download. Please help me.

### ISSUE THREAD

**Issue by LoneLon1** [facebookresearch/llama#110]
Could someone please be so kind as to help me? I received an email with a URL, but I'm not sure how to download the contents. I have limited knowledge and I think I need a Linux terminal, but I only have a PC. Would someone please explain how I can download this? Thank you so much in advance!

**Comment by Inserian** [comment]
You need to understand linux environments, python, cuda and a few other things in order to understand how to compile Llama. The link that was sent to you is to be placed in the download.sh file so you can access the distributions by running it in your given environment.

**Comment by dsoselia** [comment]
More specifically, you should modify the PRESIGNED_URL assignment line in download.sh by pasting the link you received. Then run the sh file (source download.sh). Note that downloading all models takes a significant amount of storage (100GB+) and you also need a lot of video memory to run it on a GPU.
