### ISSUE TITLE
UnicodeEncodeError: 'latin-1' codec can't encode character '\u201c' in position 992: ordinal not in range(256)

### ISSUE THREAD

**Issue by AIWithShrey** [facebookresearch/llama#119]
I keep running into this error. I realise that there are certain characters that can't be encoded properly. I did some digging around and tried changing the codec but it didn't work. 

I'm trying to execute the command: `torchrun example.py 7B tokenizer.model`

**Comment by AIWithShrey** [comment]
What's interesting is that when I remove most of the examples and keep only the first three prompts, everything works as expected.

**Comment by anirudhssundar** [comment]
I was able to resolve this by setting my locale to use utf-8. I found this answer helpful (https://stackoverflow.com/a/35508945)
