### ISSUE TITLE
Anyone able to run 7B on google colab?

### ISSUE THREAD

**Issue by andrewmlu** [facebookresearch/llama#120]
Interested to see if anyone is able to run on google colab. Seems like 16 GB should be enough and is granted often for colab free. Not sure if Colab Pro should do anything better, but if anyone is able to, advice would be much appreciated.

**Comment by reycn** [comment]
Not for free users. The model must be loaded into the CPU memory but Colab only provides a capacity of less than 13G. Therefore, it cannot be run on the free version of Colab. 

However, it may work if you have a Pro subscription. I look forward to hearing about your outcome.

**Comment by Daviljoe193** [comment]
What about loading it onto the TPU? KoboldAI can load 20B models (Like Erebus 20B) just fine to TPU, barring the fact it takes about 15 minutes to load a 40~ GB model, which Erebus specifically is split into 23 parts.

**Comment by pauldog** [comment]
I got it to run on a Shadow PC #105 which has only 12GB RAM.  So it crunched the page file a fair bit. But still loaded the model in about 110 seconds. As it clears the RAM after moving it to the GPU.  

So it can work on a computer with less than 14GB RAM, but perhaps Google Colab doesn't have a page file? IDK.

**Comment by brendan-donohoe** [comment]
Since colab gives you more GPU VRAM than RAM, what you'll want to do is load the checkpoint into CUDA rather than CPU. Once I'd done that, split the model dict on the layers, saved the sharded model, and then in another run, sequentially loaded each shard onto the GPU afterward. Once you do this, it should work.

**Comment by andrewmlu** [comment]
Update: able to run on google colab pro. Seems 12 GB of ram is the issue.

**Comment by brendan-donohoe** [comment]
Here's a notebook that goes through the steps I just mentioned and works for me using colab pro's standard GPU (~15 GB VRAM) and regular RAM runtime (~12.7 GB RAM), which I think is identical to the free version but I'm not completely certain. If the free colab gives less than the pro standard, it may indeed be impossible, but it should at least use compute units more efficiently:

https://pastebin.com/Le2zaJCy

This uses a 15 GB T4 GPU. If you have colab pro, there's an option to run 13B that should work as well, though you'll have to be patient executing the second cell. Colab is slow to save files, so you may have to wait and check your drive to make sure that everything has saved as it should before proceeding.

**Comment by Daviljoe193** [comment]
I've gotten [this one notebook](https://pastebin.com/E4LWRpNe) from a 4chan user to work for me on the free tier. It's VERY cumbersome to get working, but it does work. All I changed when I ran it was to not use Google Drive, and instead get the model from somebody who mirrored the model on Huggingface.

**Comment by zeeboi9** [comment]
> Interested to see if anyone is able to run on google colab. Seems like 16 GB should be enough and is granted often for colab free. Not sure if Colab Pro should do anything better, but if anyone is able to, advice would be much appreciated.

i was able to run it in normal colab but it is horribly slow because the model is linked to g drive can anyone help me make the loading times and the time the model takes to type out the response faster?

link to code or commands becasue it is a linux environment -- https://colab.research.google.com/drive/1otfwOihFBtNznj7ZXqiUJV_OXPm_BnN3?usp=sharing

**Comment by johnwick123f** [comment]
I am writing this a few months later, but its easy to run the model if you use llama cpp and a quantized version of the model. You can even run a model over 30b if you did. 
You don't even need colab. On my phone, its possible to run a 3b model and it outputs 1 token or half per second which is slow but pretty surprising its working on my phone!

**Comment by liushiyi1994** [comment]
> I am writing this a few months later, but its easy to run the model if you use llama cpp and a quantized version of the model. You can even run a model over 30b if you did. You don't even need colab. On my phone, its possible to run a 3b model and it outputs 1 token or half per second which is slow but pretty surprising its working on my phone!

I'm doing some edge computing research, might if i ask how do you run it on the phone?

**Comment by windmaple** [comment]
> > I am writing this a few months later, but its easy to run the model if you use llama cpp and a quantized version of the model. You can even run a model over 30b if you did. You don't even need colab. On my phone, its possible to run a 3b model and it outputs 1 token or half per second which is slow but pretty surprising its working on my phone!
> 
> I'm doing some edge computing research, mind if i ask how do you run it on the phone?

llama.cpp supports Android. Ref: https://github.com/ggerganov/llama.cpp#android
