### ISSUE TITLE
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by delibae** [facebookresearch/llama#122]
from tqdm import tqdm
  import time
  model = GPT()
  optimizer = torch.optim.Adam(model.parameters(), lr=1e-6)

  loss_fn = nn.CrossEntropyLoss().cuda()
  losses = []
  
  for epoch in range(10):
      epoch_loss = 0
      for batch in tqdm(dataloader):

          optimizer.zero_grad()
          input_ids = batch.cuda()
  

          input_ids = input_ids[:, :]
          input_ids.requires_grad = True
          logits = model(input_ids)

          targets = input_ids[:, 1:].long() 
  
          logits = logits.view(-1, toke2.sp_model.vocab_size())
  
  
          loss = loss_fn(logits, targets.reshape(-1))
          loss.backward()
          optimizer.step()
          epoch_loss += loss.item()
      losses.append(epoch_loss / len(dataloader))
      print("Epoch %d Loss: %.5f" % (epoch+1, losses[-1]))

I keep getting a RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn error during training, even though all layers of the model are set to requires_grad=True and the model is also set to train. Is there a solution to this problem?

**Comment by delibae** [comment]
d

**Comment by vgoklani** [comment]
@delibae Did you ever resolve this? Thanks!
