### ISSUE TITLE
Download and get forbidden

### ISSUE THREAD

**Issue by AISuperMa** [facebookresearch/llama#124]
Connecting to dobf1k6cxlizq.cloudfront.net (dobf1k6cxlizq.cloudfront.net)|13.226.237.67|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-03-05 18:04:37 ERROR 403: Forbidden.

**Comment by GeekDream-x** [comment]
Me too

**Comment by tekspirit** [comment]
are you using Windows or Mac?  and which shell command?

**Comment by GeekDream-x** [comment]
> are you using Windows or Mac? and which shell command?

I used Mac. Have tried zsh and bash

**Comment by a2012456373** [comment]
Me too....

**Comment by ShiJiawenwen** [comment]
Me too. I use Windows.

**Comment by aris992-git** [comment]
Connecting to dobf1k6cxlizq.cloudfront.net (dobf1k6cxlizq.cloudfront.net)|13.35.153.114|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-03-06 10:26:21 ERROR 403: Forbidden.
I also met this problem in windows.

**Comment by huzpsb** [comment]
(at all)
Please kindly take a look by opening this link[link](dobf1k6cxlizq.cloudfront.net) in your unproxied browser.
See that reason?
Ok, y'all know what to do.

**Comment by a2012456373** [comment]
@huzpsb Problem solved. I downloaded the leaked file from huggingface

**Comment by jsriram9** [comment]
me too

**Comment by lxq** [comment]
me too
