### ISSUE TITLE
Checking checksums ./download.sh: line 32: md5sum: command not found

### ISSUE THREAD

**Issue by QingyunSun** [facebookresearch/llama#125]
I am downloading the model using mac pro intel chip version using iterminal.

When I run a few different command:
1)./download.sh
2)`brew --prefix bash`/bin/bash ./download.sh

I get error:

Checking checksums
./download.sh: line 32: md5sum: command not found

Is there a way to by-pass it?

If not, what is the easiest way to install md5sum

**Comment by ZhengQinLai** [comment]
if you have already downloaded it, and you can check it like this:

Open the Terminal app. You can find it in the Applications folder.
Navigate the Terminal to the directory where the file you want to verify and the checksum.chk file are located using the "cd" command.
Run the following command in the Terminal:
shasum -a algorithm -c checksum.chk
Replace "algorithm" with the algorithm used to create the checksum, such as MD5, SHA1, SHA256, etc., and "checksum.chk" with the name of the checksum file you downloaded.
For example, if you want to verify a file named "example.dmg" using the SHA256 algorithm and the checksum file name is "example.chk", the command will be:
shasum -a 256 -c example.chk
Compare the hash value generated by the command with the hash value in the checksum.chk file. If they match, the file has not been tampered with.

what's more, if you simply want to by-pass it, feel free to delete " (cd ${TARGET_FOLDER}"/${i}" && md5sum -c checklist.chk)" in download.sh

**Comment by tekspirit** [comment]
If you have md5sum already installed, then the command is `bin/bash ./download.sh` in the llama directory.  You might want to use the download.sh provided in https://github.com/facebookresearch/llama/issues/41#issuecomment-1451290160 as it was corrected to run on mac bash.  To install md5sum with brew, the command is `brew install md5sha1sum`
