### ISSUE TITLE
Are the weights of the lm head of the model tied with the word embeddings?

### ISSUE THREAD

**Issue by lvcc2018** [facebookresearch/llama#138]
Thanks for the amazing work.
I wonder whether the weights of the lm head of the model are tied with the word embeddings of the model. From the code, it seems that they are not tied.

**Comment by lvcc2018** [comment]
And I am curious about the difference between tied or untied word embeddings. Does it have an effect on training stability?

**Comment by AlbertMarashi** [comment]
They are now shared in Llama 3.2 3b

**Comment by AlbertMarashi** [comment]
@glample Could you explain why decisions or reasons were made to not use weight tying for earlier models, but the 3.2 models are tied?

**Comment by notoookay** [comment]
> They are now shared in Llama 3.2 3b
> 
> 
> 
> I don't understand why the other model's (3.1 - Llama 70b's) weights were untied...

I observed the same configuration in Qwen 2.5 model, which is also mentioned in their [paper](https://arxiv.org/pdf/2407.10671). For smaller models (e.g. 0.5B, 1B), they use weight tying for parameter efficiency. For larger model (e.g. 7B, 72B), they don't use for better performance in the cost of parameter efficiency. So I think it's the choice between performance and efficiency.
