### ISSUE TITLE
13B Int8 huggingface space

### ISSUE THREAD

**Issue by deep-diver** [facebookresearch/llama#139]
Not sure how long I can keep this running 

https://huggingface.co/spaces/chansung/LLaMA-13B

**Comment by Titaniumtown** [comment]
doesn't even work

**Comment by pauldog** [comment]
"Space not ready. Reason: Error, exitCode: 1, message: None"

**Comment by Daviljoe193** [comment]
Damn. I got there within the same hour you announced it here, and it did actually work. It was already a little busy, but not too bad. Sucks it's down now, but GG getting something up and running for it so quickly.

**Comment by juncongmoo** [comment]
check https://github.com/juncongmoo/pyllama if you want to run it locally in a single GPU

**Comment by deep-diver** [comment]
sorry about this guys.
I was granted free GPU for 7B and 13B by HuggingFace team, but that was withdrawn today

**Comment by deep-diver** [comment]
so.. this is it

<img width="459" alt="캡처" src="https://user-images.githubusercontent.com/26025527/223468953-d7e8e21f-7cd8-4bd8-b9b8-3a89906642d0.PNG">

**Comment by deep-diver** [comment]
https://huggingface.co/spaces/chansung/LLaMA-7B/discussions/5

**Comment by pauldog** [comment]
> Looks like it is not allowed to deploy LLaMA in any kind of form
> 
> https://huggingface.co/spaces/chansung/LLaMA-7B/discussions/5

That's unfortunate since weights are not copyrightable. Pity Huggingface 🤗 capitulated. Guess they just want to stay on the good side of Meta.

**Comment by deep-diver** [comment]
Yeah

But I didnt expose the hard link of the weights. So it looks like the weights should be used soley for personal purpose

**Comment by pauldog** [comment]
It's just Meta trying to stay out of the papers in case it outputs something offensive. It's nothing to do with legality. It's just Meta's PR team at work I expect.
