### ISSUE TITLE
Intermediate checkpoints

### ISSUE THREAD

**Issue by shoaibahmed** [facebookresearch/llama#14]
Thank you for such amazing work. I was wondering if there are any plans to also release intermediate checkpoints for the models, similar to Pythia (https://github.com/EleutherAI/pythia). This might enable more interesting analysis of the model by observing its evolution throughout the training process.

**Comment by jspisak** [comment]
Thanks - closing this issue. We don't have immediate plans to release intermediate checkpoints but we can consider in the future for new versions of Llama. Thanks!
