### ISSUE TITLE
Approved no tnot able to download 

### ISSUE THREAD

**Issue by riskyhomo** [facebookresearch/llama#140]
iam using windows 10 wheni run download.sh it shows the error like this 
please tell how to solve this 
 
PS C:\Users\Administrator\Documents\GitHub\llama> bash "c:\Users\Administrator\Documents\GitHub\llama\download.sh"
bash : The term 'bash' is not recognized as the name of a cmdlet, function, script file, or 
operable program. Check the spelling of the name, or if a path was included, verify that the path    
is correct and try again.
At line:1 char:1
+ bash "c:\Users\Administrator\Documents\GitHub\llama\download.sh"
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (bash:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by Titaniumtown** [comment]
You're using windows.

**Comment by riskyhomo** [comment]
Yes

**Comment by neuhaus** [comment]
The download script download.sh is not for windows.

**Comment by CWX01** [comment]
You need to use Git Bash to download it on Windows.
