### ISSUE TITLE
Inquiry about the maximum number of tokens that Llama can handle

### ISSUE THREAD

**Issue by magicknight** [facebookresearch/llama#148]
I am wondering if there is a limit to the number of tokens that a Llama can handle in OpenAI's GPT models. I am planning to use the GPT models for a project that requires handling a large amount of text data, and I want to make sure that I don't exceed the maximum token limit that the Llama can handle.

I have searched the documentation, but I couldn't find any information on this topic. Therefore, I am hoping that someone from the OpenAI team can help me with this inquiry.

If there is a limit, can you please provide me with the details on the maximum number of tokens that a Llama can handle, and any suggestions on how to optimize my use of the GPT models to work within this limit?

Thank you very much for your assistance.

**Comment by glample** [comment]
It was trained with 2048 tokens, so you can use up to that. If you want to use more tokens, you will need to fine-tune the model so that it supports longer sequences.

**Comment by teknium1** [comment]
Can you actually just "fine tune more context size"?

**Comment by couldbejake** [comment]
@teknium1 how would one do so?

**Comment by teknium1** [comment]
> @teknium1 how would one do so? I am a bit of a newbie here, is the process easy? Else I may find help elsewhere.

That's why I asked because I too didn't know this was possible. After some research, it seems it probably is possible. I still don't know how to do it or what it would require though

**Comment by couldbejake** [comment]
It could effectively make a chat diary but provide additional context, such as what the question pertains to.

**Comment by MoritzLaurer** [comment]
@glample do you have a source for the 2048 max token limit? I didn't find any info on this

**Comment by Delcos** [comment]
I remember Meta saying 4096 at one point but I haven't tested this yet.

**Comment by teknium1** [comment]
I'm hearing you can just raise the max sequence length and fine tune it on longer prompts

**Comment by SKRohit** [comment]
> @glample do you have a source for the 2048 max token limit? I didn't find any info on this

https://huggingface.co/docs/transformers/main/en/model_doc/llama#transformers.LlamaConfig `max_position_embeddings'

**Comment by yuye2133** [comment]
Is there any parameter that needs to be optimized for the maximum length? It should just be that the training data has not seen a longer one, so the prediction result will be worse. When adding finetune, set a larger length and add relevant data, will the length be expanded?

**Comment by teknium1** [comment]
> Is there any parameter that needs to be optimized for the maximum length? It should just be that the training data has not seen a longer one, so the prediction result will be worse. When adding finetune, set a larger length and add relevant data, will the length be expanded?

See my tweet on this topic: https://twitter.com/Teknium1/status/1654446899859177472

**Comment by jspisak** [comment]
thanks - let's add this to the documentation / FAQ as well. Closing for now as it's been answered..
