### ISSUE TITLE
Where can I download the weights of the 7B model?

### ISSUE THREAD

**Issue by BenBill2077** [facebookresearch/llama#149]
Still waiting for the email.

**Comment by Daviljoe193** [comment]
[Bittorrent](magnet:?xt=urn:btih:b8287ebfa04f879b048d4d4404108cf3e8014352&dn=LLaMA). Some people have allegedly been getting ghosted, so just do it, the speeds via bittorrent ain't bad once it gets started.

**Comment by shadowwalker2718** [comment]
try this hacked llama: https://github.com/juncongmoo/pyllama pretty good

**Comment by pauldog** [comment]
Just search Twitter for torrents. 

Just to be clear downloading and using these weights is all **totally legal** as weights are not copyrightable. 

Whether uploading these weights in the first place was legal if the person signed the Meta form, is a grey area. 

Well it would be writing every even letter of a Wikipedia article to a text file and then creating a form which says if I give you this text file you have to promise not to give it to anyone else. Now would that hold up in court? 🤔

**Comment by BenBill2077** [comment]
Thx, nice




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Shadow ***@***.***&gt;; 
发送时间: 2023年3月8日(星期三) 凌晨2:38
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [facebookresearch/llama] Where can I download the weights of the 7B model? (Issue #149)





 
try this hacked llama: https://github.com/juncongmoo/pyllama pretty good

**Comment by zanghu** [comment]
I would recommend this: https://github.com/howl-anderson/unlocking-the-power-of-llms if anyone live in China.

**Comment by sw-yx** [comment]
https://github.com/shawwn/llama-dl

**Comment by xyproto** [comment]
The shawwn/llama-dl README.md file has an archived copy here, if it's helpful: https://archive.is/7t3it

**Comment by Immortalise** [comment]
> https://archive.is/7t3it
seems not available for now :(

**Comment by Daviljoe193** [comment]
> > https://archive.is/7t3it
> > seems not available for now :(

Yup... just get the torrent, or the IPFS mirror.

> Some have been having trouble with the magnet. For preservation, I've reuploaded the original torrent content to an [ipfs](https://ipfs.tech/) node.
> 
> http gateways (the links below) will be slow to retrieve until more people have the files. Use a local node like Kubo or Brave Browser if possible - it's faster and helps reseed the content for others temporarily (after downloading), or permanently (if pinned).
> 
> Full backup: [ipfs://Qmb9y5GCkTG7ZzbBWMu2BXwMkzyCKcUjtEKPpgdZ7GEFKm](https://ipfs.io/ipfs/Qmb9y5GCkTG7ZzbBWMu2BXwMkzyCKcUjtEKPpgdZ7GEFKm)
> 
> 7B: [ipfs://QmbvdJ7KgvZiyaqHw5QtQxRtUd7pCAdkWWbzuvyKusLGTw](https://ipfs.io/ipfs/QmbvdJ7KgvZiyaqHw5QtQxRtUd7pCAdkWWbzuvyKusLGTw) 13B: [ipfs://QmPCfCEERStStjg4kfj3cmCUu1TP7pVQbxdFMwnhpuJtxk](https://ipfs.io/ipfs/QmPCfCEERStStjg4kfj3cmCUu1TP7pVQbxdFMwnhpuJtxk) 30B: [ipfs://QmSD8cxm4zvvnD35KKFu8D9VjXAavNoGWemPW1pQ3AF9ZZ](https://ipfs.io/ipfs/QmSD8cxm4zvvnD35KKFu8D9VjXAavNoGWemPW1pQ3AF9ZZ) 65B: [ipfs://QmdWH379NQu8XoesA8AFw9nKV2MpGR4KohK7WyugadAKTh](https://ipfs.io/ipfs/QmdWH379NQu8XoesA8AFw9nKV2MpGR4KohK7WyugadAKTh)
> 
> You can download normally, or use these commands from the Kubo CLI:
> 
> ```powershell
> # Optional: Preload the 7B model. Retrieves the content you don't have yet. Replace with another CID, as needed.
> ipfs refs -r QmbvdJ7KgvZiyaqHw5QtQxRtUd7pCAdkWWbzuvyKusLGTw
> 
> # Optional: Pin the 7B model. The GC removes old content you don't use, this prevents the model from being GC'd if enabled.
> ipfs pin add QmbvdJ7KgvZiyaqHw5QtQxRtUd7pCAdkWWbzuvyKusLGTw
> 
> # Download from IPFS and save to disk via CLI:
> ipfs get QmbvdJ7KgvZiyaqHw5QtQxRtUd7pCAdkWWbzuvyKusLGTw --output ./7B
> ```


> 
> > > > Where can I get the original LLaMA model weights?
> > > 
> > > 
> > > Easy, [just fill out this official form](https://forms.gle/jk851eBVbX1m5TAv5), give them very clear reasoning why you should be granted a temporary (Identifiable) download link, and hope that you don't get ghosted. Or you could just use the torrent, like the rest of us.
> > 
> > 
> > Thanks.How can I use the torrent?
> 
> While you can use any bittorrent client, just use a client like Aria2c (It's basically just a CLI downloader that _just so happens_ to support bittorrent), which on Ubuntu can be gotten through `sudo apt install aria2`, and on Windows and Mac OS (Which I'm not very familiar with) can be [gotten from this page](https://aria2.github.io/). With `aria2c` in your path (On Ubuntu, it just is. For Windows/Mac, in a termal or CMD, just navigate into the path of `aria2c`), run one of the following...
> 
> For the 7B model...
> 
> ```
> aria2c --select-file 21-23,25,26 'magnet:?xt=urn:btih:b8287ebfa04f879b048d4d4404108cf3e8014352&dn=LLaMA'
> ```
> 
> For the 13B model...
> 
> ```
> aria2c --select-file 1-4,25,26 'magnet:?xt=urn:btih:b8287ebfa04f879b048d4d4404108cf3e8014352&dn=LLaMA'
> ```
> 
> For the 30B model...
> 
> ```
> aria2c --select-file 5-10,25,26 'magnet:?xt=urn:btih:b8287ebfa04f879b048d4d4404108cf3e8014352&dn=LLaMA'
> ```
> 
> For the 65B model...
> 
> ```
> aria2c --select-file 11-20,25,26 'magnet:?xt=urn:btih:b8287ebfa04f879b048d4d4404108cf3e8014352&dn=LLaMA'
> ```
> 
> And for everything...
> 
> ```
> aria2c 'magnet:?xt=urn:btih:b8287ebfa04f879b048d4d4404108cf3e8014352&dn=LLaMA'
> ```
> 
> Once the download status goes to "SEED", you can press CTRL+C to end the process, or alternatively, let it seed to a ratio of 1.0, at which point it'll close on it's own. On Windows/Mac, the usage is nearly identical, just use ./ in front of the executable name (Again, while in the directory of it), and for Windows specifically, call the executable as `./aria2c.exe`. The last version for Mac was [aria2 1.35.0](https://github.com/aria2/aria2/releases/tag/release-1.35.0). Once you have the models, it's up to you how you use them. Also note, aria2c doesn't trim ajacent files from what's selected (Torrents always require things be in chunks, and chunks almost always contain either the middle of a file, or two ends of two files, so this is normal), so if you see model dirs that you didn't want, just remove them once the download is complete. There's also the other magnet link that was specifically a part of this pull request (magnet:?xt=urn:btih:ZXXDAUWYLRUXXBHUYEMS6Q5CE5WA3LVA&dn=LLaMA), but I could not get this one to work for me. Also note, I personally could not get either of these magnet links to work within Colab (Even using reconstructed seed files, made from `aria2c --bt-metadata-only=true --bt-save-metadata=true MAGNETURL` wouldn't start on there), but I could get the former link working on my local system.

**Comment by russeree** [comment]
What does getting 'Ghosted' mean?

**Comment by Daviljoe193** [comment]
> What does getting 'Ghosted' mean?

![ghosty](https://user-images.githubusercontent.com/67191631/230691600-e6c02b17-412e-4366-962e-627bfc6d9bcf.png)

**Comment by xyproto** [comment]
~LMGTFY~ LMCGTFY

**Comment by russeree** [comment]
Sorry for my ignorance, I thought it had some technical meaning beyond that. Such as those that obtain the weights through non standard channels end up suffering from some sort of negative effect of 'Ghosting' 

Thanks!

**Comment by TheNotary** [comment]
I'm a little lost, isn't what we need in this repo which is publicly available https://huggingface.co/decapoda-research/llama-7b-hf

**Comment by iperov** [comment]
> Bittorrent (magnet:?xt=urn:btih:b8287ebfa04f879b048d4d4404108cf3e8014352&dn=LLaMA). Some people have allegedly been getting ghosted, and getting ghosted ain't cool, so just do it, the speeds via bittorrent ain't bad once it gets started.

it has no config.json for 13B. Where I can obtain it ?

**Comment by sr5434** [comment]
How long is the waitlist?

**Comment by russeree** [comment]
You likely will not even get a response from the team at Facebook. 'Ghosted' is a term used commonly around here. None the less it never hurts to try.

**Comment by sr5434** [comment]
Ok.

**Comment by GameDevKitY** [comment]
How do I use these weights?

**Comment by sr5434** [comment]
I think you can use them with hugging face transformers

**Comment by nexushamer** [comment]
> > Bittorrent (magnet:?xt=urn:btih:b8287ebfa04f879b048d4d4404108cf3e8014352&dn=LLaMA). Some people have allegedly been getting ghosted, and getting ghosted ain't cool, so just do it, the speeds via bittorrent ain't bad once it gets started.
> 
> it has no config.json for 13B. Where I can obtain it ?
> 
> (solved)

I would appreciate it if you could provide information on the location of the config.json file. I am currently encountering an error while attempting to run the command "python -m 'fastchat.model.apply_delta'," and it appears to be related to the config file.

**Comment by trbedwards** [comment]
> Bittorrent (magnet:?xt=urn:btih:b8287ebfa04f879b048d4d4404108cf3e8014352&dn=LLaMA). Some people have allegedly been getting ghosted, and getting ghosted ain't cool, so just do it, the speeds via bittorrent ain't bad once it gets started.

It seems quite large (219GB). Is that right? Is this the correct torrent for the 7B parameter weights?

**Comment by kod02** [comment]
14 May 2023 Paz, saat 23:49 tarihinde Thomas Edwards <
***@***.***> şunu yazdı:

**Comment by kod02** [comment]
Havehhdjejx Ben []()

**Comment by Vikho** [comment]
These methods  seems very helpful! Thanks all of you!

**Comment by kod02** [comment]
selissarichi.com

**Comment by kenhuangsy** [comment]
> 

Hey @Daviljoe193 thank you! I'm wondering is it possible to only download the 7B and 13B weights?

**Comment by Cliffia123** [comment]
I find a useful way to download model weights, just use this in terminal
```
curl -o- https://raw.githubusercontent.com/shawwn/llama-dl/56f50b96072f42fb2520b1ad5a1d6ef30351f23c/llama.sh | $(brew --prefix)/bin/bash

```
you can copy the script in your computer and choose to download the sepcific weighets (i.e. 7B) in llama.sh

**Comment by Cliffia123** [comment]
@kenhuangsy you can try this
```
curl -o- https://raw.githubusercontent.com/shawwn/llama-dl/56f50b96072f42fb2520b1ad5a1d6ef30351f23c/llama.sh | $(brew --prefix)/bin/bash
```
It help to me

**Comment by kenhuangsy** [comment]
@Cliffia123 thanks!

**Comment by ThePieMonster** [comment]
> > Bittorrent (magnet:?xt=urn:btih:b8287ebfa04f879b048d4d4404108cf3e8014352&dn=LLaMA). Some people have allegedly been getting ghosted, and getting ghosted ain't cool, so just do it, the speeds via bittorrent ain't bad once it gets started.
> 
> it has no config.json for 13B. Where I can obtain it ?
> 
> (solved)

How?

**Comment by dongfeicui** [comment]
> I would recommend this: https://github.com/howl-anderson/unlocking-the-power-of-llms for anyone live in China.


The ability to download is no longer available.

![image](https://github.com/facebookresearch/llama/assets/60336738/d0d79342-775f-40f9-81f5-dedc4325d429)

**Comment by dongfeicui** [comment]
https://huggingface.co/nyanko7/LLaMA-7B/tree/main

**Comment by shams2023** [comment]
> https://huggingface.co/nyanko7/LLaMA-7B/tree/main

这是完整版的llama-7b权重文件吗？

**Comment by lixit** [comment]
> > https://huggingface.co/nyanko7/LLaMA-7B/tree/main
> 
> 这是完整版的llama-7b权重文件吗？

https://huggingface.co/huggyllama/llama-7b

**Comment by shams2023** [comment]
> > > https://huggingface.co/nyanko7/LLaMA-7B/tree/main
> > 
> > 
> > 这是完整版的llama-7b权重文件吗？
> 
> 这个应该是 https://huggingface.co/huggyllama/llama-7b

I saw your answer, thank you very much for answering my question!
Thank you!

**Comment by hanxunyu** [comment]
> > > https://huggingface.co/nyanko7/LLaMA-7B/tree/main
> > 
> > 
> > 这是完整版的llama-7b权重文件吗？
> 
> 这个应该是 https://huggingface.co/huggyllama/llama-7b
为什么这个里面有两组大文件呀，一组的后缀是.safetensors；另一组的后缀是.bin；并且它们的大小是相同的。
![image](https://github.com/meta-llama/llama/assets/64463353/da9ce597-9889-4fd2-9400-797c4bc7b429)
