### ISSUE TITLE
This is just a sneaky advertisement for researchers to send their data to Meta.

### ISSUE THREAD

**Issue by cmp-nct** [facebookresearch/llama#15]
Nice try. Like all other Meta "open" models and "open source" models it's the same game:
You have to fill out one of their data collection portals, provide all details about yourself and your projects.
Then some data collector at Meta/Facebook will decide if you receive limited access.

I suppose it helps if you have a Facebook account and blog about "Meta" being an open company.
Because we all know, that is what they are known for. Not to be the worst private data harvester in the world.

**Comment by cmp-nct** [comment]
Nice try. Like all other Meta "open" models and "open source" models it's the same game:
You have to fill out one of their data collection portals, provide all details about yourself and your projects.
Then some data collector at Meta/Facebook will decide if you receive limited access.

I suppose it helps if you have a Facebook account and blog about "Meta" being an open company.
Because we all know, that is what they are known for. Not to be the worst private data harvester in the world.

**Comment by hollykbuck** [comment]
Exactly

**Comment by pauldog** [comment]
They've probably got all our data anyway!

**Comment by FrankChu0229** [comment]
exactly
