### ISSUE TITLE
Cannot download checkpoints

### ISSUE THREAD

**Issue by helen9975** [facebookresearch/llama#154]
Hi,

Thanks for open sourcing this work!

I have received access to download the model weights, however have encountered an error: **ERROR: cannot verify dobf1k6cxlizq.cloudfront.net's certificate, issued by ‘CN=Amazon RSA 2048 M01,O=Amazon,C=US’**

See below:
<img width="401" alt="Screen Shot 2023-03-08 at 12 40 22 AM" src="https://user-images.githubusercontent.com/50860781/223664557-8f675f0b-4f9d-45ec-829f-480e4c7b2bb5.png">

Was wondering if there is anyway to resolve the problem? Thanks!

Here are the steps to reproduce:
1. Modified PRESIGNED_URL & TARGET_FOLDER
2. chmod -x download.sh
3. ./download.sh

System information:
* Ubuntu 20.04

**Comment by WuhanMonkey** [comment]
Seems like this is an issue with your OpenSSL version. Please update those and see if that resolve your problem

**Comment by samuelselvan** [comment]
@helen9975 please retry requesting one more time via https://ai.meta.com/resources/models-and-libraries/llama-downloads/

And let us know if you still face issues.
