### ISSUE TITLE
How good is the 65B model? Anyone tested it?

### ISSUE THREAD

**Issue by pauldog** [facebookresearch/llama#157]
I have tried the 7B model and while its definitely better than GPT2 it is not quite as good as any of the GPT3 models. This is somewhat subjective.
How do the other models compare 13B,... 65B etc.?

For example the 7B model succeeds with the prompt

`The expected response for a highly intelligent computer to the input "What is the capital of France?" is "`

but fails with the more tricky:

`The expected response for a highly intelligent computer to the input "Write the alphabet backwards" is "`

Has anyone got examples where it shows the difference between the models?

P.S.
Is there a better place to discuss these things rather than the issues section of github? We need a discord server.

**Comment by MrBIMC** [comment]
LLama is not instruction tuned, neither was rlhfed so it doesn't act as an agent by default. 

In order for it to do what you want you have to be much more precise in your prompts. Do a character description as a header, give few examples and then go on with your actual question. 

There are a bunch of related discord servers already btw.

**Comment by barleyj21** [comment]
@randaller did you run it all in RAM or did you manage to use it with swap file on ssd?

**Comment by randaller** [comment]
> @randaller did you run it all in RAM or did you manage to use it with swap file on ssd?

@barleyj21 128 Gb of RAM + 256 Gb swap on pci-e 4.0 nvme

**Comment by neuhaus** [comment]
You can also run Llama 65B (a bit slow but not terrible) on a CPU and with 128GB RAM with llama.cpp

See the discussion at https://github.com/ggerganov/llama.cpp/issues/34

**Comment by leszekhanusz** [comment]
> You can also run Llama 65B (a bit slow but not terrible) on a CPU and with 128GB RAM with llama.cpp

You don't need 128GB RAM, 65B runs on CPU with only 48GB RAM without swap with llama.cpp

**Comment by sushi-hackintosh** [comment]
unable to run 65b for windows  bouhhh

**Comment by WuhanMonkey** [comment]
Closing since it is not an issue.
