### ISSUE TITLE
Sequence/context length of this model?

### ISSUE THREAD

**Issue by TimDettmers** [facebookresearch/llama#16]
I was searching the paper/blog post but I could not find a mention of which sequence length/context length the models were trained with. I want to write some CUDA optimizations for these models and this information would be critical for optimizing these implementations.

**Comment by glample** [comment]
We used a sequence length of 2048 tokens. Thanks for spotting this out, will add it to the paper!

**Comment by TimDettmers** [comment]
Thanks, Guillaume!
