### ISSUE TITLE
Not actually open source and incompatible with other GPL 3 projects

### ISSUE THREAD

**Issue by redhog** [facebookresearch/llama#161]
While the license for the code is GPL 3, and possible to link to other GPL 3 code, the trained weights are not, and the combined work of code and trained weights, is not under GPL 3, and can thus not be linked to other GPL 3 software.

**Comment by RabblerouserGT** [comment]
Yeah, people ALL OVER YouTube are getting this confused, trying to say LLaMA is open-source, which is leading people to believe they can do with the model what they want.

They should read the model card instead.

**Comment by pauldog** [comment]
> While the license for the code is GPL 3, and possible to link to other GPL 3 code, the trained weights are not, and the combined work of code and trained weights, is not under GPL 3, and can thus not be linked to other GPL 3 software.

You can't copyright trained weights (in my view) so the point is mute.

**Comment by redhog** [comment]
Why not? If they are nontrivially many? If not, they definitely full under database rights under EU law, leading to the same issue, that they can not be shared freely w/o an open source license.

**Comment by pauldog** [comment]
Well there's more countries in the world than the EU

**Comment by redhog** [comment]
Database rights exists in many jurisdictions. The fact that their license for the weights is invalid/irrelevant in some, does not make this any more open source.

But, if you are so sure, go get access to the weights, then publish them on github in another repo, and link to it in this ticket, and wait for them to sue. Note: This is not legal advice. Seriously talk to a lawyer first, before doing something that most likely lands you in an expensive lawsuit.

**Comment by WuhanMonkey** [comment]
Closing as this is not an issue and we also have Llama 2 released.
