### ISSUE TITLE
Official LLaMA on HuggingFace anytime soon?

### ISSUE THREAD

**Issue by teslyuk** [facebookresearch/llama#163]
While I'm still waiting for my email from you guys, are you planning to publish 7-65B model versions on HuggingFace?

**Comment by tianhao960** [comment]
+1

**Comment by BugReporterZ** [comment]
Worth pointing out that the cat is out of the bag already: https://github.com/facebookresearch/llama/pull/73

Having an official source for the weights would make it safer to download these files; a proper open-source license would remove ambiguity regarding what can be done with them.

**Comment by Dampfinchen** [comment]
Yes please. This would be groundbreaking for the whole AI community and it would demonstrate Meta really is committed being open and transparent.

**Comment by archwolf118** [comment]
We are waiting for the llama on hugingface! Thank you!
