### ISSUE TITLE
AccessDenied

### ISSUE THREAD

**Issue by df19900725** [facebookresearch/llama#164]
I have received the email that tells me I can download the model from the link. However, I find that I have been blocked by  the server.

I am  in China, and the server response below:

```
403 ERROR
The request could not be satisfied.
The Amazon CloudFront distribution is configured to block access from your country. We can't connect to the server for this app or website at this time. There might be too much traffic or a configuration error. Try again later, or contact the app or website owner.
If you provide content to customers through CloudFront, you can find steps to troubleshoot and help prevent this error by reviewing the CloudFront documentation.
```

When I use VPN, it shows error below:

```
This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>HPATD0783TRTG86R</RequestId>
<HostId>TRFFhySM24AbL99nt8BHMtPIqBZHaHSHoDbWDnnCXMF23jPw1t005T3Ya7FKT2hZswJkInNumIM=</HostId>
</Error>
```

So is there any license or note that which countries can not download the model? and why?

I filled the form with my real information and the Meta should know where I come from, but even the application was approved, but the server is configured to block me. I don't know why?

**Comment by felipehime** [comment]
Did you use the download.sh script?

**Comment by CWX01** [comment]
I encountered the same errors. But I downloaded the model using this: magnet:?xt=urn:btih:cdee3052d85c697b84f4c1192f43a2276c0daea0&dn=LLaMA. And I successfully ran the 7B model on 3080. Though it seems that the 7B model is not working well and couldn't understand my questions.

**Comment by df19900725** [comment]
> Did you use the download.sh script?

Sorry, it was my fault that I did not try to use the download.sh script to download the model file. And the link from email is invalid now. I can not check now....

**Comment by df19900725** [comment]
> I encountered the same errors. But I downloaded the model using this: magnet:?xt=urn:btih:cdee3052d85c697b84f4c1192f43a2276c0daea0&dn=LLaMA. And I successfully ran the 7B model on 3080. Though it seems that the 7B model is not working well and couldn't understand my questions.

thanks, I will try to use this link
