### ISSUE TITLE
how to access the pre-training corpus?

### ISSUE THREAD

**Issue by lshowway** [facebookresearch/llama#17]
will the corpus be packed and provided?

**Comment by jspisak** [comment]
We will not be releasing the pre-training corpus but we've described the datasets used in the papers. 
<img width="312" alt="Screenshot 2023-09-06 at 9 51 50 AM" src="https://github.com/facebookresearch/llama/assets/11398925/402eb277-6e51-48d3-8d38-0bcfffb8ff09">


Paper: https://arxiv.org/pdf/2302.13971.pdf

**Comment by jspisak** [comment]
Closing this issue - thanks!
