### ISSUE TITLE
To Meta: If I release an app with the weights embedded will you take me to court? 🤔

### ISSUE THREAD

**Issue by knightofdoom** [facebookresearch/llama#171]
To Meta Lawyers,

1) I am considering releasing an commercial app with the weights embedded in the app and also a robot toy with the weights embedded in its software.
2) I will not use the meta code, I will write my own code based on knowledge of the model structure.
3) I did not receive the weights from you by signing the form, therefor I am not bound by that form.

Since I believe that neural network weights can not be copyrighted as no-one has ever been sued for using someone else's network weights. Also since the data used to make the weights is public access and created by public contributions (such as me as I have edited Wikipedia pages). Since also the weights were made by machine and do not have human creative input.

And, 2, since I will write my own code to avoid copyleft of the python code. I believe I can avoid copyright here as this is a simple transformer model which many people have used.

And, 3, since Facebook was originally made by also 'borrowing' photos of public Facebooks at Harvard, so I am also going to 'borrow' these weights for my app.

4 if you wished to keep these weights confidential you could have done so but you didn't.

I will take an absence of response as an official endorsement. Otherwise please let me know of your intentions to take me to the civil court and give your reasons. Also please let me know of what amount you would sue me for. (I do not have a billion dollars to spare)

Thanks

KofD

**Comment by spv420** [comment]
lol, this is amazing

**Comment by BetaDoggo** [comment]
This isn't how anything works. There is nothing stopping you from using the inference code, as gpl3 does not restrict commercial use. The issue is the model weights which explicitly use a non commercial license. You do not have to agree to anything to be bound by this restriction.

If you truly believe that they shouldn't be allowed to copyright the weights because they were trained with public material, then you also shouldn't be attempting to profit from the weights for the same reason.

**Comment by pauldog** [comment]
Do it 😁

**Comment by TeamDman** [comment]
> because they were trained with public material, then you also shouldn't be attempting to profit from the weights for the same reason.

If you make your code public too then I don't see why not .-.

**Comment by BetaDoggo** [comment]
> If you make your code public too then I don't see why not .-.

Definitely, but based on what they said about making a commercial product and avoiding copyleft I assumed that they wouldn't be releasing code if this hypothetical product was actually made.

**Comment by Ghost---Shadow** [comment]
>  ...absence of response as an official endorsement...
Absence of response cannot be an endorsement. That part is legally wrong.

> I did not receive the weights from you by signing the form...
Did you train your own model, or did you acquire it unlawfully? 

As a general rule of thumb, if it feels illegal, then it is probably illegal. Talk to a real lawyer.

**Comment by utkarshsingh77** [comment]
> `I am considering` releasing an commercial app with the weights embedded in the app and also a robot toy with the weights embedded in its software.
> `I will` not use the meta code, I will write my own code based on knowledge of the model structure.
> `I did not` receive the weights from you by signing the form, therefor I am not bound by that form.

> And, 2, since` I will` write my own code to avoid copyleft of the python code. I believe I can avoid copyright here as this is a simple transformer model which many people have used.

Have you actually built anything useful? 

> Since I believe that neural network weights can not be copyrighted as no-one has ever been sued for using someone else's network weights. Also since the data used to make the weights is public access and created by public contributions (such as me as I have edited Wikipedia pages). Since also the weights were made by machine and do not have human creative input.
>



@knightofdoom Why would we sue you? It doesn't appear that you've had any impact..on anything at all..
These "ideas" sound more like delusions of grandeur.



> I will take an absence of response as an official endorsement. Otherwise please let me know of your intentions to take me to the civil court and give your reasons. Also please let me know of what amount you would sue me for. (I do not have a billion dollars to spare)

@knightofdoom  I would focus on the impact you can make on the world with the tools you are provided rather than stirring up conflict in an attempt to garner attention. The world will not allow bad actors to use this type of revolutionary tech for you to sell upscaled snake oil.

Best of luck!

**Comment by jspisak** [comment]
@knightofdoom - thanks for your question. A LOT has happened since this issue was opened. :) 

For your commercial app, please use Llama 2 and reach out if you have any issues accessing the model. thanks for your support!
