### ISSUE TITLE
The first load of the model is very slow, and the second load is very fast

### ISSUE THREAD

**Issue by Valdanitooooo** [facebookresearch/llama#174]
- My server environment:

```
AWS EC2 p3.2xlarge
1 V100 GPU 16GB memory
```

- My tests

I use the official example.py file.

`time torchrun --nproc_per_node 1 example.py --ckpt_dir /code/data_llama/7B --tokenizer_path /code/data_llama/tokenizer.model`

```
# The first time takes 30 minutes
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Loading
Loaded in 1740.90 seconds

# The second time takes 12 seconds
...
Loaded in 11.95 seconds
```

Does anyone know why？

**Comment by diegomontoya** [comment]
Disk caching to ram on first load. However this doesn't explain  your horrendous speed. Maybe your ecs disk sans is just too saturated for any io.

**Comment by WuhanMonkey** [comment]
Is this issue still persist? If so, please provide more information.
