### ISSUE TITLE
How to create a General AI 🤖

### ISSUE THREAD

**Issue by pauldog** [facebookresearch/llama#181]
Hi,

just thought I'd post this little essay I wrote [about how to create a general AI](https://docs.google.com/document/d/1WutuvK7zLB6xINN6SUsAUz2kEPQaQJibfDjUjHMnQKo/edit?usp=sharing). with a modified language model. What's your opinion?

**Comment by jumang4423** [comment]
bruh

**Comment by miolini** [comment]
It's an intriguing idea. We could close the loop by distilling a training dataset and making it dynamic, and then continuously refining the model with new observed data.

**Comment by jumang4423** [comment]
i host my own llms into my linux server and every conversations with friends are collected and trained every 24 hours.
it is quite cool for me.
that changed how i communicate with friends (not for most of people, because i am not good at communicating with people that is why i made that ecosystem)

**Comment by pauldog** [comment]
> i host my own llms into my linux server and every conversations with friends are collected and trained every 24 hours. it is quite cool for me. that changed how i communicate with friends (not for most of people, because i am not good at communicating with people that is why i made that ecosystem)

Does the llm begin to sound like your friends?

**Comment by miolini** [comment]
It would be great if can visualize update waves inside models day to day. And maybe, incorporate how waves propogates into mdoel itself.

**Comment by pauldog** [comment]
> @pauldog Could you please talk a little bit more about your fine tuning pipeline and foundation model? What hardware are you using for it?

I haven't tried fine tuning this model yet. I've done reinforcement learning on other models not this one yet. My hardware probably isn't good enough. I can only just get the 7B model working!

**Comment by miolini** [comment]
What other models have you used?

**Comment by jspisak** [comment]
Closing this one - we will have some forums for this type of discussion soon. thanks!
