### ISSUE TITLE
Run 13B on 1 GPU A100 (48GB VRAM)

### ISSUE THREAD

**Issue by ayeeyecorp** [facebookresearch/llama#186]
I know the 13B model fit on a single A100 GPU which has sufficient VRAM but I can't seem to figure out how to get it working..

**Comment by ayeeyecorp** [comment]
Apologies for the redundant post - I found the solution

[1] https://gist.github.com/benob/4850a0210b01672175942203aa36d300 

Reshard 13B with above script: python reshard.py 1 ~/llama/models/13B/ ~/llama/models_reshard/

and then run as usual --nproc_per_node 1

**Comment by breadbrowser** [comment]
> I know the 13B model fit on a single A100 GPU which has sufficient VRAM but I can't seem to figure out how to get it working..

i think you can run 13B like nothing on an a100 with this https://github.com/randaller/llama-chat

**Comment by WuhanMonkey** [comment]
I think this issue should be resolved as shown above. In generally you will need to merge checkpoint files for running on one process in single GPU.
