### ISSUE TITLE
How to train a LLaMA-7B on multiple GPUs?

### ISSUE THREAD

**Issue by cmnfriend** [facebookresearch/llama#190]

**Comment by wnma3mz** [comment]
I finished the multi-GPU inference for the 7B model. I'm still working on implementing the fine-tuning / training part.

Note: No redundant packages are used, so there is no need to install transformer. if anyone is interested in this sort of thing, feel free to discuss it together.

https://github.com/wnma3mz/llama

**Comment by amitsangani** [comment]
Thanks for the info and contribution. We do have recipes for multi-GPU training and inferencing on Llama recipes repo. Closing this issue. 

https://github.com/facebookresearch/llama-recipes
