### ISSUE TITLE
Scripts to reproduce the Paper's results ?

### ISSUE THREAD

**Issue by vince62s** [facebookresearch/llama#191]
It would be great to be able to reproduce the results provided in the paper.

![image](https://user-images.githubusercontent.com/15141326/224653940-cc3afb81-7bb3-43e0-b63d-d51094361695.png)

the zero-shot ones but also the other tables with few-shots.

Can this be released ?

**Comment by yysjasmine** [comment]
I want to do the same thing, do you have any idea?

**Comment by vince62s** [comment]
It's up to the Meta team @glample to release or not. Would be great though.

**Comment by jspisak** [comment]
We are considering to also release things like our eval platform but for now I'd recommend the OpenLLM leaderboard from HF - https://huggingface.co/spaces/HuggingFaceH4/open_llm_leaderboard
