### ISSUE TITLE
I want to use 65B on 4 A100-80G to talk like GPTChat. What should I do

### ISSUE THREAD

**Issue by Chting** [facebookresearch/llama#192]

**Comment by breadbrowser** [comment]
> _No description provided._

i recommend using this. https://github.com/randaller/llama-chat

**Comment by Chting** [comment]
> I recommend using this. https://github.com/randaller/llama-chat

Thank you for your answer. I have used this one. It does not support multiple GPUs at present

**Comment by Blocker45** [comment]
[Check this](https://github.com/ggerganov/llama.cpp), Maybe helpful.

**Comment by Chting** [comment]
> [Check this](https://github.com/ggerganov/llama.cpp), Maybe helpful.

Thank you, I have tried this

**Comment by XuyaoWang** [comment]
this [link](https://github.com/nebuly-ai/nebullvm/tree/main/apps/accelerate/chatllama) is another way to make llama looks like a ChatGPT

**Comment by WuhanMonkey** [comment]
Closing as we released Llama 2 chat.
