### ISSUE TITLE
The Text-to-SQL Capabilities of LLaMA

### ISSUE THREAD

**Issue by liang8qi** [facebookresearch/llama#196]
Has anyone evaluated the Text-to-SQL Capabilities of LLaMA?

**Comment by randaller** [comment]
@liang8qi yes it does writing SQL code https://github.com/randaller/llama-chat/issues/7#issuecomment-1467861922

**Comment by liang8qi** [comment]
> @liang8qi yes it does writing SQL code [randaller/llama-chat#7 (comment)](https://github.com/randaller/llama-chat/issues/7#issuecomment-1467861922)

Thanks a lot, that's great.

**Comment by WuhanMonkey** [comment]
Closing as we released Code Llama and also Snowflakes had works with it on SQL generation. Check out here -https://www.snowflake.com/blog/meta-code-llama-testing/

**Comment by Perseus14** [comment]
Just curious, Did Snowflake release the weights and code for their fine-tuned Code-LLama models?
