### ISSUE TITLE
Relationship with EleutherAI/GPT-J ?

### ISSUE THREAD

**Issue by tpoisonooo** [facebookresearch/llama#204]
Thanks for your open-source model and paper, its great.

[llama.cpp hack in one night](https://github.com/ggerganov/llama.cpp/issues/33) noticed that it `has a very similar architecture to GPT-J` .

No offense, are you just train it with trivial modification and multiple opensource dataset ?

**Comment by bth5032** [comment]
A lot of the llms are extremely similar architecture wise. The training process and resultant model are the novel contributions, not the architecture.

**Comment by tpoisonooo** [comment]
Ah.. facebook is rich, that is all I read from the LLaMa paper ..
