### ISSUE TITLE
Can I use this model in my company or is it research only?

### ISSUE THREAD

**Issue by crescedo** [facebookresearch/llama#219]

**Comment by Coderx7** [comment]
the license is GNU General Public License v3.0 and is here https://github.com/facebookresearch/llama/blob/main/LICENSE 
you an use this commercially based on the GPL v3. but its best to consult with your lawyer on how stuff works.

**Comment by simonSlamka** [comment]
> the license is GNU General Public License v3.0 and is here https://github.com/facebookresearch/llama/blob/main/LICENSE you an use this commercially based on the GPL v3. but its best to consult with your lawyer on how stuff works.

The license only covers the inference code, not the weights!

**Comment by anubop** [comment]
Please go ahead and use Llama2 for commercial use and reach out if you have any issues with accessing the model :)
