### ISSUE TITLE
Does it support Chinese?

### ISSUE THREAD

**Issue by terrifyzhao** [facebookresearch/llama#22]

**Comment by AISuperMa** [comment]
i have same question

**Comment by qwer10** [comment]
i have the same question too， in llama paper i could not find any zh corpus

**Comment by AISuperMa** [comment]
> I have tested the Chinese support with the 7B model. Unfortunately, it seems the support of Chinese is extremely poor. (Perhaps increase the parameters can improve the performance in Chinese, but I have no ability to test)

I think if the vocab contains chinese character, it is fine, we can fine-tuning it, but if it doesn't, it is hard to us to do more research in chinese

**Comment by ShomyLiu** [comment]
Hi, I have tested the 6/13/30/65B models with Chinese, the performances are all poor. 
Then I checked the sentencepiece vocab, and found that it contains quite few Chinese tokens.
Hence, maybe we could extend the vocab and then continue pretrain the existing models.

**Comment by feizc** [comment]
Hi, i have tried to fine-tune LLaMA model for better Chinese text generation.
Please refer to: https://github.com/feizc/MLE-LLaMA

**Comment by jspisak** [comment]
Closing this issues - Cool project @feizc !!
