### ISSUE TITLE
Is there a way to fine-tune this model?

### ISSUE THREAD

**Issue by TNTTheLagger** [facebookresearch/llama#221]
> Have you tried changing the gradio interface to use the [gradio chatbot component](https://www.gradio.app/docs/#chatbot-header)?

I think this doesn't quite fit, since LLama is not fine-tuned for chatbot-like capabilities. I think it would definitely be possible (even if it probably doesn't work too well) to use it as a chatbot with some clever prompting. Might be worth a try, thanks for the idea and the feedback.

_Originally posted by @bjoernpl in https://github.com/facebookresearch/llama/issues/4#issuecomment-1454806237_

I want to try and fine-tune this model to see if I can make it into a sort of chatbot.
I have plenty of chat data in json files but I don't know how exactly would I fine-tune the llama model.

Does anyone have any references or tutorials like videos or GitHub repos on this subject?

**Comment by feizc** [comment]
Hi, i have tried for instruct tuning on LLaMa, and provides scripts and alignment datasets : ) .
You can reference for: https://github.com/feizc/MLE-LLaMA

**Comment by FrancescoSaverioZuppichini** [comment]
you can also use lora on the [hugging face peft library](https://github.com/huggingface/peft)

**Comment by zhongjianluxian** [comment]
seems to be duplicate with https://github.com/facebookresearch/llama/issues/23

have you checked out https://github.com/facebookresearch/llama-recipes?
