### ISSUE TITLE
improve LLaMA for multi-language performance

### ISSUE THREAD

**Issue by feizc** [facebookresearch/llama#222]
Thanks for the good works! 

I have tried to improve LLaMa model to generate more fluency Chinese. 
We are inspired that LLaMa have learned good English expression and a little alignment prompt can makes it capture Chinese.

The results are promising in 7B and we call on more people to support testing of larger models. 

Github: https://github.com/feizc/MLE-LLaMA

- [x]  fine-tuning scripts and hyper-parameters setting
- [X]  datasets for fine-grained alignment and instruct tuning
- [X]  interactive gradio and chatbot

**Comment by baketbek** [comment]
这个是微调是吗 ？不是增量预训练

**Comment by darpan-jain** [comment]
Hi @feizc, I went through your [repo](https://github.com/feizc/MLE-LLaMA). It's very well written!
Can you share the code for the gradio app you created to mimic the user chat setting with the fine-tuned LLaMA model?
