### ISSUE TITLE
where is the train file?

### ISSUE THREAD

**Issue by liukaiyueyuo** [facebookresearch/llama#227]
where is the train file? I want to learn how to train.

**Comment by StephennFernandes** [comment]
@liukaiyueyuo hey any luck finding the pretraining docs and scripts ? i am looking forward to actually pretrain the 7B model on my own data on some cloud TPUs would be helpful to find the pretraining scripts

**Comment by bokesyo** [comment]
also interested in training data composition, as it was not mentioned in technical report :)
