### ISSUE TITLE
Could a 20B model be made

### ISSUE THREAD

**Issue by iMacker2020** [facebookresearch/llama#236]
I have a computer with 16GB of RAM and noticed that the 30B model was too much for it to handle. The 13B model does work well with my computer's RAM size. I believe a 20B parameter model might be a better balance between memory requirements and output quality. So I ask if a 20B parameter model could be created.

Thank you.

**Comment by HeadCrab65** [comment]
I'm not from Facebook, but I believe that this could be really unlikely: Training a new model of this scale from scratch would imply a decision from the high floors and a consistent budget, commitment and people being allocated, without any real gain for Facebook.

**Comment by iMacker2020** [comment]
Now I am curious if the community could do it using their computers. If we could break the training up into several manageable chunks that individuals could work on on their own then maybe we won't need to rely on Facebook to do it. Is this possible?

**Comment by HeadCrab65** [comment]
I believe it is technically possible (and there is quite a bit of research in the field), but to the best of my knowledge, nothing too concrete has been done in the realm of large language models yet, so we'll have to wait and see.

**Comment by ef73568466** [comment]
I believe it is technically possible (and there is quite a bit of research in the field)

**Comment by pauldog** [comment]
The easiest solution to your problem is..... to buy some more RAM.

Cost of training a new 20B model:   $1 million
Cost of buying 16GB of RAM       :   $30

To be honest, most people only have 4-8GB of RAM.

**Comment by iMacker2020** [comment]
@pauldog Thanks for the advice. I did find it very interesting that we could run large language models on our own computers. But after trying out Bing Chat and seeing its superior output to about all locally available models I have moved on.
