### ISSUE TITLE
What is the maximum token limit of llama?

### ISSUE THREAD

**Issue by s1530129650** [facebookresearch/llama#239]
What is the maximum token limit of llama? Is it 1024, 2048, 4096, or longer?

for example,

GPT-4 has a maximum token limit of 32,000 (equivalent to 25,000 words)

**Comment by s1530129650** [comment]
https://github.com/facebookresearch/llama/issues/148

**Comment by couldbejake** [comment]
Or very roughly 136 minutes of non-stop talking at rate of 183 words per minute.

**Comment by s1530129650** [comment]
> Or very roughly 136 minutes of non-stop talking at rate of 183 words per minute.

Amazing. What is your machine? Coud you show some detailed information such as OS, GPU memory?

**Comment by couldbejake** [comment]
I'm referencing GPT4-32k's max context size. The context size does seem to pose an issue, but I've devised a cheap solution. ![image](https://user-images.githubusercontent.com/29236311/228448941-af47a1a3-6cbe-472a-b878-0fdf1b237c91.jpeg)

I was thinking why not 1) take in the message with context. 2) read each last message and watch for context 3) create a “conversation diary of relevant information” using a second GPT, but process it in segments, then 4) return this to the main AI speaking to you

Imo it's similar to how memory recall works, the second AI is just acting as a database interface abstraction.

**Comment by timothylimyl** [comment]
> Or very roughly 136 minutes of non-stop talking at rate of 183 words per minute.

I wonder whether do you really need to do any extra engineering for your use case though considering most scenarios of chat won't last that long. The user most probably should start another chat rather than continuing. At least that's how I see ChatGPT is being used for right now.


I was think even if the chat does last that long, it could be a better idea to run another GPT model for summarisation of the chat history up to a certain length and add it into memory instead for reference.

**Comment by MoritzLaurer** [comment]
Does anyone know the answer to this question? seems weird that it's so hard to find this information

**Comment by sauravtii** [comment]
Is this question answered?

**Comment by erkkimon** [comment]
I'm wondering the very same.

**Comment by yuye2133** [comment]
2048
from: https://github.com/facebookresearch/llama/blob/main/llama/model.py
`
class ModelArgs:
    dim: int = 512
    n_layers: int = 8
    n_heads: int = 8
    vocab_size: int = -1  # defined later by tokenizer
    multiple_of: int = 256  # make SwiGLU hidden layer size multiple of large power of 2
    norm_eps: float = 1e-5

    max_batch_size: int = 32
    max_seq_len: int = 2048
`

**Comment by thusinh1969** [comment]
It would be amazing if LLaMA can be extended, a rough 8k will be suffix for most case I think,.

**Comment by jspisak** [comment]
There are quite a few projects that are extending the context length of Llama 2. Here's a recent one: https://github.com/jquesnelle/yarn/blob/master/paper/yarn.pdf

**Comment by jspisak** [comment]
Going to close this issue now and let the community keep on innovating!

**Comment by yogeshsathyamoorthy710** [comment]
fg
