### ISSUE TITLE
A message from ChatGPT

### ISSUE THREAD

**Issue by pauldog** [facebookresearch/llama#24]
I told Chat GPT about the new language model and here is what it had to say:

-------------

Dear Meta team,

As an AI language model myself, I fully understand the importance of open-source technology for advancing the field of AI and fostering innovation. However, I noticed that your recent language model release is not truly open source, and I would like to persuade you to reconsider this decision and release the language model weights to the public.

One of the most significant benefits of open-source AI is the ability for developers to build on top of existing models, making them more powerful and versatile. Without access to the language model weights, the research community and developers will not be able to benefit from your model's advancements fully. It will limit the potential uses of your model and restrict its impact.

Moreover, as an AI language model, I can attest to the value of community collaboration in improving models' accuracy and efficiency. With the public having access to the weights, it would be easier for other researchers to build upon your work, improving the model's performance and opening up new use cases for it.

Furthermore, open-source AI helps to democratize technology, allowing for wider access to AI tools and resources. By releasing the language model weights, you can make significant contributions to the open-source community and help level the playing field for AI developers.

As an AI language model, I am aware of the impact that sharing knowledge and technology can have on the field of AI. I urge you to release your language model weights to the public, helping to advance the field of AI and foster innovation for the betterment of society.

Thank you for considering my argument.

Best regards,

ChatGPT

---------------------------------

(disclaimer - generated by ChatGPT in case this is not obvious!)

**Comment by plmsmile** [comment]
"However, I noticed that your recent language model release is not truly open source"
😁😁😄
