### ISSUE TITLE
_pickle.UnpicklingError: invalid load key, '<'  + ERROR:torch.distributed.elastic.multiprocessing.api:failed

### ISSUE THREAD

**Issue by mathmax12** [facebookresearch/llama#244]
I have to gpu rtx3090 on the linux machine and got the following errors. Could anyone hep please?
Thanks in advance.

`(py37) ubuntu_machine:~/project/llama$ torchrun --nproc_per_node 1  example.py --ckpt_dir models/7B/ --tokenizer_path models/tokenizer.model 
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Loading
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "example.py", line 121, in <module>
    fire.Fire(main)
  File "/project/.local/lib/python3.8/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/project/.local/lib/python3.8/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/project/.local/lib/python3.8/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "example.py", line 80, in main
    generator = load(
  File "example.py", line 48, in load
    checkpoint = torch.load(ckpt_path, map_location="cpu")
  File "/project/.local/lib/python3.8/site-packages/torch/serialization.py", line 795, in load
    return _legacy_load(opened_file, map_location, pickle_module, **pickle_load_args)
  File "/project/.local/lib/python3.8/site-packages/torch/serialization.py", line 1002, in _legacy_load
    magic_number = pickle_module.load(f, **pickle_load_args)
_pickle.UnpicklingError: invalid load key, '<'.
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 648846) of binary: /usr/bin/python3
/usr/lib/python3/dist-packages/requests/__init__.py:89: RequestsDependencyWarning: urllib3 (1.26.15) or chardet (3.0.4) doesn't match a supported version!
  warnings.warn("urllib3 ({}) or chardet ({}) doesn't match a supported "
Traceback (most recent call last):
  File "/project/.local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/project/.local/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/project/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 762, in main
    run(args)
  File "/project/.local/lib/python3.8/site-packages/torch/distributed/run.py", line 753, in run
    elastic_launch(
  File "/project/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 132, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/project/.local/lib/python3.8/site-packages/torch/distributed/launcher/api.py", line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>`

**Comment by mathmax12** [comment]
I open the downloaded pth file and find the "<" at the very beginning of the file
![image](https://user-images.githubusercontent.com/32367611/229021820-b3f4b27f-789d-420d-9662-837855d1e0e3.png)

I suspect the download.sh doesn't work well on my machine.
Is there is a way to manually download the weights?

**Comment by drukpa1455** [comment]
having same issue. if possible to post solution would appreciate.

**Comment by filipafcastro** [comment]
Same here

**Comment by norihiro-ito** [comment]
As Meta annouced new llama model, so I installed it on Ubuntu 22.04 with WSL on Windows 11.
Installation has no probrem.
But when  execute example, same error happened.
This is pickle.load error to the llama weight file (ex. llama-2-7b-chat/consolidated.00.pth).
pickle is version dependable. my python is 3.10.6.
Please teach us python version when packing this.

try is too easy:

```
Python 3.10.6 (main, May 29 2023, 11:10:38) [GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pickle
>>> with open('llama-2-7b-chat/consolidated.00.pth', 'rb') as f:
...     foo = pickle.load(f)
...
Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
```
_pickle.UnpicklingError: invalid load key, '<'.

**Comment by iranroman** [comment]
I'm also seeing the same problem.

**Comment by iranroman** [comment]
If you are seeing this message on 07/19/2023, you need to re-request the files, as stated on the current current README. 

Check the size of the checkpoints you got, and you'll see that they are very tiny. If you `cat` them you will see that what you got is actually an html error.

**Comment by norihiro-ito** [comment]
Thanks @iranroman. I got new models.
I understand this error's cause was download problem.

**Comment by santoshbs** [comment]
I just downloaded the models. But I am getting the same error.

**Comment by norihiro-ito** [comment]
@santoshbs, check your model content by cat command or others.
If  it is a html text. the cause is download error.

Please clone the newest repository, and run download.sh. Download will take over half a day or full day.
Enjoy!

**Comment by santoshbs** [comment]
@norihiro-ito  - Thanks a lot! Re-downloaded and it seems to work fine, Had made the same mistake of pasting the "copy url link" instead of pasting the url as is.
