### ISSUE TITLE
How to fine-tune LLaMA with longer model_max_length and not increase the GPU memory too much?

### ISSUE THREAD

**Issue by 14H034160212** [facebookresearch/llama#250]
Hi,

Is there any way to increase the model_max_length but not increase the GPU memory too much? I have reduced the batch size to `1` and increased the gradient_accumulation_steps to `16`. I am currently using model_max_length as `1024` which I want to increase it to a maxer number. The GPU memory for the following script causes nearly `80` GPU memory for `4 A100` GPUs for each. Thank you very much in advance for any suggestions!
```
CUDA_VISIBLE_DEVICES=4,5,6,7 torchrun --nproc_per_node=4 --master_port=2024 train.py \
   --model_name_or_path llama_7B_hf/llama-7b \
   --data_path alpaca_data.json \
   --bf16 True \
   --output_dir alpaca-7B \
   --num_train_epochs 3 \
   --model_max_length 1024 \
   --per_device_train_batch_size 1 \
   --per_device_eval_batch_size 1 \
   --gradient_accumulation_steps 16 \
   --evaluation_strategy "no" \
   --save_strategy "steps" \
   --save_steps 2000 \
   --save_total_limit 1 \
   --learning_rate 2e-5 \
   --weight_decay 0. \
   --warmup_ratio 0.03 \
   --lr_scheduler_type "cosine" \
   --logging_steps 1 \
   --fsdp "full_shard auto_wrap" \
   --fsdp_transformer_layer_cls_to_wrap 'LlamaDecoderLayer' \
   --tf32 True
```

**Comment by 14H034160212** [comment]
In my case, more GPUs can really help. I can use 8 A100 80GB GPUs to fine-tune the Alpaca-13B.
Here is a link that may be helpful.
https://github.com/tatsu-lab/stanford_alpaca/issues/174#issuecomment-1499248712

**Comment by dittops** [comment]
@14H034160212 Do you have a reference script that can be used to distribute the fine-tuning to multiple A100s?
