### ISSUE TITLE
Possible use for healthcare commercial application

### ISSUE THREAD

**Issue by alex-smith-bind** [facebookresearch/llama#252]
Hi,    I am interested in using Llama as the basis of a further-fine-tuned model to answer questions specific to healthcare and our specific application. My name is Alex Smith, a principal data scientist for a company called Surest that is now a part of United Healthcare.  We are a consumer-centric health insurance that is saving members like myself a huge amount on healthcare.
Specifically, I am wondering if there is a possibility to get permissions to use the GPT4All model, that is built upon your powerful Llama model, for our commercial application.  I believe this could be of great benefit to our members seeking answers to their questions and would be a really cool use case to try out.

Thanks, Alex Smith

**Comment by ejsd1989** [comment]
Hey @alex-smith-bind, thanks for your inquiry. If you haven't already, then I'd suggest you take a look at Llama 2, which is available for free for Research and Commercial Use - https://ai.meta.com/llama/
