### ISSUE TITLE
Plan for non-supported languages!

### ISSUE THREAD

**Issue by AliAkbarBadri** [facebookresearch/llama#254]
Hi, 
As mentioned in the paper, supported languages are bg, ca, cs, da, de, en, es, fr, hr, hu, it, nl, pl, pt, ro, ru, sl, sr, sv, uk.
Is there any plan to support other high-resource languages like Persian in the future Or release the training and preprocessing scripts?

**Comment by jspisak** [comment]
The Llama models thus far have been mainly focused on the english language. We are looking at true multi-linguality for the future but for now there are a lot of community projects that fine tune Llama models to support languages beyond what is currently supported. Thanks!
