### ISSUE TITLE
Download weights for organisation usage

### ISSUE THREAD

**Issue by andrea032** [facebookresearch/llama#255]
Hi, my organisation (investment management company) is looking to adopt LLaMA model in our work. As such, we will need to bring the weights in house. Please advice how we can proceed and if there is a contact person I can reach out to on this.

**Comment by russeree** [comment]
LLaMA weights are non-commercial use only.

**Comment by andrea032** [comment]
Our use case is focused on research. We would like to explore the benefits of large language models in our internal use cases, such as understanding news articles or internal documents. Hope this can be recognized under research, non commercial license. If so, wondering how we can go about bringing the weights in house.

**Comment by russeree** [comment]
https://ai.facebook.com/blog/large-language-model-llama-meta-ai/

Fill out this form, it is the only official way to obtain the weights. Responses are for some very quick and others have not been responded to yet as seen in other issues.

**Comment by ejsd1989** [comment]
Hey @andrea032, thanks for the inquiry. If you haven't already, then I suggest you take a look at Llama 2, which is free for research and commercial use - https://ai.meta.com/llama/
