### ISSUE TITLE
Training field corpora

### ISSUE THREAD

**Issue by lisa563** [facebookresearch/llama#259]
Can I train field corpora based on the LLaMA Model for use in the field. what should I do? Thanks

**Comment by anubop** [comment]
LLama2 is available for commercial use if that was your question. If your question was more pertaining to using your own data to fine tune the model, there are numerous ways to do this - here's a [blog post](https://www.anyscale.com/blog/fine-tuning-llama-2-a-comprehensive-case-study-for-tailoring-models-to-unique-applications) to help you get started :)
