### ISSUE TITLE
Is it ok to use leaked LLaMA for research? 

### ISSUE THREAD

**Issue by sergsb** [facebookresearch/llama#266]
I would like to pose a question: Is it appropriate for the scientific community to utilize LLaMA for research if the application has not been explicitly approved? This inquiry seems to concern numerous conscientious researchers. As many know, the model's weights can be found on torrent, and even more, the link to this torrent is accessible within this repository. The license for these weights permits their use for scientific purposes. According to Yann LeCun, the sole reason LLaMA was not made freely available was due to concerns that the model could "destroy the fabric of society." However, with the leaked model, the circumstances have changed. Those who intend to use LLaMA for malicious purposes now have an advantage, while researchers find themselves in a "gray zone," restrained by licensing complications.

I have two questions to present. First, for the research community, what are your thoughts on using the leaked LLaMA for research from both ethical and legal perspectives? Secondly, I would like to ask the Facebook team to share their standpoint on this matter, given that the model's weights are already _de-facto_ available.

**Comment by dagelf** [comment]
https://docs.google.com/forms/d/e/1FAIpQLSfqNECQnMkycAp2jP4Z9TFX0cGR4uf7b_fBxjY_OjhJILlKGA/viewform

**Comment by walking-octopus** [comment]
I guess there's OpenLLaMA, which aims to retrain the weights from scratch...

**Comment by ejsd1989** [comment]
Thanks for posting your inquiry about this @sergsb. I hope that you were able to get access via the official form and with Llama 2 the access should be much faster - https://ai.meta.com/llama/
