### ISSUE TITLE
what is the context size/context window of LLaMA?

### ISSUE THREAD

**Issue by sauravtii** [facebookresearch/llama#267]
What is the maximum token limit of llama? Is it 1024, 2048, 4096, or longer?

How much can it handle during the inference?

I did find similar issues but no one has really answered the question, so I would appreciate any help I can get.

**Comment by AlyoshaVasilieva** [comment]
https://github.com/facebookresearch/llama/commit/a81fb4e211d6656854a5dd24cf8631dc319234d1

2048

**Comment by sauravtii** [comment]
Thanks @AlyoshaVasilieva, is it the same for all models (7B, 13B, 33B, 65B)?

**Comment by dhirajsuvarna** [comment]
@sauravtii  - did you find the answer to this question? 
Also how to find the context window of various new open source models?

**Comment by dmd404** [comment]
llama: 2048 tokens
llama2: 4096 tokens

**Comment by dmd404** [comment]
> Same for Llama 2? (I can't seem to find an answer)

llama: 2048 tokens
llama2: 4096 tokens

**Comment by ejsd1989** [comment]
Thanks all for the help in responding here and I hope your questions were answered @sauravtii. 
You can also get this information via the model card for Llama 2 - https://github.com/facebookresearch/llama/blob/main/MODEL_CARD.md and the website https://ai.meta.com/llama/
