### ISSUE TITLE
Please give Llama an Apache license for the 7B model.

### ISSUE THREAD

**Issue by pauldog** [facebookresearch/llama#269]
(1) To Mr Zuckerberg, please consider giving the 7B model an Apache license. There are already other opensource models that are about 7B in size that match Llama so there's no harm in releasing 7B model as Apache license. 

(2) Please can you make also 3.5B model with an Apache license.

Thank you Mr Zuckerberg. 🙏

**Comment by ejsd1989** [comment]
Hey @pauldog, thanks for your request/inquiry. Definitely check out Llama 2 which is now free for both research and commercial use - https://ai.meta.com/llama/
