### ISSUE TITLE
There are some uncertainties about the calculations for the prediction.

### ISSUE THREAD

**Issue by zhuweipg99** [facebookresearch/llama#272]
When I was looking at the source code of the generation.py, I found that only the previously calculated token is fed into the model each time. 
```
logits = self.model.forward(tokens[:, prev_pos:cur_pos], prev_pos)
```
Would this result in using only the first few positions of the network that use the transformer module? 
What I mean is that the input position in taring for **[prev_pos : cur_pos]** is **[prev_pos-----prev_pos + len(current token)-1]**. If we follow the above code in generation, the input position becomes **[0----len(current token)- 1]**. 
Wouldn't this affect the predicted output? Or is it because of the power of the model, we don't need to compute the current token within [prev_pos-----prev_pos + len(current token)-1] like we do during training?I know we **cached previous keys&values**, but I still confuse the above problem.

I would greatly appreciate it if someone could help me resolve my confusion.

First Edit：
In the Transformer module, **the parameters at each position are shared**, so we can only pass the last genrated tokens. 
But the model still doesn't know the correct position of the input tokens.

**Comment by woghdwoghd113** [comment]
I'm curious too... please answer..

**Comment by zhuweipg99** [comment]
When I looked at the GPT2 code of Hugging Face's Transformers or the Source GPT code of OpenAI, they used the following code to calculate positions.
```
# Hugging Face
if position_ids is None:
    position_ids = torch.arange(past_length, input_shape[-1] + past_length, dtype=torch.long, device=device)
    position_ids = position_ids.unsqueeze(0).view(-1, input_shape[-1])
#Open AI
 h = tf.gather(wte, X) + tf.gather(wpe, positions_for(X, past_length))
def positions_for(tokens, past_length):
    batch_size = tf.shape(tokens)[0]
    nsteps = tf.shape(tokens)[1]
    return expand_tile(past_length + tf.range(nsteps), batch_size)
```
We can refer to this code [Hugging Face line800-802](https://github.com/huggingface/transformers/blob/main/src/transformers/models/gpt2/modeling_gpt2.py#L800)、[Open AI line157, 141-144](https://github.com/openai/gpt-2/blob/a74da5d99abaaba920de8131d64da2862a8f213b/src/model.py#L141)
