### ISSUE TITLE
Main Results: incorrect analysis in the Research paper

### ISSUE THREAD

**Issue by monaja** [facebookresearch/llama#273]
Hello, 
I finished reading the paper "LLaMA: Open and Efficient Foundation Language Models" and noted an error in reporting of results. 
The following sub-section caught my attention: 

+ Under subsection 3.1 Common Sense Reasoning => you indicated that the LLaMA-65B outperformed Chinchilla-70B on all reported benchmarks but BoolQ but the data in Table 3 shows that LLaMA-65B has outperformed Chinchilla in all benchmarks including BoolQ  ( LLaMA-65B shows 85.3 whereas Chinchilla-70B shows 83.7).

**Comment by kaolin** [comment]
@glample

**Comment by jspisak** [comment]
and @TouvronHugo - do you want to update the paper?
