### ISSUE TITLE
Suddenly 403 Forbidden

### ISSUE THREAD

**Issue by phisad** [facebookresearch/llama#277]
I managed to download the 7B and 13B models; from 30B onwards the URL did suddenly not work anymore, but only returned "Forbidden" (even for the 7B now)...

```
Connecting to dobf1k6cxlizq.cloudfront.net (dobf1k6cxlizq.cloudfront.net)|18.66.9.80|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
ERROR 403: Forbidden.
```

Is this a temporary thing? Is this some kind of traffic threshold on the cloudfront side?

**Comment by BarkaviSJ** [comment]
Same 403 Forbidden error for me. I just got access to weights and am unable to download the weights for any model sizes. 

Connecting to dobf1k6cxlizq.cloudfront.net (dobf1k6cxlizq.cloudfront.net)|18.164.66.34|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
ERROR 403: Forbidden.

**Comment by sergsb** [comment]
I have the same issue.

**Comment by sacrrie** [comment]
Everything 403 for me.

**Comment by Munkyfoot** [comment]
Same! Just got the link yesterday and keep getting "ERROR 403: Forbidden".

**Comment by NiccoBiondi** [comment]
Same here!

**Comment by SamSamhuns** [comment]
Here as well. Tokenizer is all messed up since I got 403 mid download

**Comment by Luxios22** [comment]
I got error like the following not matter from browser or download.sh script:

```xml
<?xml version="1.0" encoding="UTF-8"?><Error><Code>AccessDenied</Code><Message>Access denied</Message></Error>
```

**Comment by slvnwhrl** [comment]
Same issue for me...

**Comment by joshvfleming** [comment]
Same for me. It worked last night, but today linky no worky. 403 Forbidden.

**Comment by CommanderPho** [comment]
Same issue when I tried for the first time today after being approved. Pretty sure I'm doing everything right, I'm glad to see that it seems to be a server thing.

**Comment by kagani** [comment]
Same here.

**Comment by farhadmohsin** [comment]
Same issue here. FWIW, I also just received the link today.

**Comment by wereretot** [comment]
Same issue

**Comment by joannacss** [comment]
same issue.

**Comment by uticu** [comment]
Same here.

**Comment by uticu** [comment]
I downloaded 13B last night, but today I found that the GRAM is not enough, and 403 appeared when I tried to download 7B

**Comment by uticu** [comment]
I will email llmaccess@meta.com for help

**Comment by sqxccdy** [comment]
Same issue. Just got access. Can't download anything.

**Comment by cm2435** [comment]
Bumping as same here running to download 7b.

**Comment by schoi98** [comment]
same here

**Comment by vanessailana** [comment]
I have the same issue. I literally looked at every post.

**Comment by JinL0** [comment]
checkout the torrent downloading option, here is the PR https://github.com/facebookresearch/llama/pull/73 
magnet:?xt=urn:btih:ZXXDAUWYLRUXXBHUYEMS6Q5CE5WA3LVA&dn=LLaMA

**Comment by sacrrie** [comment]
> 

Are you sure this is the legal source?

**Comment by schauppi** [comment]
Same issue here... 403 Forbidden

**Comment by YD-19** [comment]
Same issue here... 403 Forbidden

**Comment by Loufe** [comment]
403 forbidden error here as well

**Comment by Aganonce** [comment]
Same as well. 403 forbidden error.

**Comment by CommanderPho** [comment]
> checkout the torrent downloading option, here is the PR #73 magnet:?xt=urn:btih:ZXXDAUWYLRUXXBHUYEMS6Q5CE5WA3LVA&dn=LLaMA

Is this legal/official? Will I get in trouble downloading this on my university's network?

**Comment by Loufe** [comment]
> > checkout the torrent downloading option, here is the PR #73 magnet:?xt=urn:btih:ZXXDAUWYLRUXXBHUYEMS6Q5CE5WA3LVA&dn=LLaMA
> 
> Is this legal/official? Will I get in trouble downloading this on my university's network?

It is against the TOS. Will you get in trouble? probably not. You should just wait for Meta to fix this issue, though.

**Comment by PraxisWasTaken** [comment]
+1 to the 403

**Comment by vtwoptwo** [comment]
+1 to 403 error

**Comment by siddk** [comment]
+1

**Comment by notron30** [comment]
+1

**Comment by vanessailana** [comment]
When is Meta Going to fix this :(

**Comment by Misaka-9982-coder** [comment]
ERROR 403: Forbidden as well

**Comment by MythraV** [comment]
+1

**Comment by shimosan** [comment]
+1 to 403 error. I sent an email to Meta two days ago. Still waiting for a response.

**Comment by vanessailana** [comment]
I sent two emails to meta.

**Comment by m5a0r7** [comment]
same here. Any updates?

**Comment by mmiakashs** [comment]
I am also getting the same error: `403 Forbidden`
Any solutions or updates?

**Comment by harbinzhang** [comment]
Same for me.

**Comment by Rhitabrat** [comment]
Still not resolved - I am on linux

**Comment by megakitten** [comment]
same issue. on windows

**Comment by youthHan** [comment]
+1 the 403 forbidden error.

**Comment by ShingoHiruma** [comment]
same issue for me on linux

**Comment by LaurineDargaud** [comment]
Same problem here

**Comment by saurabh-singh-rajput** [comment]
Same issue on linux, Any workarounds???

**Comment by Milkdrop** [comment]
Same issue here too :( I thought it was just me...

**Comment by arazd** [comment]
I have the same issue!

**Comment by wejarrard** [comment]
Same issue here

**Comment by HoytWen** [comment]
same issue here

**Comment by Hsg4ustc** [comment]
Same issue

**Comment by Japoneris** [comment]
Same issue here

**Comment by phisad** [comment]
still doesn't work (and link will expire)

**Comment by berttty** [comment]
Hello @timlacroix and @glample,

I hope you're both doing well. I wanted to reach out regarding the links and downloads that we've been experiencing some issues with lately. While we understand that you may not be directly responsible for them, we were hoping you could provide some assistance as the links are set to expire soon.

From what we can tell, it seems that the issue may be related to the server side. Would it be possible for you to provide us with a guideline on what we might have done wrong, or perhaps even report the issue to the appropriate people?

We appreciate any help you can provide, and thank you in advance for your time and attention to this matter.

**Comment by ukkupca** [comment]
Same issue here

**Comment by wereretot** [comment]
At this point, it would be easier to find a torrent of the models and download them there lol.

**Comment by ssdavidson** [comment]
Same issue here

**Comment by Munkyfoot** [comment]
Has anyone received a response from llmaccess@meta.com? My link expires tomorrow and I still haven't heard back.

**Comment by ma08** [comment]
Same issue.

**Comment by shicode** [comment]
@Munkyfoot I have not received any response from llmaccess@meta.com

**Comment by martin-chen-mj** [comment]
Same Issue here as well

**Comment by AurRod** [comment]
Hey all,
We have noticed some server errors that are related to the expiration date of the links. Effectively links expired after a day instead of a week for the emails that were sent out on the 18th of april.
We shall send some new access tokens in the upcoming days to people that received their email access on the 18th, sorry for the inconvenience!

**Comment by BarkaviSJ** [comment]
@AurRod: Thank you for the update. I received the email access on the 18th April. Look forward to receiving the new access.

**Comment by nstylia** [comment]
@AurRod Hey, I am having the same issue today, what appears to be ~24h after receiving my link on the 25th. Should I also reach out to [llmaccess@meta.com](mailto:llmaccess@meta.com) or is this something you are also aware and I should await a new link?

**Comment by liconoc** [comment]
@AurRod Hey, I also got the link on the 25th and it worked for a while until I started getting the same error as everyone else.

**Comment by EmanuelaBoros** [comment]
I got the link earlier April and got the same issue. I have the impression we’ve been ghosted..

**Comment by AurRod** [comment]
It is possible that the same issue also affected the emails that were sent out this week.
We'll make sure that we resend tokens to anyone that had their emails delivered this week and last week.
This should solve everything.

We're not aware of any other server-side issues, but we'll keep you posted.

**Comment by maharun0** [comment]
same issue here

**Comment by shadmantaqi** [comment]
You can solve this issue by downloading the files from torrent. Yes its a legit link.
Check this pull request:
https://github.com/facebookresearch/llama/pull/73/files

**Comment by ZN1010** [comment]
This issue happened to me today.. Stopped when it was downloading 07.pth of the 65B model. I received my access through email yesterday. Thanks a lot for resending the emails! @AurRod

**Comment by AndrewDamico** [comment]
> 

I received my access on 4/25 (yesterday) and this appears to have the same issue (access denied, even though link is 1 day old). No VPN... could be server overload (or bad link)

**Comment by hrxia** [comment]
Happy to receive my access on 4/26, while I came across the same 403 issue today.

**Comment by PawelPerek** [comment]
Same here

**Comment by tjumyk** [comment]
Same here

**Comment by yileitu** [comment]
Same here. I sent email to llmaccess@meta.com but no reply. Sad.

**Comment by msaad02** [comment]
same issue. Received weights 2 days ago, no new email yet.

**Comment by abdulazizab2** [comment]
same issue ...

**Comment by arjunkrishna** [comment]
just received a new link... downloading it now before it gets disabled. :)

**Comment by abdulazizab2** [comment]
@arjunkrishna Did you contact LLaMa's team to resolve the problem ? was the problem with the link ?

**Comment by arjunkrishna** [comment]
> @arjunkrishna Did you contact LLaMa's team to resolve the problem ? was the problem with the link ?

it seems like from one of the messages above... the links expired in a day..  instead of a week.

**Comment by arjunkrishna** [comment]
> Hey all, Thanks for bringing this out to our attention! We have noticed some server errors that are related to the expiration date of the links. Effectively links expired after a day instead of a week for the emails that were sent out on the 18th of april. We shall send some new access tokens in the upcoming days to people that received their email access on the 18th, sorry for the inconvenience!

this message

**Comment by ma08** [comment]
> Hey all, Thanks for bringing this out to our attention! We have noticed some server errors that are related to the expiration date of the links. Effectively links expired after a day instead of a week for the emails that were sent out on the 18th of april. We shall send some new access tokens in the upcoming days to people that received their email access on the 18th, sorry for the inconvenience!

Thank you! I received a new email today and am able to download using the link in it.

**Comment by s4lm-xi** [comment]
Had the same issue as well, but just received a new email and was able to download all models. We can close this issue.

**Comment by cm2435** [comment]
Even after my new signed url it still persists. I think it may be going off a week from my first email rather than the second (the first being sent well over a week ago.)

**Comment by saravananpsg** [comment]
Got the same error.
HTTP request sent, awaiting response... 403 Forbidden
2023-05-31 18:36:49 ERROR 403: Forbidden.

Please resend the link to rsaravanan@u.nus.edu

**Comment by jyeung2** [comment]
Running into the same issue here!

**Comment by SEMNON** [comment]
Same issue! 23 Juli today

**Comment by mardellingram** [comment]
same issue. please resend link to i.ingram@omgroupinc.us

**Comment by irshad001** [comment]
Same issue. Is there any limit on the number of times one can download the models?

**Comment by jisu-hong** [comment]
There's a trap in the sentence for the argument selection,
"Enter the list of models to download without spaces (7B,13B,70B,7B-chat,13B-chat,70B-chat), or press Enter for all:"

You only need to press [Enter] to download the all models. (do not type "all")

**Comment by YoussefKafa** [comment]
I just hit Enter ( to download all ) and it worked

**Comment by Sion1225** [comment]
Same issue.

**Comment by zmykevin** [comment]
Hello, I have encountered the same issue, please resend link to mz2974@columbia.edu

**Comment by ValentinLeblanc** [comment]
Hi , i have the same issue here. Is there any solution to this ?
