### ISSUE TITLE
How do i download the weights, the read md files unclear to me 

### ISSUE THREAD

**Issue by promiseve** [facebookresearch/llama#280]
Hey all, 

I received the link to download and i have already installed the requirement .txt file and the "pip install e .". 
I have changed the url in the  PRESIGNED_URL string to thw received link. 
What should i do with the .sh file to download the weights?

**Comment by andrewmbrown** [comment]
Originally you were supposed to execute the .sh file to download the weights. Currently, I'm pretty sure everybody is encountering 403 (forbidden HTTP reqs) when trying to download. Can anybody confirm?

**Comment by promiseve** [comment]
Yessss, that’s the error I am getting hereOn Apr 24, 2023, at 4:40 PM, Andrew Brown ***@***.***> wrote:﻿
Originally you were supposed to execute the .sh file to download the weights. Currently, I'm pretty sure everybody is encountering 403 (forbidden HTTP reqs) when trying to download. Can anybody confirm?

**Comment by fabiocat93** [comment]
same 403 error here :(

**Comment by fazledyn** [comment]
![image](https://user-images.githubusercontent.com/47297916/234373719-692cfa75-81a4-4103-80e4-7c49f0d1bf50.png)

1. Replace the `PRESIGNED_URL` with the one sent to your email
2. Assign a value to `TARGET_FOLDER` (The folder name you want to have)
3. Run `bash download.sh` or `chmod +x download.sh && ./download.sh`

Hope it helps!

**Comment by fabiocat93** [comment]
> 

thank you @fazledyn for your quick reply. I have followed your instructions, but nothing has changed.

`Resolving dobf1k6cxlizq.cloudfront.net (dobf1k6cxlizq.cloudfront.net)... 13.249.176.163, 13.249.176.53, 13.249.176.194, ...
Connecting to dobf1k6cxlizq.cloudfront.net (dobf1k6cxlizq.cloudfront.net)|13.249.176.163|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-04-25 15:53:26 ERROR 403: Forbidden.

Checking checksums
md5sum: checklist.chk: no properly formatted MD5 checksum lines found`

**Comment by ajinkyapuar** [comment]
> > 
> 
> thank you @fazledyn for your quick reply. I have followed your instructions, but nothing has changed. from the issues, it looks like a general problem...
> 
> ```
> Resolving dobf1k6cxlizq.cloudfront.net (dobf1k6cxlizq.cloudfront.net)... 13.249.176.163, 13.249.176.53, 13.249.176.194, ...
> Connecting to dobf1k6cxlizq.cloudfront.net (dobf1k6cxlizq.cloudfront.net)|13.249.176.163|:443... connected.
> HTTP request sent, awaiting response... 403 Forbidden
> 2023-04-25 15:53:26 ERROR 403: Forbidden.
> 
> Checking checksums
> md5sum: checklist.chk: no properly formatted MD5 checksum lines found
> ```

Hey @fabiocat93 were you able to resolve this?

**Comment by fabiocat93** [comment]
> 

Nope. I didn't hear back from them

**Comment by maharun0** [comment]
> ERROR 403: Forbidden.

Having the same issue

**Comment by maekawatoshiki** [comment]
Same here.

**Comment by abdulazizab2** [comment]
I keep getting ERROR 403: Forbidden. same as everyone

**Comment by Aidiiin** [comment]
Same isssue

**Comment by fazledyn** [comment]
You guys can check out this torrent system [here](https://github.com/facebookresearch/llama/pull/73)

[Torrent Magnet](magnet:?xt=urn:btih:ZXXDAUWYLRUXXBHUYEMS6Q5CE5WA3LVA&dn=LLaMA))

**Comment by JacobFV** [comment]
Works now for me

**Comment by DamithDR** [comment]
Same issue for me
