### ISSUE TITLE
When can I get the llama weight download link after requesting via Google form?

### ISSUE THREAD

**Issue by kgw4073** [facebookresearch/llama#281]
Hey all,

I submitted a request for a weight file download link via a Google Form over a week ago, but I have not received the link yet. Can you please let me know when I can expect to receive the download link?"

**Comment by fazledyn** [comment]
I had filled up the form about 2-3 weeks ago and got the signed URL a while ago. So, I guess you have to be patient.

**Comment by maharun0** [comment]
@fazledyn Is your llama working?

**Comment by fazledyn** [comment]
Hey @maharun0 , I just ran LLaMA using the 'llama.cpp' port on Ryzen 5700G, 16 GB RAM.

![image](https://user-images.githubusercontent.com/47297916/236707559-23e21539-4c4d-4069-8b00-23ed6808f251.jpeg)

**Comment by ejsd1989** [comment]
Thanks all for your responses and posts here. As Llama 2 is now released, I will close this issue. Please feel free to open a new issue if you are running into problems downloading Llama 2 weights. https://ai.meta.com/llama/
