### ISSUE TITLE
Time to release a tokenizer? 

### ISSUE THREAD

**Issue by cranky-cyborg** [facebookresearch/llama#285]
Hi there, I've requested the Tokenizer using the google form a couple times and have not received any email or response. 

Is it possible to let me know, if this is a hold or block on any new requests?

**Comment by fapret** [comment]
When you ask for the model on the google form you also receive the tokenizer if you are selected.
I asked for the model near mid march, and at mid april i received the link to download the model with the tokenizer, so probably they just didnt read your form, or they rejected it.
