### ISSUE TITLE
Does inference use single token

### ISSUE THREAD

**Issue by bastia1989** [facebookresearch/llama#286]
Hi, I have a question, in https://github.com/facebookresearch/llama/blob/57b0eb62de0636e75af471e49e2f1862d908d9d8/llama/generation.py#L42
it seems the input is just a single token since cur_pos = pre_pos+1, is this true? If so, what's the logic here? Thanks.

**Comment by mawilson1234** [comment]
I had the same question :-) ! What happens is that the attention values are cached from the previous step so they don't need to be recalculated at each inference step. See #151.

**Comment by bastia1989** [comment]
> I had the same question :-) ! What happens is that the attention values are cached from the previous step so they don't need to be recalculated at each inference step. See #151.

thanks for pointing it out!
