### ISSUE TITLE
🤩🤩🤩Awesome LLaMA extension with Vision Capability beyond GPT-4.

### ISSUE THREAD

**Issue by vateye** [facebookresearch/llama#288]
I find an awesome work that uses pure LLaMA to understand visual information and support multi-modal chatting. The repo is called mPLUG-Owl, and it states better than miniGPT-4 and LLaVA with only 7B model size. 

By the way, the code and demo are both released! 🤩

Github Link: https://github.com/X-PLUG/mPLUG-Owl

**Comment by ejsd1989** [comment]
@vateye this is awesome, thanks for your contribution! I've gone ahead and closed this but again, thanks!
