### ISSUE TITLE
Embedding shape / Vocab size

### ISSUE THREAD

**Issue by Lrakotoson** [facebookresearch/llama#29]
Hello to all,
Thank you for this work.

I guess anyone who had access to the model weights as well as the authors can answer my question.
I may have missed it in the paper but it seems to me that there is no mention of the embedding shape or just the tokenizer vocabulary size.

**Comment by WikiGenius** [comment]
I have the same question here.
I didn't access the weights yet. so I am asking if any one has.

**Comment by JOHW85** [comment]
The vocab size is 32000.
