### ISSUE TITLE
Download script not working ERROR 403: Forbidden

### ISSUE THREAD

**Issue by dbanda** [facebookresearch/llama#291]
I received my signed link but I can't download the model weights. My wget keeps getting `HTTP request sent, awaiting response... 403 Forbidden`. Is this an intermittent server issue that will be resolved soon, has anyone been able to download it recently? I'm using Ubuntu 20.

**Comment by deciding** [comment]
same here, when using `bash download.sh`, keep getting 403

**Comment by gaborpalko** [comment]
same here:
HTTP request sent, awaiting response... 403 Forbidden                                                                                                                                       
2023-04-27 09:09:06 ERROR 403: Forbidden.

**Comment by JacobFV** [comment]
Working now for me

**Comment by LaurineDargaud** [comment]
It works for me too.
Also, if it can help some of you, since I'm using WSL, I had to convert the `download.sh` file to Unix line endings convention by installing `dos2unix`.

**Comment by deciding** [comment]
I solved the issue by first clicking on the link in the email, then the browser will redirect me to the actual presigned link. I copy this true presigned link in the address bar to the download.sh script. Now it works.

**Comment by dbanda** [comment]
I got a new email. The new link works fine for me. Thanks

**Comment by bretonr** [comment]
> I solved the issue by first clicking on the link in the email, then the browser will redirect me to the actual presigned link. I copy this true presigned link in the address bar to the download.sh script. Now it works.

Thumbs up for this suggestion. This has solved the issue. Perhaps I had missed something, or the instructions were just unclear. I also know that my work filters links and in spite of my best attempt to remove the junk to add to them, perhaps the real thing had been hidden. Anyway, thanks @deciding !
