### ISSUE TITLE
Legality of models fine-tuned on Llama

### ISSUE THREAD

**Issue by MarcoDiMarek** [facebookresearch/llama#299]
I would like to know the official stance on the legality of models that claim to be a fine-tune of Llama.

For example: [gpt4all-lora](https://huggingface.co/nomic-ai/gpt4all-lora) has a GPL 3 license (allows commercial use), yet it is built by fine-tuning Llama (which prohibits commercial use).

**Comment by pauldog** [comment]
We'll only know for certain once the first person gets sued. 

Nobody's been sued so far though...

**Comment by amitsangani** [comment]
Llama 2 has a commercially permissive open license. So this should not be an issue anymore. Closing this issue.
