### ISSUE TITLE
Can pre-trained models be used in commercial applications?

### ISSUE THREAD

**Issue by Franck-Dernoncourt** [facebookresearch/llama#3]
https://twitter.com/ylecun/status/1629189925089296386 ([mirror 1](https://web.archive.org/web/20230224190816/https://twitter.com/ylecun/status/1629189925089296386), [mirror 2](https://archive.ph/E0X67), [mirror 3](https://i.stack.imgur.com/pNiuJ.png)) says yes (with the GPL v3 license):

> Meta is committed to open research and releases all the models the research community under a **GPL v3 license**.

https://github.com/facebookresearch/llama/blob/main/MODEL_CARD.md says no:  

> License Non-commercial bespoke license.

So I'm confused.

**Comment by Franck-Dernoncourt** [comment]
Since the tweet got deleted, here's a [copy](https://web.archive.org/web/20230224190816/https://twitter.com/ylecun/status/1629189925089296386):

![image](https://user-images.githubusercontent.com/15331/221271045-cf7d257a-ead8-47fc-93dc-cb39625e91b1.png)

The deletion makes me think it's not GPL v3 license though.

**Comment by nightvision04** [comment]
Very important question right here.

**Comment by dionator** [comment]
> 



> Since the tweet got deleted right after I opened this issue, here's a [copy](https://web.archive.org/web/20230224190816/https://twitter.com/ylecun/status/1629189925089296386):
> 
> ![image](https://user-images.githubusercontent.com/15331/221271045-cf7d257a-ead8-47fc-93dc-cb39625e91b1.png)
> 
> The deletion makes me think it's not GPL v3 license though.

The LinkedIn Post claiming GPL v3 is still on though:
https://www.linkedin.com/feed/update/urn:li:activity:7034956639526952960/

**Comment by Franck-Dernoncourt** [comment]
@dionator  my bad, typo. Fixed.

**Comment by MesiA** [comment]
I think this issue should be closed:
https://twitter.com/ylecun/status/1629214720405143552
<img width="588" alt="image" src="https://user-images.githubusercontent.com/16356253/221290924-207aef50-a621-449d-b989-4ad3404ca64e.png">

**Comment by dizys** [comment]
> I think this issue should be closed: https://twitter.com/ylecun/status/1629214720405143552 <img alt="image" width="588" src="https://user-images.githubusercontent.com/16356253/221290924-207aef50-a621-449d-b989-4ad3404ca64e.png">

My guess is that the model architecture code is open sourced under GPL3, but the weights ain't. Technically Yann isn't wrong, just that he might not be referring to the trained weights which are gated and not in this repo.

**Comment by andrewssobral** [comment]
Hello everyone,

Has anyone successfully obtained the pre-trained weights? I submitted the form a few days ago, but haven't received a response yet.

**Comment by nightvision04** [comment]
Not yet

**Comment by subramen** [comment]
Llama2 is permissible for commercial use with an important caveat: https://github.com/facebookresearch/llama/blob/main/LICENSE#L65

**Comment by Franck-Dernoncourt** [comment]
Thanks! Another important caveat of Llama 2, from the [license](https://github.com/facebookresearch/llama/blob/6d4c0c290aeec1fa4399694fefb864be5a153bb6/LICENSE#L61C24-L61C24):

> v. You will not use the Llama Materials or any output or results of the Llama Materials to improve any other large language model (excluding Llama 2 or derivative works thereof).
