### ISSUE TITLE
Is there lost the codes of token one-hot encoding?

### ISSUE THREAD

**Issue by loongMin** [facebookresearch/llama#302]
In model.py, the `toekn` is pasted to `self.tok_embeddings = Linear(params.vocab_size, params.dim)` in `forward()` function. But in generation.py, `token` was defined as `tokens = torch.full((bsz, total_len), self.tokenizer.pad_id).cuda().long()`, which will be pasted to `forward()`. Is there loss the code of token one-hot encoding?  thanks very much!!!

**Comment by dongwang218** [comment]
The `self.tok_embeddings` is the embeddings table to convert each int token into float vector. The second statement initialize the input token to be -1 as padding and later -1 will be replaced with int tokens from the prompt. There is no one-hot encoding. The following print out shows an example of processing an input of batch=4, length=8. The max token <32000, the result is the look up in the embedding table.
```
-> h = self.tok_embeddings(tokens)
(Pdb) tokens
tensor([[    1,   306,  4658,   278,  6593,   310,  2834,   338],
        [    1,  3439, 17632,  1925, 29892,   278,  6368,   310],
        [    1,   319, 11473,  2643,   378,   629,   271, 18099],
        [    1,  4103,  9632,  4223,   304,  5176, 29901,    13]])
(Pdb) tokens.shape
torch.Size([4, 8])
(Pdb) self.tok_embeddings.weight.shape
torch.Size([32000, 4096])
(Pdb) next
(Pdb) p h.shape
torch.Size([4, 8, 4096])
(Pdb) p (h[0, 1] - self.tok_embeddings.weight[306]).abs().sum()
tensor(0., grad_fn=<SumBackward0>)
```
