### ISSUE TITLE
same question --> same answer.

### ISSUE THREAD

**Issue by byeongcheoljo** [facebookresearch/llama#307]
I trained the llama model and tried inference.
However, I don't know why this always generates the same answer for the same question.
Please answer to me if you know the reason for this.

write parameter blew:
       temperature=0.9,
        top_p=1,
        top_k=100,
        num_beams=5,

**Comment by kaolin** [comment]
Can you check the seed, possibly it's set to a constant, if you're running from scratch each time?

**Comment by kaolin** [comment]
(closing as stale)
