### ISSUE TITLE
403 Forbidden for downloading the models

### ISSUE THREAD

**Issue by dlcen** [facebookresearch/llama#313]
I got access yesterday, but when I was trying to download the models today, the URL did not work:

```
Connecting to dobf1k6cxlizq.cloudfront.net (dobf1k6cxlizq.cloudfront.net)|65.8.165.183|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-05-26 18:40:22 ERROR 403: Forbidden.
```

I saw some people had the same issue last month, #277. Is this the same problem?

**Comment by muglacia** [comment]
same issue here

**Comment by RohitSingh0007** [comment]
I am having the same issue. I got the access on the 25th but the same error is coming up. I started downloading them today since I was traveling but not working.

**Comment by saravananpsg** [comment]
I have received the access mail on 25th May 2023. I am unable to download the model and tokenizers with the url.

HTTP request sent, awaiting response... 403 Forbidden
2023-05-31 18:36:49 ERROR 403: Forbidden.

md5sum: tokenizer_checklist.chk: no properly formatted MD5 checksum lines found

**Comment by Pari-singh** [comment]
Same issue with the new llama-2 weights. It shows this along with 
Checking checksums
md5sum: checklist.chk: no properly formatted MD5 checksum lines found

**Comment by babucha** [comment]
Same with llama 2

**Comment by wasd96040501** [comment]
Same with llama 2

**Comment by 08Aristodemus24** [comment]
@Pari-singh is the `Checking checksums
md5sum: checklist.chk: no properly formatted MD5 checksum lines found` a problem with how I may downloaded the md5sums.exe file and then adding its directory to my path environment variables or is this a sole issue by Meta?

**Comment by agunapal** [comment]
Hi @dlcen Please check this Download FAQ
https://github.com/facebookresearch/llama/blob/bug-fix-Sep6/Download.md
Please re-open if the issue persists.
