### ISSUE TITLE
Not running, probably user error - Linux Ubuntu

### ISSUE THREAD

**Issue by dcpetit** [facebookresearch/llama#315]
I did the following:

- got the URL to download the model weights, 
- did the installation (pip install -r requirements.txt and pip install -e .), 
- edited the download.sh's value of PRESIGNED_URL="https://dobf1k6cxlizq.cloudfront.net/... 
- edited the TARGET_FOLDER="/home/{USERNAME}/Documents/llama" 

and now not sure what to do. I made the .sh file executable (chmod) and tried to run it. It gives this error:

```
:~/Documents/llama$ sudo ./download.sh 
./download.sh: 8: declare: not found
./download.sh: 10: N_SHARD_DICT[7B]=0: not found
./download.sh: 11: N_SHARD_DICT[13B]=1: not found
./download.sh: 12: N_SHARD_DICT[30B]=3: not found
./download.sh: 13: N_SHARD_DICT[65B]=7: not found
Downloading tokenizer
./download.sh: 16: Bad substitution
```

I tried running the example command: torchrun --nproc_per_node MP example.py --ckpt_dir $TARGET_FOLDER/model_size --tokenizer_path $TARGET_FOLDER/tokenizer.model  and this gave this error:

:~/Documents/llama$ torchrun --nproc_per_node MP example.py --ckpt_dir $TARGET_FOLDER/model_size --tokenizer_path $TARGET_FOLDER/tokenizer.model
Traceback (most recent call last):
  File "/home/{USERNAME}/anaconda3/lib/python3.8/site-packages/torch/distributed/run.py", line 632, in determine_local_world_size
    return int(nproc_per_node)
ValueError: invalid literal for int() with base 10: 'MP'

The above exception was the direct cause of the following exception:

```
Traceback (most recent call last):
  File "/home/{USERNAME}/anaconda3/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/{USERNAME}/anaconda3/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/{USERNAME}/anaconda3/lib/python3.8/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/{USERNAME}/anaconda3/lib/python3.8/site-packages/torch/distributed/run.py", line 784, in run
    config, cmd, cmd_args = config_from_args(args)
  File "/home/{USERNAME}/anaconda3/lib/python3.8/site-packages/torch/distributed/run.py", line 691, in config_from_args
    nproc_per_node = determine_local_world_size(args.nproc_per_node)
  File "/home/{USERNAME}/anaconda3/lib/python3.8/site-packages/torch/distributed/run.py", line 650, in determine_local_world_size
    raise ValueError(f"Unsupported nproc_per_node value: {nproc_per_node}") from e
ValueError: Unsupported nproc_per_node value: MP
```
And the more simple attempt of :~/Documents/llama$ python3 example.py failed with:

```
:~/Documents/llama$ python3 example.py 
ERROR: The function received no value for the required argument: ckpt_dir
Usage: example.py CKPT_DIR TOKENIZER_PATH <flags>
  optional flags:        --temperature | --top_p | --max_seq_len |
                         --max_batch_size

For detailed information on this command, run:
  example.py --help
```
_Some computer information: I am using..._
Ubuntu 23.04, 64-bit
Terminal
Lenovo V145-15AST
AMD A4-9125 RADEON R3, 4 COMPUTE CORES 2C+2G × 2
Linux 6.2.0-20-generic

Let me know if you know what I'm doing wrong (or, unlikely, there's a bug in the code). Thanks!

**Comment by jdm365** [comment]
try `bash download.sh`. (Explicit `bash`)

I had run `sh download.sh` which gave the same error.
I think sh is a more basic shell for Ubuntu.

**Comment by binmosa** [comment]
> 

This works for me. Thanks
