### ISSUE TITLE
face problems when downloading weights

### ISSUE THREAD

**Issue by chenqihong** [facebookresearch/llama#316]
Hi, I got my access link on May 24th, and I tried to download the weight for the model using the modified download.sh file. But I was stuck at 

Connecting to dobf1k6cxlizq.cloudfront.net (dobf1k6cxlizq.cloudfront.net)|108.139.0.22|:443... connected.HTTP request sent, awaiting response... 403 Forbidden2023-05-28 18:07:48 ERROR 403: Forbidden.
Checking checksums

I checked online and noticed that people have similar issues. Some reply that the link expires within a day instead of a week. I don't know if that's the problem. 

Thanks

**Comment by agunapal** [comment]
Hi @chenqihong Please check this Download FAQ
https://github.com/facebookresearch/llama/blob/bug-fix-Sep6/Download.md

Please reopen if the issue persists
