### ISSUE TITLE
download.sh 403 Forbidden

### ISSUE THREAD

**Issue by EslamAli86** [facebookresearch/llama#317]
Hello,

I received the approval link on May 24, 2023. Yet, I get the download forbidden message as below:

Resolving dobf1k6cxlizq.cloudfront.net (dobf1k6cxlizq.cloudfront.net)... 13.225.210.160, 13.225.210.61, 13.225.210.136, ...
Connecting to dobf1k6cxlizq.cloudfront.net (dobf1k6cxlizq.cloudfront.net)|13.225.210.160|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden

I believe the link expired, even though the email said it would expire after seven days. Is there a solution to this error?

Thanks

**Comment by mamarcus64** [comment]
I'm in the same boat - got my approval on 5/24, also getting 403 forbidden.

**Comment by jennywi** [comment]
same for me

**Comment by merav82** [comment]
same date, same forbidden message :-(

**Comment by hssalemi** [comment]
I have the same issue with the link approved on 5/24.

**Comment by JakobJBauer** [comment]
So did you guys send an additional email or what is the way to go?

**Comment by kod02** [comment]
31 May 2023 Çar, saat 02:03 tarihinde hssalemi ***@***.***>
şunu yazdı:

**Comment by JiangWenPL** [comment]
I have the same issue.

**Comment by kod02** [comment]
Lütfen kurulumunda bana yardım edin teşekkür ederim 🙏 🙏🙏🙏



31 May 2023 Çar, saat 04:27 tarihinde Wen Jiang ***@***.***>
şunu yazdı:

**Comment by thirumalairajr** [comment]
+1 , I am also getting 403 error

**Comment by saravananpsg** [comment]
+1 
Got the same error.
----------------
HTTP request sent, awaiting response... 403 Forbidden
2023-05-31 18:36:49 ERROR 403: Forbidden.

md5sum: tokenizer_checklist.chk: no properly formatted MD5 checksum lines found
-----------------

**Comment by halnegheimish** [comment]
I'm having the same error, with the link approved 5/24. It has not been 7 days since the time the link was received.

**Comment by moonshot-s** [comment]
like wise same error HTTP request sent, awaiting response... 403 Forbidden

**Comment by wd496** [comment]
Got approval on 5/24, getting 403 forbidden here. Please resend the url.

**Comment by Ramsenthil** [comment]
same here

**Comment by nickboucher** [comment]
I'm seeing the same 403, but only for `consolidated.0.pth` files; other files downloaded as expected.

LLAMA team, can you resend a new URL?

**Comment by adnanboz** [comment]
Same here. HTTP Error 403: Forbidden

**Comment by danielbichuetti** [comment]
Just received a Llama 2 URL and except the tokenizer, all models are returning 403 Forbidden.

**Comment by robcaulk** [comment]
Encountering same error with Llama 2.

**Comment by NasonZ** [comment]
I have the same issue with llama 2, how do I obtain a new link?

**Comment by saravananpsg** [comment]
> Got the same error. HTTP request sent, awaiting response... 403 Forbidden 2023-05-31 18:36:49 ERROR 403: Forbidden.
> 
> md5sum: tokenizer_checklist.chk: no properly formatted MD5 checksum lines found

Mine got fixed after llama2
