### ISSUE TITLE
Is there a multi-lingual checkpoint for researchers to download

### ISSUE THREAD

**Issue by johnny-richards** [facebookresearch/llama#32]
Hi, I'm an NLP researcher on Chinese datasets, is there a released checkpoint which supports multiple languages or Chinese?

**Comment by mkygogo** [comment]
兄弟搞到模型了么？

**Comment by Frederikmh90** [comment]
Can anyone find information on which languages the models support or found ways to test it already?

**Comment by hurun** [comment]
it is support english right now and can run your local machine.

**Comment by jspisak** [comment]
The Llama models thus far have been mainly focused on the english language. We are looking at tru multi-linguality for the future but for now there are a lot of community projects that fine tune Llama models to support languages like chinese.

Here's a few i found after a quick search:

https://github.com/longyuewangdcu/Chinese-Llama-2
https://huggingface.co/seeledu/Chinese-Llama-2-7B
