### ISSUE TITLE
Missing tokenizer.model

### ISSUE THREAD

**Issue by rajicon** [facebookresearch/llama#323]
I seem to be missing tokenizer.model.  Looking at the code, it seems download.sh should have downloaded this, but for some reason I don't have it.

Unfortunately, my link no longer works, but is there any way for me to get this file?  Or get a renewed link to download everything again?

**Comment by alex5956** [comment]
you have to register in this link => https://docs.google.com/forms/d/e/1FAIpQLSfqNECQnMkycAp2jP4Z9TFX0cGR4uf7b_fBxjY_OjhJILlKGA/viewform

**Comment by dongwang218** [comment]
hi @rajicon, might try to resubmit the request google form. In fact, llama and llama2 are using the same tokenizer.model, llama2 request form is at [here](https://ai.meta.com/resources/models-and-libraries/llama-downloads/).
