### ISSUE TITLE
Llama access URL not received recently

### ISSUE THREAD

**Issue by yileitu** [facebookresearch/llama#330]
I've been actively using Llama and am quite appreciative of your work. However, I'm currently facing an issue. I received an access URL last month, which worked fine, but when I filled out the form last week, I didn't receive any email providing me with a new access URL.

I've double-checked my spam folder and haven't seen any emails from Meta LLaMa team. Can anyone confirm if there are recent cases of successful URL deliveries?

Additionally, I would like to inquire about the validity period of these URLs. From my understanding, it seems the URL expires after 7 days of receipt. Is this truly the case? If so, could you possibly clarify why such a restriction is in place?

Your assistance would be greatly appreciated.

Best regards,
Yilei

**Comment by hatala91** [comment]
Hello Yilei, thanks for submitting this issue. May I ask you to resubmit the form here: https://ai.meta.com/resources/models-and-libraries/llama-downloads/

The unique custom URL provided will remain valid for model downloads for 24 hours, and requests can be submitted multiple times.

**Comment by yileitu** [comment]
Problem no longer exists.
