### ISSUE TITLE
Model Weights Link Access Denied

### ISSUE THREAD

**Issue by omariosc** [facebookresearch/llama#331]
Clicking on the emailed linked leads to page with the following error:

AccessDeniedAccess DeniedXP1ACAE69WX2NG54MjIAG3bSu05Pv+a+XxISullX18c/b7nb8GHPKK7mrJ/WrdK4iNoMtFdtGx0zCtRnsyF3Te7JCYY=

**Comment by mdp18** [comment]
You cant download it by simply clicking the link, but I've been getting a 403 forbidden when using the download script.

**Comment by bretonr** [comment]
I'm having the same issue here. Not sure if it's something wrong with the link or else. I've tried with the download.sh script both on a linux box and my mac.

**Comment by bretonr** [comment]
Note that others have the same issue. See, e.g., https://github.com/facebookresearch/llama/issues/317#issue-1732645165

**Comment by bretonr** [comment]
I found the solution there: https://github.com/facebookresearch/llama/issues/291#issuecomment-1527752583

**Comment by agunapal** [comment]
@omariosc  Please refer to the download FAQ https://github.com/facebookresearch/llama/blob/bug-fix-Sep6/Download.md

**Comment by agunapal** [comment]
Please re-open if issue is not resolved

**Comment by haninimo** [comment]
Hello, I had the issue when I wanted to download the model. Did the meta team provided a solution?
