### ISSUE TITLE
I get the following error when I click on the link in the email

### ISSUE THREAD

**Issue by AnishPahilajani** [facebookresearch/llama#332]
Here is the error:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>0FQQB9R5P8Q4PY3Y</RequestId>
<HostId>vfbb50ppYBrbKrO8p1OmFZtS3uJIgjNUUKlfTL6jUBcB57sAmtc6Q0JCqJbKW5LtxO8vrWhIP9A=</HostId>
</Error>

**Comment by Shaotran** [comment]
Read the email carefully
