### ISSUE TITLE
Running example on MacBookPro

### ISSUE THREAD

**Issue by RhondaFischer** [facebookresearch/llama#333]
I've just received LLAMA access and trying to run the example.py provided.  My MacBookPro with an Apple M1 Pro chip isn't showing as supporting CUDA.   What is needed to make the example.py code work? 

Running this command: 
torchrun --nproc_per_node 1 example.py --device cpu  --ckpt_dir $/Users/rkfische/Dropbox/MetaLLaMA/downloaded_files/7BB/ --tokenizer_path $/Users/rkfische/Dropbox/MetaLLaMA/downloaded_files/tokenizer.model

Here's the error messages received.  

Is CUDA supported by this system?False
CUDA version: None
local rank 0 world size 1
> initializing model parallel with size 1
> initializing ddp with size 1
> initializing pipeline with size 1
Traceback (most recent call last):
  File "/Users/rkfische/Dropbox/MetaLLaMA/example.py", line 123, in <module>
    fire.Fire(main)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/Users/rkfische/Dropbox/MetaLLaMA/example.py", line 82, in main
    generator = load(
  File "/Users/rkfische/Dropbox/MetaLLaMA/example.py", line 44, in load
    assert world_size == len(
AssertionError: Loading a checkpoint for MP=0 but world size is 1
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 17089) of binary: /Library/Frameworks/Python.framework/Versions/3.10/bin/python3.10
Fatal Python error: Segmentation fault

**Comment by Sanchay-T** [comment]
Find generation.py file and either comment out the nlpm line or add a if block on top

**Comment by AhmedIssa11** [comment]
> Find generation.py file and either comment out the nlpm line or add a if block on top

I have the same problem, what do u mean by nlpm line?

**Comment by dongwang218** [comment]
Running on CPU is very slow, but it can be done with this [patch](https://gist.github.com/dongwang218/eaf1aca6dd636b72c400fcf88e4afacc).
* 7b:  ```torchrun --nproc_per_node 1 example_text_completion.py \
--ckpt_dir $HOME/llama2/llama-2-7b \
    --tokenizer_path $HOME/llama2/tokenizer.model \
    --max_seq_len 128 --max_batch_size 4```
* 13b: ```torchrun --nproc_per_node 2 example_text_completion.py \
--ckpt_dir $HOME/llama2/llama-2-13b \
    --tokenizer_path $HOME/llama2/tokenizer.model \
    --max_seq_len 128 --max_batch_size 4```
