### ISSUE TITLE
30B =! 33B

### ISSUE THREAD

**Issue by GbrlOl** [facebookresearch/llama#336]
You show a table that says that the model has 33B, but at the moment of downloading you must specify 30B, why is this?
![imagen_2023-06-22_171429104](https://github.com/facebookresearch/llama/assets/129237692/b8930d52-8142-4fd0-8c5e-355022cdefb7)

PRESIGNED_URL=""             # replace with presigned url from email
MODEL_SIZE="7B,13B,30B,65B"  # edit this list with the model sizes you wish to download
TARGET_FOLDER=""

**Comment by Beomi** [comment]
https://github.com/facebookresearch/llama/issues/49

Indeed typo I guess.

**Comment by macarran** [comment]
Correct, this was a typo and the repo has been updated since then. Thanks for the report.
