### ISSUE TITLE
Link sent by llmaccess@extern.facebookmail.com does not appear to work

### ISSUE THREAD

**Issue by shawnmjones** [facebookresearch/llama#337]
Thank you for accepting my application for access to LLAMA. Unfortunately, the link you sent me does not work. I apologize for posting an issue for this, but was uncertain as to how else I could notify you.

CloudFront responds with:

```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>8H0153ASGCH3V20T</RequestId>
<HostId>
t9QtZYdcRceQMtzSeBq2qXI6p+70IXCXmlu9RbUWUGvrcI9jjfmNelRCEuFgxvAVyWI034UOfuvnongs2V7ZfQ==
</HostId>
</Error>
```

My email address is smjones at lanl.gov.

**Comment by catundchat** [comment]
same error.
`This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>WPTQ4Z4W2GSKHN4P</RequestId>
<HostId>VA2bckqPRuQ9gtGAjBZU+53sFEKvdlPJ9Bu2t215sA+RTQv1WJX2QZyie376EIS0Y5fj8ji4dvo=</HostId>
</Error>`

**Comment by Ryan-Red** [comment]
Same deal here:
```
<Error>
<Code>AccessDenied</Code>
<Message>Access Denied</Message>
<RequestId>M450FX9X5W0ACSAM</RequestId>
<HostId>JmVYO62VYXgq62kT3dPpRiAWeKLigjNDSvgyT5MWvBaHJFbaszRbbYnpRgrXOvr1mseIoJP3tIhIzC/ODhTxfw==</HostId>
<div style="all: initial !important;"/>
</Error>
```

**Comment by xhandar** [comment]
Hello,

I had the same issue, but resolved the problem after following the recommendations posted in https://github.com/facebookresearch/llama/issues/291#issuecomment-1527752583.

The original post that pointed me to this solution is https://github.com/facebookresearch/llama/issues/331#issuecomment-1602218918.

Hope this helps!

**Comment by shawnmjones** [comment]
I apologize. The directions at https://github.com/facebookresearch/llama/blob/main/README.md do state 

```
Once your request is approved, you will receive links to download the tokenizer and model files. Edit the download.sh script with the signed url provided in the email to download the model weights and tokenizer.
```

Thanks to those who pointed this out. I changed the URL in the script and it worked.

Closing...
