### ISSUE TITLE
Do you have plan to traing multi LLM model for public?

### ISSUE THREAD

**Issue by moseshu** [facebookresearch/llama#339]
The Llama 7b,13B,33B,65B is very famous in the whole world. Do you have the plan to expand the work vocab size or multi languages? for example add more chinese ,Korean,Jpanese and so on.

**Comment by albertodepaola** [comment]
Thanks for your interest in expanding Llama's language suppport! At this time, the core team has no plans for such expansions, but we highly encourage community efforts in these areas and there are multiple projects for the languages you mention already.
