### ISSUE TITLE
Required number of GPUs to TRAIN LLaMA 7b 

### ISSUE THREAD

**Issue by aryopg** [facebookresearch/llama#342]
Hi, thank you for the amazing work!

I'm wondering, as I tried to fine-tune LLaMA-7b with 1x NVIDIA A100-80GB to no avail, what is the minimum number of GPUs to train this smallest variant of LLaMA? I managed to train it with 2x NVIDIA A100-80GB, but I wonder if I did something inefficient and maybe I could've trained LLaMA 7b with only 1 GPU. To be more specific, the successful training requires 2x 80GB GPUs to run:
```
Batch size: 8 (4 per GPU)
Sequence length: 128
```
Does this look normal or does it seem that I do something wrong?
Looking forward to hearing back from you!

**Comment by andrewchungg** [comment]
@aryopg It is dependent on the optimizer you use. 

For an optimizer that implements the AdamW algorithm, you need 8 bytes per parameter * 7 billion parameters (for a 7B model) = 56 GB of GPU memory. If you use an optimizer that implements the AdaFactor algorithm, then you need 4 bytes per parameter*  7 billion parameters = 28 GB of GPU memory. With the optimizers of bitsandbytes (like 8 bit AdamW), you would need 2 bytes per parameter, or 14 GB of GPU memory.

Also, you will want to identify the appropriate batch size to achieve optimal performance. Tensor Core requirements define the multiplier based on the dtype and the hardware. For instance, for fp16 data type a multiple of 8 is recommended, unless it’s an A100 GPU, in which case use multiples of 64.

See [Methods an tools for effective training on a single GPU](https://huggingface.co/docs/transformers/perf_train_gpu_one#anatomy-of-models-memory) as well as [NVIDIA's recommendation for batch size](https://docs.nvidia.com/deeplearning/performance/dl-performance-fully-connected/index.html#batch-size) for more detail
