### ISSUE TITLE
Issue downloading weights and Tokenizer

### ISSUE THREAD

**Issue by koweiss** [facebookresearch/llama#343]
I followed the steps in the README and properly edited the download.sh file to include the Target folder where the model weoghts should be downoaded. It returns the errors in the below file. Please advise!

[karimoweiss.txt](https://github.com/facebookresearch/llama/files/11885974/karimoweiss.txt)

**Comment by andrewchungg** [comment]
Looks like you're getting "RuntimeError: Distributed package doesn't have NCCL built in"

Same issue as #50, #104, #112, and #722. 

Feel free to re-open as needed if those don't solve your issue.
