### ISSUE TITLE
no properly formatted MD5 checksum lines found

### ISSUE THREAD

**Issue by fecet** [facebookresearch/llama#351]
I get this while run download script:
```
Checking checksums md5sum: checklist.chk: no properly formatted MD5 checksum lines found
```

It this script require some certain version of md5sum ?

**Comment by giancarlo-metitieri** [comment]
Getting same error

**Comment by deadbits** [comment]
Are all the files it downloads the same size? I'm getting this same issue due to https://github.com/facebookresearch/llama/issues/350

**Comment by giancarlo-metitieri** [comment]
Yes. That's also what I am getting

**Comment by fecet** [comment]
It seems that the download have not been prepared? It turns out that all the downloaded file are html format and they are of course "no properly formatted MD5"


![image](https://github.com/facebookresearch/llama/assets/41792945/637126f6-d2b9-41e5-b25f-741834788bc3)

**Comment by chrismarra** [comment]
When you're pasting in the download URL, make sure that you're copying the URL text as displayed (with a URL of download.llamameta.net), not the fully linked URL (which may be wrapped by a l.facebook.com redirect).

**Comment by taesiri** [comment]
Had the same issue and solved it [here](https://github.com/facebookresearch/llama/issues/352#issuecomment-1640970484). tl;d: first click on the email's link, then copy!

**Comment by grasmanek94** [comment]
The url can contain "Select" at the end, remove that text if you have 403.

https://download.llamameta.net/*?Policy=**********&Key-Pair-Id=******************ZSelect

^ Remove Select:
https://download.llamameta.net/*?Policy=**********&Key-Pair-Id=******************Z

**Comment by itsashishupadhyay** [comment]
Download wget.exe from "[https://eternallybored.org/misc/wget/](https://eternallybored.org/misc/wget/)"  and then unzip and wget.exe to the path (I just replaced my old wget.exe [which wget]). and it started working

**Comment by tintin1926** [comment]
remove 2 files (tokenizer.model and tokenizer_checklist.chk)
and run ./download.sh again

**Comment by mayankpm** [comment]
@tintin1926 this worked, thank you!
