### ISSUE TITLE
[llama2] checksum did NOT match

### ISSUE THREAD

**Issue by elicassion** [facebookresearch/llama#353]
Hi,

I'm getting a warning regarding the checksum when downloading llama2. I'm wondering whether it is problem from the model weights or the checksum itself.

```
Checking checksums
consolidated.00.pth: FAILED
params.json: OK
md5sum: WARNING: 1 computed checksum did NOT match
Downloading llama-2-13b
--2023-07-18 12:50:31--  https://download.llamameta.net/llama-2-13b/consolidated.00.pth
```

Thanks,

**Comment by MatchaOnMuffins** [comment]
Same issue here

**Comment by bsharper** [comment]
It might not have downloaded correctly, check if the resulting files are close to the same size. When I initially tried to download the files, it downloaded really quickly and all of the files were around 48KB, which was suspicious. I checked one of the files and it was an HTML file which displayed the contents in the image I attached.

The fix was to simply copy and paste the URL from the email instead of clicking "Copy link address". The copied and pasted URL worked with `download.sh` to download the files correctly.

![error_download](https://github.com/facebookresearch/llama/assets/3291225/a509080f-ad75-4298-beb7-0c09aa248ef5)

**Comment by elicassion** [comment]
> It might not have downloaded correctly, check if the resulting files are close to the same size. When I initially tried to download the files, it downloaded really quickly and all of the files were around 48KB, which was suspicious. I checked one of the files and it was an HTML file which displayed the contents in the image I attached.
> 
> The fix was to simply copy and paste the URL from the email instead of clicking "Copy link address". The copied and pasted URL worked with `download.sh` to download the files correctly.
> 
> ![error_download](https://user-images.githubusercontent.com/3291225/254345313-a509080f-ad75-4298-beb7-0c09aa248ef5.jpg)

Thanks, but I am sure that I was using the exact text url in the email.

**Comment by chrismarra** [comment]
[elicassion](https://github.com/elicassion) how large are your .pth files that downloaded? You have the right URL domain above, but I just did a test and the models downloaded correctly for me, which makes me think you hit an error and do need to retry.

**Comment by MatchaOnMuffins** [comment]
While you were downloading, did you see any HTTP 403 errors in the output? I encountered a few but it seems that the models are still downloading without any issues.

**Comment by elicassion** [comment]
> [elicassion](https://github.com/elicassion) how large are your .pth files that downloaded? You have the right URL domain above, but I just did a test and the models downloaded correctly for me, which makes me think you hit an error and do need to retry.

I got 12.12G on this file. Would you mind comparing it with what you got?
`./llama-2-13b/consolidated.00.pth         100%[====================================================>]  12.12G  95.6MB/s    in 2m 10s`

**Comment by elicassion** [comment]
> While you were downloading, did you see any HTTP 403 errors in the output? I encountered a few but it seems that the models are still downloading without any issues.

Yes I got 403 errors. Please see #354 .
And I don't think I can figure out a pattern on these failures... 
Could you please check the size of downloaded weights, for example by `ls -lah` ? My failures are giving me empty files like below.
`
drwxrwxr-x  2 4.0K Jul 18 13:19 .
drwxrwxr-x 10 4.0K Jul 18 13:19 ..
-rw-rw-r--  1   0 Jul 18 13:19 checklist.chk
-rw-rw-r--  1   0 Jul 18 13:07 consolidated.00.pth
-rw-rw-r--  1   0 Jul 18 13:07 consolidated.01.pth
-rw-rw-r--  1   0 Jul 18 13:07 consolidated.02.pth
-rw-rw-r--  1 17G Jul 13 19:12 consolidated.03.pth
-rw-rw-r--  1   0 Jul 18 13:13 consolidated.04.pth
-rw-rw-r--  1   0 Jul 18 13:13 consolidated.05.pth
-rw-rw-r--  1   0 Jul 18 13:13 consolidated.06.pth
-rw-rw-r--  1 17G Jul 13 19:15 consolidated.07.pth
-rw-rw-r--  1   0 Jul 18 13:19 params.json
`

**Comment by mtisz** [comment]
Same issue

```Checking checksums
md5sum: checklist.chk: no properly formatted checksum lines found```

**Comment by chrismarra** [comment]
[mtisz](https://github.com/mtisz) - your issue is most likely coming from using the wrong URL. In the email, make sure that you're copying the URL text as displayed (with a URL of download.llamameta.net), not the fully linked URL (which may be wrapped by a l.facebook.com redirect). A properly formatted URL should look like https://download.llamameta.net/*?Policy=____&Signature=____&Key-Pair-Id=____ when pasted in.

**Comment by elicassion** [comment]
> [mtisz](https://github.com/mtisz) - your issue is most likely coming from using the wrong URL. In the email, make sure that you're copying the URL text as displayed (with a URL of download.llamameta.net), not the fully linked URL (which may be wrapped by a l.facebook.com redirect). A properly formatted URL should look like https://download.llamameta.net/*?Policy=____&Signature=____&Key-Pair-Id=____ when pasted in.

Thanks, as I mentioned, I'm exactly using that. https://github.com/facebookresearch/llama/issues/353#issuecomment-1640656795

**Comment by mtisz** [comment]
I am using the right URL. Copied it properly.

**Comment by elicassion** [comment]
See https://github.com/facebookresearch/llama/issues/354#issuecomment-1640719110 for the solution. Thanks @chloebubble.
