### ISSUE TITLE
Unable to download llama2 using pre-signed URL link

### ISSUE THREAD

**Issue by access2rohit** [facebookresearch/llama#360]
I just get an error:
```
ERROR 403: Forbidden
```

I got the link today at 11:39am PST

**Comment by xiaoyunwu** [comment]
same here.

**Comment by Barnett8** [comment]
I also see this error

**Comment by gordonhu608** [comment]
same
2023-07-18 12:24:58 ERROR 403: Forbidden.

Checking checksums
md5sum: checklist.chk: no properly formatted MD5 checksum lines found

**Comment by ghoshi** [comment]
Same here.

Download was working for a while (so I'm sure signature was fine) but it suddenly got cut off in the middle and now it's all

`Connecting to download.llamameta.net (download.llamameta.net)|18.65.206.91|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-07-19 04:22:25 ERROR 403: Forbidden.`

on all models.

**Comment by shi-kejian** [comment]
See issue #350  and #351

**Comment by gordonhu608** [comment]
I exactly tried issue #350 and #351 and used the format URL should be https://download.llamameta.net/*?Policy=...&Signature=....&Key-Pair-Id=... but still not working, 
2023-07-18 12:24:58 ERROR 403: Forbidden.

Checking checksums
md5sum: checklist.chk: no properly formatted MD5 checksum lines found

**Comment by Avmb** [comment]
Same

**Comment by shadoq** [comment]
I see a "browser not supported" error in downloads files from wget.

**Comment by msichterman** [comment]
Seeing these 403 issues too :/

**Comment by sfc-gh-jlangseth** [comment]
me too

**Comment by eloaf** [comment]
Same

**Comment by jingyng** [comment]
For me also, the second link comes instantly and the new link works like a charm.

**Comment by access2rohit** [comment]
got the second link and still fails 
```
HTTP request sent, awaiting response... 302 Found
Location: /jerror [following]
--2023-07-18 19:56:35--  https://urldefense.com/jerror
Reusing existing connection to urldefense.com:443.
HTTP request sent, awaiting response... 400 Bad Request
2023-07-18 19:56:35 ERROR 400: Bad Request.
```

**Comment by jingyng** [comment]
> got the second link and still fails
> 
> ```
> HTTP request sent, awaiting response... 302 Found
> Location: /jerror [following]
> --2023-07-18 19:56:35--  https://urldefense.com/jerror
> Reusing existing connection to urldefense.com:443.
> HTTP request sent, awaiting response... 400 Bad Request
> 2023-07-18 19:56:35 ERROR 400: Bad Request.
> ```

Seems like you have a different error code. It worked for me but the first time the error was 403 Forbidden. Maybe you pasted the url in a wrong format.

**Comment by access2rohit** [comment]
yes! i was copying from the browser that adds urldefense. I just highlighted the txt again and copied it. Download has begun. Will colose once I am able to download completely

**Comment by sfc-gh-jlangseth** [comment]
Requested new link via email, came in <10 min, works now.  Also HF works.

**Comment by syafiq** [comment]
2nd requested link worked for me, but not the first one.

**Comment by sumukshashidhar** [comment]
new link works - got it immediately

**Comment by jingyng** [comment]
> How to re-request the link? The one I got in the email doesn't work. 403 forbidden error.

Just use the same download request form as you did the first time

**Comment by access2rohit** [comment]
Re-Requesting the model params work. I was able to get all the model weights.

**Comment by baltaci-r** [comment]
works here with the second link

**Comment by dennis-d** [comment]
For arch64 just remove if statement in the end  of  `downlaod.sh` and add ```
    (cd ${TARGET_FOLDER}"/${MODEL_FOLDER_PATH}" && md5 checklist.chk```
