### ISSUE TITLE
RLHF versions availability

### ISSUE THREAD

**Issue by shijie-wu** [facebookresearch/llama#368]
Hi,

In both email and `download.sh`, only non-RLHF versions are mentioned. Are the RLHF versions available from the official download?

> Model weights available:
> * Llama-2-7b
> * Llama-2-7b-chat
> * Llama-2-13b
> * Llama-2-13b-chat
> * Llama-2-70b
> * Llama-2-70b-chat

https://github.com/facebookresearch/llama/blob/cfc3fc8c1968d390eb830e65c63865e980873a06/download.sh#L11

**Comment by ruanslv** [comment]
`-chat` = RLHF

**Comment by tomorrmato** [comment]
https://github.com/hpcaitech/ColossalAI has RLHF implementation.

**Comment by chrismarra** [comment]
The -chat models are the RLHF fine-tuned models.

**Comment by tugot17** [comment]
Aren't all the models RLHF'ed for safety and helpfulless by default? Or is just the pre-trained version, without the safety and helpfulness measures, available as well?
