### ISSUE TITLE
download.sh: 12: [[ Not Found (Cannot Download Models)

### ISSUE THREAD

**Issue by blevlabs** [facebookresearch/llama#372]
Hello, I recently gained access to the Llama-2 models, but every time I try to use download.sh, I get the following:

```
Enter the list of models to download without spaces (7B,13B,70B,7B-chat,13B-chat,70B-chat), or press Enter for all: 7B
download.sh: 12: [[: not found
Downloading LICENSE and Acceptable Usage Policy
download.sh: 17: Bad substitution
```
My link is valid, with no extra characters as far as I can tell, so what could be going wrong here?

**Comment by blevlabs** [comment]
Update: I used the source command, and got some outputs but ran into the same issue as this issue ticket:

https://github.com/facebookresearch/llama/issues/373

**Comment by alexanderfrey** [comment]
same here. just press enter for all works though

**Comment by blevlabs** [comment]
@alexanderfrey Really? I tried that and got the same issue as #373

**Comment by thsno02** [comment]
simply use `./download.sh` to execute the download script

**Comment by SAIL-LAB155** [comment]
> simply use `./download.sh` to execute the download script

But it returned: bash: ./download.sh: Permission denied

**Comment by hayunjong83** [comment]
> > simply use `./download.sh` to execute the download script
> 
> But it returned: bash: ./download.sh: Permission denied

Change mode of the script file, and you can execute it.

<code>chmod +x download.sh</code>

<code> ./download.sh</code>

**Comment by Kanan99X** [comment]
> > > simply use `./download.sh` to execute the download script
> > 
> > 
> > But it returned: bash: ./download.sh: Permission denied
> 
> Change mode of the script file, and you can execute it.
> 
> `chmod +x download.sh`
> 
> ` ./download.sh`

Just logged in to say thanks, this solved my issue as well.

**Comment by shaunxu** [comment]
use `bash ./download.sh` rather than `sh ./download.sh` in my case.

**Comment by ValentinBancel** [comment]
Same I use Bash and not sh and it works

**Comment by FuzzLightyear** [comment]
Using wsl, bash wasn't working and sh was half-working. Here was the error message when trying to select the models to download (using sh)
```shell
: bad variable named: MODEL_SIZE
: not found: 12:
download.sh: 22: Syntax error: word unexpected (expecting "do")
```
And here is the error when using bash
```bash
download.sh: line 2: $'\r': command not found
download.sh: line 5: $'\r': command not found
': not a valid identifier: `PRESIGNED_URL

': not a valid identifier: `MODEL_SIZE
download.sh: line 12: $'\r': command not found
download.sh: line 22: syntax error near unexpected token `$'do\r''
'ownload.sh: line 22: `do
```
Then I tried just doing `./download.sh` and got the following:
```
-bash: ./download.sh: /bin/bash^M: bad interpreter: No such file or directory
```

Looking this up led to the solution. It had to do with me being on Windows (and in the windows directory) despite using wsl. The **solution** for me was executing:
```bash
sed -i -e 's/\r$//' download.sh
```
in the top level of the repo.

**Comment by bluedenim** [comment]
Looks like nowadays they want you to use their "llama" package to download

```
pip install llama-stack -U
llama model list
llama model download --source meta --model-id {MODEL ID from the list}
```

However, if anyone's interested, the syntax used for the `if` statement in the script is inconsistent:

```
if [[ $MODEL_SIZE == "" ]]; then
    MODEL_SIZE="7B,13B,70B,7B-chat,13B-chat,70B-chat"
fi

...

  if [ "$CPU_ARCH" = "arm64" ]; then
    (cd ${TARGET_FOLDER} && md5 tokenizer_checklist.chk)
  else
    (cd ${TARGET_FOLDER} && md5sum -c tokenizer_checklist.chk)
  fi
```

The 2nd `if [ ... ]` format works. The 1st `if [[ ... ]]` doesn't (it works for **zsh** but not **bash**).

Changing the above to:
```
if [ $MODEL_SIZE = "" ]; then
    MODEL_SIZE="7B,13B,70B,7B-chat,13B-chat,70B-chat"
fi
```

will get past the error.
