### ISSUE TITLE
Request granted yet 403 Forbidden

### ISSUE THREAD

**Issue by Bipasha-banerjee** [facebookresearch/llama#383]
I was granted llama2 model weight access (bipashabanerjee@vt.edu) around 8 PM EST on Jul 18. I am getting 403 Forbidden when I try to download any/all of the models. 

Along with 403 Forbidden, I also got the following error:
 checklist.chk: no properly formatted MD5 checksum lines found.

**Comment by RunsenXu** [comment]
Same here.

**Comment by omarsar** [comment]
having the same issue here

**Comment by marksher** [comment]
samsies :)  im sure its wild over there right now, so good luck!

error message: ```Resolving download.llamameta.net (download.llamameta.net)... xx.xxx.x.xx, xx.xx.xxx.xx,xx.xx.xxx.xx, ...
Connecting to download.llamameta.net (download.llamameta.net)|18.165.9.86|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-07-18 21:32:35 ERROR 403: Forbidden.```

**Comment by RunsenXu** [comment]
Hi, request a link once again, and it works. Meta approve my second request very quickly.

**Comment by elicassion** [comment]
See #354

**Comment by Bipasha-banerjee** [comment]
> See #354

Thanks! It

**Comment by Bipasha-banerjee** [comment]
Worked with hugging face.
