### ISSUE TITLE
What is the difference between a model with the suffix "chat" and one without it?

### ISSUE THREAD

**Issue by cyc00518** [facebookresearch/llama#385]
As mentioned, any assistance would be greatly appreciated. Thank you very much!

**Comment by missflash** [comment]
As explained in the following page, suffix chat models are optimized for **dialogue use cases**.

https://huggingface.co/meta-llama/Llama-2-70b-chat
> Our fine-tuned LLMs, called Llama-2-Chat, are optimized for dialogue use cases. Llama-2-Chat models outperform open-source chat models on most benchmarks we tested, and in our human evaluations for helpfulness and safety, are on par with some popular closed-source models like ChatGPT and PaLM.

**Comment by cyc00518** [comment]
Sorry, I missed that  page.
