### ISSUE TITLE
Incorrect upload of meta-llama/Llama-2-13b-chat-hf model on Huggingface

### ISSUE THREAD

**Issue by iseesaw** [facebookresearch/llama#386]
It seems that there might be an error in the upload of [meta-llama/Llama-2-13b-chat-hf](https://huggingface.co/meta-llama/Llama-2-13b-chat-hf/tree/main) on Huggingface. The sizes do not match up. 

The [13b-hf](https://huggingface.co/meta-llama/Llama-2-13b-hf/tree/main) model contains 6 checkpoints, approximately 52GB in total, whereas the [13b-chat-hf](https://huggingface.co/meta-llama/Llama-2-13b-chat-hf/tree/main) model only includes 3 checkpoints, around 26GB (same as [7b-hf](https://huggingface.co/meta-llama/Llama-2-7b-hf/tree/main) and [7b-chat-hf](https://huggingface.co/meta-llama/Llama-2-7b-chat-hf/tree/main)). 

Could you please confirm if there was an error in the upload of [meta-llama/Llama-2-13b-chat-hf](https://huggingface.co/meta-llama/Llama-2-13b-chat-hf/tree/main)?

**Comment by Penglikai** [comment]
Same question here

**Comment by ArthurZucker** [comment]
Yes! The checkpoints are in float 32 (the .bin ones) while the safetensors are in float16. Re-uploading now!

**Comment by Colengc** [comment]
This is also the case for Llama-2-70b-hf as well, right?  The safetensors are only ~150G, while the pytorch_model files are ~300G.

**Comment by ArthurZucker** [comment]
Yes, updating this one now!

**Comment by ArthurZucker** [comment]
Fixed!
