### ISSUE TITLE
How many blocks of 80g a100 are needed to fine-tune the 70b model

### ISSUE THREAD

**Issue by BEILOP** [facebookresearch/llama#389]

**Comment by varunvummadi** [comment]
I would assume, you would need roughly 16 GPUs, we are experimenting on finetuning the 70B model and lyk once we succeed

**Comment by anshoomehra** [comment]
@varunvummadi  would you be able to share the fine-tuning script?

**Comment by andrewchungg** [comment]
@anshoomehra You can find the scripts for finetuning and inference at https://github.com/facebookresearch/llama-recipes

**Comment by andrewchungg** [comment]
@BEILOP Feel free to re-open if you feel like you need more information.
