### ISSUE TITLE
Whether transformers was used？

### ISSUE THREAD

**Issue by hywchina** [facebookresearch/llama#393]
Thank you for open sourcing these models. Have you used the open source library: transformers？

**Comment by macarran** [comment]
@hywchina thanks for the feedback. Is your question about HuggingFace's transformers library?
If so, that's generally used as a tool to train pre-trained models and can certainly be used with llama. I will mark this issue as resolved, if you have specific questions about the transformers library I'd recommend their repo: https://github.com/huggingface/transformers
