### ISSUE TITLE
No config.json in meta-llama/Llama-2-7b

### ISSUE THREAD

**Issue by wuhuaguocao** [facebookresearch/llama#394]
I downloaded the model from the huggingface.
And I tested it with the following code:
``` python
import torch
from transformers import LlamaForCausalLM, LlamaTokenizer

model_id="/PATH/to/Llama-2-7b"

tokenizer = LlamaTokenizer.from_pretrained(model_id)
# model =LlamaForCausalLM.from_pretrained(model_id)
model =LlamaForCausalLM.from_pretrained(model_id, load_in_8bit=True, device_map='auto', torch_dtype=torch.float16)
# model = LlamaForCausalLM()
```
Then I got the following output:
```
OSError: /PATH/to/Llama-2-7b does not appear to have a file named config.json. 
```

**Comment by nakarin** [comment]
You should load model that converted to HF. such as "meta-llama/Llama-2-7b-chat-hf".

**Comment by wuhuaguocao** [comment]
> You should load model that converted to HF. such as "meta-llama/Llama-2-7b-chat-hf".

Sorry, I am still confused. Could you kindly clarify whether I should download "meta-llama/Llama-2-7b-hf" instead of "meta-llama/Llama-2-7b"?

**Comment by nakarin** [comment]
> Sorry, I am still confused. Could you kindly clarify whether I should download "meta-llama/Llama-2-7b-hf" instead of "meta-llama/Llama-2-7b"?

Yes.

**Comment by romilgoel** [comment]
But how can you load "meta-llama/Llama-2-7b" with is not fine tuned on chat ?

**Comment by nakarin** [comment]
> But how can you load "meta-llama/Llama-2-7b" with is not fine tuned on chat ?

May be you should register to access the model.

**Comment by simeneide** [comment]
@nakarin  This seems to work for me

```
from transformers import AutoModelForCausalLM, AutoTokenizer

model_id="meta-llama/Llama-2-7b-hf"

tokenizer = AutoTokenizer.from_pretrained(model_id)
import torch
model =AutoModelForCausalLM.from_pretrained(model_id, load_in_8bit=True, device_map='auto', torch_dtype=torch.float16)
```

**Comment by yudhiesh** [comment]
> But how can you load "meta-llama/Llama-2-7b" with is not fine tuned on chat ?

As the other comments mention you just need to use the models that are converted to Huggingface i.e., have `hf` in them. These are the `Llama2-hf` and `Llama2-chat-hf` models only.

**Comment by bholagabbar** [comment]
Just look at the official repo, they have a chat completion example: https://github.com/facebookresearch/llama/blob/main/example_text_completion.py

Just clone the repo and pip install it

**Comment by flaviobrienza** [comment]
It says that a PRO subscription is required.

**Comment by flaviobrienza** [comment]
> You should load model that converted to HF. such as "meta-llama/Llama-2-7b-chat-hf".

To do this a Pro account is needed.

**Comment by arazd** [comment]
I was able to resolve this by upgrading my huggingface to 4.28.1 (before that I was using dev version, which threw out this error)

**Comment by alokkrsahu** [comment]
> I downloaded the model from the huggingface. And I tested it with the following code:
> 
> ```python
> import torch
> from transformers import LlamaForCausalLM, LlamaTokenizer
> 
> model_id="/PATH/to/Llama-2-7b"
> 
> tokenizer = LlamaTokenizer.from_pretrained(model_id)
> # model =LlamaForCausalLM.from_pretrained(model_id)
> model =LlamaForCausalLM.from_pretrained(model_id, load_in_8bit=True, device_map='auto', torch_dtype=torch.float16)
> # model = LlamaForCausalLM()
> ```
> 
> Then I got the following output:
> 
> ```
> OSError: /PATH/to/Llama-2-7b does not appear to have a file named config.json. 
> ```

Hi @wuhuaguocao . I am facing the same issue. Were you able to resolve it? Please let me know.

**Comment by A-Ahmad98** [comment]
I also downloaded the weights using the [meta form](https://ai.meta.com/resources/models-and-libraries/llama-downloads/). I was facing the same issue. I converted the weights to hf using the following code after seeing parts of it commented in their quickstart example.
```
!pip install llama-recipes transformers datasets accelerate sentencepiece protobuf==3.20 py7zr scipy peft bitsandbytes fire torch_tb_profiler ipywidgets
TRANSFORM="""`python -c "import transformers;print('/'.join(transformers.__file__.split('/')[:-1])+'/models/llama/convert_llama_weights_to_hf.py')"`"""
model_dir = './models'
model_size = '7Bf'
hf_model_dir = './hf_models/llama-2-7B-chat'
!python $TRANSFORM --input_dir $model_dir --model_size $model_size --output_dir `$hf_model_dir` 
```
The model_dir is the path to the directory which the weights have been downloaded to, it should contain the tokenizer.model and the directories with the checkpoints like llama-2-7B.
model_size configures for the specific model weights which is to be converted. It also checks for the weights in the subfolder of model_dir with name model_size. So I renamed the directories to the keywords available in the script. For example llama-2-7B-chat was renamed to 7Bf and llama-2-7B was renamed to 7B and so on.
That got the code working in my case by using the hf_model_dir here as the model_id.

**Comment by xens** [comment]
> I also downloaded the weights using the [meta form](https://ai.meta.com/resources/models-and-libraries/llama-downloads/). I was facing the same issue. I converted the weights to hf using the following code after seeing parts of it commented in their quickstart example.
> 
> ```
> !pip install llama-recipes transformers datasets accelerate sentencepiece protobuf==3.20 py7zr scipy peft bitsandbytes fire torch_tb_profiler ipywidgets
> TRANSFORM="""`python -c "import transformers;print('/'.join(transformers.__file__.split('/')[:-1])+'/models/llama/convert_llama_weights_to_hf.py')"`"""
> model_dir = './models'
> model_size = '7Bf'
> hf_model_dir = './hf_models/llama-2-7B-chat'
> !python $TRANSFORM --input_dir $model_dir --model_size $model_size --output_dir `$hf_model_dir` 
> ```
> 
> The model_dir is the path to the directory which the weights have been downloaded to, it should contain the tokenizer.model and the directories with the checkpoints like llama-2-7B. model_size configures for the specific model weights which is to be converted. It also checks for the weights in the subfolder of model_dir with name model_size. So I renamed the directories to the keywords available in the script. For example llama-2-7B-chat was renamed to 7Bf and llama-2-7B was renamed to 7B and so on. That got the code working in my case by using the hf_model_dir here as the model_id.

I confirm, I was able to convert the model downloaded from meta's download.sh, I've followed the example provided here https://github.com/facebookresearch/llama-recipes?tab=readme-ov-file#model-conversion-to-hugging-face.

**Comment by TanzeelAbbas** [comment]
same issue:

OSError: NousResearch/Llama-2-7b-chat-hf does not appear to have a file named config.json. Checkout 'https://huggingface.co/NousResearch/Llama-2-7b-chat-hf/tree/None' for available files.

**Comment by langxinspieder** [comment]
I meet the same question.OSError: /PATH/to/Llama-2-7b does not appear to have a file named config.json. 
"llama2-7b" is false,But “llama-2-7b-hf”is correct.
what is difference  between llama2-7b and llama2-7b-hf? 
maybe I can use the method "https://github.com/facebookresearch/llama-recipes?tab=readme-ov-file#model-conversion-to-hugging-face."
Is the converted version the same as the llama2-hf downloaded from the official website? Or is it different?

**Comment by hdnh2006** [comment]
> I meet the same question.OSError: /PATH/to/Llama-2-7b does not appear to have a file named config.json. "llama2-7b" is false,But “llama-2-7b-hf”is correct. what is difference between llama2-7b and llama2-7b-hf? maybe I can use the method "https://github.com/facebookresearch/llama-recipes?tab=readme-ov-file#model-conversion-to-hugging-face." Is the converted version the same as the llama2-hf downloaded from the official website? Or is it different?

Exactly, they are showing how to retrain the model using hugging face format but the forgot to mention that in the notebook.

**Comment by langxinspieder** [comment]
Great！ I have got a lot~




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "meta-llama/llama"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年10月28日(星期一) 晚上8:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [meta-llama/llama] No config.json in meta-llama/Llama-2-7b (Issue #394)





  
I meet the same question.OSError: /PATH/to/Llama-2-7b does not appear to have a file named config.json. "llama2-7b" is false,But “llama-2-7b-hf”is correct. what is difference between llama2-7b and llama2-7b-hf? maybe I can use the method "https://github.com/facebookresearch/llama-recipes?tab=readme-ov-file#model-conversion-to-hugging-face." Is the converted version the same as the llama2-hf downloaded from the official website? Or is it different?
  
Exactly, they are showing how to retrain the model using hugging face format but the forgot to mention that in the notebook.
