### ISSUE TITLE
Unable to run example_chat_completion.py

### ISSUE THREAD

**Issue by yash9439** [facebookresearch/llama#396]
ModuleNotFoundError: No module named 'fire'
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 2553) of binary: /usr/bin/python3
Traceback (most recent call last):
  File "/home/ubuntu/.local/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/ubuntu/.local/lib/python3.10/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example_chat_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------

Also the fire module is installed, then also its showing that its not installed. I am doing this on a aws ec2 instance

**Comment by nicolasembleton** [comment]
Have you ran `pip install -r requirements.txt` first? If not, can you try? There could be conflicts between different python paths.

**Comment by kuangshengkai** [comment]
I come across this error as well, with fire-0.5 installed by pip3. I am using conda environment with Python 3.10.x. And when I entered the python interpreter and then tried `import fire`,  it succeeded.

**Comment by agunapal** [comment]
Hi @yash9439 Please make sure you have no conflicting dependencies.
I have created a conda venv, installed pytorch (with CUDA) followed the instructions for install . I am able to run the script successfully

**Comment by MatousAc** [comment]
> Have you ran `pip install -r requirements.txt` first? If not, can you try? There could be conflicts between different python paths.

> Hi @yash9439 Please make sure you have no conflicting dependencies. I have created a conda venv, installed pytorch (with CUDA) followed the instructions for install . I am able to run the script successfully

So I have tried both of these, but a fresh environment did not help me. I still get a `ModuleNotFoundError: No module named 'fire'` error.

**Comment by MatousAc** [comment]
Okay. yeah same here. Luckily, the HuggingFace ecosystem of models and libraries has worked well for me, so K recommend that to anyone else with the same issue.
