### ISSUE TITLE
The experimental results in the llama paper cannot be reproduced.

### ISSUE THREAD

**Issue by luoxindi** [facebookresearch/llama#398]
Hello, thank you for your contributions to the development of the large language model. 
While testing Llama7b on the Openbookqa dataset, I noticed that the results differ from the ones reported in the original paper. I treated it as a text completion task, iterating through all candidate answers to find the one with the minimum loss as the correct result. However, the accuracy was only 38.4%, whereas the original paper reported 57.2%. I would like to inquire about the experimental setup used in the original paper.

**Comment by justinphan3110** [comment]
Got the same performance gaps for both full answer logprobs and answer choice label. Can you please share the correct template was used for OBQA?

**Comment by andrewPoulton** [comment]
Ah right, that's my bad - I should have looked more closely. Ever since GPT-3 it has been common to evaluate OBQA using a normalized version of log probs (see Section 2.4 in that paper), since they found using that method improved perf on the dev set.

**Comment by justinphan3110** [comment]
Thank you for your response, 
I tried implement based on the GPT-3 template, acc_norm by length will give a Llama2-7b ~45 accuracy. OpenbookQA implementations from [lm-eval-harness](https://github.com/EleutherAI/lm-evaluation-harness/blob/e81d3cce155e93ba2445068767c738891ad97024/lm_eval/tasks/openbookqa.py#L30) also give around ~45 after normalized for both 7b and 13b models.
