### ISSUE TITLE
Starting example_chat_completion.py on M1 Mac drops errors

### ISSUE THREAD

**Issue by nasinasi** [facebookresearch/llama#404]
Hi there,

Download and installation works great, but I got errors with examples. Here is what I did: 
- I created and activated a conda environment and installed necessary dependencies
- pip install -e .

and copy paste the example. I got this. Any idea, what I did wrong?:

(llama2) $ torchrun --nproc_per_node 1 example_chat_completion.py     --ckpt_dir llama-2-7b-chat/     --tokenizer_path tokenizer.model     --max_seq_len 512 --max_batch_size 4
NOTE: Redirects are currently not supported in Windows or MacOs.
Traceback (most recent call last):
  File "/ai/llama2/llama/example_chat_completion.py", line 73, in <module>
    fire.Fire(main)
  File "/opt/homebrew/lib/python3.11/site-packages/fire/core.py", line 141, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/fire/core.py", line 475, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/fire/core.py", line 691, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/ai/llama2/llama/example_chat_completion.py", line 20, in main
    generator = Llama.build(
                ^^^^^^^^^^^^
  File "/ai/llama2/llama/llama/generation.py", line 62, in build
    torch.distributed.init_process_group("nccl")
  File "/opt/homebrew/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 907, in init_process_group
    default_pg = _new_process_group_helper(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/distributed/distributed_c10d.py", line 1013, in _new_process_group_helper
    raise RuntimeError("Distributed package doesn't have NCCL " "built in")
RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 7780) of binary: /opt/homebrew/opt/python@3.11/bin/python3.11
Traceback (most recent call last):
  File "/opt/homebrew/bin/torchrun", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/opt/homebrew/lib/python3.11/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/opt/homebrew/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/homebrew/lib/python3.11/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example_chat_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-07-19_13:50:49
  host      : host.local
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 7780)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

Any advice is highly appreciated, thanks
Nasinasi

**Comment by krychu** [comment]
The official implementation requires CUDA. I've written a simple CPU adaptation: https://github.com/krychu/llama. Bear in mind that the official implementation might add CPU support at some point, so good to keep an eye on it.

**Comment by pzim-devdata** [comment]
Thank you so much @krychu !!!
I have solved this error message because I didn't have an AMD or Nvidia graphic card, so I have installed the cpu version by installing this : `https://github.com/krychu/llama` instead of `https://github.com/facebookresearch/llama`
Complete process to install : 
1. download the original version of Llama from : `https://github.com/facebookresearch/llama` and extract it to a `llama-main` folder
2. download th cpu version from : `https://github.com/krychu/llama` and extract it and replace files in the `llama-main` folder
3. run the `download.sh` script in a terminal, passing the URL provided when prompted to start the download
4. go to the `llama-main` folder
5. cretate an Python3 env : `python3 -m venv env` and activate it : `source env/bin/activate`
6. install the cpu version of pytorch : `python3 -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu #pour la version cpu`
7. install dependencies off llama : `python3 -m pip install -e .`
8. run if you have downloaded llama-2-7b : 
```
torchrun --nproc_per_node 1 example_text_completion.py \
    --ckpt_dir llama-2-7b/ \
    --tokenizer_path tokenizer.model \
    --max_seq_len 128 --max_batch_size 1 #(instead of 4)
```

**Comment by alex5956** [comment]
> The official implementation requires CUDA. I've written a simple CPU adaptation: https://github.com/krychu/llama. Bear in mind that the official implementation might add CPU support at some point, so good to keep an eye on it.

what did you modified ?

**Comment by albertodepaola** [comment]
Thanks for your question, closing as it's solved.

**Comment by ayyanztech** [comment]
> Thank you so much @krychu !!! I have solved this error message because I didn't have an AMD or Nvidia graphic card, so I have installed the cpu version by installing this : `https://github.com/krychu/llama` instead of `https://github.com/facebookresearch/llama` Complete process to install :
> 
> 1. download the original version of Llama from : `https://github.com/facebookresearch/llama` and extract it to a `llama-main` folder
> 2. download th cpu version from : `https://github.com/krychu/llama` and extract it and replace files in the `llama-main` folder
> 3. run the `download.sh` script in a terminal, passing the URL provided when prompted to start the download
> 4. go to the `llama-main` folder
> 5. cretate an Python3 env : `python3 -m venv env` and activate it : `source env/bin/activate`
> 6. install the cpu version of pytorch : `python3 -m pip install torch torchvision torchaudio --index-url https://download.pytorch.org/whl/cpu #pour la version cpu`
> 7. install dependencies off llama : `python3 -m pip install -e .`
> 8. run if you have downloaded llama-2-7b :
> 
> ```
> torchrun --nproc_per_node 1 example_text_completion.py \
>     --ckpt_dir llama-2-7b/ \
>     --tokenizer_path tokenizer.model \
>     --max_seq_len 128 --max_batch_size 1 #(instead of 4)
> ```
Do i need to redownload the whole model again>?
