### ISSUE TITLE
README.md is executable, `download.sh` is not

### ISSUE THREAD

**Issue by jflatow** [facebookresearch/llama#409]
Cloning the repo, it looks like `./download.sh` couldn't really work as it is not executable, but `README.md` is (as is `requirements.txt`), which seems like a mistake.

**Comment by AhmedIssa11** [comment]
Set execute permission on your script using chmod command :
`chmod +x download.sh`
To run your script :
`./download.sh`
OR
`sh download.sh`
OR
`bash download.sh`

**Comment by jflatow** [comment]
> Set execute permission on your script using chmod command : `chmod +x download.sh` To run your script : `./download.sh` OR `sh download.sh` OR `bash download.sh`

Those are helpful if anyone is blocked by this, but it's not really the issue being reported here

**Comment by kaolin** [comment]
addressing here ~ https://github.com/facebookresearch/llama/commit/51ff3c7a520babba653c94c716fc608b200e9c3e
