### ISSUE TITLE
Error on download.sh download.sh: 23: Syntax error:

### ISSUE THREAD

**Issue by barrettab** [facebookresearch/llama#412]
When running the download.sh script I am getting a syntax error 

```
: bad variable named: PRESIGNED_URL

Enter the list of models to download without spaces (7B,13B,70B,7B-chat,13B-chat,70B-chat), or press Enter for all: 
: bad variable named: MODEL_SIZE
: not found: 11:
download.sh: 23: Syntax error: word unexpected (expecting "then")
```

**Comment by arnestl** [comment]
Cloning the repo in Ubuntu terminal over copy pasting from windows resolved my issue.

**Comment by barrettab** [comment]
That solved the syntax error but now I have a new error "Bad substitution"

```
Enter the list of models to download without spaces (7B,13B,70B,7B-chat,13B-chat,70B-chat), or press Enter for all: 7B
download.sh: 12: [[: not found
Downloading LICENSE and Acceptable Usage Policy
download.sh: 17: Bad substitution
```

**Comment by anand-shubham** [comment]
![image](https://github.com/facebookresearch/llama/assets/47324013/bac8b543-6759-4f30-a960-84bf17907eb4)

**Comment by PaulMorel1** [comment]
You're using wsl I'm guessing? See https://github.com/facebookresearch/llama/issues/413 for Windows download scripts

**Comment by Zhangy-ly** [comment]
I use the linux with the same question.
![屏幕截图 2023-07-20 164704](https://github.com/facebookresearch/llama/assets/44971816/9328e4fb-333f-4325-86db-5dd6f38541a5)

**Comment by barrettab** [comment]
Nope, this was on ubuntu.  Originally tired on WSL but then switched to ubuntu based on first comment.

**Comment by ypc82** [comment]
same problem here. also on ubuntu.

**Comment by barrettab** [comment]
I requested a new URL and then ran it as "bash download.sh" and it worked on ubuntu, have not tested it with WSL yet

**Comment by gusseppe** [comment]
> I requested a new URL and then ran it as "bash download.sh" and it worked on ubuntu, have not tested it with WSL yet

Worked with `bash download.sh` thanks!

**Comment by Zhangy-ly** [comment]
bash download.sh is work!
and then, new Error is: HTTP request sent, awaiting response... 403 Forbidden
This link (https://github.com/facebookresearch/llama/issues/370#issuecomment-1641024286) is useful, click the link in email, and copy the link starting with https://download.llamameta.net in your browser's address bar. 

In the command line, first enter chmod 755 download.sh, then enter bash download.sh, and finally enter the link you just copied.

**Comment by pderendinger-everse** [comment]
In my case, these are the steps I did to make it work on WSL:

1. Change line breaks from \r\n to \n
2. chmod +x download.sh
3. bash download.sh

**Comment by MarcoSteinke** [comment]
You can also just open the `download.sh` with the code editor of your choice and copy the contents of [the remote `download.sh`](https://github.com/facebookresearch/llama/blob/main/download.sh) from your web browser into the local file. It will also replace all `\r\n` with `\n`

**Comment by Syzygy2048** [comment]
> In my case, these are the steps I did to make it work on WSL:
> 
> 1. Change line breaks from \r\n to \n
> 2. chmod +x download.sh
> 3. bash download.sh

Seems like just using `bash download.sh` is enough
