### ISSUE TITLE
403 errors on consolidated-02 for 70B-chat

### ISSUE THREAD

**Issue by Tipizen** [facebookresearch/llama#414]
download.sh is getting a 403 error for consolidated.02.pth

this has happened on multiple retries .. other shards download fine

--2023-07-19 10:23:09--  https://download.llamameta.net/llama-2-70b-chat/consolidated.02.pth?Policy=
.....
Resolving download.llamameta.net (download.llamameta.net)... 18.160.225.23, 18.160.225.122, 18.160.225.113, ...
Connecting to download.llamameta.net (download.llamameta.net)|18.160.225.23|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden.
2023-07-19 10:23:09 ERROR 403: Forbidden..

**Comment by mgcollie** [comment]
same

**Comment by hatala91** [comment]
Thanks for raising this, @Tipizen. Check out this download FAQ: https://github.com/facebookresearch/llama/blob/bug-fix-Sep6/Download.md

Feel free to re-open if the issue persists.
