### ISSUE TITLE
Need help downloading the model files

### ISSUE THREAD

**Issue by realhaik** [facebookresearch/llama#429]
I have already tried 6 links, today an yesterday, one of the links worked, but only for a short time and it was able to download only some of the files before going dead.

Since then  all the links that I try, return the same response:

```
Please follow the instructions on our [Llama GitHub repository](https://github.com/facebookresearch/llama) page to access the Llama 2 model downloads.

Github [README](https://github.com/facebookresearch/llama/blob/main/README.md)

Github [download.sh](https://github.com/facebookresearch/llama/blob/main/download.sh)
```

**Comment by Daryl149** [comment]
Try the ones I converted to HF format for 7B-chat and 13B-chat: https://huggingface.co/daryl149
Can't help you with the 70B-chat or the non chat versions.
