### ISSUE TITLE
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto-&gt;ParseFromArray(serialized.data()， serialized.size())]

### ISSUE THREAD

**Issue by wells-harrison** [facebookresearch/llama#437]
RuntimeError: Internal: src/sentencepiece_processor.cc(1101) [model_proto-&gt;ParseFromArray(serialized.data()， serialized.size())]

**Comment by connldunc** [comment]
What was the solution on this? @wells-harrison
