### ISSUE TITLE
Enter the URL from email

### ISSUE THREAD

**Issue by MonkeyTB** [facebookresearch/llama#439]
This is a form to enable access to Llama 2 on Hugging Face after you have been granted access from Meta. Please visit the [Meta website](https://ai.meta.com/resources/models-and-libraries/llama-downloads) and accept our license terms and acceptable use policy before submitting this form. Requests will be processed in 1-2 days.

根本打不开，有没有大佬给个url， 借用下载一下

**Comment by namaggarwal** [comment]
Hi @MonkeyTB ,

Can you please provide more information on this, what is the issue you are facing. Are you not able to open the link ?

**Comment by MonkeyTB** [comment]
> 

Thanks for the reply, it's settled now

**Comment by MonkeyTB** [comment]
> Hi @MonkeyTB ,
> 
> Can you please provide more information on this, what is the issue you are facing. Are you not able to open the link ?

Thanks for the reply, it's settled now

**Comment by Linece** [comment]
@MonkeyTB 大佬可以给个url， 借用下载一下吗

**Comment by Linda230** [comment]
Hi, I also encounter the similar question as you. how you solve this problem? could you provide me with the url? Thank you very much!

**Comment by Alex-csc-JY** [comment]
Meta show me this：There was an error submitting your email address.

**Comment by goodchong** [comment]
Meta show me this：There was an error submitting your email address.why？

**Comment by IanSmith123** [comment]
Same issue. Solved by change to another proxy IP address.

**Comment by xingxiaoyang** [comment]
Same issues: There was an error submitting your email address.

**Comment by sunfeng90** [comment]
Me too. Why

**Comment by AlberHu** [comment]
> Meta show me this：There was an error submitting your email address.why？

Me too, is there any solution?

**Comment by huanranchen** [comment]
> > Meta show me this：There was an error submitting your email address.why？
> 
> Me too, is there any solution?

same issue, why????

**Comment by zzyzeyuan** [comment]
Me too, any help??

**Comment by sunfeng90** [comment]
any help?



---- Replied Message ----
| From | Zeyuan ***@***.***> |
| Date | 03/22/2024 11:10 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [meta-llama/llama] Enter the URL from email (Issue #439) |

Me too, any help??

**Comment by AlberHu** [comment]
> > Meta show me this：There was an error submitting your email address.why？
> 
> Me too, is there any solution?

This is because your country's ip is banned by meta, change a country ip or use vpn can solve it.
