### ISSUE TITLE
What projects are people planning on making with this?

### ISSUE THREAD

**Issue by pauldog** [facebookresearch/llama#44]
Just wondered what cool projects people will be making with this?

I have some good ideas such as trying to combine it with a math engine to make it genius level at math.

Or combine it with an art engine to make it generate art.

Or combine it with a computer game to see if it can navigate its way through a maze by describing it in natural language.

One thing idea is to combine it with an Alpha-Zero like model so that it can think ahead in its conversations instead of just saying the first thing that comes to mind. 

These are just some ideas.

I'm wondering what other benefits could be got from having this run locally rather than using, say the ChatGPT web API?

**Comment by anubop** [comment]
Closing this as it's not an issue! Check out hugggingface and other community discussion forums :)
