### ISSUE TITLE
Don't call "open source" what isn't?

### ISSUE THREAD

**Issue by clempou** [facebookresearch/llama#440]
Meta is muddying the waters using a term that has an industry-wide recognized definition. The Llama2 license is simply not open source, nor free software: https://blog.opensource.org/metas-llama-2-license-is-not-open-source/

**Comment by J-Dunn** [comment]
Yes, this is totally dishonest. Attempting to get the kudos, respect and TRUST implied but the term open source .... but **there is no source code.**  All we see here is a script to download and executable and datafiles representing certain pre-run training session for the model. 

It seems to be open use ( with a few exceptions and caveats ).

**Comment by zhangxiaoxuan1** [comment]
I wish they would release the code for model training. In the paper the authors proposed a lot of interesting training approaches (e.g. RL) that improved the model performance significantly, but they didn't release the training code to GitHub, which is unfortunate. The only code available is the model and inference code. I guess this is common industry practice (e.g. GPT2 also only released model/inference code) but I do wish the training code is available to the public for study - it could be quite helpful.

**Comment by J-Dunn** [comment]
Are you saying the zip you can down load after applying for permission does include the source code for the model, not just an executable file ? 
I'd read that they had released the open source code to github, which clearly they have not. There is nothing useful here just a trivial script which runs wget.

**Comment by amitsangani** [comment]
Llama 2 is free for research and commercial use. By making AI models available openly, they can benefit everyone. Weights are available and open-sourced. Weights can also be updated though fine-tuning. Let us know if you need additional info. Closing this issue.
