### ISSUE TITLE
uccessfully installed  llama-0.0.1,  but can not import module??   why? 

### ISSUE THREAD

**Issue by melfebulu** [facebookresearch/llama#447]
>>> import sys
>>> for path in sys.path:
...     print(path)
... 

/data/CONDA/anaconda3/envs/llama7bchat-test/lib/python311.zip
/data/CONDA/anaconda3/envs/llama7bchat-test/lib/python3.11
/data/CONDA/anaconda3/envs/llama7bchat-test/lib/python3.11/lib-dynload
/data/CONDA/anaconda3/envs/llama7bchat-test/lib/python3.11/site-packages
/data/LLAMA/llama2/llama2-7bchat-test/llama.copy
/tmp/tmp3c6xjx7d
>>> exit()
/data/CONDA/anaconda3/envs/llama7bchat-test/lib/python3.11/tempfile.py:895: ResourceWarning: Implicitly cleaning up <TemporaryDirectory '/tmp/tmp3c6xjx7d'>
  _warnings.warn(warn_message, ResourceWarning)
(llama7bchat-test) [root@mainserver llama.copy]# pip list|grep llama
llama                    0.0.1      /data/LLAMA/llama2/llama2-7bchat-test/llama.copy
(llama7bchat-test) [root@mainserver llama.copy]# python
Python 3.11.4 (main, Jul  5 2023, 13:45:01) [GCC 11.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import llama
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'llama'
>>>

**Comment by kaolin** [comment]
Apologies for not addressing this earlier, but this seems very old. Are you still stuck here? How did you install llama (was it inside the conda env you're currently running?). Feel free to reopen this if you need more help.
