### ISSUE TITLE
why i can not load model from llama-2-7b

### ISSUE THREAD

**Issue by QJShan** [facebookresearch/llama#453]
![image](https://github.com/facebookresearch/llama/assets/131762142/3269af33-5517-46be-83b2-13eca6e31847)

**Comment by hans-ekbrand** [comment]
https://github.com/facebookresearch/llama/blob/6c7fe276574e78057f917549435a2554000a876d/CONTRIBUTING.md says the following about issues:

> We use GitHub issues to track public bugs. Please ensure your description is clear and has sufficient instructions to be able to reproduce the issue.

Your screenshot does not demonstrate an issue with llama-2-7b. We can only guess what your problem is since you do not include any error message, nor any proof that your configuration is correct.

**Comment by QJShan** [comment]
> https://github.com/facebookresearch/llama/blob/6c7fe276574e78057f917549435a2554000a876d/CONTRIBUTING.md says the following about issues:
> 
> > We use GitHub issues to track public bugs. Please ensure your description is clear and has sufficient instructions to be able to reproduce the issue.
> 
> Your screenshot does not demonstrate an issue with llama-2-7b. We can only guess what your problem is since you do not include any error message, nor any proof that your configuration is correct.

think you for your guidance.

**Comment by dongwang218** [comment]
Looks like the `tokenizer.model` is not under the given path, for the llama-2 download
```
ls ~/llama2/
llama-2-13b  llama-2-13b-chat  llama-2-70b  llama-2-70b-chat  llama-2-7b  llama-2-7b-chat  tokenizer_checklist.chk  tokenizer.model
```
Use the parent directory should work
```
python
>>> import os
>>> from transformers import LlamaTokenizer
>>> tokenizer = LlamaTokenizer.from_pretrained(os.path.join(os.path.expanduser('~'), 'llama2'))
>>> tokenizer.tokenize("hello world")
['▁hello', '▁world']
```
