### ISSUE TITLE
Out-of-memory for 7B on Ubuntu native, runs fine in WSL2 Ubuntu on same machine, RTX 3060 12 GB, 32 GB RAM

### ISSUE THREAD

**Issue by aamanlamba** [facebookresearch/llama#455]
I've been able to run the 7B examples on my PC with 32 GB RAM and nVidia RTX 3060 12 GB. I have dual-boot Ubuntu and installed the Llama git & 2-7b model. When I run it using the example command, I get an out-of-memory error. What can I do to resolve this?

`torchrun --nproc_per_node 1 example_text_completion.py --ckpt_dir llama-2-7b/     --tokenizer_path tokenizer.model --max_seq_len 128 --max_batch_size 4`

I get this error even if I change the batch size to 2. nvidia shows a spike in GPU memory just before the error.

`torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 0; 11.75 GiB total capacity; 10.97 GiB already allocated; 120.06 MiB free; 10.98 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
`

**Comment by realhaik** [comment]
Need to have 16 GB for the 7b

**Comment by dhruvildarji** [comment]
Does it run fine in WSL linux and doesnt run on Ubuntu native?
Is that what you are trying to say?

I am trying to run on ubuntu native, it give me the same error as your. 

I am using AMD Ryzen 9 5900X 12-Core Processor
Dhruvil

**Comment by ram510** [comment]
It did not run for me on WSL Ubuntu too, did you install and GPU dependencies from Nvidia, please help

**Comment by maxi-w** [comment]
I think it does not fit into the RTX 3060. It consumes ~14.3 GB of VRAM running on a RTX 4080.

**Comment by agunapal** [comment]
Yes,  @maxi-w is right. 7B model takes around 14GB of GPU memory
You can explore quantization techniques to resolve the issue @aamanlamba .
Closing the issue

**Comment by Johnwei386** [comment]
you can use some quantization techniques to fine-tune the llama2 model. you can see this blog -- https://blog.ovhcloud.com/fine-tuning-llama-2-models-using-a-single-gpu-qlora-and-ai-notebooks/
I try and it's work!

**Comment by Johnwei386** [comment]
you can use some quantization techniques to fine-tune the llama2 model. you can see this blog -- https://blog.ovhcloud.com/fine-tuning-llama-2-models-using-a-single-gpu-qlora-and-ai-notebooks/
I try and it's work!
