### ISSUE TITLE
How to run download.sh on a MacBook Pro (M1)?

### ISSUE THREAD

**Issue by GuidoStarter01** [facebookresearch/llama#458]
What do I have to do to run download.sh on my MBP (M1)?

**Comment by Tushar-ml** [comment]
Steps to do that are:
1. Open terminal, git clone the repository and change the directory to llama
2.  run ```chmod +x ./download.sh```
3. ```./download.sh```

**Comment by littlehifive** [comment]
> I opened terminal but I need more help. How do I clone the repository (and change the directory to llama)?

I did the following in a virtual env with pytorch installed:
```
conda activate llama_env
git clone https://github.com/facebookresearch/llama.git
cd llama
pip install -e .
```
and then

```
./download.sh
chmod +x download.sh
```

**Comment by adnanboz** [comment]
I wrote a python version if that helps. But I am still getting the 403 forbidden issues some people are talking about. https://github.com/adnanboz/llama/blob/main/download.py

**Comment by genffy** [comment]
should be install `wget` and `md5sum` first
```shell
brew install wget
brew install md5sha1sum
```

**Comment by lmarcon** [comment]
@GuidoStarter01 did the instruction above solve your issue?

**Comment by GuidoStarter01** [comment]
Yes, thank you.

Guido

 

 

 

Von: Lorenzo Marcon ***@***.***>
Antworten an: facebookresearch/llama ***@***.***>
Datum: Freitag, 1. September 2023 um 12:46
An: facebookresearch/llama ***@***.***>
Cc: GuidoStarter01 ***@***.***>, Mention ***@***.***>
Betreff: Re: [facebookresearch/llama] How to run download.sh on a MacBook Pro (M1)? (Issue #458)

 

@GuidoStarter01 did the instruction above solve your issue?
