### ISSUE TITLE
Windows10 download.sh error

### ISSUE THREAD

**Issue by SlookUP** [facebookresearch/llama#475]
When I run the download.sh file and enter the information as prompted, git bash emits an error message
`OpenSSL: error :140773E8:SSL routines:SSL23_GET_SERVER_HELLO:reason(1000)
Unable to establish SSL connection`

**Comment by SlookUP** [comment]
The last line of the prompt is：
md5sum: checklist.chk: no properly formatted MD5 checksum lines found

**Comment by umershaikh123** [comment]
> When I run the download.sh file and enter the information as prompted, git bash emits an error message `OpenSSL: error :140773E8:SSL routines:SSL23_GET_SERVER_HELLO:reason(1000) Unable to establish SSL connection`

Can you write the full error. 
keep in mind the link url access will expire after 24 hours

**Comment by borvanov** [comment]
@SlookUP I've been running through the same issue.

Please check if:
1. You copied the download URL correctly. Just copy / paste the link from the email. Do not use "Right click" + "Copy link URL" as it's gonna copy proxied URL. Your link should start with https://download.llamameta.net
2. You have enough space. As you're trying to get it downloaded on Windows, you have probably installed an extrernal WGET package. The WGET package puts the content to it's own temporary path while downloading, so if it's installed to C: disk it's probably ran out of space. Go to this [link](https://eternallybored.org/misc/wget/) and download the ZIP that matches your system requirements. Then unzip it on D: disk and add it to user/system PATH manually.

**Comment by vithikapungliya** [comment]
My opinion is dont use Windows, use a Linux Kernel and having GPU is great too. I had the same connection error and then switched to Linux, was resolved.

**Comment by SlookUP** [comment]
> > 提示的最后一行是：md5sum：checklist.chk：未找到格式正确的 MD5 校验和行
> 
> 你找到任何解决方案了吗？
borvanov's advice was very helpful. Do not directly download and install wget-setup.exe, you should download the wget.zip file, decompress it, and add to PATH

**Comment by lmarcon** [comment]
@SlookUP, try to update it to the latest version and retry, older versions might not support SSL.

Download 1.21.4 from https://eternallybored.org/misc/wget/

**Comment by samuelselvan** [comment]
@SlookUP are you still facing issues? Would be worth update to the latest version and retry.

**Comment by samuelselvan** [comment]
Will close for now. Please comment if you still face issues.
