### ISSUE TITLE
Bash error in download.sh

### ISSUE THREAD

**Issue by egulias** [facebookresearch/llama#476]
I'm getting the following error:
```bash
download.sh: 12: [[: not found
Downloading LICENSE and Acceptable Usage Policy
download.sh: 17: Bad substitution
```

However looking at the code it seems to be ok. I'm executing this on a WSL2 on Windows 10.

Thanks.

**Comment by lindeci** [comment]
PLS EXECUTE:
bash download.sh

**Comment by egulias** [comment]
It worked, thanks.
