### ISSUE TITLE
dbgpt already supports llama2，you can run llama2 locally use dbgpt.

### ISSUE THREAD

**Issue by csunny** [facebookresearch/llama#479]
In our project [DB-GPT](https://github.com/csunny/DB-GPT).  Supports multiple large language models, currently supporting Vicuna (7b, 13b), ChatGLM-6b (int4, int8), guanaco(7b,13b,33b), Gorilla(7b,13b), 🔥 llama-2(7b, 13b, 70b)

We're building some really interesting applications around databases and large language models. 
![image](https://github.com/facebookresearch/llama/assets/17919400/806a0348-e50b-4517-8730-3455d13d7d4c)

https://github.com/csunny/DB-GPT/assets/13723926/55f31781-1d49-4757-b96e-7ef6d3dbcf80

**Comment by varunfb** [comment]
Thanks for the information.
