### ISSUE TITLE
Inconsistent Usage of .forward and PyTorch's nn.Module __call__

### ISSUE THREAD

**Issue by Chriss4123** [facebookresearch/llama#486]
The codebase exhibits inconsistent use of the methods `.forward` and PyTorch's `nn.Module` `__call__`. Both methods are employed interchangeably in different modules and scripts which is an inconsistent coding style.

To enhance code clarity and maintainability, I believe it is a good practice to choose one method (`forward` or `__call__`) and apply it consistently throughout the entire codebase. Identifying all instances where both methods are used and replacing the non-preferred method with the chosen one will improve readability and facilitate collaboration among developers.

For example, in model.py on line 239 in the forward method of the `TransformerBlock` class, `.forward` is used in the sub-layers, however in the `Transformer` class, `__call__` is used consistently for the sub-layers.

**Comment by hatala91** [comment]
Hey, thanks for reporting this. I just checked and couldn't find `__call__` being used anymore: https://github.com/search?q=repo%3Afacebookresearch%2Fllama+__call__&type=code

Feel free to re-open if I got that wrong or you feel like there's more discussion needed.

**Comment by Chriss4123** [comment]
> Hey, thanks for reporting this. I just checked and couldn't find `__call__` being used anymore: https://github.com/search?q=repo%3Afacebookresearch%2Fllama+__call__&type=code
> 
> Feel free to re-open if I got that wrong or you feel like there's more discussion needed.

Hi, apologies for the confusion. When you call an object in Python, it tries to run the `__call__` method of the object. For example, `myobj()` would be equivalent to `myobj.__call__()`, however the `__call__` part is abstracted away for readability by Python.

https://github.com/facebookresearch/llama/blob/main/llama/model.py
Look at lines 406 and 482. As you can see, one of them is using the `forward` method while the other one is calling the object directly (`__call__`). When you call a subclass of PyTorch's `Module`, it calls the `forward` of said class, however it also adds additional functionality like hooks. There are multiple examples of this scattered throughout the codebase, this is just one.

In general, it is better to call the object directly as it allows for more functionality to be added on. The main thing I opened this for is to add a level of consistency to the codebase. Use one or the other, but not both to ensure consistency.
