### ISSUE TITLE
Mask is a square matrix but scores might not always be a square matrix

### ISSUE THREAD

**Issue by zhangxiaoxuan1** [facebookresearch/llama#494]
Hi all, thank you very much for sharing the code and the great work,

I'm looking at [this piece of code](https://github.com/facebookresearch/llama/blob/6c7fe276574e78057f917549435a2554000a876d/llama/model.py#L179C13-L179C19) in model.py:

`scores = scores + mask  # (bs, n_local_heads, seqlen, cache_len + seqlen)`

Ignoring the batch size and n_local_heads dimensions, the scores matrix's dimension is `(seqlen, cache_len+seqlen)`, where `cache_len = start_pos`.

The mask matrix is a square matrix of size `(seqlen, seqlen)` ([code pointer](https://github.com/facebookresearch/llama/blob/6c7fe276574e78057f917549435a2554000a876d/llama/model.py#L280))

If the scores matrix is also a square matrix of size seqlen (this is when start_pos=0), or if `seqlen=1` (in this case we have no mask), these 2 matrices can be added together. However, if `start_pos > 0` and `seqlen > 1`, wouldn't the score matrix's dimensions not match the mask matrix's dimensions?

**Comment by ruanslv** [comment]
Fix in https://github.com/facebookresearch/llama/pull/900
