### ISSUE TITLE
I feel like vicuna is better than llama v2-chat when doing math task

### ISSUE THREAD

**Issue by XuanRen4470** [facebookresearch/llama#495]
When performing math tasks, such as:

Problem:

Given a/b = 2, what is the value of 4b/a?

A) 0
B) 1
C) 2
D) 4

I feel that Vicuna 13B performs better than Llama-v2-chat-13b when doing math. Additionally, I've observed that the answers provided by Llama-v2-chat-13b are more consistent across multiple runs, and it seems more inclined to state that a problem is unsolvable. Is this just my imagination?

**Comment by RahulBhalley** [comment]
OpenAI suggested to run some Oregon code instead to do math operations because LLMs (like any other DL model) are probabilistic and can’t do math well (because it’s deterministic).

**Comment by varunfb** [comment]
Through careful prompt engineering and fine tuning the model would improve the performance. Having said that some of your observations can be found [here](https://lmsys.org/blog/2023-03-30-vicuna/#how-to-evaluate-a-chatbot).
