### ISSUE TITLE
Can't download models on windows.

### ISSUE THREAD

**Issue by mephisto83** [facebookresearch/llama#498]
Enter the list of models to download without spaces (7B,13B,70B,7B-chat,13B-chat,70B-chat), or press Enter for all:
Downloading LICENSE and Acceptable Usage Policy
SYSTEM_WGETRC = c:/progra~1/wget/etc/wgetrc
syswgetrc = C:\Program Files (x86)\GnuWin32/etc/wgetrc
--2023-07-22 07:33:25--  https://download.llamameta.net/LICENSE?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoiPz95Llx1NDI5Yj8iLCJSZXNvdXJjZSI6Imh0dHBzOlwvXC9kb3dubG9hZC5sbGFtYW1ldGEubmV0XC8qIiwiQ29uZGl0aW9uIjp7IkRhdGVMZXNzVGhhbiI6eyJBV1M6RXBvY2hUaW1lIjoxNjg5OTgyMzcxfX19XX0_&Signature=nkZAwQAtDrC0JFIzqvJdwHysv2%7Ea0HDleFaDzc9MK3AdKk8frkEB21pb4bWfq7UQT9YtPmd--kE3n4u7J4w1NxXaCrvQCpVRbje4ka8h00rBKL8ToPRRirITIzqxKiPDILe6f4TDfrz7ODBVFMVUDzJbg8gjGKXr4B6nb47iKT4E-ppdpvpwM9HyYm0EQplsCkzMwQrp2AXH4mCveoEDeajWp7NyV5YcKzhxf8VCQ-TPJYSvMqJ9PuchecOcwS5IbtuDCfJjW-fl5ri-zfFYgjMO-JZsX5-6GaxG359i2CZxIXHzaGd-vaaClTvdjtaUjxJIvWrm9iihmSmWWGb-YQ__&Key-Pair-Id=K15QRJLYKIFSLZ
Resolving download.llamameta.net... 18.160.96.18, 18.160.96.14, 18.160.96.40, ...
Connecting to download.llamameta.net|18.160.96.18|:443... connected.
OpenSSL: error:140773E8:SSL routines:SSL23_GET_SERVER_HELLO:reason(1000)
Unable to establish SSL connection.

**Comment by d8ahazard** [comment]
+1. Come on guys. Windows is an OS that's been around for a while now. 

Even when I run the download.sh under WSL, I get a 403 forbidden error.

**Comment by SlookUP** [comment]
I have the same problem as you, my problem has been solved, you can try this method:https://github.com/facebookresearch/llama/issues/475#issuecomment-1645392096

**Comment by lmarcon** [comment]
@mephisto83 what version of wget do you have (wget --version)?

Try to update it to the latest version and retry, older versions might not support SSL.
