### ISSUE TITLE
download.sh not working

### ISSUE THREAD

**Issue by mr0bn0xi0us** [facebookresearch/llama#509]
Enter the list of models to download without spaces (7B,13B,70B,7B-chat,13B-chat,70B-chat), or press Enter for all: 70B-chat
download.sh: 12: [[: not found
Downloading LICENSE and Acceptable Usage Policy
download.sh: 17: Bad substitution

**Comment by ilyassjaatit** [comment]
Como estas ejecutando el comando?

**Comment by ilyassjaatit** [comment]
How are you executing the command? 
```bash
chmod +x download.sh
./download.sh

```

**Comment by deltaboukensha** [comment]
Copy paste the entire terminal input & output to receive better help

**Comment by dron3flyv3r** [comment]
> ###
> **[ilyassjaatit](/ilyassjaatit) ** commented [Jul 23, 2023](#issuecomment-1646798900) •

That worked for me, thanks for the help 😄

**Comment by SaraiQX** [comment]
./download.sh worked! Thank you
