### ISSUE TITLE
Download.sh not working "no such file or directory" FIRST SOLUTION BELOW IN THE COMMENTS, IN A FEW DAYS I'LL MAKE THE TUTORIAL

### ISSUE THREAD

**Issue by G10Rg10C** [facebookresearch/llama#514]
After I understand the debugger to use I tried to run it but it gives to me the error "the bash/bin directory can be found",at the moment I don't have in front of me the PC, after I'll write the correct literally error, can anyone help me?

**Comment by deltaboukensha** [comment]
I had the same error recently. The download.sh file has been saved with CRLF line endings. Save the file with LF line endings. Try changine the line endings on the file and see if it works.

Also try checking if bin/bash exists "ls bin/bash". I noticed you reversed the order here. I generally get the feeling you noob ;P

**Comment by G10Rg10C** [comment]
I solved it, If you and the others are interested I can post a solution and make a tutorial too on YT.

**Comment by PureRockets** [comment]
Please share the solution

**Comment by G10Rg10C** [comment]
Okay guys for the moment I write it down here then I do the tutorial but for the moment I stopped to the download, the solution is that you have to specify the directory and then debug it, for some reason that I don't know it doesn't find the file and the directory by itself so you have to tell to it by your own, if you don't do that  it will give always that error!
I'm still completing the download, after doing it the problem will be to run it!😂😅
