### ISSUE TITLE
some questions about training of Llama2

### ISSUE THREAD

**Issue by pengfeixiang** [facebookresearch/llama#517]
1. In the program of '*-hf', why do you use the type of float16 instead of bf16?
2. Does '*-hf' mean half precision, why are the model sizes of Llama-2-7b-hf and Llama-2-7b the same?

**Comment by WOPH96** [comment]
I think hf means hugging-face

**Comment by dongwang218** [comment]
Thanks @WOPH96 for clarifying hf means hugging-face!

The llama model weights are stored in bf16, the huggingface conversion [script](https://github.com/huggingface/transformers/blame/main/src/transformers/models/llama/convert_llama_weights_to_hf.py#L273) may store weights in float16. Both float16 and bf16 are 16 bit, but bf16 has less precision and larger range. bf16 is preferred for training. The two should make no difference for llama inference. Although only Ampere and later microarchitecture supports bf16, eg v100/p100 do not support bf16. For more details, this [doc](https://huggingface.co/docs/transformers/v4.15.0/performance#floating-data-types) discusses the trade off of float data type esp for mixed precision training.
