### ISSUE TITLE
no llama library instead "llamatest"

### ISSUE THREAD

**Issue by jacobpowaza** [facebookresearch/llama#525]
not sure if this is just a me problem, but for some reason theres no proper llama library. i installed both 7B and 7B-chat and this is what i get:

```
ModuleNotFoundError: No module named 'llama'
```
I used download.sh and attempted to use setup.py but got this error:

```
python3 setup.py
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: no commands supplied
```

i dont want to say this is an issue on the developers part but any help is appreciated here.

FIXED THIS I WAS BEING DUMB CANT FIGURE OUT HOW TO DELETE SORRY

**Comment by kaolin** [comment]
Glad you fixed it, no worries! ^_^
