### ISSUE TITLE
download.sh doesn't work on default bash on mac

### ISSUE THREAD

**Issue by dseddah** [facebookresearch/llama#53]
Hi everyone,
I've noticed that the downloading script doesn't work as it on mac. (the declare -A option is not recognized by the default bash)

fix: 
install bash with homebrew 
and use it to call the script
/opt/homebrew/bin/bash ./download.sh

Thanks for making this available btw :)

**Comment by HarrywillDr** [comment]
Thanks!! Just met the same problem on mac. Really helpful!

**Comment by talhaanwarch** [comment]
Thanks in Ubuntu i also have to tried
```
/bin/bash download.sh 
```

**Comment by ergosumdre** [comment]
> 

Nice! This works. Thank you!

**Comment by bgarzonm** [comment]
Someone knows how to solve the same problem but in windows?

**Comment by byildiz** [comment]
`/opt/homebrew/bin/bash ./download.sh` didn't worked for me because homebrew doesn't use `/opt/homebrew` directory anymore. You can use `brew --prefix bash` to find the location once you install the bash with `brew install bash` and you can run the download script with `\`brew --prefix bash\`/bin/bash ./download.sh`.

**Comment by tekspirit** [comment]
all on a Mac M1, you might enjoy this video from a AI professor for getting things running on a mac:  https://www.youtube.com/watch?v=VEDy-c5Sk8Y

**Comment by tekspirit** [comment]
from another discussion, using mac and bash, use this one:
`# Copyright (c) Meta Platforms, Inc. and affiliates.
# This software may be used and distributed according to the terms of the GNU General Public License version 3.

PRESIGNED_URL=""             # replace with presigned url from email
MODEL_SIZE="7"  # edit this list with the model sizes you wish to download
TARGET_FOLDER="download"             # where all files should end up

declare -A N_SHARD_DICT

N_SHARD_DICT["7"]="0"
N_SHARD_DICT["13"]="1"
N_SHARD_DICT["30"]="3"
N_SHARD_DICT["65"]="7"

echo "Downloading tokenizer"
wget ${PRESIGNED_URL/'*'/"tokenizer.model"} -O ${TARGET_FOLDER}"/tokenizer.model"
wget ${PRESIGNED_URL/'*'/"tokenizer_checklist.chk"} -O ${TARGET_FOLDER}"/tokenizer_checklist.chk"

(cd ${TARGET_FOLDER} && md5 tokenizer_checklist.chk)

for i in ${MODEL_SIZE//,/ }
do
    echo "Downloading ${i}B"
    mkdir -p ${TARGET_FOLDER}"/${i}B"
    for s in $(seq -f "0%g" 0 ${N_SHARD_DICT[$i]})
    do
        echo "Downloading shard ${s}"
        wget ${PRESIGNED_URL/'*'/"${i}B/consolidated.${s}.pth"} -O ${TARGET_FOLDER}"/${i}B/consolidated.${s}.pth"
    done
    wget ${PRESIGNED_URL/'*'/"${i}B/params.json"} -O ${TARGET_FOLDER}"/${i}B/params.json"
    wget ${PRESIGNED_URL/'*'/"${i}B/checklist.chk"} -O ${TARGET_FOLDER}"/${i}B/checklist.chk"
    echo "Checking checksums"
    (cd ${TARGET_FOLDER}"/${i}B" && md5 checklist.chk)
done`

Thanks to [@ramithut ](https://github.com/ramithuh) for this

**Comment by aris992-git** [comment]
> 

hello, have you solved the problem in windows, I also met  ERROR 403: Forbidden.

**Comment by mpskex** [comment]
Here is a python script may help you
https://github.com/facebookresearch/llama/issues/41#issuecomment-1459518524

**Comment by erbolle** [comment]
io da windows non trovo il link da mettere su download.sh

**Comment by AvisP** [comment]
Still getting this error on mac M1

```
Resolving urldefense.com (urldefense.com)... 52.6.56.188, 52.204.90.22, 52.71.28.102
Connecting to urldefense.com (urldefense.com)|52.6.56.188|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: /jerror [following]
--2023-07-20 12:31:55--  https://urldefense.com/jerror
Reusing existing connection to urldefense.com:443.
HTTP request sent, awaiting response... 400 Bad Request
2023-07-20 12:31:55 ERROR 400: Bad Request.
```

I tried what was mentioned in these two comments specifically https://github.com/facebookresearch/llama/issues/53#issue-1606582963 https://github.com/facebookresearch/llama/issues/53#issuecomment-1452669223... Any advise?

**Comment by lmarcon** [comment]
Thanks for sharing, @dseddah. Since this is not an issue but a comment, closing to avoid cluttering.
