### ISSUE TITLE
How To Run Llama 2 without a gpu?

### ISSUE THREAD

**Issue by raghu-007** [facebookresearch/llama#534]
Is there any way to run without gpu or with an integrated graphics card?

**Comment by sitecho** [comment]
To run llama2 locally you will need ~10GB-200GB VRAM

You can test it on huggingface
https://huggingface.co/spaces/huggingface-projects/llama-2-13b-chat

and this is llama2 without gpu:
https://www.youtube.com/watch?v=KaBsh5uhixU

**Comment by shivprasad94** [comment]
Even, I am looking for the same!
How to run for window system without GPUs 
I have GPU 0: Intel(R) Iris(R) Xe Graphics as an integrated graphics card to my windows system.

**Comment by mcorkidi** [comment]
I am trying to run Llama2 on my MacBookPro, getting error "RuntimeError: Distributed package doesn't have NCCL built in". I believe this is because I don't have a GPU. Is there a way around this? Is it even possible with 16Gb of RAM?

**Comment by talhaanwarch** [comment]
I think you can try GGML versions, such as https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML

**Comment by raghu-007** [comment]
Thank You @talhaanwarch will try !!!

**Comment by raghu-007** [comment]
https://aws.amazon.com/blogs/machine-learning/llama-2-foundation-models-from-meta-are-now-available-in-amazon-sagemaker-jumpstart/
please do check it!!!

**Comment by coffee-mug** [comment]
Stumbled on this article couple of days ago that shows how to train and infer on CPU only: https://towardsdatascience.com/running-llama-2-on-cpu-inference-for-document-q-a-3d636037a3d8
