### ISSUE TITLE
Don't redownload model files if already there

### ISSUE THREAD

**Issue by Herz3h** [facebookresearch/llama#535]
I was trying to download the 70B-chat model without knowing it's size on disk, then ended up not having enough disk space.

After moving it to an external SSD and upon relaunching the download script, it seems that it is redownloading (consolidated.xx) files that are already there. 

It would be nice to avoid this by using some kind of checksum to see if file is already here without having to redownload. This would also reduce server bandwidth

**Comment by kaolin** [comment]
being addressed in https://github.com/facebookresearch/llama/pull/552 :)
