### ISSUE TITLE
Can't get access to llama-2 models

### ISSUE THREAD

**Issue by okhat** [facebookresearch/llama#542]
Hi all, sorry to open this as an issue; I don't see other ways to diagnose the problem.

I've filled the llama-2 form for okhattab@stanford.edu on the day of release (and then again since, and the same for llama-1 recently) and I can't seem to get access to the models—or to get any other communication for that matter.

I see plenty of seemingly automatic approvals. Anything I can do to facilitate access?

**Comment by okhat** [comment]
For context, I'm a PhD candidate at Stanford — author of ColBERT, DSP, and other popular papers/software — and this is for my research.

**Comment by ejsd1989** [comment]
@okhat @fdschmidt93 just wanted to check in and confirm if you were eventually able to get access? If not, then you may be want to resubmit the request via the llama 2 site - https://ai.meta.com/llama/

**Comment by fdschmidt93** [comment]
Yes, thanks for checking in!

**Comment by okhat** [comment]
Yes thanks guys!

**Comment by Pegahgdk** [comment]
Hi.
I have an error like yours.
I'm using python code in Jupyter notebook to use llma2 model.
I've used the code below. After I logged in successfully, I called the model by AutoTokenizer method, But I've got the access error.
So, I've requested to access the site: https://huggingface.co/{path_or_repo_id} basis error guidance, But I've got this email result from Meta & AI:
**Email Answer**
Sorry, you are not eligible to access Llama 2.
Thank you for your interest in using Llama 2. Unfortunately, you do not meet the criteria to obtain a license at this time.

Could you please help me? I need to test this model for my project soon.
Thanks


**My Code:**
from transformers  import AutoTokenizer,AutoModelForCausalLM
from huggingface_hub import notebook_login
notebook_login() # Login is successful
tokenizer= AutoTokenizer.from_pretrained("meta-llama/Llama-2-7b-chat-hf", use_auth_token=True)# Error line


**Error Result**
HTTPError                                 Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_errors.py](https://localhost:8080/#) in hf_raise_for_status(response, endpoint_name)
    269     try:
--> 270         response.raise_for_status()
    271     except HTTPError as e:

13 frames
HTTPError: 403 Client Error: Forbidden for url: https://huggingface.co/meta-llama/Llama-2-7b-chat-hf/resolve/main/tokenizer_config.json

The above exception was the direct cause of the following exception:

GatedRepoError                            Traceback (most recent call last)
GatedRepoError: 403 Client Error. (Request ID: Root=1-6581e077-173624a51f0747ad64c76f71;acb1e130-5a8f-4574-9e3e-44334b2153f1)

Cannot access gated repo for url https://huggingface.co/meta-llama/Llama-2-7b-chat-hf/resolve/main/tokenizer_config.json.
Your request to access model meta-llama/Llama-2-7b-chat-hf is awaiting a review from the repo authors.

The above exception was the direct cause of the following exception:

OSError                                   Traceback (most recent call last)
[/usr/local/lib/python3.10/dist-packages/transformers/utils/hub.py](https://localhost:8080/#) in cached_file(path_or_repo_id, filename, cache_dir, force_download, resume_download, proxies, token, revision, local_files_only, subfolder, repo_type, user_agent, _raise_exceptions_for_missing_entries, _raise_exceptions_for_connection_errors, _commit_hash, **deprecated_kwargs)
    443         )
    444     except GatedRepoError as e:
--> 445         raise EnvironmentError(
    446             "You are trying to access a gated repo.\nMake sure to request access at "
    447             f"[https://huggingface.co/{path_or_repo_id}](https://huggingface.co/%7Bpath_or_repo_id%7D) and pass a token having permission to this repo either "

OSError: You are trying to access a gated repo.
Make sure to request access at https://huggingface.co/meta-llama/Llama-2-7b-chat-hf and pass a token having permission to this repo either by logging in with `huggingface-cli login` or by passing `token=<your_token>`.
