### ISSUE TITLE
how to use my downloaded model locally on my macos

### ISSUE THREAD

**Issue by gavin1818** [facebookresearch/llama#546]
forgive me if the question is naive, im new.
I tried to use langchain to access to the model that I have downloaded by running the ./download.sh, but I dont know how to access to the model, all instructions online are about using accessing the LLama using HuggingFace, I dont want to use HuggingFace, I want to use my local downloaded model, what should i do, thanks.

**Comment by anyangml** [comment]
I might be wrong, but I think you need to use [this](https://github.com/ggerganov/llama.cpp) to convert your model and then you can probably access it through langchain.

**Comment by anyangml** [comment]
> forgive me if the question is naive, im new. I tried to use langchain to access to the model that I have downloaded by running the ./download.sh, but I dont know how to access to the model, all instructions online are about using accessing the LLama using HuggingFace, I dont want to use HuggingFace, I want to use my local downloaded model, what should i do, thanks.

I might be wrong, but I think you need to use [this](https://github.com/ggerganov/llama.cpp) to convert your model and then you can probably access it through langchain.

**Comment by dongwang218** [comment]
Continue the suggestions from @anyangml, langchain user guide has a page on llamacpp [integration](https://python.langchain.com/docs/integrations/llms/llamacpp) on Mac. You can either convert the downloaded llama weight to the required GGUF format llama.cpp quantization [tool](https://github.com/ggerganov/llama.cpp#prepare-data--run), or download the existing 7b chat GGUF [model](https://huggingface.co/TheBloke/Llama-2-7b-Chat-GGUF/tree/main).
