### ISSUE TITLE
Cant download the form isn't working properly 

### ISSUE THREAD

**Issue by DMTarmey** [facebookresearch/llama#554]
when i fill in the form it just wont allow it to be sent https://ai.meta.com/resources/models-and-libraries/llama-downloads/

**Comment by agunapal** [comment]
Hi @DMTarmey  When you fill the form, you will get an email with the url to the model. 

You need to use the url in the download script in this repo. 
If you run into issues with the script, please check this FAQ
https://github.com/facebookresearch/llama/blob/bug-fix-Sep6/Download.md
