### ISSUE TITLE
Llama 2 70B weights with model-parallel (MP) = 4

### ISSUE THREAD

**Issue by bronzafa** [facebookresearch/llama#556]
There is any way to convert the 70B model to run on only 4x H100s? The memory utilization for 8x H100 is around 154GB not sure if there is enough space left (6GB) for running it on 4 GPUs

**Comment by andrewchungg** [comment]
You can reshard the 8 pths (MP=8) to 4 pths (MP=4) by [converting pth shards to huggingface weights](https://github.com/huggingface/transformers/blob/d27e4c18fe2970abcb9a48dcb8a824e48083b15f/src/transformers/models/llama/convert_llama_weights_to_hf.py#L105) and loading llama2 local model using huggingface transformers

See  #594
