### ISSUE TITLE
Hrdware requirements to run 13B and 30B smoothly

### ISSUE THREAD

**Issue by ibrahim737701** [facebookresearch/llama#561]
I am looking to build a pc which will be able to run these LLMs smoothly and also finetune them. No budget constraints. Please recommend a good build.

**Comment by andrewchungg** [comment]
There is a fork at https://github.com/tloen/llama-int8 by [tloen](https://github.com/tloen) that uses INT8.
And [neuhaus](https://github.com/neuhaus) used a single RTX 3090, see #79
