### ISSUE TITLE
Change license so Using Llama output to fine tune Galactica is ok?

### ISSUE THREAD

**Issue by KnutJaegersberg** [facebookresearch/llama#568]
For research purposes, it would be great to use Llama2 70B like ChatGPT api to generate data for fine tuning Galactica. To my understanding, it is only allowed to use output of llama2 to fine tune other llama2. 
Wouldn't it make sense to change the license so one can do this for research purposes on your own model, Galactica, too? 
Otherwise, I just use Falcon-40b. 
I want to try to generate data for RLAIF with autocrit (https://github.com/CarperAI/autocrit) to make the model reason such that it sticks to the truth better.

**Comment by amitsangani** [comment]
We can fine-tune a llama 2 with output from llama 2 model. Closing this issue, since there is no action item here.
