### ISSUE TITLE
convert  hf llama2 weight to   meta llama2 weight 

### ISSUE THREAD

**Issue by GxjGit** [facebookresearch/llama#570]
We get a llama2-70B model,  which was fine-tuned from huggingface model, and save as huggingface format  in  one file.  We want to convert this model to meta llama2 weight . Then we can use this repo to run my model.

There is a script for converting  llama weights to hf:
https://github.com/huggingface/transformers/blob/main/src/transformers/models/llama/convert_llama_weights_to_hf.py

Is there a script for this reverse converting  (conver  hf weights to meta llama)?

**Comment by amitsangani** [comment]
I haven't seen a reverse conversion scripts i.e. HF to Meta Llama weights. Why don't you directly use the HF model for inferencing?

**Comment by dongwang218** [comment]
@GxjGit please checkout the [README](https://github.com/facebookresearch/llama-recipes/blob/main/examples/hf_llama_conversion/README.md) to convert hf to llama weights and run inference.
