### ISSUE TITLE
what is meaning of max_seq_len: int = 512,  max_gen_len: Optional[int] = None? please can anybody give me the answer? 

### ISSUE THREAD

**Issue by Sumit5194** [facebookresearch/llama#572]
max_seq_len is it about combined length of input context text and output text?

**Comment by hatala91** [comment]
`max_seq_len` and `max_gen_len` are two hyperparameters that control the maximum length of input sequences and generated sequences, respectively.

```
max_seq_len = Maximum sequence length for input text.
max_gen_len = Maximum length of the generated text sequence.
```
[Source](https://github.com/facebookresearch/llama/blob/main/llama/generation.py)

Hope this answers your question, feel free to re-open if still anything is unclear.
