### ISSUE TITLE
Llama-70B-chat-hf

### ISSUE THREAD

**Issue by md-rifatkhan** [facebookresearch/llama#574]
What are the pc requirement to run Llama-70B-chat-hf model locally? What about 7B and 13B also?

**Comment by 25icecreamflavors** [comment]
Hello, I was able to run 70B-chat on 2 tesla A100, it took about 66GB on each of them. I also was able to run it on 1 A100, using `load_in_8bit=True`, that takes about 68GB.

**Comment by Germany321** [comment]
How to run Llama-70B-chat-hf?

**Comment by amitsangani** [comment]
Are you asking for training or inferencing? For inferencing you can use it on a single A100. For training, you might need multiple GPUs depending on how you plan to shard. You can use PyTorch's FSDP for sharding. Also, if you have further questions on fine-tuning, you can post it on llama github recipes. 

https://github.com/facebookresearch/llama-recipes
