### ISSUE TITLE
No permission to run ./download.sh

### ISSUE THREAD

**Issue by xsstbka** [facebookresearch/llama#582]
When I run ./download.sh, Mac shows that:
(llama2) richardxu@Richards-MacBook-Pro llama % ./download.sh
zsh: permission denied: ./download.sh

it never reminds me to paste URL

**Comment by kechan** [comment]
chmod +x download.sh 

and then retry.

**Comment by sonu71432** [comment]
chmod +x download.sh

**Comment by macarran** [comment]
closing as the answers above should do the trick.

**Comment by TheFinalJoke** [comment]
Fixed file permissions with https://github.com/facebookresearch/llama/pull/536, Closing issue.
