### ISSUE TITLE
ERROR 403: Forbidden.

### ISSUE THREAD

**Issue by Eacintosh** [facebookresearch/llama#584]
--2023-07-29 14:31:14--  https://download.llamameta.net/llama-2-70b-chat/consolidated.06.pth?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoiPz8%7EP1x1MDAxNEE%7EPyIsIlJlc291cmNlIjoiaHR0cHM6XC9cL2Rvd25sb2FkLmxsYW1hbWV0YS5uZXRcLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2OTA2MTE0NjF9fX1dfQ__&Signature=qa4xW-soZS6k7sX9EPu3aHrx-QalpJoCzMgU1rsSOfruVcZzRIdrpx%7ESwptCMMCAhpCKx8xLdLgwVCjDWX9IY8D7wFm5FvmT9%7ERE21klw8%7Ej7mgFZPABA1Da8JSpD7iqOhmNA0iyt4YiIChz78IACHC0jSPP1OaShmvalT5TFuRI-NJVxvUSFmGvYIGAX6iOQq-Vz068OPJWVbjMDDomcGeIW46eNVI8ng5ergR68pOVgrv1muEtTYI3wEt8ehUaqyznJw5hu1EGSG96IvYSVBOt%7EkxATRjz%7EF-J0BozzwpxzT5-EgXPpXrBMSOE0rrCarFyAbHCqjE0ejf7Xi4Z9w__&Key-Pair-Id=K15QRJLYKIFSLZ
Resolving download.llamameta.net (download.llamameta.net)... 198.18.2.46
Connecting to download.llamameta.net (download.llamameta.net)|198.18.2.46|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-07-29 14:31:14 ERROR 403: Forbidden.

--2023-07-29 14:31:14--  https://download.llamameta.net/llama-2-70b-chat/consolidated.07.pth?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoiPz8%7EP1x1MDAxNEE%7EPyIsIlJlc291cmNlIjoiaHR0cHM6XC9cL2Rvd25sb2FkLmxsYW1hbWV0YS5uZXRcLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2OTA2MTE0NjF9fX1dfQ__&Signature=qa4xW-soZS6k7sX9EPu3aHrx-QalpJoCzMgU1rsSOfruVcZzRIdrpx%7ESwptCMMCAhpCKx8xLdLgwVCjDWX9IY8D7wFm5FvmT9%7ERE21klw8%7Ej7mgFZPABA1Da8JSpD7iqOhmNA0iyt4YiIChz78IACHC0jSPP1OaShmvalT5TFuRI-NJVxvUSFmGvYIGAX6iOQq-Vz068OPJWVbjMDDomcGeIW46eNVI8ng5ergR68pOVgrv1muEtTYI3wEt8ehUaqyznJw5hu1EGSG96IvYSVBOt%7EkxATRjz%7EF-J0BozzwpxzT5-EgXPpXrBMSOE0rrCarFyAbHCqjE0ejf7Xi4Z9w__&Key-Pair-Id=K15QRJLYKIFSLZ
Resolving download.llamameta.net (download.llamameta.net)... 198.18.2.46
Connecting to download.llamameta.net (download.llamameta.net)|198.18.2.46|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-07-29 14:31:15 ERROR 403: Forbidden.

--2023-07-29 14:31:15--  https://download.llamameta.net/llama-2-70b-chat/params.json?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoiPz8%7EP1x1MDAxNEE%7EPyIsIlJlc291cmNlIjoiaHR0cHM6XC9cL2Rvd25sb2FkLmxsYW1hbWV0YS5uZXRcLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2OTA2MTE0NjF9fX1dfQ__&Signature=qa4xW-soZS6k7sX9EPu3aHrx-QalpJoCzMgU1rsSOfruVcZzRIdrpx%7ESwptCMMCAhpCKx8xLdLgwVCjDWX9IY8D7wFm5FvmT9%7ERE21klw8%7Ej7mgFZPABA1Da8JSpD7iqOhmNA0iyt4YiIChz78IACHC0jSPP1OaShmvalT5TFuRI-NJVxvUSFmGvYIGAX6iOQq-Vz068OPJWVbjMDDomcGeIW46eNVI8ng5ergR68pOVgrv1muEtTYI3wEt8ehUaqyznJw5hu1EGSG96IvYSVBOt%7EkxATRjz%7EF-J0BozzwpxzT5-EgXPpXrBMSOE0rrCarFyAbHCqjE0ejf7Xi4Z9w__&Key-Pair-Id=K15QRJLYKIFSLZ
Resolving download.llamameta.net (download.llamameta.net)... 198.18.2.46
Connecting to download.llamameta.net (download.llamameta.net)|198.18.2.46|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-07-29 14:31:15 ERROR 403: Forbidden.

--2023-07-29 14:31:15--  https://download.llamameta.net/llama-2-70b-chat/checklist.chk?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoiPz8%7EP1x1MDAxNEE%7EPyIsIlJlc291cmNlIjoiaHR0cHM6XC9cL2Rvd25sb2FkLmxsYW1hbWV0YS5uZXRcLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2OTA2MTE0NjF9fX1dfQ__&Signature=qa4xW-soZS6k7sX9EPu3aHrx-QalpJoCzMgU1rsSOfruVcZzRIdrpx%7ESwptCMMCAhpCKx8xLdLgwVCjDWX9IY8D7wFm5FvmT9%7ERE21klw8%7Ej7mgFZPABA1Da8JSpD7iqOhmNA0iyt4YiIChz78IACHC0jSPP1OaShmvalT5TFuRI-NJVxvUSFmGvYIGAX6iOQq-Vz068OPJWVbjMDDomcGeIW46eNVI8ng5ergR68pOVgrv1muEtTYI3wEt8ehUaqyznJw5hu1EGSG96IvYSVBOt%7EkxATRjz%7EF-J0BozzwpxzT5-EgXPpXrBMSOE0rrCarFyAbHCqjE0ejf7Xi4Z9w__&Key-Pair-Id=K15QRJLYKIFSLZ
Resolving download.llamameta.net (download.llamameta.net)... 198.18.2.46
Connecting to download.llamameta.net (download.llamameta.net)|198.18.2.46|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-07-29 14:31:15 ERROR 403: Forbidden.

Checking checksums

**Comment by PRANJALRANA11** [comment]
Could you assign this issue to me

**Comment by MalikRumi** [comment]
Add me to this list!
`Resolving download.llamameta.net (download.llamameta.net)... 13.227.37.125, 13.227.37.85, 13.227.37.9, ...
Connecting to download.llamameta.net (download.llamameta.net)|13.227.37.125|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-07-29 13:45:21 ERROR 403: Forbidden.
`
This is just a single representative sample. I got a ton of these. Thanks!

**Comment by MalikRumi** [comment]
UPDATE: The OP didn't mention this, and I just discovered it myself. I got new folders, each named for a model. But three of them are empty.  llama-2-13b, llama-2-70b-chat, & llama-2-13b have text files like 'checklist' and 'consolidated', but they are all zero bytes. Don't know if that helps you debug , but I decided to throw it in there.

**Comment by Eacintosh** [comment]
> Could you assign this issue to me

It's strange, I can't find the assign button, usually represented by a gear icon.
I tried regenerating the download link, but still couldn't download it completely.
Could this be related to my internet connection? My location is in China.

**Comment by KineticCookie** [comment]
Encountered the same issue.
Just got the fresh link, trying the `download.sh` script, and it fails with 403 errors

> Resolving download.llamameta.net (download.llamameta.net)... 52.84.106.31, 52.84.106.74, 52.84.106.72, ...
Connecting to download.llamameta.net (download.llamameta.net)|52.84.106.31|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-07-30 09:57:00 ERROR 403: Forbidden.
...
Checking checksums
md5sum: checklist.chk: no properly formatted checksum lines found

**Comment by KineticCookie** [comment]
> Encountered the same issue. Just got the fresh link, trying the `download.sh` script, and it fails with 403 errors. Doesn't matter which model I choose.
> 
> > Resolving download.llamameta.net (download.llamameta.net)... 52.84.106.31, 52.84.106.74, 52.84.106.72, ...
> > Connecting to download.llamameta.net (download.llamameta.net)|52.84.106.31|:443... connected.
> > HTTP request sent, awaiting response... 403 Forbidden
> > 2023-07-30 09:57:00 ERROR 403: Forbidden.
> > ...
> > Checking checksums
> > md5sum: checklist.chk: no properly formatted checksum lines found

Nevermind, in my case `&` symbol somehow  became `&amp;` and broke the downloader. Now it works.

**Comment by MaticConradi** [comment]
There were TWO `&amp;` in the URL. Replacing those solved this issue for me.

**Comment by CamilleZ99** [comment]
> > Could you assign this issue to me
> 
> It's strange, I can't find the assign button, usually represented by a gear icon. I tried regenerating the download link, but still couldn't download it completely. Could this be related to my internet connection? My location is in China.
Hi, did you fix the issue? Any solution help resolving? Thanks.
