### ISSUE TITLE
llama-2-70b-cht-hf. git lfs. cloning issue

### ISSUE THREAD

**Issue by ahadda5** [facebookresearch/llama#586]
run > git clone 

I have plenty of space for this model. 

git clone https://huggingface.co/meta-llama/Llama-2-70b-chat-hf
Cloning into 'Llama-2-70b-chat-hf'...
remote: Enumerating objects: 78, done.
remote: Counting objects: 100% (54/54), done.
remote: Compressing objects: 100% (54/54), done.
remote: Total 78 (delta 19), reused 0 (delta 0), pack-reused 24
Unpacking objects: 100% (78/78), 504.52 KiB | 2.56 MiB/s, done.
Filtering content: 100% (32/32), 32.96 GiB | 5.44 MiB/s, done.
Encountered 28 files that may not have been copied correctly on Windows:
        model-00001-of-00015.safetensors
        pytorch_model-00011-of-00015.bin
        pytorch_model-00001-of-00015.bin
        model-00011-of-00015.safetensors
        model-00007-of-00015.safetensors
        pytorch_model-00007-of-00015.bin
        model-00003-of-00015.safetensors
        pytorch_model-00003-of-00015.bin
        pytorch_model-00010-of-00015.bin
        pytorch_model-00006-of-00015.bin
        pytorch_model-00005-of-00015.bin
        pytorch_model-00009-of-00015.bin
        pytorch_model-00013-of-00015.bin
        model-00005-of-00015.safetensors
        model-00009-of-00015.safetensors
        pytorch_model-00002-of-00015.bin
        model-00006-of-00015.safetensors
        model-00013-of-00015.safetensors
        model-00010-of-00015.safetensors
        model-00002-of-00015.safetensors
        pytorch_model-00004-of-00015.bin
        pytorch_model-00008-of-00015.bin
        pytorch_model-00012-of-00015.bin
        model-00012-of-00015.safetensors
        pytorch_model-00014-of-00015.bin
        model-00014-of-00015.safetensors
        model-00004-of-00015.safetensors
        model-00008-of-00015.safetensors

**Comment by ahadda5** [comment]
Git smudge is not offering any insight. 
When running the model through the 'Transformers' pipeline, it seem to complain about the 

[2023-07-29 11:46:27,892][ERROR][root] shape '[1, 531, 64, 128]' is invalid for input of size 543744
There is a size mismatch possibly b/c of the "they may have not been copied correctly?"

**Comment by ahadda5** [comment]
Even if I use huggface_hub snapshot_download there seems the same issue 


`RuntimeError: shape '[1, 531, 64, 128]' is invalid for input of size 543744`

**Comment by cywen6** [comment]
I encountered a similar issue, and I resolved it by updating transformers to version 4.31.0

**Comment by samuelselvan** [comment]
Tagging @osanseviero

**Comment by osanseviero** [comment]
Hi all! As mentioned by @cywen6, please make sure to use transformers 4.31.0 or later! Llama 2 was introduced in that release https://github.com/huggingface/transformers/releases/tag/v4.31.0

**Comment by ujjwalkarn** [comment]
Closing since this is answered above, please reopen if further discussion is needed.
