### ISSUE TITLE
Where is the download script?

### ISSUE THREAD

**Issue by MalikRumi** [facebookresearch/llama#587]
The readme says in relevant part:

> Once your request is approved, you will receive a signed URL over email. Then run the download.sh script, passing the URL provided when prompted to start the download. 

Maybe it's just me, but I see **nothing** about _where_ to find this script _to begin with_. I decided to just guess:

```
malikarumi@Tetuoan2:~$ ./download.sh
bash: ./download.sh: No such file or directory
```
But of course that didn't work. Evidently other people had no issues here, so, can anyone help me out here? SOON, before my 24 hours expire later today? Thanks.

**Comment by MalikRumi** [comment]
Found someone who knew the answer:  https://www.youtube.com/watch?v=qmcOlGCjQyg

**Comment by imvetri** [comment]
Clone the repo, cd into the directory

**Comment by rexionmars** [comment]
Step 1: Clone the repository
```
git clone https://github.com/facebookresearch/llama.git
```

Step 2: Enter the cloned repository
```
cd llama && ls
```

Step 3: Add execution permission to the script
```
chmod +x download.sh
```

**Alternate method:**
Step 1: Download the script using wget
```
wget https://raw.githubusercontent.com/facebookresearch/llama/main/download.sh
```

Step 2: Add execution permission to the script
```
chmod +x download.sh
```

**Comment by lmarcon** [comment]
@MalikRumi did the step above help in solving your issue?

**Comment by TheFinalJoke** [comment]
Closing Issue. If the fix above did not resolve your issue, Feel Free to reopen
