### ISSUE TITLE
Config.json Error

### ISSUE THREAD

**Issue by flaviobrienza** [facebookresearch/llama#593]
When I try to use it  with the following code: 
`from langchain.llms import HuggingFaceHub 

google_kwargs = {'temperature':0.6, 'max_length': 64}
llm = HuggingFaceHub(repo_id='meta-llama/Llama-2-7b-chat', huggingfacehub_api_token=hugging_face_token, model_kwargs=google_kwargs) 
name = llm('I want to open an Italian restaurant, suggest me a name for this')
print(name)` 

It returns me this error:
`ValueError: Error raised by inference API: meta-llama/Llama-2-7b-chat does not appear to have a file named config.json. Checkout 'https://huggingface.co/meta-llama/Llama-2-7b-chat/2abbae1937452ebd4eecb63113a87feacd6f13ac' for available files.`

Why this?

**Comment by flaviobrienza** [comment]
Thanks for your reply, but unfortunately the hf version is only for PRO users, so there is no free way to use it forn HuggingFaceHub.Inviato dal mio Galaxy
-------- Messaggio originale --------Da: Emanuela Boros ***@***.***> Data: 01/08/23  16:29  (GMT+01:00) A: facebookresearch/llama ***@***.***> Cc: Flavio Brienza ***@***.***>, Author ***@***.***> Oggetto: Re: [facebookresearch/llama] Config.json Error (Issue #593) 
To load it with hf, this is the correct version: meta-llama/Llama-2-7b-chat-hf

**Comment by EmanuelaBoros** [comment]
If you’re talking about the HuggingFace account, it’s free by the way. Otherwise, I don’t know to which PRO users you’re referring to.

**Comment by flaviobrienza** [comment]
When I try the same code with "-hf" it returns me an error saying that a
PRO version is needed. HuggingFace allows you to create a PRO account for
~€10 per month.
Personally, I switched to OpenAI, at least until they will make it for free.

Il Mer 2 Ago 2023, 09:54 Emanuela Boros ***@***.***> ha
scritto:

**Comment by EmanuelaBoros** [comment]
The problem most probably comes from `langchain`, cause the model is freely available. Try loading it with `AutoModelForCausalLM`.

**Comment by flaviobrienza** [comment]
Still the same error, I am seeing that I am not the only one.
I am attaching you the error.
Thank you.

Il Mer 2 Ago 2023, 17:36 Emanuela Boros ***@***.***> ha
scritto:

**Comment by gangula-karthik** [comment]
am also facing the same issue, is it resolved yet ?

```
repo_id = "meta-llama/Llama-2-7b-chat-hf"
llama_llm = HuggingFaceHub(
    repo_id=repo_id, model_kwargs={"temperature": 0.6, "max_new_tokens": 2000}, huggingfacehub_api_token=HUGGINGFACEHUB_API_TOKEN
)
```

**Comment by flaviobrienza** [comment]
Nope, I suggest you OpenAI if you want to do some projects with it. Its
models are really cheap.

Il Dom 20 Ago 2023, 05:00 LEAP ***@***.***> ha scritto:

**Comment by dongwang218** [comment]
The hf hub inference api has a [10gb](https://discuss.huggingface.co/t/does-llama-2-need-pro-subscription/48554/2) free limit, over that needs prod subscription. You can run the pipeline locally. Without a GPU, it needs ~30GB ram using FloatTensor.
```
> huggingface-cli login
> python
from langchain.llms import HuggingFacePipeline
hf = HuggingFacePipeline.from_model_id(
    model_id='meta-llama/Llama-2-7b-chat-hf',
    task="text-generation",
    pipeline_kwargs={'temperature':0.6, 'max_length': 512},
)
hf('I want to open an Italian restaurant, suggest me a name for this')

' restaurant.\nThe name of the restaurant should be catchy and memorable, and it should reflect the theme and cuisine of the restaurant. Here are some suggestions for an Italian restaurant name:\n1. Bella Vita - This name means "beautiful life" in Italian, and it\'s a fitting name for a restaurant that serves delicious Italian food.\n2. La Dolce Vita - This name means "the sweet life" in Italian, and it\'s a great name for a restaurant that serves rich and indulgent Italian dishes.\n3. Il Posto - This name means "the place" in Italian, and it\'s a great name for a restaurant that wants to be seen as a cozy and welcoming place to eat.\n4. Pasta Fresca - This name means "fresh pasta" in Italian, and it\'s a great name for a restaurant that specializes in homemade pasta dishes.\n5. Buon Appetito - This name means "good appetite" in Italian, and it\'s a great name for a restaurant that wants to be seen as a fun and lively place to eat.\n6. Cucina - This name means "kitchen" in Italian, and it\'s a great name for a restaurant that wants to be seen as a place where food is prepared with love and care.\n7. Ristorante - This name means "restaurant" in Italian, and it\'s a great name for a restaurant that wants to be seen as a place that serves traditional Italian cuisine.\n8. Amore - This name means "love" in Italian, and it\'s a great name for a restaurant that wants to be seen as a place where food is prepared with love and care.\n9. Toscano - This name means "Tuscan" in Italian, and it\'s a great name for a restaurant that wants to be seen as a place that serves traditional Tuscan cuisine.\n10. Trattoria - This name means "tavern" in Italian, and it\'s a great name for a restaurant that wants to be seen as a place that serves simple, hearty Italian dishes.\nThese are just a few suggestions for an Italian restaurant name. You can choose the name that you think best reflects the'
```

**Comment by flaviobrienza** [comment]
Sorry but is there any way to solve this problem? From the official HF Meta's account the model is not usable. Still the config.json file error.
