### ISSUE TITLE
How to load llama2-70b-chat with only 4 GPUs(A6000 ada 48GB)

### ISSUE THREAD

**Issue by llmind** [facebookresearch/llama#594]
The default llama2-70b-chat is sharded into 8 pths with MP=8, but I only have 4 GPUs and 192GB GPU mem. Is there any way to reshard the 8 pths into 4 pths? So that I can load the state_dict for inference.

**Comment by artetaout** [comment]
hey, i want to run on 4 * A10, my command is 
```
torchrun --nproc_per_node 4 example_text_completion.py     --ckpt_dir /Llama-2-7b/     --tokenizer_path /Llama-2-7b/tokenizer.model     --max_seq_len 128 --max_batch_size 4
```

but it says 
```
AssertionError: Loading a checkpoint for MP=1 but world size is 4
```

and i find everywhere but nothing to provide this multi-gpu args

do you know how should i set it ?

**Comment by llmind** [comment]
> hey, i want to run on 4 * A10, my command is
> 
> ```
> torchrun --nproc_per_node 4 example_text_completion.py     --ckpt_dir /Llama-2-7b/     --tokenizer_path /Llama-2-7b/tokenizer.model     --max_seq_len 128 --max_batch_size 4
> ```
> 
> but it says
> 
> ```
> AssertionError: Loading a checkpoint for MP=1 but world size is 4
> ```
> 
> and i find everywhere but nothing to provide this multi-gpu args
> 
> do you know how should i set it ?

I think 7b has only one shard, so
`torchrun --nproc_per_node **1** example_text_completion.py     --ckpt_dir /Llama-2-7b/     --tokenizer_path /Llama-2-7b/tokenizer.model     --max_seq_len 128 --max_batch_size 4` will work for you.

**Comment by llmind** [comment]
Solved! 
step1. convert pth shards to huggingface weights by https://github.com/huggingface/transformers/blob/d27e4c18fe2970abcb9a48dcb8a824e48083b15f/src/transformers/models/llama/convert_llama_weights_to_hf.py#L105

step2. load llama2 local model using huggingface transformers

**Comment by lzy37ld** [comment]
How to do multi-node inference?

I only have 4 gpus per node but I can access two nodes with 4 GPU each.

**Comment by ColinHuanghb** [comment]
Hi, I wonder whether 4x6000ada could run the full parameter finetuning on pure_bf16?

**Comment by mexiQQ** [comment]
Hi, all, 

Please try the following script: https://github.com/mexiQQ/llama-70b-chat-4-shards/tree/main

**Comment by mexiQQ** [comment]
> The default llama2-70b-chat is sharded into 8 pths with MP=8, but I only have 4 GPUs and 192GB GPU mem. Is there any way to reshard the 8 pths into 4 pths? So that I can load the state_dict for inference.

https://github.com/mexiQQ/llama-70b-chat-4-shards/tree/main

**Comment by mexiQQ** [comment]
> How to do multi-node inference?
> 
> I only have 4 gpus per node but I can access two nodes with 4 GPU each.

https://github.com/mexiQQ/llama-70b-chat-4-shards/tree/main
