### ISSUE TITLE
How to prompt llama to do multiple choice questions for benchmarking?

### ISSUE THREAD

**Issue by zy-Liang** [facebookresearch/llama#596]
Hello, I'm trying to benchmark llama (and some llama-based models) with a range of question-answer datasets. A question consists of a question and several choices. Currently, my prompt is similar to this format:
```python
prompt = ["question: ...", "options: A: ..., B: ..., ...", "The correct answer is"]
```
The generation result is like
```
The correct answer is B ...
The correct answer is C ...
The correct answer is A ...
...
```
Is it possible to have the model output a singe choice?

**Comment by subramen** [comment]
You can either finetune on your QA datasets (refer to https://github.com/facebookresearch/llama-recipes/blob/main/docs/LLM_finetuning.md) or include some examples of your desired format in the prompt
