### ISSUE TITLE
Unable to establish SSL connection.

### ISSUE THREAD

**Issue by xsstbka** [facebookresearch/llama#597]
<img width="682" alt="Screenshot 2023-07-31 at 22 41 31" src="https://github.com/facebookresearch/llama/assets/140682424/d597986f-0110-4ad1-ae9d-e3eb591e7103">
<img width="682" alt="Screenshot 2023-07-31 at 22 42 38" src="https://github.com/facebookresearch/llama/assets/140682424/9263685d-2965-4661-a0ff-97c8b716283f">

**Comment by lmarcon** [comment]
@xsstbka what version of wget do you have (wget --version)?

Try to update it to the latest version and retry, older versions might not support SSL.

**Comment by samuelselvan** [comment]
@xsstbka please retry with the latest version. If any issues, please feel free re-open/comment. Thanks
