### ISSUE TITLE
md5sum: checklist.chk: no properly formatted MD5 checksum lines found

### ISSUE THREAD

**Issue by irshad001** [facebookresearch/llama#598]
Getting the following error while downloading any model. I was able to download the models last week with no issue

```
Reusing existing connection to download.llamameta.net:443.
HTTP request sent, awaiting response... 403 Forbidden
2023-08-01 01:06:14 ERROR 403: Forbidden.

Checking checksums
md5sum: checklist.chk: no properly formatted MD5 checksum lines found
```

**Comment by pantondp** [comment]
I am getting same error trying to download any model.

**Comment by IrshadUbix** [comment]
I was able to resolve it by deleting the git repository on my machine and requesting a new download link.

**Comment by rungjoo** [comment]
I have a same issue.

**Comment by sagarduwal** [comment]
I am getting the same issue for any of the models.

**Comment by irshad001** [comment]
Clean up your repo and request a new download link. It worked for me.

**Comment by mahyar-osn** [comment]
This worked for me:

https://github.com/facebookresearch/llama/issues/388#issuecomment-1641457475
