### ISSUE TITLE
Can we use xformers with LLaMA?

### ISSUE THREAD

**Issue by KohakuBlueleaf** [facebookresearch/llama#60]
I want to know if it is possible to run LLaMA with xformers.
And how to use it.

**Comment by timlacroix** [comment]
Definitely :)  Anything that computes a causal attention would work.
Feel free to use xformers.ops.memory_efficient_attention  with an xformers.ops.LowerTriangularMask for example.

Didn't include it in this example repo to be as clear as possible on what is being computed, and to make the installation as simple as possible.

**Comment by toothacher17** [comment]
> If anyone is interested, I implemented the xformers usage in my fork. Though it doesn't give any boost on a 4090 machine, maybe I did something wrong. Feel free to make PRs fixing that, if you'll find a way. Tried it on pytorch 1.13 and 2.0 as well. https://github.com/0xprincess/royal-llama

hi, @0xprincess , I guess your implementation might be wrong... I just checked your implementations:
```
            if self.use_xformers:
                mask = xformers.ops.LowerTriangularMask()
            else:
                mask = torch.full((1, 1, seqlen, seqlen), float("-inf"), device=tokens.device)
                mask = torch.triu(mask, diagonal=start_pos + 1).type_as(h)

```

xformers.ops.LowerTriangularMask() is not identical to torch.triu(mask, diagnonal=start_pos + 1) when start_pos is not zero?

**Comment by MaveriQ** [comment]
For anyone who came here looking for xformers integration with llama, maybe this would help : https://huggingface.co/ybelkada/llama-xformers/tree/main
