### ISSUE TITLE
i tried to run the code in windows 11 but showing this error. please give me some ideas to run in locally

### ISSUE THREAD

**Issue by manojajapro** [facebookresearch/llama#600]
Downloading LICENSE and Acceptable Usage Policy
./download.sh: line 17: wget: command not found
./download.sh: line 18: wget: command not found
Downloading tokenizer
./download.sh: line 21: wget: command not found
./download.sh: line 22: wget: command not found
md5sum: tokenizer_checklist.chk: No such file or directory
Downloading llama-2-7b
./download.sh: line 52: wget: command not found
./download.sh: line 55: wget: command not found
./download.sh: line 56: wget: command not found
Checking checksums
md5sum: checklist.chk: No such file or directory

**Comment by sfradley** [comment]
I was able to get moving using this: https://stackoverflow.com/a/74709129

It's for git bash, though

**Comment by harishbattula** [comment]
download this file(download.sh) from [here](https://github.com/facebookresearch/llama/blob/main/download.sh) and save it in your pwd.. it will work

**Comment by YinhaoDeng** [comment]
you don't have wget installed in your environment

**Comment by rexionmars** [comment]
sudo apt install wget
