### ISSUE TITLE
How to stream the result?

### ISSUE THREAD

**Issue by baizhaoyi523** [facebookresearch/llama#601]
The chat_completion() returns the whole result text in sync way.

Please help. To make it more human like, is there anyway to get the streamy tokens?

I guess the key point is under generate() in class Llama, but I don't know much about torch.

**Comment by baizhaoyi523** [comment]
Solved this by reaching huggingface's transformer.

**Comment by xiaobaiha** [comment]
> Solved this by reaching huggingface's transformer.

@baizhaoyi523 could you share how to stream the result?

**Comment by baizhaoyi523** [comment]
> > Solved this by reaching huggingface's transformer.
> 
> @baizhaoyi523 could you share how to stream the result?

just use TextIteratorStreamer
