### ISSUE TITLE
Cannot download the models' weights via bash

### ISSUE THREAD

**Issue by dxlong2000** [facebookresearch/llama#609]
Dear the team,

Thank you for your excellent contributions. I tried to clone the repo and run ```sh download.sh``` and then paste the URL to the ```Enter the URL from email:```. However, I consistently got the error:

```
Enter the list of models to download without spaces (7B,13B,70B,7B-chat,13B-chat,70B-chat), or press Enter for all: 
download.sh: 12: [[: not found
Downloading LICENSE and Acceptable Usage Policy
download.sh: 17: Bad substitution
```

Do you have any suggestion?

Thanks!

**Comment by Zplusdragon** [comment]
I have the same question.

**Comment by santoshbs** [comment]
I have the same issue. Any solution?

**Comment by guoxiangke** [comment]
I have the same issue. Any solution?

**Comment by guoxiangke** [comment]
Fixed:
bash download.sh
not 
sh download.sh
