### ISSUE TITLE
i cant install showing failed . help me out.

### ISSUE THREAD

**Issue by manojajapro** [facebookresearch/llama#611]
failed to create process.
while using this --""""""              torchrun --nproc_per_node 1 example_text_completion.py --ckpt_dir llama-2-7b --tokenizer_path tokenizer.model --max_seq_len 128 --max _batch_            """""""""""""""""""""""

**Comment by rguan1** [comment]
Hey @manojajapro, can you give more context on the error that you are facing? I noticed that your command you pasted is similar to the one in this section of the readme (https://github.com/facebookresearch/llama#pretrained-models). However, you may have just pasted the command wrong. 

```
torchrun --nproc_per_node 1 example_text_completion.py \
    --ckpt_dir llama-2-7b/ \
    --tokenizer_path tokenizer.model \
    --max_seq_len 128 --max_batch_size 4
```

**Comment by rguan1** [comment]
Closing out issue. Please re-open if you need further assistance.
