### ISSUE TITLE
Confused about the "hf" meaning.

### ISSUE THREAD

**Issue by pokerc** [facebookresearch/llama#612]
So, could any one tell me the "hf" mean in Llama-2-70b-hf? What's the difference between Llama-2-70b-hf and Llama-2-70b in hugging face?
"hf" means fp16? or hugging-face-format?

**Comment by eyuansu62** [comment]
hugging-face-format

**Comment by brianjking** [comment]
Isn't it human feedback?

**Comment by MatousAc** [comment]
> Isn't it human feedback? The 70b-hf is the chat tuned one with RLHF, the 70b base, isn't RLHF'ed and not trained for conversational data.

That would make sense to me if there wasn't already a Llama-2-chat and a Llama-2-chat-hf
Do you mean something different by human feedback than the Chat?

**Comment by Kwanky-Millet** [comment]
> Do you mean something different by human feedback than the Chat?

AFAIK, the chat model _is_ trained for conversations, but they went further and refined the model to be more _helpful_ using RLHF. 

[Here](https://ai.meta.com/resources/models-and-libraries/llama/#u_0_f_3C)

**Comment by MatousAc** [comment]
> > Do you mean something different by human feedback than the Chat?
> 
> AFAIK, the chat model _is_ trained for conversations, but they went further and refined the model to be more _helpful_ using RLHF.
> 
> [Here](https://ai.meta.com/resources/models-and-libraries/llama/#u_0_f_3C)

Gotcha. That makes a bit more sense. Thanks.

**Comment by lmarcon** [comment]
Seems like this issue has been answered, thanks. Closing

**Comment by armyofda12mnkeys** [comment]
so the highest rated answer here says "hugging-face-format" but another answer says the HF is cause its RLHF (Reinforced Learned Human Feedback). Which is it?

**Comment by bjascob** [comment]
I can't say for sure but, I can tell that `.from_pretrained("meta-llama/Llama-2-7b")` fails because it doesn't have a `config.json` file. However, the `meta-llama/Llama-2-7b-hf` model does have `config.json` and you can download it via the transformers `.from_pretrained()` command.

ie... it looks like `-hf` identifies a version that is converted to the Huggingface / transformers format.

**Comment by vtecftwy** [comment]
The model card on HF is clear on this: 

meta-llama/Llama-2-7b: 
"Llama 2 is a collection of pretrained and fine-tuned generative text models ranging in scale from 7 billion to 70 billion parameters. This is the repository for the 7B pretrained model. Links to other models can be found in the index at the bottom."

meta-llama/Llama-2-7b-hf: 
"Llama 2 is a collection of pretrained and fine-tuned generative text models ranging in scale from 7 billion to 70 billion parameters. This is the repository for the 7B pretrained model, **converted for the Hugging Face Transformers format**. Links to other models can be found in the index at the bottom."
