### ISSUE TITLE
example_text_completion.py gives AssertionError: tokenizer.model

### ISSUE THREAD

**Issue by harik68** [facebookresearch/llama#619]
Hi, after I downloaded the Llama-2 model weights and git cloned the llama repo, tried to run the following command on a AWS G5.12xlarge instance 

torchrun --nproc_per_node 1 example_text_completion.py --ckpt_dir llama-2-7b/ --tokenizer_path tokenizer.model --max_seq_len 128 --max_batch_size 4

But it gives the following error:

AssertionError: tokenizer.model
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 7424) of binary: /opt/conda/bin/python3.9

I do not see any file named tokenizer.model anywhere in the downloaded folders.

Thanks and Regards,
-Hari

**Comment by GenerativeAI4Finance** [comment]
You need to run download.sh
