### ISSUE TITLE
Using a different number of GPUs by merging weights

### ISSUE THREAD

**Issue by prhbrt** [facebookresearch/llama#623]
I was able to merge the 8 files for the 70B model into two, such that it runs on 2 (large) GPUs, in our case we have 2 of 80GB but not 8.

It seems to work as well, e.g. I was able to run the model and got an excellent response where gibberish is expected if the weights are wrongly concatenated.

Could this be a script or something in this repository? Is there a better or easier way to do this?

```python
import os
import re
import torch
from tqdm.cli import tqdm

path_70b = '...'

weights = {
  int(fn.split('.')[1]): torch.load(f'{path_70b}{fn}', map_location=torch.device('cpu'))
  for fn in tqdm(sorted(os.listdir(path_70b)))
  if fn.endswith('.pth')
}

# These tensors are duplicated rather than distributed among the files

not_distributed = {
  k 
  for k in weights[0].keys()
  if all((weights[0][k] == weights[i][k]).min() for i in range(1,8))
}

# What tensor dimensions should be merged, based on whether they are implemented
# as Embedding, Row or Column Parallel.

merge_dimensions ={
  r'^layers.\d+.attention.wq.weight$': 0,
  r'^layers.\d+.attention.wk.weight$': 0,
  r'^layers.\d+.attention.wv.weight$': 0,
  r'^layers.\d+.attention.wo.weight$': 1,

  r'^tok_embeddings.weight$': 1,

  r'^layers.\d+.feed_forward.w1.weight$': 0,
  r'^layers.\d+.feed_forward.w2.weight$': 1,
  r'^layers.\d+.feed_forward.w3.weight$': 0,
  r'^output.weight$': 0 
}

# Which files are merged into one
merge_groups = [[0,1,2,3], [4,5,6,7]]

# Merging (or copying if not distributed)
output_weights = {}
for output, group in enumerate(merge_groups):
  output_weights[output] = dict()
  for name in tqdm(weights[group[0]], leave=False):
    if name in not_distributed:
      output_weights[output][name] = weights[0][name]
    else:
      axis = next(axis for exp, axis in merge_dimensions.items() if re.match(exp, name))
      output_weights[output][name] = torch.cat([
          weights[member][name]
          for member in group
      ], axis=axis)

os.makedirs(f'{path_70b}/two-nodes/', exist_ok=True)
with open(f'{path_70b}/params.json') as fin:
  with open(f'{path_70b}/two-nodes/params.json', 'w') as fout:
    fout.write(fin.read())

torch.save(
    output_weights[0],
    f'{path_70b}/two-nodes/consolidated.00.pth'
)
torch.save(
    output_weights[1],
    f'{path_70b}/two-nodes/consolidated.01.pth'
)
```

**Comment by Zplusdragon** [comment]
Thanks a lot for your sharing! I tried your code and got the satisfactory results too!

**Comment by subramen** [comment]
cc @WuhanMonkey

**Comment by WuhanMonkey** [comment]
If you are using vllm, this can actually be done by setting the TP and specify which core you want to use. As long as you have enough VRAM, you can load 4 checkpoints into one GPU and run 70B models on 2 GPUs.  Here is an example:

`CUDA_VISIBLE_DEVICES=0,1 python -m vllm.entrypoints.api_server  --model meta-llama/Llama-2-70b-chat-hf --tensor-parallel-size 2 --disable-log-requests --port  8000`

**Comment by WuhanMonkey** [comment]
Closing this issue since the answers should be helpful here. Please re-open as needed.

**Comment by Jackarry188** [comment]
> Closing this issue since the answers should be helpful here. Please re-open as needed.

use i script, but got a error, like this, is that something wrong with my env?

karry@super-server:~/llms/llama3$ python3.12 split_two.py 
 73%|██████████████████████████████████████████████████████████████████████████████████▉                               | 8/11 [02:10<00:55, 18.46s/it]Killed
