### ISSUE TITLE
Logging & privacy during model use

### ISSUE THREAD

**Issue by exp-ouroborous** [facebookresearch/llama#624]
I was looking for any specific details around:

1) What happens to the data that is run through Llama 2? Is it logged or sent elsewhere? If yes what is done with that information?
2) Is there any other information (like telemetry or metadata) that is logged or sent elsewhere? If yes what is done with that information?
3) Does Meta claim any rights/access on the data is processed using Llama 2?

We are excited to test out this model but it would be great to get clarification around this.

**Comment by brianjking** [comment]
1. If you are running the model locally or through a provider that doesn't collect info, it is not logged or stored anywhere unless you tell it to do so.

2. I don't believe so.

3. Read the license and their paper.

**Comment by h1shem** [comment]
A private Instagram account was linked to Facebook, help me to reach my private Instagram account Instagram (@hsuo)
