### ISSUE TITLE
ImportError: cannot import name 'Literal' 

### ISSUE THREAD

**Issue by fundou** [facebookresearch/llama#627]
Running

$ torchrun --nproc_per_node 1 example_text_completion.py --ckpt_dir llama-2-7b --to
kenizer_path tokenizer.model     --max_seq_len 128 --max_batch_size 4

on ubuntu-18.04, WSL2 on Windows

**Comment by tanmayghare** [comment]
Which Python version are you using? ‘typing.Literal’ is only available in Python 3.8 and up.
If the latter is satisfied, try pip installing the module manually.
