### ISSUE TITLE
Training precision

### ISSUE THREAD

**Issue by imoneoi** [facebookresearch/llama#634]
What precision is used in Llama 2 training? I heard it's `bfloat16`, but why is the checkpoint released in `float16`?

Also, casting checkpoints to `bfloat16` slightly degrades performance, reducing MMLU accuracy by about 0.3%

**Comment by wangzhonghai** [comment]
Why am I training the LLAMA7B model to start training NaN

**Comment by WuhanMonkey** [comment]
Please refer to the issue above for more information.
