### ISSUE TITLE
Suggestions on running LLAMA with limited resources?

### ISSUE THREAD

**Issue by ashryaagr** [facebookresearch/llama#64]
Being a grad student, I have limited free personal resources such as Google Colab available. But in Google Colab, when I try running the `example.py` script (after downloading weights), I run out of System RAM on the following line:
```python
torch.load(ckpt_path, map_location="cpu")
```

Would greatly appreciate if anyone has suggestions on how I can run LLAMA?
1. Suggestion for free compute resources available which would have enough compute power available for running it?
2. Ways to reduce the compute required for LLAMA?

**Comment by cedrickchee** [comment]
> But in Google Colab, when I try running the `example.py` script (after downloading weights), I run out of System RAM

Which GPU and the specs in Colab?

> Would greatly appreciate if anyone has suggestions on how I can run LLAMA?

If you manage to get past model loading, I suggest you try different optimizations for inference:
- reducing the model args like max batch size, max sequence length
- Compression and acceleration like model quantization, FlexGen (algorithm and 4-bit compression), 8-bit optimizers and quantization functions (i.e., [Bitsandbytes](https://github.com/facebookresearch/bitsandbytes)), 4-bit precision
- and more here: https://github.com/cedrickchee/awesome-ml-model-compression

**Comment by ashryaagr** [comment]
Thanks a lot for your reply and suggestions But I believe that the problem is while loading the model.

> If you manage to get past model loading,
Given that Colab crashes after executing the line `torch.load(ckpt_path, map_location="cpu"`, I do not think I am getting past the model loading phase. Do you have any suggestions or workarounds to overcome this?

> Which GPU and the specs in Colab?
I am using the free version of Colab. It has 12.7 Gb System RAM and 12Gb GPU. The type of GPU they allot is not fixed.

**Comment by jagilley** [comment]
@cedrickchee Usually Colab allots me a T4, personally

**Comment by jaygdesai** [comment]
How to find which GPU has Colab allocated?

**Comment by b0kch01** [comment]
> How to find which GPU has Colab allocated?

Run this in a code cell
```
!nvidia-smi -L
```

**Comment by rpforrest1** [comment]
I am wanting to run in colab as well. How did you get the weights downloaded? I was about to manually upload but my upload speed is terrible.

I get this error:
Connecting to dobf1k6cxlizq.cloudfront.net (dobf1k6cxlizq.cloudfront.net)|13.35.153.114|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-03-03 00:35:59 ERROR 403: Forbidden.

**Comment by TechniumUnlimited** [comment]
Guys reduce the batch size to 1. You don't need 32 for limited resources

**Comment by ashryaagr** [comment]
@TechniumUnlimited The issue I am facing is with model loading `torch.load(ckpt_path, map_location="cpu")` . Batch size wont have any effect. Nevertheless, I have tried by setting batch size to 1 and couldnt load the model on colab

**Comment by lavaaa7** [comment]
> I am wanting to run in colab as well. How did you get the weights downloaded? I was about to manually upload but my upload speed is terrible.
> 
> I get this error: Connecting to dobf1k6cxlizq.cloudfront.net (dobf1k6cxlizq.cloudfront.net)|13.35.153.114|:443... connected. HTTP request sent, awaiting response... 403 Forbidden 2023-03-03 00:35:59 ERROR 403: Forbidden.

did you manage to download the files?

**Comment by rpforrest1** [comment]
> 

Not through colab. I am going to do this in AWS instead.

**Comment by fabawi** [comment]
I was able to run 7B on two 1080 Ti (only inference). Next, I'll try 13B and 33B. It still needs refining but it works! I forked LLaMA here:

https://github.com/modular-ml/wrapyfi-examples_llama

and have a readme with the instructions on how to do it:

# LLaMA with Wrapyfi

Wrapyfi enables distributing LLaMA (inference only) on multiple GPUs/machines, each with less than 16GB VRAM 

**currently distributes on two cards only using ZeroMQ. Will support flexible distribution soon!** 

**This approach has only been tested on 7B model for now, using Ubuntu 20.04 with two 1080 Tis. Testing 13B/30B models soon!**
**UPDATE: Tested on Two 3080 Tis as well!!!**

### How to?

0. Replace all instances of <YOUR_IP> and <YOUR CHECKPOINT DIRECTORY> before running the scripts
  
1. Download LLaMA weights using the official form below and install this wrapyfi-examples_llama inside conda or virtual env:

  ```
  git clone https://github.com/modular-ml/wrapyfi-examples_llama.git
  cd wrapyfi-examples_llama
  pip install -r requirements.txt
  pip install -e .
  ```

3. Install Wrapyfi with the same environment:

  ```
  git clone https://github.com/fabawi/wrapyfi.git
  cd wrapyfi
  pip install .[pyzmq]
  ```

4. Start the Wrapyfi ZeroMQ broker from within the Wrapyfi repo:

  ```
  cd wrapyfi/standalone 
  python zeromq_proxy_broker.py --comm_type pubsubpoll
  ```

5. Start the first instance of the Wrapyfi-wrapped LLaMA from within this repo and env (order is important, dont start wrapyfi_device_idx=0 before wrapyfi_device_idx=1):

  ```
  CUDA_VISIBLE_DEVICES="0" OMP_NUM_THREADS=1 torchrun --nproc_per_node 1 example.py --ckpt_dir <YOUR CHECKPOINT DIRECTORY>/checkpoints/7B --tokenizer_path <YOUR CHECKPOINT DIRECTORY>/checkpoints/tokenizer.model --wrapyfi_device_idx 1
  ```
6. Now start the second instance (within this repo and env) :

  ```
  CUDA_VISIBLE_DEVICES="1" OMP_NUM_THREADS=1 torchrun --master_port=29503 --nproc_per_node 1 example.py --ckpt_dir <YOUR CHECKPOINT DIRECTORY>/checkpoints/7B --tokenizer_path <YOUR CHECKPOINT DIRECTORY>/checkpoints/tokenizer.model --wrapyfi_device_idx 0
  ```

7. You will now see the output on both terminals

8. EXTRA: To run on different machines, the broker must be running on a specific IP in step 4. Start the ZeroMQ broker by setting the IP and provide the env variables for steps 5+6 e.g.,

  ```
  ### (replace 10.0.0.101 with <YOUR_IP> ###
  
  # step 4 modification 
  python zeromq_proxy_broker.py --socket_ip 10.0.0.101 --comm_type pubsubpoll
  
  # step 5 modification
  CUDA_VISIBLE_DEVICES="0" OMP_NUM_THREADS=1 WRAPYFI_ZEROMQ_SOCKET_IP='10.0.0.101' torchrun --nproc_per_node 1 example.py --ckpt_dir <YOUR CHECKPOINT DIRECTORY>/checkpoints/7B --tokenizer_path <YOUR CHECKPOINT DIRECTORY>/checkpoints/tokenizer.model --wrapyfi_device_idx 1
  
  # step 6 modification
  CUDA_VISIBLE_DEVICES="1" OMP_NUM_THREADS=1 WRAPYFI_ZEROMQ_SOCKET_IP='10.0.0.101' torchrun --master_port=29503 --nproc_per_node 1 example.py --ckpt_dir <YOUR CHECKPOINT DIRECTORY>/checkpoints/7B --tokenizer_path <YOUR CHECKPOINT DIRECTORY>/checkpoints/tokenizer.model --wrapyfi_device_idx 0
  ```

**Comment by markasoftware** [comment]
Use CPU: https://github.com/markasoftware/llama-cpu

It is faster than you think. Modern gaming CPU will get at least 1 word/second.

**Comment by jspisak** [comment]
Closing this one - great suggestions everyone!
