### ISSUE TITLE
model's default max_seq_len set to 512 when the model is trained to accommodate 4096 

### ISSUE THREAD

**Issue by wise-east** [facebookresearch/llama#645]
Printing `self.model.params.max_seq_len` in `llama/generation.py`: 
https://github.com/facebookresearch/llama/blob/82ce861078ce1d2a1ac17db15bda3604c684ccbe/llama/generation.py#L121C5-L121C5  shows that it is set to 512, when the [technical report](https://scontent-sea1-1.xx.fbcdn.net/v/t39.2365-6/10000000_662098952474184_2584067087619170692_n.pdf?_nc_cat=105&ccb=1-7&_nc_sid=3c67a6&_nc_ohc=O3eQj9LEMfQAX_lLbh0&_nc_ht=scontent-sea1-1.xx&oh=00_AfB4tj7yUe0PzHVEUSz27OZ03nWdbjSQDY4ZEYPSgr_EpA&oe=64D81C3F) says it is trained to accommodate 4096.

I realized this as many responses that required a long response were getting cut off mid-sentence. 

the quick fix was to do the following: 
```
        # comment out original 
        # assert max_prompt_len <= params.max_seq_len
        # total_len = min(params.max_seq_len, max_gen_len + max_prompt_len)
        total_len = min(4096, max_gen_len + max_prompt_len) 
```

**Comment by andrewchungg** [comment]
The maximum output token length is 2048, see #148 and #239.

As stated in the latter: "There are quite a few projects that are extending the context length of Llama 2. Here's a recent one: https://github.com/jquesnelle/yarn/blob/master/paper/yarn.pdf"

Feel free to re-open if still anything is unclear.

**Comment by Sravani-ytp** [comment]
If it is beyond 4096 , it is throwing error how do we handle it ??
