### ISSUE TITLE
ValueError: do_sample is set to False. when Loading Llama 2 7b chat

### ISSUE THREAD

**Issue by MUZAMMILPERVAIZ** [facebookresearch/llama#648]
ValueError: do_sample is set to False. However, temperature is set to 0.9 – this flag is only used in sample-based generation modes. Set do_sample=True or unset temperature to continue.

my code is:

from transformers import GenerationConfig, LlamaForCausalLM, LlamaTokenizer

MODEL_NAME = “meta-llama/Llama-2-7b-chat-hf”

bnb_config = BitsAndBytesConfig(
load_in_4bit=True,
bnb_4bit_use_double_quant=True,
bnb_4bit_quant_type=“nf4”,
bnb_4bit_compute_dtype=torch.bfloat16,
)

model = LlamaForCausalLM.from_pretrained(
MODEL_NAME,
device_map=“auto”,
trust_remote_code=True,
use_auth_token=True,
temperature=0.1,
do_sample=True,
quantization_config=bnb_config,
)

tokenizer = LlamaTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token

Also I explicitly changed the do_sample=True in configuration_utils.py but didn`t worked

**Comment by muhammadhasnain100** [comment]
I am encountering an issue while attempting to load the model meta-llama/Llama-2-7b-chat-hf. The specific error message I receive is:
ValueError: `do_sample` is set to `False`. However, temperature is set to 0.9 -- this flag is only used in sample-based generation modes. Set `do_sample=True` or unset temperature to continue.
To address this, I've tried implementing a solution that involves adjusting the GenerationConfig settings as follows:
generation_config = GenerationConfig(
    do_sample=True,
    temperature=0.9  # This value can be adjusted as necessary
)
However, this modification did not resolve the problem.

Below is the relevant segment of my code:

from transformers import GenerationConfig, LlamaForCausalLM, LlamaTokenizer

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
)

model = LlamaForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    trust_remote_code=True,
    quantization_config=bnb_config,
)
model.config.do_sample = True
tokenizer = LlamaTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token

I would greatly appreciate any guidance or suggestions to overcome this challenge.

**Comment by MUZAMMILPERVAIZ** [comment]
For anyone looking for a solution, it was an issue with the latest release of hugging face transformers released recently. Please downgrade to the previous version !pip install git+https://github.com/huggingface/transformers@v4.31-release to fix the issue.

I am closing the issue.

**Comment by MUZAMMILPERVAIZ** [comment]
Resolved

**Comment by pevogam** [comment]
Has this issue been reported in the Transformers project? Might be great to close with with an alternative tracker ID to follow up there.
