### ISSUE TITLE
wget: unable to resolve host address ‘download.llamameta.net’

### ISSUE THREAD

**Issue by dogxxxxx** [facebookresearch/llama#655]
error log:
![259669111-dc59f7fc-8d4f-48de-a202-77121e6abb96](https://github.com/facebookresearch/llama/assets/53805780/e0329ff9-03a7-4f63-8945-da251f441120)

I modify download.sh to download files with proxy as shown below:
![259671863-9fd93fa3-c230-4137-953d-d13c986d3be9](https://github.com/facebookresearch/llama/assets/53805780/00700a70-6a5b-4cd7-90a1-14c778bdc1a8)

How can I download llama 2 with proxy?

**Comment by Hsad1644** [comment]
you can try setting up [proxychains](https://linuxhint.com/proxychains-tutorial/), as i did, but you might not have any luck (also as myself) if the proxy is enterprise controlled and has its own shenanigans to deal with

you'd have to edit every request to be preceded by `proxychains` for instance any `wget` would become `proxychains wget`

good luck!
