### ISSUE TITLE
Confusion about the default max_seq_len = 2048

### ISSUE THREAD

**Issue by Orion-Zheng** [facebookresearch/llama#658]
When reading the class Transformer, I found that the code use max_seq_len * 2 to prepare the rotary positional encoding, which confused me for a while. Then I realized that the default max_seq_len was set to 2048, and the 'max_seq_len * 2' aims to generate 4096 positional embeddings, corresponding to the 4K context length in the paper. I understand it can achieve the purpose but why not setting max_seq_len directly to 4096? which is more clear and less likely to cause misconception.

self.freqs_cis = precompute_freqs_cis(
            self.params.dim // self.params.n_heads, self.params.max_seq_len * 2
        )

**Comment by JaredLevi18** [comment]
Maybe is for dynamism. Like you only have to change the ModelArgs instead of going direcly to the transformer block, and then multiply it two times, automatically, in case you want to change the max_seq_len value to a different one.

**Comment by JaredLevi18** [comment]
https://github.com/openai/openai-cookbook/blob/main/examples/How_to_finetune_chat_models.ipynb
it says:
Please note that currently there is a 4096 token limit for each training example. Anything longer than this will be truncated at 4096 tokens.
that's the reason.
