### ISSUE TITLE
Typo at download.sh: should be 33B, instead of 30B

### ISSUE THREAD

**Issue by imranraad07** [facebookresearch/llama#66]
This issue is related to issue #49 

The 3rd largest model size in the paper and readme file is 33B, `download.sh`, it is 30B.

Line 5:

`MODEL_SIZE="7B,13B,30B,65B"`

Line 12:

`N_SHARD_DICT["30B"]="3"`

**Comment by neuhaus** [comment]
No, 30B is correct.
