### ISSUE TITLE
Running LLaMA-2-7B on 8x K80 GPUs

### ISSUE THREAD

**Issue by ryland-goldman** [facebookresearch/llama#665]
I am trying to run the `llama-2-7b` model on an AWS EC2 p2.8xlarge instance with 8x Nvidia Tesla K80 GPUs, each with 12 GB VRAM (for a total of 96 GB). I set `--nproc-per-node=8`, but then I get this error message:

    AssertionError: Loading a checkpoint for MP=1 but world size is 8

**Comment by EmanuelaBoros** [comment]
You need to set model_parallel_size to 8. Otherwise it’s set by default to 1.  
https://github.com/facebookresearch/llama/blob/ea9f33d6d3ea8ed7d560d270986407fd6c2e52b7/llama/generation.py#L63

**Comment by ryland-goldman** [comment]
I did set `model_parallel_size` to 8. However, the 7B model has only one file (`consolidated.00.pth`), so `assert model_parallel_size = len(checkpoints)` on line 79 causes the error.

https://github.com/facebookresearch/llama/blob/82ce861078ce1d2a1ac17db15bda3604c684ccbe/llama/generation.py#L79

**Comment by EmanuelaBoros** [comment]
Yes I assumed as much, try and finetune it only on one with ‘CUDA_VISIBLE_DEVICES=0 torchrun …’

**Comment by dongwang218** [comment]
By splitting the single shard into multiple shards, we can run the 7b model using more gpus with lower ram each.
* download this [script](https://gist.github.com/benob/4850a0210b01672175942203aa36d300) to reshard.py
* python reshard.py 4 llama-2-7b splitted/llama-2-7b  # reshard into 4 parts, change to 8 if you have more
* torchrun --nproc_per_node 4 example_text_completion.py \
    --ckpt_dir splitted/llama-2-7b/ \
    --tokenizer_path tokenizer.model \
    --max_seq_len 128 --max_batch_size 4
```
> initializing model parallel with size 4
> initializing ddp with size 1
> initializing pipeline with size 1
...
```
