### ISSUE TITLE
Is it possible to train the "llamav2 7b" model on a custom dataset using Google Colab Pro, which offers approximately 32 GB of system RAM and 16 GB of GPU RAM?

### ISSUE THREAD

**Issue by TapendraBaduwal** [facebookresearch/llama#669]
Llamav2 7B  required 24GB System RAM or GPU RAM ?

**Comment by WuhanMonkey** [comment]
We are talking about GPU RAM here if you use GPU for inference. Please check out this thread - https://discuss.huggingface.co/t/llama-7b-gpu-memory-requirement/34323
