### ISSUE TITLE
Counting tokens for Chat models

### ISSUE THREAD

**Issue by abhatia-07** [facebookresearch/llama#670]
Does anyone how to calculate prompt and completion tokens for Llama Chat models for monitoring purposes?
Can we add this in responses as many times we don't have libraries to achieve this in languages like java, kotlin, etc.

Similar to tiktoken by openai - https://github.com/openai/tiktoken

**Comment by subramen** [comment]
Use the llama `Tokenizer(model_path=</path/to/tokenizer.model>).encode()` from  https://github.com/facebookresearch/llama/blob/main/llama/tokenizer.py

**Comment by abhatia-07** [comment]
Thanks for your reply @subramen !
As I mentioned, we want to implement the token counting logic in a Java/kotlin codebase.

Currently, we are using the `SentencePiece` Tokenizer Java library to load the `.model` file and tokenized the text.
But we are not sure if this is the correct approach.

Please let us know if you have any insights on this, Thanks!

**Comment by subramen** [comment]
I'm not familiar with the java lib, but if it offers the same API (initialize with the `tokenizer.model` file, `encode`) I don't see why it wouldn't be the correct approach. We can connect on linkedin/twitter in case you want to discuss more about this; github issues on this repo are mainly for reporting bugs or proposing feature requests.
