### ISSUE TITLE
Llama-2 prompts for single word answer

### ISSUE THREAD

**Issue by shubhams18** [facebookresearch/llama#675]
I am working on a use case using Llama-2 wherein the model is given a prompt (contains context and question) and the model should give answer for the provided question using the context only. I want the model to respond only with the required answer and no additional text.
For eg:

Current output - "Based on the context given the name of the actor is Daniel"
Expected output - "Daniel"

Can someone provide me some prompt examples that can help me achieve output in the above required format.

**Comment by EmanuelaBoros** [comment]
Most probably you need to give it some examples before - few-shot learning.

You can take a look here: https://github.com/facebookresearch/llama/issues/70#issuecomment-1452717938
