### ISSUE TITLE
What does MP mean?

### ISSUE THREAD

**Issue by pauldog** [facebookresearch/llama#68]
What is MP and how does this relate to GPU or multi-GPU setups?

**Comment by neuhaus** [comment]
The option `--nproc_per_node` is explained at https://pytorch.org/docs/stable/distributed.html

Looks like the README assumes a certain number of GPUs for the different models.

**Comment by Inserian** [comment]
MP relates to the model size:
1 = 7B
2 = 13B
4 = 33B
8 = 65B

Change the value before processing torchrun or python -m torch.distributed.run

**Comment by timlacroix** [comment]
MP == Model parallelism
As @neuhaus said, the value of MP must match the --nproc_per_node since each GPU will run "one shard" of the model
