### ISSUE TITLE
error when adding tokens to Llama2

### ISSUE THREAD

**Issue by mactavish91** [facebookresearch/llama#680]
Before I added words to the vocabulary, everything was fine. However, once I added new words, many words turned into "unk", with index 0. Here is an example:
![20230817-204139](https://github.com/facebookresearch/llama/assets/58135925/58194422-820d-4980-a9c0-cf80f11826a8)

**Comment by dongwang218** [comment]
hi @mactavish91, adding one token will get the next token id, and no <unk> for me, could you double check?
```
>>> from transformers import AutoTokenizer, AutoModelForCausalLM
>>> model_path = "meta-llama/Llama-2-7b-hf"
>>> tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
>>> tokenizer.encode("<GMASK> Um")
[1, 529, 29954, 1529, 16033, 29958, 6379]
>>> tokenizer.add_tokens(["<GMASK>"])
1
>>> tokenizer.encode("<GMASK> Um")
[1, 32000, 6379]
```
