### ISSUE TITLE
upload script can not be restarted  properly when a wget failed in the middle - get 403 forbidden errors

### ISSUE THREAD

**Issue by klapauciusisgreat** [facebookresearch/llama#682]
My ISP seems to not like lots of large 16GB downloads, so some transfers are terminated after a few gigabytes. I found that  when I try to restart (with wget -c), I get 403 errors.

My hypothesis is that the llama download server thinks the aborted transfer finished OK and marked the key unusable (for this file).

I've been asking for new keys to download the straggler files, but it's highly inconvenient.

Am I right with my suspicion ? Is there something that can be done about it ?

If this report is not clear enough, I'm happy to give more detail.

**Comment by hatala91** [comment]
Hello! I tried to repro this by starting a download, interrupting it with `CTRL+C` and then starting it again. I did not experience any 403 errors. Could you help reproduce this by providing additional context/ instructions, please?

Note: You'd also get a 403 error if the URL from email is older than 24 hours. Could this be the issue?
