### ISSUE TITLE
Fine-tuning the model like LLama2-70B，thanks！

### ISSUE THREAD

**Issue by babytdream** [facebookresearch/llama#686]
Hello！There are few tutorials on fine-tuning this large model LLama2-70B.  What instruction should I use to fine tune it（like Lora）？
**GPU**：16 * A10（16 * 24G）
**Data**：10,000+ pieces of data，like：{**"instruction"**: "Summarize this Ethereum transaction.",**"input"**: ":'block_timestamp': '2023-08-15 04:18:47', 'from_address': '0xc16a101973403a71a1d42fdc12fed3c5f45e5bfe', 'from_address_label': 'topensdoc.eth', 'to_address': '0x0a791089acf48912a9cfde00e3a6afe9edbc3221', .......",**"output"**: "summary text",}
Can you give some advice, thank you very much？If you have some idea，, what is the recommended setting for the epoch parameter for data of this order of magnitude?
If fine-tuning is successful, I will also disclose my steps in the community.Thanks！

**Comment by hatala91** [comment]
Thanks for raising this! We recently shared scripts for finetuning and inference at https://github.com/facebookresearch/llama-recipes

Feel free to re-open if you feel like you need more information.
