### ISSUE TITLE
Max output token length 2048?  

### ISSUE THREAD

**Issue by jim-muzzall** [facebookresearch/llama#688]
Hi,

I've been looking for documentation that describes the max output token length for Llama.  I've been running Vicuna 13b, and and running into the token length issue as I try to summarize information from many documents.  Do you know where the max token limit is documented?  

Also, is there any way around it if I needed to say generate a 3 page table that listed some entities extracted from text and the sentences they are contained within?

**Comment by rguan1** [comment]
I think some prior issues have documented the max token length #148 & #239. The short answer is 2048.
