### ISSUE TITLE
JSONDecodeError: generation_config.json on Llama-2-13b-hf model repo

### ISSUE THREAD

**Issue by tanshuai** [facebookresearch/llama#691]
```json.decoder.JSONDecodeError: Expecting ',' delimiter: line 3 column 20 (char 42)``` on https://huggingface.co/meta-llama//blob/main/generation_config.json

```
$ cat generation_config.json 
{
  "bos_token_id": 1,
  "do_sample": true.
  "eos_token_id": 2,
  "max_length": 4096,
  "pad_token_id": 0,
  "temperature": 0.6,
  "top_p": 0.9,
  "transformers_version": "4.32.0.dev0"
}
```

```  "do_sample": true. ``` should be ```  "do_sample": true,```.

**Comment by ArthurZucker** [comment]
Thanks for reporting, fixed it [here](https://huggingface.co/meta-llama/Llama-2-13b-hf/commit/db6b8eb1feabb38985fdf785a89895959e944936)
