### ISSUE TITLE
pipeline vs model.generate

### ISSUE THREAD

**Issue by linqian66** [facebookresearch/llama#696]
I tried the text generation on llama 13B with following two implementations (both in huggingface format):

**model.generate**
```
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.bfloat16,
    device_map={"": 0},
    load_in_4bit=True,
)
...
outputs = model.generate(
    **inputs, 
    generation_config=GenerationConfig(
        do_sample=True,
        max_new_tokens=max_new_tokens,
        top_p=top_p,
        temperature=temperature,
    )
)
```

**pipeline**
```
model = AutoModelForCausalLM.from_pretrained(
    model_name,
    torch_dtype=torch.float16,
    load_in_4bit=True,
    trust_remote_code=True,
    device_map="auto",
)
generation_pipe = pipeline(
    "text-generation",
    model=model,
    tokenizer=tokenizer,
    trust_remote_code=True,
    device_map="auto", 
    batch_size=batch_size,
)
response = generation_pipe(
    inputs,
    max_new_tokens=50,
    num_return_sequences=1,
    pad_token_id=tokenizer.pad_token_id,
    eos_token_id=tokenizer.eos_token_id,
)
```

I found that **model.generate** is faster but consume more GPU memory.

E.g., for a certain input instance (batch size = 1), the comparison of inference time is like:
| **model** | **pipeline** |
| --- | ----------- |
| 4 s | 10 s |

On a single 80G GPU, I can set following max batch size without OOM:
**model**: 2
**pipeline**: 4

Any idea and suggestion?

**Comment by subramen** [comment]
cc @osanseviero for hugginface API

**Comment by osanseviero** [comment]
It seems like you're using `bfloat16` for the model and `float16` for the `pipeline`, which would explain the difference in speed :)

**Comment by ujjwalkarn** [comment]
Closing since this is answered above by Omar, please reopen if further discussion is needed.
