### ISSUE TITLE
down load wrong 

### ISSUE THREAD

**Issue by sssssshf** [facebookresearch/llama#698]
Enter the list of models to download without spaces (7B,13B,70B,7B-chat,13B-chat,70B-chat), or press Enter for all: 7B
download.sh: 12: [[: not found
Downloading LICENSE and Acceptable Usage Policy
download.sh: 17: Bad substitution

**Comment by xieqihui** [comment]
Same problem encountered.

**Comment by xieqihui** [comment]
Using 
```
bash download.sh
```
instead of 
```
sh download.sh
```
solved the problem.

**Comment by jspisak** [comment]
thank you @xieqihui !!!

closing this issue.. :)
