### ISSUE TITLE
Few shot inference?

### ISSUE THREAD

**Issue by zoanthal** [facebookresearch/llama#70]
The example provided doesn't make clear how to perform iterative few-shot inference. Is this possible with this model or do we basically start with tabula rasa for each sequential prompt we provide to it?

**Comment by pauldog** [comment]
Few shot inference means that you do a prompt like this:

```
QUESTION: What colour is the sky?
ANSWER: Blue
QUESTION: What colour are strawberries?
ANSWER: Red
QUESTION: What colour are lemons?
ANSWER:
```

i.e. the prompt contains a **few** examples and it should **infer** how to continue the text by recognising the pattern.

**Comment by timlacroix** [comment]
We've added a FAQ : https://github.com/facebookresearch/llama/blob/main/FAQ.md and updated the example.py

Unclear what you mean by "iterative", the simplest (but inefficient) way to achieve this would be to call generate() iteratively with "newprompt = oldprompt + output." as suggested by @pauldog .

If you want to avoid re-encoding the prompt, you might need to create your own generator.py :)

**Comment by abhibha1807** [comment]
Its still a little unclear to me, can anyone please provide a template that I can use for few shot prompting to llama2-chat?
Specifically, @pauldog how can I put relevant tags like [INST], <<SYS>> to provide few shot examples to llama2-chat?

**Comment by sekyondaMeta** [comment]
> Its still a little unclear to me, can anyone please provide a template that I can use for few shot prompting to llama2-chat? Specifically, @pauldog how can I put relevant tags like `[INST]` or `<<SYS>>` to provide few shot examples to llama2-chat?

@abhibha1807  You can find an example of how to use the [INST] and <<SYS>> tags in a chat prompt here: https://huggingface.co/blog/llama2#how-to-prompt-llama-2
Hope that helps.

**Comment by zhenliu2012** [comment]
here's a function I use for formatting the chat prompt:
```
def format_llama2_prompt(messages):
    startPrompt = "<s>[INST] "
    endPrompt = " [/INST]"
    conversation = []
    for index, message in enumerate(messages):
        if message["role"] == "system" and index == 0:
            conversation.append(f"<<SYS>>\n{message['content']}\n<</SYS>>\n\n")
        elif message["role"] == "user":
            conversation.append(message["content"].strip())
        else:
            conversation.append(f" [/INST] {message['content'].strip()}</s><s>[INST] ")

    return startPrompt + "".join(conversation) + endPrompt
```

messages is a list of dict like:

```
messages=[
        {
            "role": "system", 
            "content": """You are a helpful and honest assistant."""
        }
    ]
```

hope this helps!

**Comment by abhibha1807** [comment]
@zhenliu2012 Thank you very much for the function. Turns out we have to use the template but in a little different manner. @YudiZh I solved the problem in this manner.
`<s>[INST] <<SYS>> You are a helpful assistant..` <</SYS>>
Specific instruction about my task 
Few shot examples 
Test case [/INST]
I stopped generation when the model encounters a </s> tag.
This worked for me for now. Will update if something else comes up.

**Comment by YudiZh** [comment]
> @zhenliu2012 Thank you very much for the function. Turns out we have to use the template but in a little different manner. @YudiZh I solved the problem in this manner.
> 
> `<s>[INST] <<SYS>> You are a helpful assistant..<</SYS>>\n Specific instruction about my task \n Few shot examples \n Test case [/INST]` I stopped generation when the model encounters a `</s>` tag. This worked for me for now. Will update if something else comes up.

Thank you for your reply!
