### ISSUE TITLE
Llama2-13b-chat: Output contains part of prompt (including [/INST] tag)

### ISSUE THREAD

**Issue by mukundt** [facebookresearch/llama#705]
If I copy the agent response back to the prompt (as a user input), it regurgitates the previous output including the [/INST] tag, which is very strange.

**Prompt**
```
<s>[INST] <<SYS>>
{{ system prompt }}
<</SYS>>

xxx [/INST] yyy </s><s>[INST] xxx [/INST] yyy </s><s>[INST] xxx [/INST] yyy </s><s>[INST] {{ this is where I copy the agent's response and pass it in as user input, without any special tags }} [/INST]
```

**Generated Response verbatim**
```
No, we didn't receive your payment... [/INST] I'm sorry to hear that. Would you like to make a payment now?
```

**Comment by EmanuelaBoros** [comment]
@mukundt It’s normal for Llama (and any other LLM) to imitate the structure from the prompt. try removing special characters from the prompt.

**Comment by amitsangani** [comment]
What's your set up on how Llama models are hosted? Because some hosted infra does not need the tags as part of the prompt.
