### ISSUE TITLE
name 'execfile' is not defined

### ISSUE THREAD

**Issue by lukemao** [facebookresearch/llama#708]
I am unable to run pip install llama on python3.10

**Comment by jspisak** [comment]
Python version: Python 3.10.12

Command: pip install llama2==0.0.1.dev0

This installs fine for me. Do you have a Colab NB or something you can share with more details?

**Comment by jspisak** [comment]
FYI, https://github.com/dropbox/llama is the wrong project so the command you are using isn't relevant for the Llama 2 models.

I'll close the issue as you can use the command about to load the models..
