### ISSUE TITLE
Anyway to load a checkpoint with a different world size ?

### ISSUE THREAD

**Issue by marcusobrien** [facebookresearch/llama#710]
When loading a model that was trained with N model parallels (MP > 1), is there anyway to only use 1 GPU ? 

1. Can a single GPU be split to provide 2 MPs ?
2. Can a model be trained with >1 device, but then only require 1 device to run that model for inference ? 
3. Can I use a GPU as device and my CPU for another device ? So 1 MP = GPU, and 1 MP = CPU ?

I am following the llama instructions for using the llama 2 models, and I have a 4090 GPU, and a 7950 CPU with 96 GB RAM, but when I run the 13b model with MP=1 it says "Loading a checkpoint for MP=2 but world size is 1", and when I pass in MP=2 it says " Loading a checkpoint for MP=2 but world size is 1".

7B works fine with 1MP, but is there anyway around this, so I can use 13B ? 

Or do I need another 4090 GPU (I presume they have to be the same model etc.) ? 

Thanks.

**Comment by EmanuelaBoros** [comment]
The 13b model has two `pth` files that need to be loaded thus MP=2 as mentioned here https://github.com/facebookresearch/llama#inference so I’m not aware of any possibility to run it with MP=1.

**Comment by WuhanMonkey** [comment]
Closing based on the comments above.
