### ISSUE TITLE
interfere the llama2-70b-chat

### ISSUE THREAD

**Issue by babytdream** [facebookresearch/llama#711]
command:CUDA_VISIBLE_DEVICES="0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15" python generate.py --base_model=/data/model/llama2-70b-chat/ --prompt_type=llama2 --use_gpu_id=False --share=True
It appears a BUG when I use GPUs > 10:
![image](https://github.com/facebookresearch/llama/assets/74184102/9f065f93-4e54-4708-8584-6b80ccf438ab)
![image](https://github.com/facebookresearch/llama/assets/74184102/b8f86314-e3a8-46b2-9768-af923bd31c66)

10 gpu is ok！But more gpu is helpful!
When I use GPU <= 10, it can work! Like this command:CUDA_VISIBLE_DEVICES=0,1,2,3,4,5,6,7,8,9 python generate.py --base_model=/data/model/llama2-70b-chat/ --prompt_type=llama2 --use_gpu_id=False --share=True
But I need more gpu because longer prompt need more gpu memmory.Thanks!

**Comment by EmanuelaBoros** [comment]
8 gpus are sufficient (70b has 8 `pth` for les)

**Comment by babytdream** [comment]
@EmanuelaBoros 
Hello！My gpu is 16 * A10(16 * 23g). If I want to increase the length of prompt, the gpu memory will increase. So if I use more gpu to inference the llama2-70b-chat, the question will solve. 
I ask many people about it, but falied. Do you have some ideas? Thanks!

**Comment by albertodepaola** [comment]
Related to #719 and [this](https://github.com/facebookresearch/llama-recipes/issues/140) previous discussion, please follow up on those issues.
