### ISSUE TITLE
Unable to establish SSL connection.

### ISSUE THREAD

**Issue by roselite-iris** [facebookresearch/llama#715]
Resolving download.llamameta.net... 13.33.88.72, 13.33.88.62, 13.33.88.113, ...
Connecting to download.llamameta.net|13.33.88.72|:443... connected.
OpenSSL: error:140773E8:SSL routines:SSL23_GET_SERVER_HELLO:reason(1000)
Unable to establish SSL connection.
Checking checksums
md5sum: checklist.chk: no properly formatted MD5 checksum lines found

**Comment by brendan8c** [comment]
wget for windows 1.11.4 (the latest from https://gnuwin32.sourceforge.net/packages/wget.htm) doesn't support TLS 1.2 (per https://superuser.com/questions/1103856/wget-for-windows-with-tls-1-2), so it fails to connect.

1.21.4 from https://eternallybored.org/misc/wget/ appears to be working.

**Comment by lmarcon** [comment]
@roselite-iris did the suggestion above help solve your issue?

**Comment by roselite-iris** [comment]
solved， thanks a lot！
----- 原始邮件 -----
发件人：Lorenzo Marcon ***@***.***>
收件人：facebookresearch/llama ***@***.***>
抄送人：roselite-iris ***@***.***>,  Mention ***@***.***>
主题：Re: [facebookresearch/llama] Unable to establish SSL connection. (Issue #715)
日期：2023年09月01日 18点47分


@roselite-iris did the suggestion above help solve your issue?
