### ISSUE TITLE
binary format question for i.e.

### ISSUE THREAD

**Issue by jdgh000** [facebookresearch/llama#718]
I downloaded llama-2-7b-chat.ggmlv3.q8_0.bin and writing some parser.
The 4 byte is sig and next 4 bytes supposed to vocab. According to https://github.com/ggerganov/ggml 's example gpt-2. (look into main.cpp in example/gpt-2 and how it loads the binary and check the fields using fin  if stream object in there)
It also says llama-2-7b-chat.ggmlv3.q8_0.bin, is llvm but signature is different: tjgg vs. lmgg for gpt-2 example above.
NExt four byte of llama shows 00 00 00 03, only size 3? that can not be. Can you explain??

00000000  74 6a 67 67 03 00 00 00  00 7d 00 00 00 10 00 00  |tjgg.....}......|
00000010  00 01 00 00 20 00 00 00  20 00 00 00 80 00 00 00  |.... ... .......|
00000020  07 00 00 00 05 00 00 00  20 e2 81 87 20 00 00 00  |........ ... ...|
00000030  00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  |................|

**Comment by albertodepaola** [comment]
This repo is intended for installing Llama2 and running inference. Please submit issues related to getting the models, running inference, general questions and feature requests about Llama. I suggest opening this issue in the linked repo.
