### ISSUE TITLE
HuggingFace request not yet approved

### ISSUE THREAD

**Issue by shashank140195** [facebookresearch/llama#724]
Hi, I requested to access the model cards on HF from the same ID i requested on Meta Website and yet my HF request is not approved yet.

**Comment by osanseviero** [comment]
The HF request is processed/accepted by Meta, not by HF. @shashank140195, I would suggest to verify you filled both with the same email address

**Comment by osanseviero** [comment]
Meta website tends to approve in few minutes-few hours. It should not take more than that

**Comment by yazanatibm** [comment]
Same thing here. The HF and Meta website emails are identical. Been waiting for 9 days now. No email ("with more information" as described) was sent upon filling the form on Meta website.

Kindly asking for Meta to look into this. Thanks.

**Comment by shashank140195** [comment]
> The HF request is processed/accepted by Meta, not by HF. @shashank140195, I would suggest to verify you filled both with the same email address

I requested from the same Email ID. I got the access. Thank you

**Comment by aakb101** [comment]
I'm in a similar situation; I submitted a request from the same Email ID (The HF and Meta website emails are the same) over a month ago, and it's still pending. Could you kindly assist me in expediting the approval process?

**Comment by haenara-shin** [comment]
Same here :(

**Comment by Rm1n90** [comment]
@osanseviero Having the same issue with DINOV3. I requested on both the Meta and the Hugging Face platforms. Got approved in a minute on the Meta platform, but still pending on the HuggingFace platform. I used the same email and information to fill up the forms. Could you please tell me what I need to do?
