### ISSUE TITLE
Question about SFT details in llama2 paper

### ISSUE THREAD

**Issue by maxwellzh** [facebookresearch/llama#737]
Hi, I'm not sure if this is the right place for such discussion.

Read the llama2 paper section 3.1, you mentioned
> To ensure the model sequence length is properly filled, we concatenate all the prompts and answers from the training set.

I don't understand how padding zeros differs to concating prompts. For a causal LM, for example, there is a concat sample (prompt1, answer1, prompt2), but the attentions at answer1 positions won't see that from prompt2, so I think use a prompt2 or zeros (longer or shorter than 4096) doesn't make any difference. Can someone please clarify this? Thank you.

**Comment by xs1997zju** [comment]
+1 same question

**Comment by maxwellzh** [comment]
@ruanslv Thank you! I now understand.

So the point is that, you merged multiples samples into one (if shorter than max_length), and use the [SEP] token to tell models to ignore context in front. I thought prompt2 just for padding so it confused me.
