### ISSUE TITLE
Unable to run inference 

### ISSUE THREAD

**Issue by varshachawan** [facebookresearch/llama#74]
`nvcc --version`
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Wed_Jul_22_19:09:09_PDT_2020
Cuda compilation tools, release 11.0, V11.0.221
Build cuda_11.0_bu.TC445_37.28845127_0

`uname -m`
x86_64

`lsb_release -a`
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster

```torchrun --nproc_per_node 1 example.py --ckpt_dir /home/jupyter/llama/model/7B --tokenizer_path /home/jupyter/llama/model/tokenizer.model```

Traceback (most recent call last):
  File "/opt/conda/lib/python3.7/site-packages/torch/__init__.py", line 172, in _load_global_deps
    ctypes.CDLL(lib_path, mode=ctypes.RTLD_GLOBAL)
  File "/opt/conda/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
**_OSError: /opt/conda/lib/python3.7/site-packages/torch/lib/../../nvidia/cublas/lib/libcublas.so.11: symbol cublasLtHSHMatmulAlgoInit version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference_**

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/bin/torchrun", line 5, in <module>
    from torch.distributed.run import main
  File "/opt/conda/lib/python3.7/site-packages/torch/__init__.py", line 217, in <module>
    _load_global_deps()
  File "/opt/conda/lib/python3.7/site-packages/torch/__init__.py", line 178, in _load_global_deps
    _preload_cuda_deps()
  File "/opt/conda/lib/python3.7/site-packages/torch/__init__.py", line 158, in _preload_cuda_deps
    ctypes.CDLL(cublas_path)
  File "/opt/conda/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /opt/conda/lib/python3.7/site-packages/nvidia/cublas/lib/libcublas.so.11: symbol cublasLtHSHMatmulAlgoInit version libcublasLt.so.11 not defined in file libcublasLt.so.11 with link time reference

**Comment by Chanka0** [comment]
This error is due to CUDA being improperly installed. In my experience the best manner to install CUDA and PyTorch is with Conda.

Conda install guide: https://conda.io/projects/conda/en/latest/user-guide/install/linux.html

After installing Conda and initializing it (you should see (base) in the terminal if you ran conda init) create an environment with Python 3.9, and install PyTorch + CUDA.

```
conda create -n llama python=3.9
//Enter the new environment
conda activate llama
//Install PyTorch and CUDA (via PyTorch dependencies)
conda install pytorch pytorch-cuda=11.7 -c pytorch -c nvidia
```

You can verify if CUDA is functioning by using the following:
```
python
>>import torch
>>torch.cuda.is_available()
True
```
