### ISSUE TITLE
download.sh: Enter for all models fails

### ISSUE THREAD

**Issue by ltimmerman3** [facebookresearch/llama#740]
- Procedure
`source download.sh; <enter url>; <Enter for all models>`
- Result
Folders etc. set up, models not downloaded. 403 Forbidden Error
- TS
Was able to download all models by explicitly passing names as a list

**Comment by EmanuelaBoros** [comment]
@ltimmerman3 Maybe a naive question, but did you press Enter or you typed Enter? (It happened before)

**Comment by c4pointer** [comment]
I have the same issue `--2023-08-31 14:21:10--  https://download2.llamameta.net/llama-2-70b/checklist.chk?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoiMHVybXEzMnViZmllMDE5bXI1bjloejZoIiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQyLmxsYW1hbWV0YS5uZXRcLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2OTM1NjU1ODV9fX1dfQ__&Signature=t-rugP1sji9bcG7oiutZ5rN9vpFWDKM3gq%7Emf%7Eoitloka9XeC4p6lH7iE3pinpradJXJ4wRF2lMuvId2qunQxvQHpB32NLI3TvkZyQ2JUmRYRbuP6Z0TngU1kGmjgFcc8RDmNMs9mCK4cqMutnqFqMg5yWdJMUAKPFcdtR8DbADeaxLyNJ09wDNV0jcnzNKauD--VCFwXLCaUIpnKj5OgMZsRBo4dF3DVjCSFxZ30qmDKoplvt3ZNujdwXF8X4qLr0P258NM2go4YoMjWVnd2dLSBJbKkiHEazwIpM6b5Q2nt1REidX-dxWJDqj5KL8dzbYiaTdvSutNw7224IDDXQ__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=271626345648990
Loaded CA certificate '/etc/ssl/certs/ca-certificates.crt'
Resolving download2.llamameta.net (download2.llamameta.net)... 52.84.106.6, 52.84.106.68, 52.84.106.98, ...
Connecting to download2.llamameta.net (download2.llamameta.net)|52.84.106.6|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-08-31 14:21:11 ERROR 403: Forbidden.`

**Comment by lmarcon** [comment]
@ltimmerman3, @c4pointer what version of wget do you have (wget --version)?

Try to update it to the latest version and retry, older versions might not support SSL.

**Comment by wheaney** [comment]
I'm getting a 403 forbidden as well. apt reports that my wget is on the latest version. Here's what I see with `--version`:
GNU Wget 1.21 built on linux-gnu

**Comment by samuelselvan** [comment]
@ltimmerman3 @c4pointer @wheaney - are you all still facing the issues? if yes would you be able to request new link and paste the logs.

Downloading all the models at the same time is a lot to run in a single session. I would suggest downloading one at a time to unblock.

**Comment by reyfuu** [comment]
yeah when i get rid --continue and get new link. i can download all the model now
