### ISSUE TITLE
Discussion: MIDI generation

### ISSUE THREAD

**Issue by pancoaster** [facebookresearch/llama#743]
Curious what’s needed to train/fine tune the open source model weights’ prior knowledge to connect with new sources of data to generate MIDI files? Any suggestions?

**Comment by HamidShojanazeri** [comment]
@pancoaster you can find some resources on [llama-recipe](https://github.com/facebookresearch/llama-recipes).

**Comment by pancoaster** [comment]
Thanks for the pointer. Would be pretty sweet if meta released an open-source polyphonic midi generator

**Comment by jspisak** [comment]
thanks for the thread and the request. will take this back to the team!  cc @deviparikh
