### ISSUE TITLE
download.sh run error

### ISSUE THREAD

**Issue by Houtx** [facebookresearch/llama#747]
root@*****:/home/****/workspace/llama# sh download.sh
Enter the URL from email: https://download2.llamameta.net/*?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoicG..................................

Enter the list of models to download without spaces (7B,13B,70B,7B-chat,13B-chat,70B-chat), or press Enter for all:
download.sh: 12: [[: not found
Downloading LICENSE and Acceptable Usage Policy
download.sh: 17: Bad substitution

**Comment by Houtx** [comment]
After press enter, some error messages will be prompted.

**Comment by Houtx** [comment]
Ubuntu 22.04

**Comment by lmarcon** [comment]
What does your `/bin/bash --version` print?

Make sure you got the latest version of download.sh. Do the first 15 lines show the following?

```
#!/bin/bash

# Copyright (c) Meta Platforms, Inc. and affiliates.
# This software may be used and distributed according to the terms of the Llama 2 Community License Agreement.

read -p "Enter the URL from email: " PRESIGNED_URL
echo ""
read -p "Enter the list of models to download without spaces (7B,13B,70B,7B-chat,13B-chat,70B-chat), or press Enter for all: " MODEL_SIZE
TARGET_FOLDER="."             # where all files should end up
mkdir -p ${TARGET_FOLDER}

if [[ $MODEL_SIZE == "" ]]; then
    MODEL_SIZE="7B,13B,70B,7B-chat,13B-chat,70B-chat"
fi
```

**Comment by miyang211** [comment]
Make sure you are running the script in a Bash environment;  ensure this by running 'bash download.sh' in the terminal

**Comment by agunapal** [comment]
Please check this FAQ 
https://github.com/facebookresearch/llama/blob/bug-fix-Sep6/Download.md
