### ISSUE TITLE
Discussion: Optimization by snapshoting LLM with partial prompt

### ISSUE THREAD

**Issue by kripper** [facebookresearch/llama#749]
This issue is to discuss the following optimization algorithm idea:

1. Given a prompt = `start-prompt` (constant) + `end-prompt` (variable)
2. Run the LLM only with `start-prompt` in the context
3. Snapshot the process memory and stop the LLM
4. Somehow, add `end-prompt` to the context
5. Resume the LLM operation until getting a result
6. Restore memory snapshot and iterate from step 4 with `end-prompt-2`, and so on...

The idea behind this is to split the inference process in two steps:

1. Process the constant reusable information only once (eg: a text we want to ask many times).
2. Process each question without having the LLM to reprocess the invariant information each time.

If not feasible, what similar approaches could be used considering that a significant part of the context will be the same for each iteration?

**Comment by HamidShojanazeri** [comment]
@kripper thanks idea, this would be more similar to optimizing kv cache to me, you can find some example from VLLM [here](https://github.com/facebookresearch/llama-recipes/blob/main/inference/vLLM_inference.py) that uses paged attention idea to better manage kv cache.

**Comment by kripper** [comment]
> this would be more similar to optimizing kv cache to me

You are right, kv-caching has already been implemented in many frameworks.
