### ISSUE TITLE
Run llama2 on specified GPU

### ISSUE THREAD

**Issue by jerryli1019** [facebookresearch/llama#751]
Suppose I have 8 A6000 GPU, I would like to run separate experiments on separate GPU, how can I do it? For example, I want to run chat_completion.py on CUDA:0 and run text_completion.py on CUDA:1 simutaneously. Are there any ways to do it? Thank you.

**Comment by EmanuelaBoros** [comment]
@jerryli1019 

`CUDA_VISIBLE_DEVICES=0 torchrun example_chat_completion.py …`
`CUDA_VISIBLE_DEVICES=1 torchrun example_text_completion.py …`
