### ISSUE TITLE
Just so everyone knows, this thing calls home, and is likely stealing your data

### ISSUE THREAD

**Issue by Urammar** [facebookresearch/llama#76]
I have the following domain blocked because they keep trying to brick my VR with incompatible updates

[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [graph.oculus.com]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [graph.oculus.com]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [graph.oculus.com]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [graph.oculus.com]:29500 (system error: 10049 - The requested address is not valid in its context.).

Unless someone can tell me why an offline model requires talking to oculus servers to function, its absolutely sending at the very least analytics, but you can pretty much guarantee prompts and responses also. I mean its less than a kilobyte to send, if you can, why wouldn't you?

Zucc'd again

**Comment by TechniumUnlimited** [comment]
I dont think so, it tried to call my local PC when I ran it,
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-L2xXxTA]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [DESKTOP-L2xXxTA]:29500 (system error: 10049 - The requested address is not valid in its context.).

My guess is this is some way to setup distributed gpu inference server with pytorch

**Comment by Urammar** [comment]
> I dont think so,
> My guess is this is some way to setup distributed gpu inference server with pytorch

To... *checks notes* facebooks oculus rift app analytics server

Yes, a core part of pytorch and language model inference /s

Thats extremely naive, especially given facebooks whole business model is data harvesting, even for techbros thats naive, like basically willful copium at this point, or paid agent.

**Comment by dillfrescott** [comment]
Highly sus, but not a surprise from Meta, thats for sure

**Comment by pauldog** [comment]
What software is doing this? I don't understand?

Are you using a special "Meta Pytorch distribution"?

Why can't you just run the model with standard vanilla pytorch or tensorflow?

Or if you have the weights, you can even save them in onnx format and run the model using Onnxruntime. 

If you have the model and the weights I don't understand which software you are using that does anything special? Sorry for my ignorance.

**Comment by dillfrescott** [comment]
So is it something in the repo code that contacts the server? Because I agree that regular pytorch most likely doesnt unless you tell it to?

**Comment by henk717** [comment]
Are you sure its not trying to access 127.0.0.1 and displaying the domain you blocked?
Try putting something obscure in the host file and see if you can reproduce it with an arbitrary name.

**Comment by Urammar** [comment]
> Are you sure its not trying to access 127.0.0.1 and displaying the domain you blocked? Try putting something obscure in the host file and see if you can reproduce it with an arbitrary name.

You know what sherlock, you might have cracked the case, actually,

**Comment by dillfrescott** [comment]
LOL

**Comment by TearGosling** [comment]
This is one of the GitHub issues of all time

**Comment by iodine-pku** [comment]
The llama code is opensource and doesn't seem to have a part that does this
