### ISSUE TITLE
wget: server returned error: HTTP/1.1 416 Requested Range Not Satisfiable when trying to download Weights

### ISSUE THREAD

**Issue by GitVex** [facebookresearch/llama#760]
Hello,

I've been trying to download the model weights and tokenizer locally following the instructions in the readme.
Upon inputting the desired models (13B and 13B-chat) with the assumed format of `13B,13B-chat` I get this console error
```
Enter the URL from email: <email link>

Enter the list of models to download without spaces (7B,13B,70B,7B-chat,13B-chat,70B-chat), or press Enter for all: 13B,13B-chat
Downloading LICENSE and Acceptable Usage Policy
Connecting to download.llamameta.net (52.222.236.122:443)
wget: server returned error: HTTP/1.1 416 Requested Range Not Satisfiable
```

I've re-requested the link multiple times as well as recloned the repo, though the error doesnt seem to resolve itself.

Am I doing something wrong in my setup or is this a repo issue?

**Comment by GitVex** [comment]
Any Updates? I'm currently writing my Bachelor's Thesis and access to the model is quite critical.

**Comment by Bateoriginal** [comment]
I run into a same issue. But I was also told that "The file is already fully retrieved; nothing to do." I don't remember successfully downloading the weights and it makes me confused on how that could have happened. I wanted to check if the weights were downloaded or not but i didn't have GPU on my macbook pro. let me know if you hear anything. 

```
Enter the list of models to download without spaces (7B,13B,70B,7B-chat,13B-chat,70B-chat), or press Enter for all: (70B, 70B-chat)
Downloading LICENSE and Acceptable Usage Policy
--2023-09-07 11:32:38--  "link"
Resolving download.llamameta.net (download.llamameta.net)... 18.67.65.123, 18.67.65.37, 18.67.65.18, ...
Connecting to download.llamameta.net (download.llamameta.net)|18.67.65.123|:443... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

--2023-09-07 11:32:39--  link
Resolving download.llamameta.net (download.llamameta.net)... 18.67.65.123, 18.67.65.37, 18.67.65.18, ...
Connecting to download.llamameta.net (download.llamameta.net)|18.67.65.123|:443... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

Downloading tokenizer
--2023-09-07 11:32:39--  link
Resolving download.llamameta.net (download.llamameta.net)... 18.67.65.123, 18.67.65.37, 18.67.65.18, ...
Connecting to download.llamameta.net (download.llamameta.net)|18.67.65.123|:443... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

--2023-09-07 11:32:39--  link
Resolving download.llamameta.net (download.llamameta.net)... 18.67.65.123, 18.67.65.37, 18.67.65.18, ...
Connecting to download.llamameta.net (download.llamameta.net)|18.67.65.123|:443... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

tokenizer.model: OK
Downloading 
--2023-09-07 11:32:40--  link
Resolving download.llamameta.net (download.llamameta.net)... 18.67.65.123, 18.67.65.37, 18.67.65.18, ...
Connecting to download.llamameta.net (download.llamameta.net)|18.67.65.123|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-09-07 11:32:40 ERROR 403: Forbidden.
```

**Comment by ckxng** [comment]
Can you do me a favor and try something for me?  Please take a look at download.sh.  Inside, you will find a series of `wget` commands.  Do they have `--continue` in their argument list?  If so, please remove the instances of `--continue` and let me know if that allows you to proceed.

If this fixes your issue, can you please let me know what operating system release you are using (Ubuntu 22.04 LTS, etc) and the output of `wget --version`?

**Comment by GitVex** [comment]
Hey, thanks!

removing the `--continue` flags fixed the issue for me on a different computer in a new Debian WSL. I'll try to do the same tomorrow on the original machine I sent the issue from to see if it works after a fresh Debian installation as well.

**Comment by BJTFDGR** [comment]
removing the --continue flags fixed the issue for me.

**Comment by Bateoriginal** [comment]
unfortunately, I started having different issue: forbidden 403 right before it start downloading the models. let me know if you know what I should do. 

with -- continue after wget
```
Enter the list of models to download without spaces (7B,13B,70B,7B-chat,13B-chat,70B-chat), or press Enter for all: (7B, 7B-chat)
Downloading LICENSE and Acceptable Usage Policy
--2023-09-08 16:34:34-- link
Resolving download.llamameta.net (download.llamameta.net)... 13.224.214.60, 13.224.214.2, 13.224.214.122, ...
Connecting to download.llamameta.net (download.llamameta.net)|13.224.214.60|:443... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

--2023-09-08 16:34:34--  link
Resolving download.llamameta.net (download.llamameta.net)... 13.224.214.60, 13.224.214.2, 13.224.214.122, ...
Connecting to download.llamameta.net (download.llamameta.net)|13.224.214.60|:443... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

Downloading tokenizer
--2023-09-08 16:34:34--  link
Resolving download.llamameta.net (download.llamameta.net)... 13.224.214.60, 13.224.214.2, 13.224.214.122, ...
Connecting to download.llamameta.net (download.llamameta.net)|13.224.214.60|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 499723 (488K) [binary/octet-stream]
Saving to: ‘./tokenizer.model’

./tokenizer.model                       100%[===============================================================================>] 488.01K  --.-KB/s    in 0.04s   

2023-09-08 16:34:34 (11.9 MB/s) - ‘./tokenizer.model’ saved [499723/499723]

--2023-09-08 16:34:34--  link
Connecting to download.llamameta.net (download.llamameta.net)|13.224.214.60|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 50 [binary/octet-stream]
Saving to: ‘./tokenizer_checklist.chk’

./tokenizer_checklist.chk               100%[===============================================================================>]      50  --.-KB/s    in 0s      

2023-09-08 16:34:34 (751 KB/s) - ‘./tokenizer_checklist.chk’ saved [50/50]

tokenizer.model: OK
Downloading 
--2023-09-08 16:34:34--  link
Resolving download.llamameta.net (download.llamameta.net)... 13.224.214.60, 13.224.214.2, 13.224.214.122, ...
Connecting to download.llamameta.net (download.llamameta.net)|13.224.214.60|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-09-08 16:34:35 ERROR 403: Forbidden.
```

without -- continue after wget 

```

Enter the list of models to download without spaces (7B,13B,70B,7B-chat,13B-chat,70B-chat), or press Enter for all: (7B, 7B-chat)
Downloading LICENSE and Acceptable Usage Policy
--2023-09-08 16:43:12--  link
Resolving download.llamameta.net (download.llamameta.net)... 13.224.214.60, 13.224.214.105, 13.224.214.2, ...
Connecting to download.llamameta.net (download.llamameta.net)|13.224.214.60|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 7020 (6.9K) [binary/octet-stream]
Saving to: ‘./LICENSE’

./LICENSE                               100%[===============================================================================>]   6.86K  --.-KB/s    in 0s      

2023-09-08 16:43:12 (19.0 MB/s) - ‘./LICENSE’ saved [7020/7020]

--2023-09-08 16:43:12--  link
Resolving download.llamameta.net (download.llamameta.net)... 13.224.214.60, 13.224.214.105, 13.224.214.2, ...
Connecting to download.llamameta.net (download.llamameta.net)|13.224.214.60|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4766 (4.7K) [binary/octet-stream]
Saving to: ‘./USE_POLICY.md’

./USE_POLICY.md                         100%[===============================================================================>]   4.65K  --.-KB/s    in 0s      

2023-09-08 16:43:12 (162 MB/s) - ‘./USE_POLICY.md’ saved [4766/4766]

Downloading tokenizer
--2023-09-08 16:43:12--  link
Resolving download.llamameta.net (download.llamameta.net)... 13.224.214.60, 13.224.214.105, 13.224.214.2, ...
Connecting to download.llamameta.net (download.llamameta.net)|13.224.214.60|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 499723 (488K) [binary/octet-stream]
Saving to: ‘./tokenizer.model’

./tokenizer.model                       100%[===============================================================================>] 488.01K  2.64MB/s    in 0.2s    

2023-09-08 16:43:13 (2.64 MB/s) - ‘./tokenizer.model’ saved [499723/499723]

--2023-09-08 16:43:13--  link
Resolving download.llamameta.net (download.llamameta.net)... 13.224.214.60, 13.224.214.105, 13.224.214.2, ...
Connecting to download.llamameta.net (download.llamameta.net)|13.224.214.60|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 50 [binary/octet-stream]
Saving to: ‘./tokenizer_checklist.chk’

./tokenizer_checklist.chk               100%[===============================================================================>]      50  --.-KB/s    in 0s      

2023-09-08 16:43:13 (788 KB/s) - ‘./tokenizer_checklist.chk’ saved [50/50]

tokenizer.model: OK
Downloading 
--2023-09-08 16:43:13--  link
Resolving download.llamameta.net (download.llamameta.net)... 13.224.214.60, 13.224.214.105, 13.224.214.2, ...
Connecting to download.llamameta.net (download.llamameta.net)|13.224.214.60|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-09-08 16:43:13 ERROR 403: Forbidden.


```

**Comment by dberlinerblau** [comment]
I've been having the same issue as Bateoriginal.

Removed the **--continue** instances after the 416 Requested Range Not Satisfiable Error then got the 403 Forbidden error.

Other solutions?

**Comment by ckxng** [comment]
Just to rule the URL out, could you try re-requesting a URL and see if that makes a difference?

**Comment by ckxng** [comment]
There has been no update in 3 weeks.  If you are still experiencing an issue after re-requesting a new URL, please feel free to re-open this issue or create a new one.  Thank you!

**Comment by athishsreeram** [comment]
➜  llama git:(main) ✗ ./download.sh
Enter the URL from email: https://download.llamameta.net/*?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoieWVqYmlpNTVoYm5tNHZwM214dGQ5b3M2IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5NjYzNjU1NX19fV19&Signature=PbtVP6R3CVdw1TJg5X7vIiWIqyHqrPJlR8vAX2k8ehaTpwvz%7EYn5FNLzNo4cEe8n7Y1rmdzeOH7eXRNejQJF69Pschb2XjwJlYlUp6%7E-6IcRrDPzh1A6IuMfhT7eaL-sW2fKoxLeOSHxw-X9d2U23r8AmvKSKOLRdunEOYqelYvz%7EggzcP090Gt4X2uJGjJ6DnHjPpX7hLhKprFmweP5Z0Ia2l8NvTI170yq6kebDc01GiNDHkYJZaba0HaDmR8xt9fr4eTz-nyO49YW6NJrfN-EFwqw218hFfEgeffecIboXh0BnaaSqnm3o4n55eJoMmhySvkUKdReda9WEeAUaA__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=1279707732715914

Enter the list of models to download without spaces (7B,13B,70B,7B-chat,13B-chat,70B-chat), or press Enter for all: 7B
Downloading LICENSE and Acceptable Usage Policy
--2023-10-05 19:56:35--  https://download.llamameta.net/LICENSE?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoieWVqYmlpNTVoYm5tNHZwM214dGQ5b3M2IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5NjYzNjU1NX19fV19&Signature=PbtVP6R3CVdw1TJg5X7vIiWIqyHqrPJlR8vAX2k8ehaTpwvz%7EYn5FNLzNo4cEe8n7Y1rmdzeOH7eXRNejQJF69Pschb2XjwJlYlUp6%7E-6IcRrDPzh1A6IuMfhT7eaL-sW2fKoxLeOSHxw-X9d2U23r8AmvKSKOLRdunEOYqelYvz%7EggzcP090Gt4X2uJGjJ6DnHjPpX7hLhKprFmweP5Z0Ia2l8NvTI170yq6kebDc01GiNDHkYJZaba0HaDmR8xt9fr4eTz-nyO49YW6NJrfN-EFwqw218hFfEgeffecIboXh0BnaaSqnm3o4n55eJoMmhySvkUKdReda9WEeAUaA__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=1279707732715914
Resolving download.llamameta.net (download.llamameta.net)... 18.245.96.11, 18.245.96.71, 18.245.96.98, ...
Connecting to download.llamameta.net (download.llamameta.net)|18.245.96.11|:443... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

--2023-10-05 19:56:35--  https://download.llamameta.net/USE_POLICY.md?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoieWVqYmlpNTVoYm5tNHZwM214dGQ5b3M2IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5NjYzNjU1NX19fV19&Signature=PbtVP6R3CVdw1TJg5X7vIiWIqyHqrPJlR8vAX2k8ehaTpwvz%7EYn5FNLzNo4cEe8n7Y1rmdzeOH7eXRNejQJF69Pschb2XjwJlYlUp6%7E-6IcRrDPzh1A6IuMfhT7eaL-sW2fKoxLeOSHxw-X9d2U23r8AmvKSKOLRdunEOYqelYvz%7EggzcP090Gt4X2uJGjJ6DnHjPpX7hLhKprFmweP5Z0Ia2l8NvTI170yq6kebDc01GiNDHkYJZaba0HaDmR8xt9fr4eTz-nyO49YW6NJrfN-EFwqw218hFfEgeffecIboXh0BnaaSqnm3o4n55eJoMmhySvkUKdReda9WEeAUaA__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=1279707732715914
Resolving download.llamameta.net (download.llamameta.net)... 18.245.96.11, 18.245.96.71, 18.245.96.98, ...
Connecting to download.llamameta.net (download.llamameta.net)|18.245.96.11|:443... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

Downloading tokenizer
--2023-10-05 19:56:35--  https://download.llamameta.net/tokenizer.model?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoieWVqYmlpNTVoYm5tNHZwM214dGQ5b3M2IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5NjYzNjU1NX19fV19&Signature=PbtVP6R3CVdw1TJg5X7vIiWIqyHqrPJlR8vAX2k8ehaTpwvz%7EYn5FNLzNo4cEe8n7Y1rmdzeOH7eXRNejQJF69Pschb2XjwJlYlUp6%7E-6IcRrDPzh1A6IuMfhT7eaL-sW2fKoxLeOSHxw-X9d2U23r8AmvKSKOLRdunEOYqelYvz%7EggzcP090Gt4X2uJGjJ6DnHjPpX7hLhKprFmweP5Z0Ia2l8NvTI170yq6kebDc01GiNDHkYJZaba0HaDmR8xt9fr4eTz-nyO49YW6NJrfN-EFwqw218hFfEgeffecIboXh0BnaaSqnm3o4n55eJoMmhySvkUKdReda9WEeAUaA__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=1279707732715914
Resolving download.llamameta.net (download.llamameta.net)... 18.245.96.11, 18.245.96.71, 18.245.96.98, ...
Connecting to download.llamameta.net (download.llamameta.net)|18.245.96.11|:443... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

--2023-10-05 19:56:35--  https://download.llamameta.net/tokenizer_checklist.chk?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoieWVqYmlpNTVoYm5tNHZwM214dGQ5b3M2IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5NjYzNjU1NX19fV19&Signature=PbtVP6R3CVdw1TJg5X7vIiWIqyHqrPJlR8vAX2k8ehaTpwvz%7EYn5FNLzNo4cEe8n7Y1rmdzeOH7eXRNejQJF69Pschb2XjwJlYlUp6%7E-6IcRrDPzh1A6IuMfhT7eaL-sW2fKoxLeOSHxw-X9d2U23r8AmvKSKOLRdunEOYqelYvz%7EggzcP090Gt4X2uJGjJ6DnHjPpX7hLhKprFmweP5Z0Ia2l8NvTI170yq6kebDc01GiNDHkYJZaba0HaDmR8xt9fr4eTz-nyO49YW6NJrfN-EFwqw218hFfEgeffecIboXh0BnaaSqnm3o4n55eJoMmhySvkUKdReda9WEeAUaA__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=1279707732715914
Resolving download.llamameta.net (download.llamameta.net)... 18.245.96.11, 18.245.96.71, 18.245.96.98, ...
Connecting to download.llamameta.net (download.llamameta.net)|18.245.96.11|:443... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

./download.sh: line 29: md5sum: command not found

**Comment by sealfoss** [comment]
Seeing the same issue here.

**Comment by sealfoss** [comment]
Solution: 1) Get a new download link. 2) Remove and replace the llama directory. 3) Try again.

**Comment by rew1ndustry** [comment]
why is this problem closed?
it is ongoing and bothering me also.
why is download.sh so fragile?
this is not encouraging, i think i will obtain these files elsewhere.

**Comment by amitbar05** [comment]
For me, deleting all the files except the download.sh and running it again solved it for me.

**Comment by criptopreto** [comment]
For me it worked after installing md5sum, because if you look closely, at the end it gives an md5sum error

**Comment by dongyang03** [comment]
> I've been having the same issue as Bateoriginal.
> 
> Removed the **--continue** instances after the 416 Requested Range Not Satisfiable Error then got the 403 Forbidden error.
> 
> Other solutions?

seme

**Comment by Piotr-rogal** [comment]
I use this method and it works.

1. Go to your llama folder (e.g. cd llama3)
2. List files (ls)
3. Remove download.sh (rm download.sh)
4. Go to https://github.com/meta-llama/llama-models/blob/main/models/llama3_1/download.sh
5. Copy data from download.sh (copy raw file)
6. Use nano to create download.sh (nano download.sh)
7. Paste data from memory (ctrl+v)
8. End nano and write to file (ctrl+x)
9. Add permision to download.sh (sudo chmod +x download.sh)
10. Run download.sh (./download.sh)

Rest the same as before - paste link from meta email and next choice model:

**** Model list ***

meta-llama-3.1-405b
meta-llama-3.1-70b
meta-llama-3.1-8b
meta-llama-guard-3-8b
prompt-guard
Choose the model to download: meta-llama-3.1-8b

Selected model: meta-llama-3.1-8b

**** Available models to download: ***

meta-llama-3.1-8b-instruct
meta-llama-3.1-8b

**Comment by divyaswormakai** [comment]
> I use this method and it works.
> 
> 1. Go to your llama folder (e.g. cd llama3)
> 2. List files (ls)
> 3. Remove download.sh (rm download.sh)
> 4. Go to https://github.com/meta-llama/llama-models/blob/main/models/llama3_1/download.sh
> 5. Copy data from download.sh (copy raw file)
> 6. Use nano to create download.sh (nano download.sh)
> 7. Paste data from memory (ctrl+v)
> 8. End nano and write to file (ctrl+x)
> 9. Add permision to download.sh (sudo chmod +x download.sh)
> 10. Run download.sh (./download.sh)
> 
> Rest the same as before - paste link from meta email and next choice model:
> 
> **** Model list ***
> 
> meta-llama-3.1-405b meta-llama-3.1-70b meta-llama-3.1-8b meta-llama-guard-3-8b prompt-guard Choose the model to download: meta-llama-3.1-8b
> 
> Selected model: meta-llama-3.1-8b
> 
> **** Available models to download: ***
> 
> meta-llama-3.1-8b-instruct meta-llama-3.1-8b

Can verify it worked for me as well.

**Comment by divyaswormakai** [comment]
https://github.com/meta-llama/llama/issues/760#issuecomment-2268308391

This worked for me.

Thanks @Piotr-rogal
