### ISSUE TITLE
Load model locally for fine-tuning, with or without HF.

### ISSUE THREAD

**Issue by GioPetro** [facebookresearch/llama#761]
Hi all.

I believe the initial question is about #394 loading the pretrained model, directly downloaded from this repo.
The first question is, how can someone load it, with huggingface, as it's seemingly easier to load a pretrained model.

Indeed, when I tried to load the downloaded model, the config.json file is missing.

How can someone load the llama model from this repo, without having to use the -hf version on huggingface. 

Secondly, how can someone load the model even without huggingface module?

Thanks in advance.

**Comment by maxwellzh** [comment]
For the first question, you can take a look at this https://github.com/facebookresearch/llama-recipes#model-conversion-to-hugging-face

**Comment by subramen** [comment]
To download, follow the instructions here, it should work: https://github.com/facebookresearch/llama#download Is there a specific model size that was having a config missing?

Once you download it, you can load the model using `Llama.build` https://github.com/facebookresearch/llama/blob/main/llama/generation.py#L53  

See the args values in this example `torchrun --nproc_per_node 1 example_text_completion.py    --ckpt_dir llama-2-7b/  --tokenizer_path tokenizer.model  --max_seq_len 128 --max_batch_size 4`

**Comment by GioPetro** [comment]
Thanks for the info so far.
@subramen I have downloaded the repo, downloaded, 7b and 7b-chat versions, however, I cannot see any config file in!
![image](https://github.com/facebookresearch/llama/assets/10716225/9b1f9c7d-a185-4597-8c40-cb8de5789fec)
![image](https://github.com/facebookresearch/llama/assets/10716225/8e391945-f20b-45c4-b898-7ae797f5e4d0)
Attached the fiiles downloaded, after running the download.sh file as per instructions.
Even on the repo I cannot see any config file, so something seems off here.

Any suggestions ?

**Comment by subramen** [comment]
The config is only needed if you want to use with huggingface. Please refer to https://github.com/facebookresearch/llama-recipes#model-conversion-to-hugging-face to generate the config and use with huggingface.

**Comment by anynomousaccount** [comment]
@subramen Hello, very helpful information. Unfortunately, the link: https://github.com/facebookresearch/llama-recipes#model-conversion-to-hugging-face, seems not work, where I find it difficult to know where shows how to generate the config and use with hugging face.
Is it convenient for you to give a newest link? 
Thank you!
