### ISSUE TITLE
Llama2 is writing wrong Quran arabic verse.

### ISSUE THREAD

**Issue by Johnny463** [facebookresearch/llama#763]

**Comment by Johnny463** [comment]
I wrote write surah ikhlaas arabic verses.
it write very wrong verses that is totaaly against islam(as it is very sensitive)

**Comment by amitsangani** [comment]
Hi Johnny - understand the sensitivity. Llama 2 is intended for commercial and research use in English only. Other languages are out-of-scope. Use of other languages in any other way is prohibited by the Acceptable Use Policy and Licensing Agreement for Llama 2.

**Comment by waleedkadous** [comment]
[Will mark this as closed, just including it here as someone who works with LLMs in Arabic] 

Relying on Llama 2 to memorize the Qur'an is not a reasonable expectation. If you want to have a flawless rendition of the Qur'an, you need to rely on something other than an LLM, such as a vector database to reduce the hallucination. An example of such a project that uses LLMs and vector + keyword search to provide a seamless inclusion of Qur'anic ayahs, see https://github.com/waleedkadous/ansari.
