### ISSUE TITLE
LLama2 model straight forward steps to run on local machine

### ISSUE THREAD

**Issue by ShreeInventive** [facebookresearch/llama#764]
As a beginner, this was my first time exploring the Llama2 model, and i have a project idea of chatbot using the LLama 2 model.
But this has been the most confusing part, that how to run the model locally??
Why do i need to download an -hf, -ggml model from other user. Why this all is needed. 
For starters I want to get "Hello World" reply from the LLama2 model as response and I don'y want to get into opensource web ui and model to do this thing, when I have LLama2 original model with me officially from meta.  

I have already gone through tons of videos on YouTube and articles, but no one uses the original model by meta, why??

Please I request someone to give me straight-forward set of steps to get "Hello World" response from the LLama 2 model, using the **ORIGINAL LLAMA2 MODEL provided by META** and no other models pls. 
or refer something relevant.

**Comment by agunapal** [comment]
Hi @ShreeInventive You can use the example script https://github.com/facebookresearch/llama/blob/main/example_text_completion.py to use llama without any third party dependency.

**Comment by zeelsheladiya** [comment]
Here are the steps to run Llama 2 locally:

1. Download the Llama 2 model files.

2. Install the required Python libraries: requirement.txt. 

3. Create a Python virtual environment and activate it. 

4. Clone the Llama repository from GitHub. 

5. Build the Llama code by running "make" in the repository directory.

6. Download sample code from the Llama repository and place the model files in the same directory. 

7. Run the sample code, passing the model path as an argument. For example:

```python
python sample.py -m path/to/model/file
```

8. You should see the model responding through the command line.

Let me know if any of these steps need more clarification or if you encounter any issues. The key things are setting up the environment correctly, getting the right model files, and running the sample code to interface with Llama 2 locally.

**Comment by livius2** [comment]
With which sample script did you tested it?

> Here are the steps to run Llama 2 locally:
> 7. Run the sample code, passing the model path as an argument. For example:
> 
> ```python
> python sample.py -m path/to/model/file

`python example_chat_completion.py -m CodeLlama-7b`

```
W:\MetaLama2\llama>python example_chat_completion.py -m CodeLlama-7b
ERROR: The argument '-m' is ambiguous as it could refer to any of the following arguments: ['max_seq_len', 'max_batch_size', 'max_gen_len']
Usage: example_chat_completion.py CKPT_DIR TOKENIZER_PATH <flags>
  optional flags:        --temperature | --top_p | --max_seq_len |
                         --max_batch_size | --max_gen_len
```

**Comment by zeelsheladiya** [comment]
Hi @livius2,

The process of running the script step by step that I followed:

1. **Register to Download the Model:**
   First, please register to download the model from this [link](https://ai.meta.com/resources/models-and-libraries/llama-downloads/).

2. **Run the download.sh File:**
   After downloading the model, navigate to the directory where you saved it. Make sure to grant execution permissions to the `download.sh` file by running the following commands:

   ```shell
   chmod +x download.sh
   ```

   Then, execute the script:

   ```shell
   ./download.sh
   ```

   During this process, you will be prompted to enter a URL. Please use the URL that you received via email after registering on the provided link.

3. **Download the Model:**
   After entering the correct URL, the script will proceed to download the model. You can choose the specific model you want to download; for example, you might select the `7B-chat` model.

4. **Run the Program:**
   Once the model is downloaded, you can run the program using the following command:

   ```shell
   torchrun --nproc_per_node 1 example_chat_completion.py \
       --ckpt_dir llama-2-7b-chat/ \
       --tokenizer_path tokenizer.model \
       --max_seq_len 512 --max_batch_size 6
   ```

   Please ensure that you replace `llama-2-7b-chat/` with the correct path to your checkpoint directory and `tokenizer.model` with the actual path to your tokenizer model if they are located elsewhere. Adjust the `max_seq_len` and `max_batch_size` parameters as needed.

   > Note: If you are using a MacBook with an M2 chip, please be aware that it does not support NCCL built, which might cause issues.

**Comment by livius2** [comment]
@zeelsheladiya so why your point 7 was `python sample.py -m path/to/model/file`?

**Comment by zeelsheladiya** [comment]
@livius2, I was for a custom Python script. I was assuming that you are using a custom Python script for llama.

**Comment by albertodepaola** [comment]
This one is solved with the answer from @zeelsheladiya. Please open a new one or reopen if needed

**Comment by WieMaKa** [comment]
> Hi @livius2,
> 
> The process of running the script step by step that I followed:
> 
> 1. **Register to Download the Model:**
>    First, please register to download the model from this [link](https://ai.meta.com/resources/models-and-libraries/llama-downloads/).
> 2. **Run the download.sh File:**
>    After downloading the model, navigate to the directory where you saved it. Make sure to grant execution permissions to the `download.sh` file by running the following commands:
>    ```shell
>    chmod +x download.sh
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Then, execute the script:
>    ```shell
>    ./download.sh
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    During this process, you will be prompted to enter a URL. Please use the URL that you received via email after registering on the provided link.
> 3. **Download the Model:**
>    After entering the correct URL, the script will proceed to download the model. You can choose the specific model you want to download; for example, you might select the `7B-chat` model.
> 4. **Run the Program:**
>    Once the model is downloaded, you can run the program using the following command:
>    ```shell
>    torchrun --nproc_per_node 1 example_chat_completion.py \
>        --ckpt_dir llama-2-7b-chat/ \
>        --tokenizer_path tokenizer.model \
>        --max_seq_len 512 --max_batch_size 6
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Please ensure that you replace `llama-2-7b-chat/` with the correct path to your checkpoint directory and `tokenizer.model` with the actual path to your tokenizer model if they are located elsewhere. Adjust the `max_seq_len` and `max_batch_size` parameters as needed.
>    > Note: If you are using a MacBook with an M2 chip, please be aware that it does not support NCCL built, which might cause issues.

@zeelsheladiya are you running the model locally on your device? Cause for me the instructions doesn't work: 

(textgen) maric@MacBook-Pro-7 llama-main % torchrun --nproc_per_node 8 example_chat_completion.py \
    --ckpt_dir ~/llama-main/llama-2-70b-chat \
    --tokenizer_path ~/llama-main/tokenizer.model \
    --max_seq_len 512 --max_batch_size 6
[2023-10-28 14:44:25,029] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
[2023-10-28 14:44:25,065] torch.distributed.run: [WARNING] 
[2023-10-28 14:44:25,065] torch.distributed.run: [WARNING] *****************************************
[2023-10-28 14:44:25,065] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
[2023-10-28 14:44:25,065] torch.distributed.run: [WARNING] *****************************************

@livius2 does it work for you ?

**Comment by Naojen** [comment]
> > Hi @livius2,
> > The process of running the script step by step that I followed:
> > 
> > 1. **Register to Download the Model:**
> >    First, please register to download the model from this [link](https://ai.meta.com/resources/models-and-libraries/llama-downloads/).
> > 2. **Run the download.sh File:**
> >    After downloading the model, navigate to the directory where you saved it. Make sure to grant execution permissions to the `download.sh` file by running the following commands:
> >    ```shell
> >    chmod +x download.sh
> >    ```
> >    
> >    
> >        
> >          
> >        
> >    
> >          
> >        
> >    
> >        
> >      
> >    Then, execute the script:
> >    ```shell
> >    ./download.sh
> >    ```
> >    
> >    
> >        
> >          
> >        
> >    
> >          
> >        
> >    
> >        
> >      
> >    During this process, you will be prompted to enter a URL. Please use the URL that you received via email after registering on the provided link.
> > 3. **Download the Model:**
> >    After entering the correct URL, the script will proceed to download the model. You can choose the specific model you want to download; for example, you might select the `7B-chat` model.
> > 4. **Run the Program:**
> >    Once the model is downloaded, you can run the program using the following command:
> >    ```shell
> >    torchrun --nproc_per_node 1 example_chat_completion.py \
> >        --ckpt_dir llama-2-7b-chat/ \
> >        --tokenizer_path tokenizer.model \
> >        --max_seq_len 512 --max_batch_size 6
> >    ```
> >    
> >    
> >        
> >          
> >        
> >    
> >          
> >        
> >    
> >        
> >      
> >    Please ensure that you replace `llama-2-7b-chat/` with the correct path to your checkpoint directory and `tokenizer.model` with the actual path to your tokenizer model if they are located elsewhere. Adjust the `max_seq_len` and `max_batch_size` parameters as needed.
> >    > Note: If you are using a MacBook with an M2 chip, please be aware that it does not support NCCL built, which might cause issues.
> 
> @zeelsheladiya are you running the model locally on your device? Cause for me the instructions doesn't work:
> 
> (textgen) maric@MacBook-Pro-7 llama-main % torchrun --nproc_per_node 8 example_chat_completion.py --ckpt_dir ~/llama-main/llama-2-70b-chat --tokenizer_path ~/llama-main/tokenizer.model --max_seq_len 512 --max_batch_size 6 [2023-10-28 14:44:25,029] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs. [2023-10-28 14:44:25,065] torch.distributed.run: [WARNING] [2023-10-28 14:44:25,065] torch.distributed.run: [WARNING] ***************************************** [2023-10-28 14:44:25,065] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. [2023-10-28 14:44:25,065] torch.distributed.run: [WARNING] *****************************************
> 
> @livius2 does it work for you ?

With this process, can we perform chat with llama like chatGPT?  I have done it, and yes, it does work perfectly, but it is not in interactive mode. It is like asking one question, and then llama-2 provides the answer. I wanna perform interactive. How do I do it?

**Comment by chris-avens** [comment]
> 5. Build the Llama code by running "make" in the repository directory.

how to exactly run make in the repository directory? I tried typing "make" (without quotes) and got an error

> make : The term 'make' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again. At line:1 char:1

**Comment by chris-avens** [comment]
> > Hi @livius2,
> > The process of running the script step by step that I followed:
> > 
> > 1. **Register to Download the Model:**
> >    First, please register to download the model from this [link](https://ai.meta.com/resources/models-and-libraries/llama-downloads/).
> > 2. **Run the download.sh File:**
> >    After downloading the model, navigate to the directory where you saved it. Make sure to grant execution permissions to the `download.sh` file by running the following commands:
> >    ```shell
> >    chmod +x download.sh
> >    ```
> >    
> >    
> >        
> >          
> >        
> >    
> >          
> >        
> >    
> >        
> >      
> >    Then, execute the script:
> >    ```shell
> >    ./download.sh
> >    ```
> >    
> >    
> >        
> >          
> >        
> >    
> >          
> >        
> >    
> >        
> >      
> >    During this process, you will be prompted to enter a URL. Please use the URL that you received via email after registering on the provided link.
> > 3. **Download the Model:**
> >    After entering the correct URL, the script will proceed to download the model. You can choose the specific model you want to download; for example, you might select the `7B-chat` model.
> > 4. **Run the Program:**
> >    Once the model is downloaded, you can run the program using the following command:
> >    ```shell
> >    torchrun --nproc_per_node 1 example_chat_completion.py \
> >        --ckpt_dir llama-2-7b-chat/ \
> >        --tokenizer_path tokenizer.model \
> >        --max_seq_len 512 --max_batch_size 6
> >    ```
> >    
> >    
> >        
> >          
> >        
> >    
> >          
> >        
> >    
> >        
> >      
> >    Please ensure that you replace `llama-2-7b-chat/` with the correct path to your checkpoint directory and `tokenizer.model` with the actual path to your tokenizer model if they are located elsewhere. Adjust the `max_seq_len` and `max_batch_size` parameters as needed.
> >    > Note: If you are using a MacBook with an M2 chip, please be aware that it does not support NCCL built, which might cause issues.
> 
> @zeelsheladiya are you running the model locally on your device? Cause for me the instructions doesn't work:
> 
> (textgen) maric@MacBook-Pro-7 llama-main % torchrun --nproc_per_node 8 example_chat_completion.py --ckpt_dir ~/llama-main/llama-2-70b-chat --tokenizer_path ~/llama-main/tokenizer.model --max_seq_len 512 --max_batch_size 6 [2023-10-28 14:44:25,029] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs. [2023-10-28 14:44:25,065] torch.distributed.run: [WARNING] [2023-10-28 14:44:25,065] torch.distributed.run: [WARNING] ***************************************** [2023-10-28 14:44:25,065] torch.distributed.run: [WARNING] Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. [2023-10-28 14:44:25,065] torch.distributed.run: [WARNING] *****************************************
> 
> @livius2 does it work for you ?

i copy and pasted
torchrun --nproc_per_node 1 example_chat_completion.py \
    --ckpt_dir llama-2-7b-chat/ \
    --tokenizer_path tokenizer.model \
    --max_seq_len 512 --max_batch_size 6
 directly in conda. but it does not work. i tried removing the backslash and made it one line, but neither does work. how exactly should i run this?
