### ISSUE TITLE
model.generate returns input in the output?

### ISSUE THREAD

**Issue by wj210** [facebookresearch/llama#767]
Hi, i like to ask if there is a way to prevent outputting the input in the output when using generate?

`model.generate(inputs = inputs, max_new_tokens=max_gen_len, temperature=gen_t, top_p=top_p,do_sample = True)`

I am trying to do research for a paper and want to extract the output solely for evaluation.

Also, another question is that I am using the chat version, for the prompt, do I have to follow strictly as documented in https://huggingface.co/blog/llama2#how-to-prompt-llama-2?

I am using few-shot cot.

Thanks!!

**Comment by rguan1** [comment]
I don't know of a way of guaranteeing that the input is not included in the output. However, you could increase the temperature and re-query the model for a new output and check if the input is included in the output as a quick fix potentially.
