### ISSUE TITLE
OOM error on V100 GPU with 7B model

### ISSUE THREAD

**Issue by PrieureDeSion** [facebookresearch/llama#77]
Hello all,

This might be similar to #55 , I'm running into OOM errors on a single (empty) V100 GPU with 16.9G VRAM, trying to load the 7B model.

```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 256.00 MiB (GPU 0; 15.78 GiB total capacity; 7.46 GiB already allocated; 65.75 MiB free; 7.46 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
```

Tried reducing `max_batch_size` as suggested by @mperacchi, but to no avail. I'm not sure why torch is reserving 7+GB. Any thoughts?

Also tried running multi GPU (I have 8x), but that doesn't seem to use the other GPUs either.

**Comment by Urammar** [comment]
import torch
torch.cuda.set_device(0)
torch.cuda.empty_cache()

might have memory allocated from elsewhere that hasnt been cleaned up, seems you only have 65.75mb free, otherwise force it to allocate more

**Comment by wupgop** [comment]
Do you also have it in half precision?

`    model = Transformer(model_args)`
to
`    model = Transformer(model_args).cuda().half()`

**Comment by timlacroix** [comment]
You might want to check with something like nvidia-smi that you don't have any other processes using the same device :)
Once the model is loaded, as mentioned in #55 you'll have to adapt max_batch_size or max_seq_len.
We've added a FAQ: https://github.com/facebookresearch/llama/blob/main/FAQ.md
