### ISSUE TITLE
book, ¿training, fine-tuning, large model?.

### ISSUE THREAD

**Issue by SilvaRaulEnrique** [facebookresearch/llama#770]
what is best, and what is the difference? training, fine-tuning or use large model.
I want llama read a book and make answered to my questions.
¿what order to use?

**Comment by rguan1** [comment]
Hey @SilvaRaulEnrique, so, if you want to read a book and answer your questions, you can probably try to use Llama with Langchain to do document retrieval (see link: https://blog.langchain.dev/retrieval/). I would probably try that option first since it is the easiest to execute on.

**Comment by rguan1** [comment]
Closing out issue. Feel free to re-open if you have further questions.
