### ISSUE TITLE
Summitted the HF request before granted the access from Meta.

### ISSUE THREAD

**Issue by Reason-Wang** [facebookresearch/llama#774]
Sorry for the inconvenience. But I missubmitted the HF request form before getting access from Meta website. Now I have got the email from Meta provoding access to Llama2. But the HF request just stay unapproved. And there is no button to resubmit the HF request.

**Comment by jspisak** [comment]
@osanseviero - do you know how to resubmit the HF request?

**Comment by MohitIntel** [comment]
@osanseviero , is there any way to expedite the HF requests? The github ones were approved pretty quick.

**Comment by guo0521** [comment]
I met the same problem. Now I have got the email from Meta provoding access to Llama2. But the HF request just stay unapproved. And there is no button to resubmit the HF request. Is there any solution?

**Comment by Reason-Wang** [comment]
What osanseviero said is correct. The order does not impact. You can refer to this #784
