### ISSUE TITLE
how to understand Data composition in reward modeling process.

### ISSUE THREAD

**Issue by weiiWill** [facebookresearch/llama#776]
<img width="985" alt="image" src="https://github.com/facebookresearch/llama/assets/46260207/6bbcbb0d-b416-4497-afc2-986e0321ef29">

I do not unserstand the meaning of the two lines highlighted by yellow color.

**Comment by raghu-007** [comment]
Train the reward model & continuously improve the reward model to achieve the result.

**Comment by melanierk** [comment]
Basically we are saying that open-source preference data are based on *someone else's* model, so they are not necessarily ideal for learning how to improve our own model outputs. However, they don't seem to hurt much, and we think they might help our model generalize better.

**Comment by lzy37ld** [comment]
How could I get access to the safe reward model?
