### ISSUE TITLE
Remembering previous contexts/conversations in llama models

### ISSUE THREAD

**Issue by manoj21192** [facebookresearch/llama#782]
Can someone tell me how to make the model remember the past conversations/output. Suppose I provide a prompt" Add 2 and 3". Output of the bot will be 5. Then If I ask the bot to add 7 to the last output, it should be able to recollect the last output which was 5 and add it to 7 to produce 12. Any idea how to do this ?

**Comment by DragonAngel1st** [comment]
I believe people use the longchain framework for this. That is what I'm going trying soon.

**Comment by manoj21192** [comment]
langchain to be used
