### ISSUE TITLE
Windows?

### ISSUE THREAD

**Issue by ArsalT** [facebookresearch/llama#783]
I have setup a server for my work and after setting up everything. I am getting errors :

`NOTE: Redirects are currently not supported in Windows or MacOs.
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [SCG]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [SCG]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [SCG]:29500 (system error: 10049 - The requested address is not valid in its context.).
[W ..\torch\csrc\distributed\c10d\socket.cpp:601] [c10d] The client socket has failed to connect to [SCG]:29500 (system error: 10049 - The requested address is not valid in its context.).
============================================================
example_chat_completion.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-09-12_19:50:24
  host      : SCG
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 13936)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================`

It seems that we cannot run this on windows and macos? Your smallest suggestion can even help me. Don't matter if it works or not, but please I am in urgent need of it. 

Thanks in advance.
Arsal.

**Comment by Ruben-Puentes** [comment]
Hello, I have the same issue. I am in an Anaconda environment running on a laptop with Windows 11. Could someone please help us? I've been stuck for 3 days...

**Comment by ddmakadia1699** [comment]
same for me :|

**Comment by alexdconf** [comment]
Is it possible to use WSL2 to do this, under Windows?

**Comment by nobilisvenator** [comment]
I am trying to get this working as well, but I'm stuck at the download.sh part.  
I have git-bash installed and wget and md5sum in the path variable so they are available in the git-bash environment.

Connecting to download.llamameta.net|ipaddresshere|:443... connected.
OpenSSL: error:140773E8:SSL routines:SSL23_GET_SERVER_HELLO:reason(1000)
Unable to establish SSL connection.

Perhaps this setup won't work and I need a full linux environment.
Once I get past this I can probably help anyone further than me.

**Comment by ArsalT** [comment]
Yes you need a complete linux setup. I got one and it works on it.

**Comment by jspisak** [comment]
I'm sorry, at this point Windows isn't a supported OS for this repo. We are answering questions and addressing issues on a best effort basis. We are adding CI though soon and will add Windows to the roadmap. Sorry!
