### ISSUE TITLE
huggingface grant issue

### ISSUE THREAD

**Issue by haenara-shin** [facebookresearch/llama#784]
Hi all,

I have faced the 'Huggingface' grant issue that some of guys have already encountered before.

First, I already got access for LlaMa2 models from meta. (It was sent immediately after I requested)
Second, I also signed up at HF and submitted the access requests to HF a 10 days ago. I am still waiting.
![image](https://github.com/facebookresearch/llama/assets/58493928/53927b50-9c1d-41b8-9f55-23c23eae284f)

I did the same email account to request this access for both meta and HF. Also I tried another email account to do this same process, but it also keeps 'pending' at HF (got access from meta)

Is there anyone who knows a solution for this issue?

Thanks,

**Comment by Reason-Wang** [comment]
Faced same issue here. Don't know how to solve it.

**Comment by MohitIntel** [comment]
Facing same Issue.

**Comment by haenara-shin** [comment]
It's very funny. 

I've got finally been granted from HF. 
Granted emails arrived after I wrote this post (apprx. 12 hours later) for BOTH accounts that I requested. 
The first one was requested about 10 days ago, and the second one was requested yesterday.

So, I think anyone who experiences this issue should write a post here 🥲

**Comment by jspisak** [comment]
Hmm sounds like there might have been some sync issue between the systems. You might have hit a corner case - regardless the folks on the Meta side are looking into it. @MohitIntel - are you still facing the same issue?
