### ISSUE TITLE
How to download the Llama1 models

### ISSUE THREAD

**Issue by kjyeon1676** [facebookresearch/llama#785]
Hi, I tried to download the Llama1 Model 30B. But, only can access the Llama2 model download link. (I already requested the access permi at https://ai.meta.com/resources/models-and-libraries/llama-downloads/). Is there any other download link or method for Llama1 Model download? (officially version)

**Comment by jspisak** [comment]
I can check on this but IIRC we are just supporting LLama 2 models going forward. Out of curiosity, what does llama 1 do that you can't with llama 2?

**Comment by kjyeon1676** [comment]
@jspisak thank you for comment. I just try to apply the optimization for LLama1 model 30B using Quantization or Kernel fusion and so on. Currently, I can't not access the LLama2 model-30B. Therefore, I want to access the LLama1-30B model. So, I'm officially blocked from getting a LLama1 model? Can't i request through the google form link in the LLama v_1 branch?

**Comment by jspisak** [comment]
thanks for the background - yeah, we don't have a current plan to release the Llama 2 30B model. I am checking though on how to get you access to the Llama 1 model - you might end up needing to go through Hugging Face but I'll advise..

**Comment by jspisak** [comment]
Looks like we still have the request form here: https://docs.google.com/forms/d/e/1FAIpQLSfqNECQnMkycAp2jP4Z9TFX0cGR4uf7b_fBxjY_OjhJILlKGA/viewform

Please use this to get access. thanks!

**Comment by ozgurcelik** [comment]
I used this request form but didn't get an answer despite 2 weeks have passed. Did anyone have managed to get a return lately?

**Comment by prajeet26** [comment]
> I used this request form but didn't get an answer despite 2 weeks have passed. Did anyone have managed to get a return lately?

no not really . i too havent gotten a reply how did you manage to get the weights of Llama 1 finally?
