### ISSUE TITLE
md5sum: tokenizer_checklist.chk: no properly formatted MD5 checksum lines found

### ISSUE THREAD

**Issue by FaizanMunsaf** [facebookresearch/llama#790]
Enter the list of models to download without spaces (7B,13B,70B,7B-chat,13B-chat,70B-chat), or press Enter for all: 
Downloading LICENSE and Acceptable Usage Policy
--2023-09-14 12:11:05--  http://faizanmunsaf@gmail.com/
Resolving gmail.com (gmail.com)... 142.250.181.133, 2a00:1450:4019:809::2005
Connecting to gmail.com (gmail.com)|142.250.181.133|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://mail.google.com/mail/u/0/ [following]
--2023-09-14 12:11:05--  https://mail.google.com/mail/u/0/
Resolving mail.google.com (mail.google.com)... 172.217.21.37, 2a00:1450:4019:806::2005
Connecting to mail.google.com (mail.google.com)|172.217.21.37|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://accounts.google.com/ServiceLogin?service=mail&passive=1209600&osid=1&continue=https://mail.google.com/mail/u/0/&followup=https://mail.google.com/mail/u/0/&emr=1 [following]
--2023-09-14 12:11:06--  https://accounts.google.com/ServiceLogin?service=mail&passive=1209600&osid=1&continue=https://mail.google.com/mail/u/0/&followup=https://mail.google.com/mail/u/0/&emr=1
Resolving accounts.google.com (accounts.google.com)... 172.217.21.45, 2a00:1450:4019:805::200d
Connecting to accounts.google.com (accounts.google.com)|172.217.21.45|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://accounts.google.com/InteractiveLogin?continue=https://mail.google.com/mail/u/0/&emr=1&followup=https://mail.google.com/mail/u/0/&osid=1&passive=1209600&service=mail&ifkv=AYZoVhd5sij4uD7e9g83utpu7-9_B-HVyBEOwXrp4nlMwRNeLA88Uze4XPzCoHWfc5-KvJXPtr6l [following]
--2023-09-14 12:11:07--  https://accounts.google.com/InteractiveLogin?continue=https://mail.google.com/mail/u/0/&emr=1&followup=https://mail.google.com/mail/u/0/&osid=1&passive=1209600&service=mail&ifkv=AYZoVhd5sij4uD7e9g83utpu7-9_B-HVyBEOwXrp4nlMwRNeLA88Uze4XPzCoHWfc5-KvJXPtr6l
Reusing existing connection to accounts.google.com:443.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&emr=1&followup=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&ifkv=AYZoVhfwDxlxVSAft7VN88Odawq4COFSZ8EbXEnNxCMXQ5MEArdP9lW0CzfVGkZc--RO6fUp1Xwn5Q&osid=1&passive=1209600&service=mail&flowName=WebLiteSignIn&flowEntry=ServiceLogin&dsh=S537562566%3A1694675467380999 [following]
--2023-09-14 12:11:07--  https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&emr=1&followup=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&ifkv=AYZoVhfwDxlxVSAft7VN88Odawq4COFSZ8EbXEnNxCMXQ5MEArdP9lW0CzfVGkZc--RO6fUp1Xwn5Q&osid=1&passive=1209600&service=mail&flowName=WebLiteSignIn&flowEntry=ServiceLogin&dsh=S537562566%3A1694675467380999
Reusing existing connection to accounts.google.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘./LICENSE’

./LICENSE                          [  <=>                                             ] 572.56K  1.94MB/s    in 0.3s    

2023-09-14 12:11:08 (1.94 MB/s) - ‘./LICENSE’ saved [586303]

--2023-09-14 12:11:08--  http://faizanmunsaf@gmail.com/
Resolving gmail.com (gmail.com)... 142.250.181.133, 2a00:1450:4019:809::2005
Connecting to gmail.com (gmail.com)|142.250.181.133|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://mail.google.com/mail/u/0/ [following]
--2023-09-14 12:11:08--  https://mail.google.com/mail/u/0/
Resolving mail.google.com (mail.google.com)... 172.217.21.37, 2a00:1450:4019:806::2005
Connecting to mail.google.com (mail.google.com)|172.217.21.37|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://accounts.google.com/ServiceLogin?service=mail&passive=1209600&osid=1&continue=https://mail.google.com/mail/u/0/&followup=https://mail.google.com/mail/u/0/&emr=1 [following]
--2023-09-14 12:11:08--  https://accounts.google.com/ServiceLogin?service=mail&passive=1209600&osid=1&continue=https://mail.google.com/mail/u/0/&followup=https://mail.google.com/mail/u/0/&emr=1
Resolving accounts.google.com (accounts.google.com)... 172.217.21.45, 2a00:1450:4019:805::200d
Connecting to accounts.google.com (accounts.google.com)|172.217.21.45|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://accounts.google.com/InteractiveLogin?continue=https://mail.google.com/mail/u/0/&emr=1&followup=https://mail.google.com/mail/u/0/&osid=1&passive=1209600&service=mail&ifkv=AYZoVhcY9vSuDfmDOufgK7fAVZWUgp842eLh9NzcWiYCIxFYEOP67dTLVjDYl8MXrA_0227ZmcqmeA [following]
--2023-09-14 12:11:09--  https://accounts.google.com/InteractiveLogin?continue=https://mail.google.com/mail/u/0/&emr=1&followup=https://mail.google.com/mail/u/0/&osid=1&passive=1209600&service=mail&ifkv=AYZoVhcY9vSuDfmDOufgK7fAVZWUgp842eLh9NzcWiYCIxFYEOP67dTLVjDYl8MXrA_0227ZmcqmeA
Reusing existing connection to accounts.google.com:443.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&emr=1&followup=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&ifkv=AYZoVhdIQUWPfEN0czMN0zdF__5Wjqf7YAqzm2biR4MgSLzdCEt4QwkBb1btQGDOzHmGSrZ8efpCMA&osid=1&passive=1209600&service=mail&flowName=WebLiteSignIn&flowEntry=ServiceLogin&dsh=S1913315439%3A1694675469611770 [following]
--2023-09-14 12:11:09--  https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&emr=1&followup=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&ifkv=AYZoVhdIQUWPfEN0czMN0zdF__5Wjqf7YAqzm2biR4MgSLzdCEt4QwkBb1btQGDOzHmGSrZ8efpCMA&osid=1&passive=1209600&service=mail&flowName=WebLiteSignIn&flowEntry=ServiceLogin&dsh=S1913315439%3A1694675469611770
Reusing existing connection to accounts.google.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘./USE_POLICY.md’

./USE_POLICY.md                    [   <=>                                            ] 572.71K  1.27MB/s    in 0.4s    

2023-09-14 12:11:10 (1.27 MB/s) - ‘./USE_POLICY.md’ saved [586454]

Downloading tokenizer
--2023-09-14 12:11:10--  http://faizanmunsaf@gmail.com/
Resolving gmail.com (gmail.com)... 142.250.181.133, 2a00:1450:4019:809::2005
Connecting to gmail.com (gmail.com)|142.250.181.133|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://mail.google.com/mail/u/0/ [following]
--2023-09-14 12:11:10--  https://mail.google.com/mail/u/0/
Resolving mail.google.com (mail.google.com)... 172.217.21.37, 2a00:1450:4019:806::2005
Connecting to mail.google.com (mail.google.com)|172.217.21.37|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://accounts.google.com/ServiceLogin?service=mail&passive=1209600&osid=1&continue=https://mail.google.com/mail/u/0/&followup=https://mail.google.com/mail/u/0/&emr=1 [following]
--2023-09-14 12:11:11--  https://accounts.google.com/ServiceLogin?service=mail&passive=1209600&osid=1&continue=https://mail.google.com/mail/u/0/&followup=https://mail.google.com/mail/u/0/&emr=1
Resolving accounts.google.com (accounts.google.com)... 172.217.21.45, 2a00:1450:4019:805::200d
Connecting to accounts.google.com (accounts.google.com)|172.217.21.45|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://accounts.google.com/InteractiveLogin?continue=https://mail.google.com/mail/u/0/&emr=1&followup=https://mail.google.com/mail/u/0/&osid=1&passive=1209600&service=mail&ifkv=AYZoVhe8EeqA1HZss-RRJYDwV5gBW-ObIfxxb4fvyUoIMoSTkj3UZIGNi9z4plhPsg_mrqOqjSTRwA [following]
--2023-09-14 12:11:11--  https://accounts.google.com/InteractiveLogin?continue=https://mail.google.com/mail/u/0/&emr=1&followup=https://mail.google.com/mail/u/0/&osid=1&passive=1209600&service=mail&ifkv=AYZoVhe8EeqA1HZss-RRJYDwV5gBW-ObIfxxb4fvyUoIMoSTkj3UZIGNi9z4plhPsg_mrqOqjSTRwA
Reusing existing connection to accounts.google.com:443.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&emr=1&followup=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&ifkv=AYZoVhet0bYxtujCB9Q3wZ2JvJApW-RRFihatyPkcKvy9CAev391I0xf9vTNgbuGUPV-DauFCdp-Jw&osid=1&passive=1209600&service=mail&flowName=WebLiteSignIn&flowEntry=ServiceLogin&dsh=S721634539%3A1694675471965145 [following]
--2023-09-14 12:11:12--  https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&emr=1&followup=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&ifkv=AYZoVhet0bYxtujCB9Q3wZ2JvJApW-RRFihatyPkcKvy9CAev391I0xf9vTNgbuGUPV-DauFCdp-Jw&osid=1&passive=1209600&service=mail&flowName=WebLiteSignIn&flowEntry=ServiceLogin&dsh=S721634539%3A1694675471965145
Reusing existing connection to accounts.google.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘./tokenizer.model’

./tokenizer.model                  [  <=>                                             ] 572.40K  2.03MB/s    in 0.3s    

2023-09-14 12:11:12 (2.03 MB/s) - ‘./tokenizer.model’ saved [587317]

--2023-09-14 12:11:12--  http://faizanmunsaf@gmail.com/
Resolving gmail.com (gmail.com)... 142.250.181.133, 2a00:1450:4019:809::2005
Connecting to gmail.com (gmail.com)|142.250.181.133|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://mail.google.com/mail/u/0/ [following]
--2023-09-14 12:11:12--  https://mail.google.com/mail/u/0/
Resolving mail.google.com (mail.google.com)... 172.217.21.37, 2a00:1450:4019:806::2005
Connecting to mail.google.com (mail.google.com)|172.217.21.37|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://accounts.google.com/ServiceLogin?service=mail&passive=1209600&osid=1&continue=https://mail.google.com/mail/u/0/&followup=https://mail.google.com/mail/u/0/&emr=1 [following]
--2023-09-14 12:11:13--  https://accounts.google.com/ServiceLogin?service=mail&passive=1209600&osid=1&continue=https://mail.google.com/mail/u/0/&followup=https://mail.google.com/mail/u/0/&emr=1
Resolving accounts.google.com (accounts.google.com)... 172.217.21.45, 2a00:1450:4019:805::200d
Connecting to accounts.google.com (accounts.google.com)|172.217.21.45|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://accounts.google.com/InteractiveLogin?continue=https://mail.google.com/mail/u/0/&emr=1&followup=https://mail.google.com/mail/u/0/&osid=1&passive=1209600&service=mail&ifkv=AYZoVhebNhpnCdDLpIX21O5HxdAOcVZia4xwR0yG9ZzD02RurlrvfxNPR4_Gi2tRAZ7HXKBA3hKQaA [following]
--2023-09-14 12:11:13--  https://accounts.google.com/InteractiveLogin?continue=https://mail.google.com/mail/u/0/&emr=1&followup=https://mail.google.com/mail/u/0/&osid=1&passive=1209600&service=mail&ifkv=AYZoVhebNhpnCdDLpIX21O5HxdAOcVZia4xwR0yG9ZzD02RurlrvfxNPR4_Gi2tRAZ7HXKBA3hKQaA
Reusing existing connection to accounts.google.com:443.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&emr=1&followup=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&ifkv=AYZoVhcni0oyUJJdqejv1f1r1LY6D3z6gtF3DTzpgDMwZHVjJSzt0k8xYmcPpPDzma-aePt-eaUF&osid=1&passive=1209600&service=mail&flowName=WebLiteSignIn&flowEntry=ServiceLogin&dsh=S822464505%3A1694675474114450 [following]
--2023-09-14 12:11:14--  https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&emr=1&followup=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&ifkv=AYZoVhcni0oyUJJdqejv1f1r1LY6D3z6gtF3DTzpgDMwZHVjJSzt0k8xYmcPpPDzma-aePt-eaUF&osid=1&passive=1209600&service=mail&flowName=WebLiteSignIn&flowEntry=ServiceLogin&dsh=S822464505%3A1694675474114450
Reusing existing connection to accounts.google.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘./tokenizer_checklist.chk’

./tokenizer_checklist.chk          [  <=>                                             ] 572.74K  1.97MB/s    in 0.3s    

2023-09-14 12:11:14 (1.97 MB/s) - ‘./tokenizer_checklist.chk’ saved [587306]

## I am totallly confused when I am downloading file from `./download.sh`, it's generate an error at the end wha'ts the solution should be work

Any kind help it's really worthfull for me

**Comment by haozhuang0000** [comment]
Hi there, did you solve the issue?

**Comment by FaizanMunsaf** [comment]
> Hi there, did you solve the issue?

Yes, I have solved this issue Because I haven't access to Downloading from Meta. Meta gives us access to download the model within a 24Hours, after that we need to apply for the get request model again. when you get the email there is a link which you will receive at gmail. just copy that and place it where they are asking about the URL of the email.

I made a mistake before that I was writing the email. that was my first mistake.
2nd  mistake I was pasting an unauthorized URL which has been expired.

Please check this thing it will be resolved. This thing works for me and I run that program easily.

but now I am using hugging face llama-2 models. [FaizanMunsaf HF GitHub LLama-2](https://github.com/FaizanMunsaf/LLMS-llama2/blob/master/index.py) That's more favourable for my project

**Comment by haozhuang0000** [comment]
Thanks Faizan for sharing, i solved this issue too
