### ISSUE TITLE
[Question] Is the Use of Llama2 Forbidden in Languages Other Than English?

### ISSUE THREAD

**Issue by SesameShibe** [facebookresearch/llama#795]
Hello,

I recently came across a claim from [Baichuan-inc](https://github.com/baichuan-inc) during their live stream event and in the press release for the Baichuan2 model. They stated that Meta prohibits the use of Llama2 in languages other than English.

However, after reviewing the [use policy](https://ai.meta.com/llama/use-policy/) and the [license agreement](https://ai.meta.com/llama/license/) provided by Meta, I couldn't find any specific restriction regarding the model's application language. Additionally, in the `Responsible-Use-Guide.pdf`, there are even mentions of considerations for markets in other languages.

Could you please clarify if the statement by [Baichuan-inc](https://github.com/baichuan-inc)  that "Meta prohibits the use of Llama2 in languages other than English," is accurate? 

Thank you!

**Comment by jspisak** [comment]
Thanks for the question! There are quite a few models floating around in the open that are fine tuned versions of Llama 2 for different languages. This is allowed and absolutely encouraged.

**Comment by SesameShibe** [comment]
Thanks for clearing that up! May I also confirm that, is commercial use in non-English languages allowed as long as we comply with the license and use policy?

**Comment by jspisak** [comment]
Yes, as long as the acceptable use policy and all of the license terms are followed.

**Comment by SesameShibe** [comment]
Thank you for the clarification!

It seems Baichuan-inc is still spreading misinformation about multilingual usage of Llama2. They continue to claim that Meta prohibits the use of Llama2 in languages other than English. It might be beneficial to clarify this in the documentation.

**Comment by jspisak** [comment]
Thanks for letting me know - I'll add an FAQ question/answer to the FAQ here and we can point people to it: https://github.com/facebookresearch/llama/blob/main/FAQ.md

**Comment by GuillaumeWRLD** [comment]
@SesameShibe @jspisak I believe  [Baichuan-inc](https://github.com/baichuan-inc) is referring to this:

You can find it here:
https://github.com/facebookresearch/llama/blob/main/MODEL_CARD.md#intended-use

We are concerned as well.

<img width="940" alt="image" src="https://github.com/facebookresearch/llama/assets/10147667/8438f3e7-8a00-457a-8949-6aa5b00cb072">

**Comment by jspisak** [comment]
thanks - let me take a look and discuss with others. I'll do my best to clear this up quickly..

**Comment by jspisak** [comment]
Ok i've updated the Model Card and FAQ to clarify things and i've copypasta'ed the language below:

https://github.com/facebookresearch/llama/blob/main/MODEL_CARD.md

[Intended Use](https://github.com/facebookresearch/llama/blob/main/MODEL_CARD.md#intended-use)
Intended Use Cases Llama 2 is intended for commercial and research use in English. Tuned models are intended for assistant-like chat, whereas pretrained models can be adapted for a variety of natural language generation tasks.

Out-of-scope Uses Use in any manner that violates applicable laws or regulations (including trade compliance laws). Use in any other way that is prohibited by the Acceptable Use Policy and Llama 2 Community License. Use in languages other than English**.

**Note: Developers may fine-tune Llama 2 models for languages beyond English provided they comply with the Llama 2 Community License and the Acceptable Use Policy.
