### ISSUE TITLE
Kaggle?

### ISSUE THREAD

**Issue by pauldog** [facebookresearch/llama#80]
If you can't get it to work in Google Colabs you could also try [Kaggle](https://www.kaggle.com/product-feedback/147587).

It has slightly different specs. I think a bit more System RAM. IDK. Worth a try.

I would advise against entering the competitions in Kaggle, however, as it seems mostly to be companies trying to get graduates to work for free. But up to you.

**Comment by iodine-pku** [comment]
@pauldog The free tier kaggle notebook seems to only has 13GB RAM which cannot load the 7B checkpoint file in it

**Comment by pauldog** [comment]
Yes, looks like you're right. Shame.
