### ISSUE TITLE
Making the download.sh script work for Mac Intel.

### ISSUE THREAD

**Issue by shyamalschandra** [facebookresearch/llama#801]
`Errors Occurred: Errors:253 Miss:0   Success:0   Total:253`

I am getting this error when running the download.sh script with the following config: MacOS 13.5.2 with Intel i9 processor.

**Comment by samuelselvan** [comment]
@shyamalschandra is that the only line of error you see? Would you be able to share some more details/logs/output?

**Comment by samuelselvan** [comment]
@shyamalschandra please feel free to comment with more details and re-open if needed.
