### ISSUE TITLE
meta-llama/Llama-2-70b-chat-hf Inference API shows incpmplete output

### ISSUE THREAD

**Issue by omarnj-lab** [facebookresearch/llama#803]
Hello community,

I need an urgent help with the inference API of the meta-llama/Llama-2-70b-chat-hf. I have subscrbied with pro in huggingface and when I tried to use the inference api, it shows incomplete responce and I am still wondering why !!

I am using the following ınference API pythoc script:

`import requests

API_URL = "https://api-inference.huggingface.co/models/meta-llama/Llama-2-70b-chat-hf"
headers = {"Authorization": "Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXx"}

def query(payload):
response = requests.post(API_URL, headers=headers, json=payload)
return response.json()

output = query({
"inputs": "Can you please let us know more details about your ",
})`

Hop you can answer ne ASAP

**Comment by manoj21192** [comment]
This is happening with me as well for even 7B model directly downlaoded from facebook site. Any help would be appreciated

**Comment by jspisak** [comment]
@osanseviero - this possibly looks like an HF API issue but also could be independent of HF end points

@manoj21192 - what is your setup for deploying the model?

**Comment by manoj21192** [comment]
> @osanseviero - this possibly looks like an HF API issue but also could be independent of HF end points
> 
> @manoj21192 - what is your setup for deploying the model?

Seems like I was passing some wrong arguments, seems to be sorted now
