### ISSUE TITLE
Hi I am not able to download the model, and i got this error, please help! Thanks

### ISSUE THREAD

**Issue by haozhuang0000** [facebookresearch/llama#807]
--2023-09-19 16:06:36--  https://ddec1-0-en-ctp.trendmicro.com/wis/clicktime/v1/query?url=https%3a%2f%2fdownload.llamameta.net%2f*%3fPolicy%3deyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoieThpdWs1cGVobnoxZWh3ZnJ6dnRoc3g4IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5NTE5NjE0MX19fV19%26Signature%3dRTTtcn9kjfLsR-ObnVrUO6YKGdhgforPieKOFN2OBSWrTDjKSy13ecB-dgBmS-r4qis2jWsvxR5Bkp7Tqd4PuiRovq7QCQHlOs11IJ6Nx9FmY5Nkz0S99%7EgmKX9gCDIsd%7E9gu2WEIhJMkhLAp4l0WBJ4sXdoI9f-3t4n%7EZ%7ERj7xF2Yqv0bTu3lH8HIJfHYLDy6aSCAHwwrazV0VBhhW1nfrCHuWommfi1OQEpBlPhh4OOzSmwstmM43OD6iFvD3tsmVr44gUldxfrxChQyBriUS%7EDHPInNz3vVm5bSyl84VM4b5z4pPxafpE5rE0LcaKt5OYlbcV3UhN%7Es6vO--8ag__%26Key-Pair-Id%3dK15QRJLYKIFSLZ%26Download-Request-ID%3d844180167294011&umid=4c32c3d4-da4d-48f0-bb19-c544d6641043&auth=8d3ccd473d52f326e51c0f75cb32c9541898e5d5-0133d6748bcc29d8ece20287888ee9ca6a4a20fc
Resolving ddec1-0-en-ctp.trendmicro.com (ddec1-0-en-ctp.trendmicro.com)... 54.69.34.243, 54.186.63.183, 54.244.106.60
Connecting to ddec1-0-en-ctp.trendmicro.com (ddec1-0-en-ctp.trendmicro.com)|54.69.34.243|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
--2023-09-19 16:06:37--  https://ddec1-0-en-ctp.trendmicro.com/wis/clicktime/v1/query?url=https%3a%2f%2fdownload.llamameta.net%2f%2a%3fPolicy%3deyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoieThpdWs1cGVobnoxZWh3ZnJ6dnRoc3g4IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5NTE5NjE0MX19fV19%26Signature%3dRTTtcn9kjfLsR%2dObnVrUO6YKGdhgforPieKOFN2OBSWrTDjKSy13ecB%2ddgBmS%2dr4qis2jWsvxR5Bkp7Tqd4PuiRovq7QCQHlOs11IJ6Nx9FmY5Nkz0S99%257EgmKX9gCDIsd%257E9gu2WEIhJMkhLAp4l0WBJ4sXdoI9f%2d3t4n%257EZ%257ERj7xF2Yqv0bTu3lH8HIJfHYLDy6aSCAHwwrazV0VBhhW1nfrCHuWommfi1OQEpBlPhh4OOzSmwstmM43OD6iFvD3tsmVr44gUldxfrxChQyBriUS%257EDHPInNz3vVm5bSyl84VM4b5z4pPxafpE5rE0LcaKt5OYlbcV3UhN%257Es6vO%2d%2d8ag%5f%5f%26Key%2dPair%2dId%3dK15QRJLYKIFSLZ%26Download%2dRequest%2dID%3d844180167294011&umid=4c32c3d4-da4d-48f0-bb19-c544d6641043&auth=8d3ccd473d52f326e51c0f75cb32c9541898e5d5-0133d6748bcc29d8ece20287888ee9ca6a4a20fc
Reusing existing connection to ddec1-0-en-ctp.trendmicro.com:443.
HTTP request sent, awaiting response... 200 OK

    The file is already fully retrieved; nothing to do.

--2023-09-19 16:06:37--  https://ddec1-0-en-ctp.trendmicro.com/wis/clicktime/v1/query?url=https%3a%2f%2fdownload.llamameta.net%2f*%3fPolicy%3deyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoieThpdWs1cGVobnoxZWh3ZnJ6dnRoc3g4IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5NTE5NjE0MX19fV19%26Signature%3dRTTtcn9kjfLsR-ObnVrUO6YKGdhgforPieKOFN2OBSWrTDjKSy13ecB-dgBmS-r4qis2jWsvxR5Bkp7Tqd4PuiRovq7QCQHlOs11IJ6Nx9FmY5Nkz0S99%7EgmKX9gCDIsd%7E9gu2WEIhJMkhLAp4l0WBJ4sXdoI9f-3t4n%7EZ%7ERj7xF2Yqv0bTu3lH8HIJfHYLDy6aSCAHwwrazV0VBhhW1nfrCHuWommfi1OQEpBlPhh4OOzSmwstmM43OD6iFvD3tsmVr44gUldxfrxChQyBriUS%7EDHPInNz3vVm5bSyl84VM4b5z4pPxafpE5rE0LcaKt5OYlbcV3UhN%7Es6vO--8ag__%26Key-Pair-Id%3dK15QRJLYKIFSLZ%26Download-Request-ID%3d844180167294011&umid=4c32c3d4-da4d-48f0-bb19-c544d6641043&auth=8d3ccd473d52f326e51c0f75cb32c9541898e5d5-0133d6748bcc29d8ece20287888ee9ca6a4a20fc
Resolving ddec1-0-en-ctp.trendmicro.com (ddec1-0-en-ctp.trendmicro.com)... 54.69.34.243, 54.186.63.183, 54.244.106.60
Connecting to ddec1-0-en-ctp.trendmicro.com (ddec1-0-en-ctp.trendmicro.com)|54.69.34.243|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
--2023-09-19 16:06:38--  https://ddec1-0-en-ctp.trendmicro.com/wis/clicktime/v1/query?url=https%3a%2f%2fdownload.llamameta.net%2f%2a%3fPolicy%3deyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoieThpdWs1cGVobnoxZWh3ZnJ6dnRoc3g4IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5NTE5NjE0MX19fV19%26Signature%3dRTTtcn9kjfLsR%2dObnVrUO6YKGdhgforPieKOFN2OBSWrTDjKSy13ecB%2ddgBmS%2dr4qis2jWsvxR5Bkp7Tqd4PuiRovq7QCQHlOs11IJ6Nx9FmY5Nkz0S99%257EgmKX9gCDIsd%257E9gu2WEIhJMkhLAp4l0WBJ4sXdoI9f%2d3t4n%257EZ%257ERj7xF2Yqv0bTu3lH8HIJfHYLDy6aSCAHwwrazV0VBhhW1nfrCHuWommfi1OQEpBlPhh4OOzSmwstmM43OD6iFvD3tsmVr44gUldxfrxChQyBriUS%257EDHPInNz3vVm5bSyl84VM4b5z4pPxafpE5rE0LcaKt5OYlbcV3UhN%257Es6vO%2d%2d8ag%5f%5f%26Key%2dPair%2dId%3dK15QRJLYKIFSLZ%26Download%2dRequest%2dID%3d844180167294011&umid=4c32c3d4-da4d-48f0-bb19-c544d6641043&auth=8d3ccd473d52f326e51c0f75cb32c9541898e5d5-0133d6748bcc29d8ece20287888ee9ca6a4a20fc
Reusing existing connection to ddec1-0-en-ctp.trendmicro.com:443.
HTTP request sent, awaiting response... 200 OK

    The file is already fully retrieved; nothing to do.

Downloading tokenizer
--2023-09-19 16:06:38--  https://ddec1-0-en-ctp.trendmicro.com/wis/clicktime/v1/query?url=https%3a%2f%2fdownload.llamameta.net%2f*%3fPolicy%3deyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoieThpdWs1cGVobnoxZWh3ZnJ6dnRoc3g4IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5NTE5NjE0MX19fV19%26Signature%3dRTTtcn9kjfLsR-ObnVrUO6YKGdhgforPieKOFN2OBSWrTDjKSy13ecB-dgBmS-r4qis2jWsvxR5Bkp7Tqd4PuiRovq7QCQHlOs11IJ6Nx9FmY5Nkz0S99%7EgmKX9gCDIsd%7E9gu2WEIhJMkhLAp4l0WBJ4sXdoI9f-3t4n%7EZ%7ERj7xF2Yqv0bTu3lH8HIJfHYLDy6aSCAHwwrazV0VBhhW1nfrCHuWommfi1OQEpBlPhh4OOzSmwstmM43OD6iFvD3tsmVr44gUldxfrxChQyBriUS%7EDHPInNz3vVm5bSyl84VM4b5z4pPxafpE5rE0LcaKt5OYlbcV3UhN%7Es6vO--8ag__%26Key-Pair-Id%3dK15QRJLYKIFSLZ%26Download-Request-ID%3d844180167294011&umid=4c32c3d4-da4d-48f0-bb19-c544d6641043&auth=8d3ccd473d52f326e51c0f75cb32c9541898e5d5-0133d6748bcc29d8ece20287888ee9ca6a4a20fc
Resolving ddec1-0-en-ctp.trendmicro.com (ddec1-0-en-ctp.trendmicro.com)... 54.69.34.243, 54.186.63.183, 54.244.106.60
Connecting to ddec1-0-en-ctp.trendmicro.com (ddec1-0-en-ctp.trendmicro.com)|54.69.34.243|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
--2023-09-19 16:06:39--  https://ddec1-0-en-ctp.trendmicro.com/wis/clicktime/v1/query?url=https%3a%2f%2fdownload.llamameta.net%2f%2a%3fPolicy%3deyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoieThpdWs1cGVobnoxZWh3ZnJ6dnRoc3g4IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5NTE5NjE0MX19fV19%26Signature%3dRTTtcn9kjfLsR%2dObnVrUO6YKGdhgforPieKOFN2OBSWrTDjKSy13ecB%2ddgBmS%2dr4qis2jWsvxR5Bkp7Tqd4PuiRovq7QCQHlOs11IJ6Nx9FmY5Nkz0S99%257EgmKX9gCDIsd%257E9gu2WEIhJMkhLAp4l0WBJ4sXdoI9f%2d3t4n%257EZ%257ERj7xF2Yqv0bTu3lH8HIJfHYLDy6aSCAHwwrazV0VBhhW1nfrCHuWommfi1OQEpBlPhh4OOzSmwstmM43OD6iFvD3tsmVr44gUldxfrxChQyBriUS%257EDHPInNz3vVm5bSyl84VM4b5z4pPxafpE5rE0LcaKt5OYlbcV3UhN%257Es6vO%2d%2d8ag%5f%5f%26Key%2dPair%2dId%3dK15QRJLYKIFSLZ%26Download%2dRequest%2dID%3d844180167294011&umid=4c32c3d4-da4d-48f0-bb19-c544d6641043&auth=8d3ccd473d52f326e51c0f75cb32c9541898e5d5-0133d6748bcc29d8ece20287888ee9ca6a4a20fc
Reusing existing connection to ddec1-0-en-ctp.trendmicro.com:443.
HTTP request sent, awaiting response... 200 OK

    The file is already fully retrieved; nothing to do.

--2023-09-19 16:06:40--  https://ddec1-0-en-ctp.trendmicro.com/wis/clicktime/v1/query?url=https%3a%2f%2fdownload.llamameta.net%2f*%3fPolicy%3deyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoieThpdWs1cGVobnoxZWh3ZnJ6dnRoc3g4IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5NTE5NjE0MX19fV19%26Signature%3dRTTtcn9kjfLsR-ObnVrUO6YKGdhgforPieKOFN2OBSWrTDjKSy13ecB-dgBmS-r4qis2jWsvxR5Bkp7Tqd4PuiRovq7QCQHlOs11IJ6Nx9FmY5Nkz0S99%7EgmKX9gCDIsd%7E9gu2WEIhJMkhLAp4l0WBJ4sXdoI9f-3t4n%7EZ%7ERj7xF2Yqv0bTu3lH8HIJfHYLDy6aSCAHwwrazV0VBhhW1nfrCHuWommfi1OQEpBlPhh4OOzSmwstmM43OD6iFvD3tsmVr44gUldxfrxChQyBriUS%7EDHPInNz3vVm5bSyl84VM4b5z4pPxafpE5rE0LcaKt5OYlbcV3UhN%7Es6vO--8ag__%26Key-Pair-Id%3dK15QRJLYKIFSLZ%26Download-Request-ID%3d844180167294011&umid=4c32c3d4-da4d-48f0-bb19-c544d6641043&auth=8d3ccd473d52f326e51c0f75cb32c9541898e5d5-0133d6748bcc29d8ece20287888ee9ca6a4a20fc
Resolving ddec1-0-en-ctp.trendmicro.com (ddec1-0-en-ctp.trendmicro.com)... 54.69.34.243, 54.186.63.183, 54.244.106.60
Connecting to ddec1-0-en-ctp.trendmicro.com (ddec1-0-en-ctp.trendmicro.com)|54.69.34.243|:443... connected.
HTTP request sent, awaiting response... 401 Unauthorized

Username/Password Authentication Failed.
--2023-09-19 16:06:41--  https://ddec1-0-en-ctp.trendmicro.com/wis/clicktime/v1/query?url=https%3a%2f%2fdownload.llamameta.net%2f%2a%3fPolicy%3deyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoieThpdWs1cGVobnoxZWh3ZnJ6dnRoc3g4IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQubGxhbWFtZXRhLm5ldFwvKiIsIkNvbmRpdGlvbiI6eyJEYXRlTGVzc1RoYW4iOnsiQVdTOkVwb2NoVGltZSI6MTY5NTE5NjE0MX19fV19%26Signature%3dRTTtcn9kjfLsR%2dObnVrUO6YKGdhgforPieKOFN2OBSWrTDjKSy13ecB%2ddgBmS%2dr4qis2jWsvxR5Bkp7Tqd4PuiRovq7QCQHlOs11IJ6Nx9FmY5Nkz0S99%257EgmKX9gCDIsd%257E9gu2WEIhJMkhLAp4l0WBJ4sXdoI9f%2d3t4n%257EZ%257ERj7xF2Yqv0bTu3lH8HIJfHYLDy6aSCAHwwrazV0VBhhW1nfrCHuWommfi1OQEpBlPhh4OOzSmwstmM43OD6iFvD3tsmVr44gUldxfrxChQyBriUS%257EDHPInNz3vVm5bSyl84VM4b5z4pPxafpE5rE0LcaKt5OYlbcV3UhN%257Es6vO%2d%2d8ag%5f%5f%26Key%2dPair%2dId%3dK15QRJLYKIFSLZ%26Download%2dRequest%2dID%3d844180167294011&umid=4c32c3d4-da4d-48f0-bb19-c544d6641043&auth=8d3ccd473d52f326e51c0f75cb32c9541898e5d5-0133d6748bcc29d8ece20287888ee9ca6a4a20fc
Reusing existing connection to ddec1-0-en-ctp.trendmicro.com:443.
HTTP request sent, awaiting response... 200 OK

    The file is already fully retrieved; nothing to do.

md5sum: tokenizer_checklist.chk: no properly formatted MD5 checksum lines found

**Comment by haozhuang0000** [comment]
> Same issue here. I have tries reclone, ask a new download link, and nothing works.

Me too, I did the same thing but still not working

**Comment by pabloantondp** [comment]
well, I hope we are doing the same stupid thing I am.

I was writing my email address when download.sh asked for "Enter the URL from email:".

**Comment by haozhuang0000** [comment]
> well, I hope you are not doing the same stupid thing I am.
> 
> I was writing my email address when download.sh asked for "Enter the URL from email:".

I copied and pasted the link from the email that Meta sent it to me tho..Still not working. Is it working for you now?

**Comment by pabloantondp** [comment]
yes, now it works. I just do:

```
> ./download.sh
Enter the URL from email: url_copied_from_email
Enter the list of models to download without spaces (7B,13B,70B,7B-chat,13B-chat,70B-chat), or press Enter for all: 7B
```

and it works.

**Comment by haozhuang0000** [comment]
Does anyone have any ideas why I am not able to download it? Thanks

**Comment by haozhuang0000** [comment]
OK..I think I know the reason for this, because my company automatically change the url that meta sent it to me...It is because some sort of firewall i guess. But i came up another issue..

Enter the list of models to download without spaces (7B,13B,70B,7B-chat,13B-chat,70B-chat), or press Enter for all: 13B-chat
Downloading LICENSE and Acceptable Usage Policy
--2023-09-20 13:57:24-- 
Resolving download.llamameta.net (download.llamameta.net)... 18.154.101.53, 18.154.101.33, 18.154.101.70, ...
Connecting to download.llamameta.net (download.llamameta.net)|18.154.101.53|:443... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

--2023-09-20 13:57:25--  
Resolving download.llamameta.net (download.llamameta.net)... 18.154.101.53, 18.154.101.33, 18.154.101.70, ...
Connecting to download.llamameta.net (download.llamameta.net)|18.154.101.53|:443... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

Downloading tokenizer
--2023-09-20 13:57:27--  
Resolving download.llamameta.net (download.llamameta.net)... 18.154.101.53, 18.154.101.33, 18.154.101.70, ...
Connecting to download.llamameta.net (download.llamameta.net)|18.154.101.53|:443... connected.
HTTP request sent, awaiting response... 206 Partial Content
Length: 499723 (488K), 492777 (481K) remaining [binary/octet-stream]
Saving to: './tokenizer.model'

     0K ,,,,,,.... .......... .......... .......... .......... 10%  219K 2s
    50K .......... .......... .......... .......... .......... 20%  482K 1s
   100K .......... .......... .......... .......... .......... 30%  301K 1s
   150K .......... .......... .......... .......... .......... 40%  504K 1s
   200K .......... .......... .......... .......... .......... 51%  754K 1s
   250K .......... .......... .......... .......... .......... 61%  912K 0s
   300K .......... .......... .......... .......... .......... 71% 1.11M 0s
   350K .......... .......... .......... .......... .......... 81% 1.11M 0s
   400K .......... .......... .......... .......... .......... 92% 1.28M 0s
   450K .......... .......... .......... ........             100% 1.46M=0.9s

2023-09-20 13:57:29 (553 KB/s) - './tokenizer.model' saved [499723/499723]

--2023-09-20 13:57:29--  
Resolving download.llamameta.net (download.llamameta.net)... 18.154.101.53, 18.154.101.33, 18.154.101.70, ...
Connecting to download.llamameta.net (download.llamameta.net)|18.154.101.53|:443... connected.
HTTP request sent, awaiting response... 416 Requested Range Not Satisfiable

    The file is already fully retrieved; nothing to do.

md5sum: tokenizer_checklist.chk: no properly formatted MD5 checksum lines found

**Comment by haozhuang0000** [comment]
issued solved.

**Comment by kapedalex** [comment]
[haozhuang0000](https://github.com/haozhuang0000) How did u solve  416 Requested Range Not Satisfiable?
