### ISSUE TITLE
No Response for Llama-2 access form for >2 weeks

### ISSUE THREAD

**Issue by ahmed-agiza** [facebookresearch/llama#812]
Hi,
I submitted the request to access Llama-2 through https://ai.meta.com/resources/models-and-libraries/llama-downloads/ ~2 weeks ago, but I got no response so far (or confirmation email that my request has been received, if there is any). Is this a normal waiting time, or there might be an issue with my email or something like the request not being delivered? How long does it usually take to get a response?
Thank you.

**Comment by jspisak** [comment]
@samuelselvan is there a way we can check on the status of this one?

**Comment by ahmed-agiza** [comment]
Any update on this? 
Still no access..my colleagues requested it after me and got it in a few minutes.. is there any way to know the reason it is not getting approved? Or someone to contact?

**Comment by jspisak** [comment]
@samuelselvan - can you look into this?

**Comment by eduheise** [comment]
I completed the form and gained immediate access through the following link:

https://ai.meta.com/resources/models-and-libraries/llama-downloads/

**Comment by ahmed-agiza** [comment]
> I completed the form and gained immediate access through the following link:
> 
> https://ai.meta.com/resources/models-and-libraries/llama-downloads/

Yeah, a lot of people I know got it almost instantly too.. I don't know why my case is different, I even tried my other e-mail, same issue..

**Comment by ahmed-agiza** [comment]
Can you please at least direct me to any platform to report the issue..??

**Comment by samuelselvan** [comment]
Apologies for the delay. Am getting a change to locate your requests easier, will get back asap.

**Comment by ahmed-agiza** [comment]
> Apologies for the delay. Am getting a change to locate your requests easier, will get back asap.

Thank you for taking the time.

**Comment by sian-chen** [comment]
@samuelselvan Same here.
I've sent the request several times with my personal email and edu email since LLaMA 2 released, but I haven't gotten any response. The access of the model is very important to my research. Could you please take a look for me? Thanks.

**Comment by joseortizm** [comment]
Hi! I submitted the request to access Llama-2 but I got no response. I'm working on a research about NLP, Can you help me?

**Comment by getao** [comment]
same here. I sent the request 2 months ago. Still no response.

**Comment by FatemehAhmadi94** [comment]
Same here. I've sent the request multiple times since last week. I am still waiting for a response.

**Comment by samuelselvan** [comment]
@all - could you please send me the "Request ID: <>" that gets displayed after you submit the request?

**Comment by ahmed-agiza** [comment]
> @ALL - could you please send me the "Request ID: <>" that gets displayed after you submit the request?

Request ID: **352895543779918**
Thanks again.

**Comment by getao** [comment]
> @ALL - could you please send me the "Request ID: <>" that gets displayed after you submit the request?

My request ID: **727173129256712**

Thank you

**Comment by sian-chen** [comment]
> @ALL - could you please send me the "Request ID: <>" that gets displayed after you submit the request?

My request ID: 292828150298423
Thanks a lot!

**Comment by FatemehAhmadi94** [comment]
> @ALL - could you please send me the "Request ID: <>" that gets displayed after you submit the request?

Request ID: 1565189250903874

Thank you.

**Comment by noy-sternlicht** [comment]
Request ID: 1056333462389134
Thanks!

**Comment by Jay19751103** [comment]
I don't get response more than 10 days with two different email. submit a new request ID.
Request ID: 1924253284700575
Thanks

**Comment by chiuhsia** [comment]
I don't get response more than 20 days with two different email. The request id is: 1370358783579387
Thank you!

**Comment by mohummedalee** [comment]
Hi, I've submitted a request multiple times as well. The most recent one has the request ID: 1396801091235705. Appreciate the help!

**Comment by ahmed-agiza** [comment]
I have submitted the request again today and got approved!

**Comment by lzslim** [comment]
> @ALL - could you please send me the "Request ID: <>" that gets displayed after you submit the request?

my request id:249769071529357, thanks for help.

**Comment by Bluzzxy** [comment]
> @ALL - could you please send me the "Request ID: <>" that gets displayed after you submit the request?

My request ID: 1567564930701462, thanks for help.
