### ISSUE TITLE
Bash Download.sh not working when trying to download the llama 2 model 

### ISSUE THREAD

**Issue by czarvsp** [facebookresearch/llama#818]
Hi, I have tried bash download.sh, several times. It keeps providing me with this error. 

download.sh: line 1: payload:allShortcutsEnabled:false: command not found

I am running on a 2019 MacBook Pro Intel i9.

Any help is greatly appreciated. 

Thanks in advance

**Comment by Sanchit-404** [comment]
Did you try with a new link?

**Comment by samuelselvan** [comment]
@czarvsp - can you please requesting a new download link and give the full log?

**Comment by nobilisvenator** [comment]
Hello, 
I receive the following after running download.sh
I also tried to enable tls 1.1 on my windows 11 machine

Connecting to download2.llamameta.net|18.165.98.78|:443... connected.
OpenSSL: error:140773E8:SSL routines:SSL23_GET_SERVER_HELLO:reason(1000)
Unable to establish SSL connection.

**Comment by samuelselvan** [comment]
@nobilisvenator can you please try what is suggested in https://github.com/facebookresearch/llama/issues/361#issuecomment-1643753122

**Comment by nobilisvenator** [comment]
> @nobilisvenator can you please try what is suggested in [#361 (comment)](https://github.com/facebookresearch/llama/issues/361#issuecomment-1643753122)

I had to change my wget to the binary hosted on eternallybored.org

**Comment by ujazishere** [comment]
> > @nobilisvenator can you please try what is suggested in [#361 (comment)](https://github.com/facebookresearch/llama/issues/361#issuecomment-1643753122)
> 
> I had to change my wget to the binary hosted on eternallybored.org

I am trying to run download.sh on Windows, but I am unable to run the download.sh on git bash using `bash download.sh` even after replacing all `wget` with `curl -O` and switching off the md5sum check. is it just not possible/too complicated to run the shell file on windows? Any alternatives? 

The furthest I got was at this error: `Warning: Got more output options than URLs
Skipping checksum verification on Windowsfor m in 70B
download.sh: line 34: syntax error near unexpected token `do'`
