### ISSUE TITLE
What are the pc configuration to run llama2 70B?

### ISSUE THREAD

**Issue by haozhuang0000** [facebookresearch/llama#819]
My current:
![image](https://github.com/facebookresearch/llama/assets/71269145/90681335-5de6-4f1f-b8f5-0f9abb88565d)
![image](https://github.com/facebookresearch/llama/assets/71269145/b5f74e45-7025-4163-be36-9e6662bfc255)

Still shows out of memory error for CPU.

Thanks

**Comment by Sanchit-404** [comment]
Can you share the error message when you try to run it?

**Comment by haozhuang0000** [comment]
![MicrosoftTeams-image (2)](https://github.com/facebookresearch/llama/assets/71269145/efb0df69-ec8f-4dfd-97d8-63ad2f3bdb89)
Error like this

**Comment by Sanchit-404** [comment]
Are you running on full precision? If yes, then you should run on half precision. 
If no, then can you share the code where you start distributing the model over 4 GPUs?

**Comment by haozhuang0000** [comment]
@Sanchit-404 

HI Sanchit, 

here is my code: (from hugging-face)

from transformers import AutoTokenizer, AutoModel
import transformers
import torch

model = "meta-llama/Llama-2-70b-chat-hf"

tokenizer = AutoTokenizer.from_pretrained(model)

pipeline = transformers.pipeline(
    "text-generation",
    model=model,
    torch_dtype=torch.float16,
    device_map="auto",
)

sequences = pipeline(
    'I liked "Breaking Bad" and "Band of Brothers". Do you have any recommendations of other shows I might like?\n',
    do_sample=True,
    top_k=10,
    num_return_sequences=1,
    eos_token_id=tokenizer.eos_token_id,
    max_length=200,
)
for seq in sequences:
    print(f"Result: {seq['generated_text']}")

**Comment by haozhuang0000** [comment]
Hi @Sanchit-404 ,

May I know if I did something wrong in the code? :) Thanks in advance!!

**Comment by Sanchit-404** [comment]
Hi @haozhuang0000 
According to your code you are still using a single GPU. Secondly, your CPU does not have enough memory to load a 70B model. You typically require 140 GB to run it in half precision.
You can pull it down by using quantization.
You can refer to the llama-recipes repo to address all the issues above. Let me know if the problems still persists.

**Comment by haozhuang0000** [comment]
Hi @Sanchit-404,

Thanks for your reply! If there is no enough CPU, then I will consider to use 13b, one additional question, how do I use 4 GPU?

**Comment by Sanchit-404** [comment]
13B models should work on your system as 26 GB ram is required. You can use quantization to further reduce the memory requirements. 
You can use hugging-face accelerate, or external frameworks like exllama for multi-gpu inference.

**Comment by haozhuang0000** [comment]
Hi @Sanchit-404,

Thanks for your suggestion!!
