### ISSUE TITLE
How much memory is required to load the 7B model?

### ISSUE THREAD

**Issue by AnitaSherry** [facebookresearch/llama#82]
**I use it for personal use, 12G video memory, and set parameters : max_seq_len=32, max_batch_size=1**
RuntimeError: CUDA out of memory. Tried to allocate 86.00 MiB (GPU 0; 10.92 GiB total capacity; 10.27 GiB already allocated; 37.06 MiB free; 10.27 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF

**Comment by pauldog** [comment]
16GB VRAM + 16GB RAM seems to be the absolute minimum so far anyone's got. #79

**Comment by tekspirit** [comment]
I have 64gb ram, 20 GPUs and 500GB free so it should be good to run.
