### ISSUE TITLE
HuggingFace request not yet approved

### ISSUE THREAD

**Issue by m-laprise** [facebookresearch/llama#820]
Same problem as #724 and #750 and #812

I filled in the META form and immediately received an email with the licence and confirmation of access. I also filled in HF request; this was over a week ago and is still pending. The META licence email is now my primary HF email though I have additional emails also associated to my HF account.

I understand from the other two issues this is handled and processed by Meta, but is there any way to trigger a review of the request? I don't see any way from HuggingFace to cancel the request and submit it again, for instance.

**Comment by m-laprise** [comment]
Approved soon after posting this.

**Comment by karan842** [comment]
Today I requested on META for Llama2 access. Will this approve in 24 hrs?
