### ISSUE TITLE
Cannot download anymore?

### ISSUE THREAD

**Issue by jianlins** [facebookresearch/llama#826]
Got the following message when run the download.sh

Connecting to download.llamameta.net (download.llamameta.net)|13.249.205.86|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-09-24 11:30:28 ERROR 403: Forbidden.

**Comment by realrk95** [comment]
You can request a new download link as mentioned in the readme.md

**Comment by samuelselvan** [comment]
@jianlins could you please to get a new URL and download and let us know if you still face issues?
