### ISSUE TITLE
AssertError: (6, 4)

### ISSUE THREAD

**Issue by FelexTriz** [facebookresearch/llama#827]
![image](https://github.com/facebookresearch/llama/assets/82858160/9320de97-54fd-4bb5-b82f-c08e96c64b87)
when i running `torchrun --nproc_per_node 1 example_chat_completion.py --ckpt_dir Llama-2-7b-chat/ --tokenizer_path  Llama-2-7b-chat/tokenizer.model --max_seq_len 128 --max_batch_size 6
`
i have set max_batch_size 6,but print it still 4.
ihave no idea about this .
i dont know bsz's meaning

**Comment by ejsd1989** [comment]
Hey @FelexTriz, thanks for submitting your question. So i just ran the same torchrun command on my side and am not running into the same issue: 

`torchrun --nproc_per_node 1 example_chat_completion.py --ckpt_dir llama-2-7b-chat/ --tokenizer_path  llama-2-7b-chat/tokenizer.model --max_seq_len 128 --max_batch_size 6`

I also added in a comparable print() statement to my generation.py file. The output i am seeing is:
<img width="391" alt="image" src="https://github.com/facebookresearch/llama/assets/9409428/5b5b2a91-8828-4486-96f9-b95906469ce5">

Were you able to run this again? Are you still seeing the same issue?

**Comment by FelexTriz** [comment]
> Hey @FelexTriz, thanks for submitting your question. So i just ran the same torchrun command on my side and am not running into the same issue:
> 
> `torchrun --nproc_per_node 1 example_chat_completion.py --ckpt_dir llama-2-7b-chat/ --tokenizer_path llama-2-7b-chat/tokenizer.model --max_seq_len 128 --max_batch_size 6`
> 
> I also added in a comparable print() statement to my generation.py file. The output i am seeing is: <img alt="image" width="391" src="https://user-images.githubusercontent.com/9409428/273054308-5b5b2a91-8828-4486-96f9-b95906469ce5.png">
> 
> Were you able to run this again? Are you still seeing the same issue?
sry,i ran this model my friend's 3090 pc.it works in the end,. i remember add '--max_seq_len' this to 256 or 512, it needs to be bigger than 128
 (i guess key problem  is windows, Windows has many package compatibility issues)

**Comment by ejsd1989** [comment]
Got it. Thanks for the response @FelexTriz. Glad to hear it worked out in the end. Going to close this for now.
