### ISSUE TITLE
Why the extra <s> is coming after tokenizer

### ISSUE THREAD

**Issue by pratikkumar018** [facebookresearch/llama#828]
Hi , 
I am trying to run DataCollatorForCompletionOnlyLM . But for that i need to get the start of response . I am trying to get the response key [/INST] but it looks like tokenizer is not deterministic. Attaching image. Encoding & decoding is changing the input string. 

![image](https://github.com/facebookresearch/llama/assets/80521981/7f37e0bc-f104-4916-b4e6-23f20b55bb4e)

**Comment by ruanslv** [comment]
This issue doesn't seem related to this codebase? This is a HuggingFace library.

<s> may refer to the BOS (beginning-of-sentence) token which might be added by default in the encode() method you are using, although not very familiar with this code
