### ISSUE TITLE
Some help with very slow performance

### ISSUE THREAD

**Issue by StepIg** [facebookresearch/llama#831]
Hi all.
I've done the installation in my PC.
My configuration is:
- 2 * Xeon E5-2678 v3 (24 cores / 48 threads) at 2,80Ghz
- 64 Gb Ram
- NVIDIA GeForce GTX 1080
- 4 SSD 

I use WSL2 on Windows 10 operating system

I use the 7B file and i start with this command:
torchrun --nproc_per_node 1 example_chat_completion.py     --ckpt_dir llama-2-7b-chat/     --tokenizer_path tokenizer.model     --max_seq_len 512 --max_batch_size 6

after seen the result when i try to launch the system is the system remains stucked and never shows the ">>>User" text, i have taken a file from a user here and changed the example_chat_completion.py to this:

```
from llama import Llama


def main(
    ckpt_dir: str,
    tokenizer_path: str,
    temperature: float = 0.6,
    top_p: float = 0.9,
    max_seq_len: int = 4096,
    max_batch_size: int = 8,
    max_gen_len: Optional[int] = None,
):
    generator = Llama.build(
        ckpt_dir=ckpt_dir,
        tokenizer_path=tokenizer_path,
        max_seq_len=max_seq_len,
        max_batch_size=max_batch_size,
    )
   
    while True:
        input1 = input(">>> User: ")
        if input1.lower() == "exit":
            print("AI Bot: Goodbye!")
            break
        temp_dialogs = []
        temp_dialogs.append({"role": "user", "content": input1})

        dialogs = [temp_dialogs]
        results = generator.chat_completion(
            dialogs,  # type: ignore
            max_gen_len=max_gen_len,
            temperature=temperature,
            top_p=top_p,
        )
        for dialog, result in zip(dialogs, results):
            # for msg in dialog:
            #     print(f"{msg['role'].capitalize()}: {msg['content']}\n")
            print(f"> {result['generation']['role'].capitalize()}: {result['generation']['content']}")
            temp_dialogs.append(result['generation'])
            print("\n==================================\n")

if __name__ == "__main__":
    fire.Fire(main)
```
it takes about 25 seconds to start, the GPU is at 100% and when i type something as >>>User: the system respond after 3 or 4 minutes or more...

After read that some users tries with CPU and also some similar GPU with aceptable results, im totally lost and stopped. What can i do to have better response? Where is my error?

I will appreciate some help.
Thanks in advance

**Comment by StepIg** [comment]
¿? its a hard question or too much newbie question?

**Comment by StepIg** [comment]
great help! hahahaha

**Comment by jspisak** [comment]
Nope - great question! You might find this example useful for more optimized inference. In general though, you are using an older GPU and so performance isn't expected to be great. Hope this helps..

https://github.com/facebookresearch/llama-recipes/tree/main/examples
