### ISSUE TITLE
download.sh error http://: Invalid host name

### ISSUE THREAD

**Issue by AmeMai** [facebookresearch/llama#840]
When I try to execute the download.sh file, first I could not get wget to work (Windows 11). I put the wget.exe file to my Git/bin path which made the `wget command not found` error go away. Now I have a new error: 

`Enter the list of models to download without spaces (7B,13B,70B,7B-chat,13B-chat,70B-chat), or press Enter for all: 7B-chat
Downloading LICENSE and Acceptable Usage Policy
http://: Invalid host name.
`
<p></p>
I already tried using a new key (URL) but that does also not seem to work.
<p></p>
Sadly I could not find out how to fix my issue so any help would be greatly appreciated.

**Comment by samuelselvan** [comment]
@AmeMai please feel free to re-open if you need any help.

**Comment by AcomputerDoge** [comment]
"I think you might not have pasted the URL into Git, but instead used Ctrl+V like I did."
