### ISSUE TITLE
hello, any solution on llama download, always encounter "tokenizer_checklist.chk: no properly formatted MD5 checksum lines found"

### ISSUE THREAD

**Issue by ali-yuze** [facebookresearch/llama#849]
I followed the instruction and didn't get a chance to paste download url.  Solutions in the closed issues seem not work for me.

$ ./download.sh
Enter the URL from email: gaoyuze.m@gmail.com

Enter the list of models to download without spaces (7B,13B,70B,7B-chat,13B-chat,70B-chat), or press Enter for all: 70B
Downloading LICENSE and Acceptable Usage Policy
--2023-10-11 11:22:46--  http://gaoyuze.m@gmail.com/
Resolving gmail.com (gmail.com)... 64.233.170.19, 64.233.170.18, 64.233.170.83, ...
Connecting to gmail.com (gmail.com)|64.233.170.19|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://mail.google.com/mail/u/0/ [following]
--2023-10-11 11:22:46--  https://mail.google.com/mail/u/0/
Resolving mail.google.com (mail.google.com)... 142.251.12.18, 142.251.12.83, 142.251.12.17, ...
Connecting to mail.google.com (mail.google.com)|142.251.12.18|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://accounts.google.com/ServiceLogin?service=mail&passive=1209600&osid=1&continue=https://mail.google.com/mail/u/0/&followup=https://mail.google.com/mail/u/0/&emr=1 [following]
--2023-10-11 11:22:46--  https://accounts.google.com/ServiceLogin?service=mail&passive=1209600&osid=1&continue=https://mail.google.com/mail/u/0/&followup=https://mail.google.com/mail/u/0/&emr=1
Resolving accounts.google.com (accounts.google.com)... 172.217.194.84
Connecting to accounts.google.com (accounts.google.com)|172.217.194.84|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://accounts.google.com/InteractiveLogin?continue=https://mail.google.com/mail/u/0/&emr=1&followup=https://mail.google.com/mail/u/0/&osid=1&passive=1209600&service=mail&ifkv=AYZoVhdCUvaDdcaJuncAlU-ZgN9WhOjeIzndWXHH1MBDPuvS0OOONkiXvZLs8sJ8FLiyZSaEO3iP5A [following]
--2023-10-11 11:22:46--  https://accounts.google.com/InteractiveLogin?continue=https://mail.google.com/mail/u/0/&emr=1&followup=https://mail.google.com/mail/u/0/&osid=1&passive=1209600&service=mail&ifkv=AYZoVhdCUvaDdcaJuncAlU-ZgN9WhOjeIzndWXHH1MBDPuvS0OOONkiXvZLs8sJ8FLiyZSaEO3iP5A
Reusing existing connection to accounts.google.com:443.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&emr=1&followup=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&ifkv=AYZoVhcCdtkE8crGBpECp5j_bRBJYaHbVaz3FQS-_gLC8ASHUrgeLaYfsyohzTuOygOktbDmgktaAA&osid=1&passive=1209600&service=mail&flowName=WebLiteSignIn&flowEntry=ServiceLogin&dsh=S1527348757%3A1696994566384267 [following]
--2023-10-11 11:22:46--  https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&emr=1&followup=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&ifkv=AYZoVhcCdtkE8crGBpECp5j_bRBJYaHbVaz3FQS-_gLC8ASHUrgeLaYfsyohzTuOygOktbDmgktaAA&osid=1&passive=1209600&service=mail&flowName=WebLiteSignIn&flowEntry=ServiceLogin&dsh=S1527348757%3A1696994566384267
Reusing existing connection to accounts.google.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘./LICENSE’

./LICENSE                              [ <=>                                                             ] 574.30K  --.-KB/s    in 0.04s

2023-10-11 11:22:46 (13.2 MB/s) - ‘./LICENSE’ saved [588741]

--2023-10-11 11:22:46--  http://gaoyuze.m@gmail.com/
Resolving gmail.com (gmail.com)... 64.233.170.18, 64.233.170.83, 64.233.170.19, ...
Connecting to gmail.com (gmail.com)|64.233.170.18|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://mail.google.com/mail/u/0/ [following]
--2023-10-11 11:22:46--  https://mail.google.com/mail/u/0/
Resolving mail.google.com (mail.google.com)... 142.251.12.83, 142.251.12.17, 142.251.12.19, ...
Connecting to mail.google.com (mail.google.com)|142.251.12.83|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://accounts.google.com/ServiceLogin?service=mail&passive=1209600&osid=1&continue=https://mail.google.com/mail/u/0/&followup=https://mail.google.com/mail/u/0/&emr=1 [following]
--2023-10-11 11:22:46--  https://accounts.google.com/ServiceLogin?service=mail&passive=1209600&osid=1&continue=https://mail.google.com/mail/u/0/&followup=https://mail.google.com/mail/u/0/&emr=1
Resolving accounts.google.com (accounts.google.com)... 172.217.194.84
Connecting to accounts.google.com (accounts.google.com)|172.217.194.84|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://accounts.google.com/InteractiveLogin?continue=https://mail.google.com/mail/u/0/&emr=1&followup=https://mail.google.com/mail/u/0/&osid=1&passive=1209600&service=mail&ifkv=AYZoVhcl2HeZQgpuh8WfD-7Xlql989QgKQ1pC5tjxq_McUTRbJadNsLZkrEvtKeBawm2F7OWy9a1JA [following]
--2023-10-11 11:22:46--  https://accounts.google.com/InteractiveLogin?continue=https://mail.google.com/mail/u/0/&emr=1&followup=https://mail.google.com/mail/u/0/&osid=1&passive=1209600&service=mail&ifkv=AYZoVhcl2HeZQgpuh8WfD-7Xlql989QgKQ1pC5tjxq_McUTRbJadNsLZkrEvtKeBawm2F7OWy9a1JA
Reusing existing connection to accounts.google.com:443.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&emr=1&followup=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&ifkv=AYZoVheQ4llBencSeTdXAeIsvoidqKujem2_hPVd4aev5frXYZ5W9r2E3mF1EQiqKYMALr2V6nDZmA&osid=1&passive=1209600&service=mail&flowName=WebLiteSignIn&flowEntry=ServiceLogin&dsh=S336028889%3A1696994566817170 [following]
--2023-10-11 11:22:46--  https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&emr=1&followup=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&ifkv=AYZoVheQ4llBencSeTdXAeIsvoidqKujem2_hPVd4aev5frXYZ5W9r2E3mF1EQiqKYMALr2V6nDZmA&osid=1&passive=1209600&service=mail&flowName=WebLiteSignIn&flowEntry=ServiceLogin&dsh=S336028889%3A1696994566817170
Reusing existing connection to accounts.google.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘./USE_POLICY.md’

./USE_POLICY.md                        [ <=>                                                             ] 573.72K  --.-KB/s    in 0.03s

2023-10-11 11:22:46 (18.4 MB/s) - ‘./USE_POLICY.md’ saved [587718]

Downloading tokenizer
--2023-10-11 11:22:46--  http://gaoyuze.m@gmail.com/
Resolving gmail.com (gmail.com)... 64.233.170.18, 64.233.170.83, 64.233.170.17, ...
Connecting to gmail.com (gmail.com)|64.233.170.18|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://mail.google.com/mail/u/0/ [following]
--2023-10-11 11:22:46--  https://mail.google.com/mail/u/0/
Resolving mail.google.com (mail.google.com)... 142.251.12.17, 142.251.12.83, 142.251.12.19, ...
Connecting to mail.google.com (mail.google.com)|142.251.12.17|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://accounts.google.com/ServiceLogin?service=mail&passive=1209600&osid=1&continue=https://mail.google.com/mail/u/0/&followup=https://mail.google.com/mail/u/0/&emr=1 [following]
--2023-10-11 11:22:47--  https://accounts.google.com/ServiceLogin?service=mail&passive=1209600&osid=1&continue=https://mail.google.com/mail/u/0/&followup=https://mail.google.com/mail/u/0/&emr=1
Resolving accounts.google.com (accounts.google.com)... 172.217.194.84
Connecting to accounts.google.com (accounts.google.com)|172.217.194.84|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://accounts.google.com/InteractiveLogin?continue=https://mail.google.com/mail/u/0/&emr=1&followup=https://mail.google.com/mail/u/0/&osid=1&passive=1209600&service=mail&ifkv=AYZoVheuDZgG7NFZjf7Ty8FgCsqvmQ3kPfCjvl78oNxIt254SPAJablJUwEjK9qreXm7yCXWMIkqYg [following]
--2023-10-11 11:22:47--  https://accounts.google.com/InteractiveLogin?continue=https://mail.google.com/mail/u/0/&emr=1&followup=https://mail.google.com/mail/u/0/&osid=1&passive=1209600&service=mail&ifkv=AYZoVheuDZgG7NFZjf7Ty8FgCsqvmQ3kPfCjvl78oNxIt254SPAJablJUwEjK9qreXm7yCXWMIkqYg
Reusing existing connection to accounts.google.com:443.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&emr=1&followup=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&ifkv=AYZoVheASEWfRNjYcVrDcpI9bkvmJ85sUt_z4-JbuR74kRR1JKZwnBNYIN5ST69tzlYQ2ecmtQTctQ&osid=1&passive=1209600&service=mail&flowName=WebLiteSignIn&flowEntry=ServiceLogin&dsh=S554229440%3A1696994567477897 [following]
--2023-10-11 11:22:47--  https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&emr=1&followup=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&ifkv=AYZoVheASEWfRNjYcVrDcpI9bkvmJ85sUt_z4-JbuR74kRR1JKZwnBNYIN5ST69tzlYQ2ecmtQTctQ&osid=1&passive=1209600&service=mail&flowName=WebLiteSignIn&flowEntry=ServiceLogin&dsh=S554229440%3A1696994567477897
Reusing existing connection to accounts.google.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘./tokenizer.model’

./tokenizer.model                      [ <=>                                                             ] 573.68K  --.-KB/s    in 0.05s

2023-10-11 11:22:47 (10.9 MB/s) - ‘./tokenizer.model’ saved [587634]

--2023-10-11 11:22:47--  http://gaoyuze.m@gmail.com/
Resolving gmail.com (gmail.com)... 64.233.170.83, 64.233.170.17, 64.233.170.19, ...
Connecting to gmail.com (gmail.com)|64.233.170.83|:80... connected.
HTTP request sent, awaiting response... 301 Moved Permanently
Location: https://mail.google.com/mail/u/0/ [following]
--2023-10-11 11:22:47--  https://mail.google.com/mail/u/0/
Resolving mail.google.com (mail.google.com)... 142.251.12.17, 142.251.12.19, 142.251.12.18, ...
Connecting to mail.google.com (mail.google.com)|142.251.12.17|:443... connected.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://accounts.google.com/ServiceLogin?service=mail&passive=1209600&osid=1&continue=https://mail.google.com/mail/u/0/&followup=https://mail.google.com/mail/u/0/&emr=1 [following]
--2023-10-11 11:22:49--  https://accounts.google.com/ServiceLogin?service=mail&passive=1209600&osid=1&continue=https://mail.google.com/mail/u/0/&followup=https://mail.google.com/mail/u/0/&emr=1
Resolving accounts.google.com (accounts.google.com)... 172.217.194.84
Connecting to accounts.google.com (accounts.google.com)|172.217.194.84|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://accounts.google.com/InteractiveLogin?continue=https://mail.google.com/mail/u/0/&emr=1&followup=https://mail.google.com/mail/u/0/&osid=1&passive=1209600&service=mail&ifkv=AYZoVhedbYb-20jO4jxRJi-TuXSI_mBY5XNp1hQ43l2EjaKfQveJJLQyd1J6oHF1MYtXj0uQJUFI [following]
--2023-10-11 11:22:49--  https://accounts.google.com/InteractiveLogin?continue=https://mail.google.com/mail/u/0/&emr=1&followup=https://mail.google.com/mail/u/0/&osid=1&passive=1209600&service=mail&ifkv=AYZoVhedbYb-20jO4jxRJi-TuXSI_mBY5XNp1hQ43l2EjaKfQveJJLQyd1J6oHF1MYtXj0uQJUFI
Reusing existing connection to accounts.google.com:443.
HTTP request sent, awaiting response... 302 Moved Temporarily
Location: https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&emr=1&followup=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&ifkv=AYZoVheB0hTnSC5YJJHGBeCxJNverburQgKQSadvU05qpYk-oKKRwpV50Vfd_xe0phJCDKO5aSE_&osid=1&passive=1209600&service=mail&flowName=WebLiteSignIn&flowEntry=ServiceLogin&dsh=S1644339074%3A1696994569110020 [following]
--2023-10-11 11:22:49--  https://accounts.google.com/v3/signin/identifier?continue=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&emr=1&followup=https%3A%2F%2Fmail.google.com%2Fmail%2Fu%2F0%2F&ifkv=AYZoVheB0hTnSC5YJJHGBeCxJNverburQgKQSadvU05qpYk-oKKRwpV50Vfd_xe0phJCDKO5aSE_&osid=1&passive=1209600&service=mail&flowName=WebLiteSignIn&flowEntry=ServiceLogin&dsh=S1644339074%3A1696994569110020
Reusing existing connection to accounts.google.com:443.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: ‘./tokenizer_checklist.chk’

./tokenizer_checklist.chk              [ <=>                                                             ] 574.36K  --.-KB/s    in 0.07s

2023-10-11 11:22:49 (8.27 MB/s) - ‘./tokenizer_checklist.chk’ saved [588147]

md5sum: tokenizer_checklist.chk: no properly formatted MD5 checksum lines found

**Comment by subramen** [comment]
You need to request a download link from the form here: https://ai.meta.com/resources/models-and-libraries/llama-downloads/ Once you do that, you'll get a presigned URL in your email. That's the URL you need to use here:

> $ ./download.sh
> Enter the URL from email: <presigned url, not your email id>

That should fix your issue :) Closing this issue but feel free to reopen it if you're encountering problems with the download

**Comment by ali-yuze** [comment]
Yes, thank you @subramen  , stupid me
