### ISSUE TITLE
Only can run in Linux?

### ISSUE THREAD

**Issue by Jalen-Zhong** [facebookresearch/llama#850]
**I try this commad on my windows computer:**

> torchrun --nproc_per_node 1 example_chat_completion.py --ckpt_dir llama-2-7b-chat --tokenizer_path tokenizer.model --max_seq_len 512 --max_batch_size 6

**Error:**

> [2023-10-11 16:30:34,795] torch.distributed.elastic.multiprocessing.redirects: [WARNING] NOTE: Redirects are currently not supported in Windows or MacOs.
> [W socket.cpp:663] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:29500 (system error: 10049 - The address of the request is invalid in its context 。).
> [W socket.cpp:663] [c10d] The client socket has failed to connect to [kubernetes.docker.internal]:29500 (system error: 10049 -  The address of the request is invalid in its context。).

**My hardware:**

> nvidia-3090-24G; Window 10

**Is that mean I can not run llama in windows system or single GPU? Any pro can reply to me? Appreciate！**

**Comment by subramen** [comment]
Hi @Jalen-Zhong, currently code in this repo only supports Linux OS. As a windows user, you have a few options:
1. Use llama2 via huggingface (https://huggingface.co/docs/transformers/main/model_doc/llama2) which is fairly platform-agnostic
2. Install WSL2 to run linux on windows
3. Use the awesome llama.cpp repo https://github.com/ggerganov/llama.cpp - you might not need a GPU also
