### ISSUE TITLE
The license for non-English services of LLaMA2.

### ISSUE THREAD

**Issue by sooftware** [facebookresearch/llama#855]
The LLaMA2 license specifies that 'unrestricted commercial use is allowed as long as the Monthly Active Users (MAU) do not exceed 700 million.' Does this mean there are no restrictions on commercial use when offering LLaMA2 in languages other than English, such as Korean or Chinese, as long as the MAU does not exceed 700 million?

**Comment by jspisak** [comment]
Hey - yes, you can fine tune Llama 2 models on other languages beyond English and deploy them in production. See the FAQ below:

https://github.com/facebookresearch/llama/blob/main/FAQ.md

If your user based is above 700 million, you can reach out and we can agree on terms of use.

**Comment by sooftware** [comment]
thank you!
