### ISSUE TITLE
Queston: What is the difference between llama2-7B and llama-7B

### ISSUE THREAD

**Issue by LT1st** [facebookresearch/llama#863]
I applied for both, but get llama2 only. If it is the same for interfaces? 

I gonna use it in NEXT_GPT

**Comment by BadrinathMJ** [comment]
llama-7B is not available for commercial purpose. Only llama-2 is available for commercial purpose that's why you only get llama-2.

**Comment by subramen** [comment]
Thanks @BadrinathMJ, that's right - llama-2 has a more permissive license

**Comment by LT1st** [comment]
Thank u guys. Got it. But what is the difference in their codes? 

I want to use it in reimplement of proposed method, and I am afraid that these two version of llama are not identical.
