### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'quantizer'

### ISSUE THREAD

**Issue by yyyddff** [facebookresearch/llama#865]
<img width="815" alt="1697685215667" src="https://github.com/facebookresearch/llama/assets/60256088/a18d9176-771a-4652-8f90-5c059e963ca5">
how to fix it

**Comment by albertodepaola** [comment]
Hi @yyyddff, can you provide more details about your setup and the command you are running when encountering this issue?

**Comment by albertodepaola** [comment]
Hi @yyyddff, closing this for now, feel free to reopen when you have additional information to share!
