### ISSUE TITLE
Llama2 Model Access Issue

### ISSUE THREAD

**Issue by ahatamiz** [facebookresearch/llama#872]
Hello, 

I have filled out the [request form](https://ai.meta.com/resources/models-and-libraries/llama-downloads/) to access Llama 2 models. However, I have not received any response. 

Could someone please help in providing the access ? 

Thanks again !

**Comment by Ross-Stein** [comment]
I met the same problem, no any response in the past 72h. 
Did you get any response? @ahatamiz

**Comment by ahatamiz** [comment]
@Ross-Stein Unfortunately no response. 

I hope the team would be able to provide access @jspisak @samuelselvan.

**Comment by jspisak** [comment]
Thanks for letting us know - we will follow up ASAP..

**Comment by ahatamiz** [comment]
Thank you for your response and attention to this issue @jspisak ! 

I have not yet received any email regarding access to Llama2 modes. Moreover, I tried to also fill out the form using my work email, and this time faced another issue (please see the screenshot below):
![llama2](https://github.com/facebookresearch/llama/assets/26806394/9ab2a7ca-cf16-4f7c-9b90-eeb072215a88)

I really hope that these issues could be resolved, as open-source models such as Llama2 play an integral role in the community. 

Thanks again for your time and efforts in solving this issue !

**Comment by ahatamiz** [comment]
The problem was not resolved.
