### ISSUE TITLE
Installing llama-2 model closes the window, does nothing else

### ISSUE THREAD

**Issue by Dekriel** [facebookresearch/llama#873]
**Before submitting a bug, please make sure the issue hasn't been already addressed by searching through the [FAQs](https://github.com/facebookresearch/llama/blob/main/FAQ.md) and [existing/past issues](https://github.com/facebookresearch/llama/issues)**

## Describe the bug
When I ran Download.sh, I inputted the URL, and selected to download the 7B model. However, upon running, the window closes immediately. Is this meant to happen? What do I do from here?

Remember to wrap the code and outputs in ```` ```triple-quotes blocks``` ````.

### Minimal reproducible example

```python
# sample code to repro the bug
```

### Output

```
<paste stacktrace and other outputs here>
```

## Runtime Environment
- Model: None
- Using via huggingface?: no
- OS: Windows
- GPU VRAM: 8GB
- Number of GPUs: 1
- GPU Make: NVIDIA

**Additional context**
Download.sh was ran from the Git command window, because windows CMD didn't want to.

**Comment by fbnav** [comment]
Hi @Dekriel,  please make sure you've installed `wget` in your working environment. You can do that by downloading Windows binaries of GNU Wget (wget.exe) from [https://eternallybored.org/misc/wget/](), and add the wget.exe file to your `PATH`.

Once you have wget, please retry running the `./download.sh` script to download the models. You might need to request a new URL link from [https://ai.meta.com/resources/models-and-libraries/llama-downloads/]().

If you'd like to run the download script using Windows CMD, try changing the line-endings from `CRLF` to `LF` then run it using `bash download.sh`.

**Comment by fbnav** [comment]
Closing this issue for now, please reopen if you need to follow-up.
