### ISSUE TITLE
How to approch quantization and fine-tuning with the llama2 7B chat model with the code given in this repository.

### ISSUE THREAD

**Issue by Harsh-raj** [facebookresearch/llama#874]

**Comment by Harsh-raj** [comment]
I have done inference with the llama 2 7B chat model in this repository and can now do conversation with it. I want to know how to do the 8 bit quantization of the model and do its finetuning on some dataset (say user-assistant chat dataset). I trying to integrate the quantization and finetuning code with the model in this repository in such a way that user can toggle whether to use the quantized model or the original pre trained model and whether to fine tune the model on some specific dataset. I am new to this domain of LLMs so and still trying to understand how things like quantization and fine tuning works in LLMs. Please help, thank you!

**Comment by subramen** [comment]
The easiest way to do all of those is using a library like huggingface or [lit-gpt](https://github.com/Lightning-AI/lit-gpt) that reduces how much boilerplate code you'd need to write. 

Check out the example scripts in https://github.com/facebookresearch/llama-recipes that uses huggingface APIs to serve and finetune quantized models.
