### ISSUE TITLE
llama2 is providing the wrong verse in English with wrong references and adding those word which isn't written in Holy Quran

### ISSUE THREAD

**Issue by FaizanMunsaf** [facebookresearch/llama#879]
Llama-2-70b-chat-hf does not provide a good result regarding the Holy Quran and its references. how is it's possible to get the exact Holy Quran verse using llama-2 even in English?

**Comment by subramen** [comment]
Llama 2 is intended for commercial and research use in English only. Other languages are out-of-scope. Use of other languages in any other way is prohibited by the Acceptable Use Policy and Licensing Agreement for Llama 2. See this reply on a similar thread https://github.com/facebookresearch/llama/issues/763#issuecomment-1731670283

**Comment by CatartcieWoodygrue** [comment]
No problem

**Comment by FaizanMunsaf** [comment]
> Llama 2 is intended for commercial and research use in English only. Other languages are out-of-scope. Use of other languages in any other way is prohibited by the Acceptable Use Policy and Licensing Agreement for Llama 2. See this reply on a similar thread [#763 (comment)](https://github.com/facebookresearch/llama/issues/763#issuecomment-1731670283)

I m not talking about arabic language. I am askimg about English Language. Sorry if you miss understood my question
