### ISSUE TITLE
meta-llama/Llama-2-7b-chat does not appear to have a file named config.json

### ISSUE THREAD

**Issue by NilayYadav** [facebookresearch/llama#880]
I have been trying to use HuggingFace Inference API for the "meta-llama/Llama-2-7b-chat" model, But unfortunately, I'm getting an error Anyway, I do have access to this model. What is the correct way to use llama with API?

Error:
{"error":"meta-llama/Llama-2-7b-chat does not appear to have a file named config.json. check out 'https://huggingface.co/meta-llama/Llama-2-7b-chat/2abbae1937452ebd4eecb63113a87feacd6f13ac' for available files."}

**Comment by jhhspace** [comment]
got the same error before, but when i swapped over to Llama-2-7b-chat-hf it solved the issue, maybe try using that

**Comment by Zuhashaik** [comment]
> I have been trying to use HuggingFace Inference API for the "meta-llama/Llama-2-7b-chat" model, But unfortunately, I'm getting an error Anyway, I do have access to this model. What is the correct way to use llama with API?
> 
> Error: {"error":"meta-llama/Llama-2-7b-chat does not appear to have a file named config.json. check out 'https://huggingface.co/meta-llama/Llama-2-7b-chat/2abbae1937452ebd4eecb63113a87feacd6f13ac' for available files."}

can you give more details about your problem, may be attach a screenshot or which huggingface api you are using to load the model?
or try keep the model.bin/ model.gguf or any extention model and config.json in the same folder now you have to give the model's folder as the path to the hugging face api. this might work

**Comment by subramen** [comment]
the repo_id on hf is `meta-llama/Llama-2-7b-chat-hf`. Please try using that.
