### ISSUE TITLE
Problem with designing the prompt for my dataset - Multiplechoice QA

### ISSUE THREAD

**Issue by Sosycs** [facebookresearch/llama#882]
Hello everyone, 

I have a dataset where I need to perform instruction fine-tuning using llama2. I am trying to make the prompt format right but I am still new so please do help me.

In the dataset I want to finetne llama2 on I have: 
1. A context where the answer should be infered.
2. A question.
3. Multiple choice.
4. Correct answer. 

and this is the structure I have created:
```
<s>[INSTRUCTION] <<SYS>>
Please select the correct answer from the given multiple options based on the given context.
<</SYS>>
Context: context1
Question: question1
Options: (A) option1 (B) option2 (C) option3 (D) option4 
Answer: [/INSTRUCTION] correct_answer </s>
```

is it correct or do I need to fix it?

Thanks in a dvance

**Comment by albertodepaola** [comment]
Hi @Sosycs, your prompt looks good overall, only change can be `[INSTRUCTION]` for `[INST]`. You can check other sample prompts in the new [getting started guide](https://ai.meta.com/llama/get-started/#prompting). Also check out this resource on [Hugging Face](https://huggingface.co/blog/llama2#how-to-prompt-llama-2).
Closing as solved, feel free to reopen if you have further questions.

**Comment by Sosycs** [comment]
@albertodepaola Thank you very much for your reply, I have created a column 'text' to train on. an example of it is as follow:
<s>[INST] <<SYS>> Please select the correct answer from the given multiple Options based on the given Context: <</SYS>> Context: Work is defined differently in physics than in everyday language. In physics, work means the use of force to move an object. The teens who are playing basketball in the picture above are using force to move their bodies and the basketball, so they are doing work. The teen who is studying isnt moving anything, so she isnt doing work. Not all force that is used to move an object does work. For work to be done, the force must be applied in the same direction that the object moves. If a force is applied in a different direction than the object moves, no work is done. The Figure 1.1 illustrates this point. Q: If the box the man is carrying is very heavy, does he do any work as he walks across the room with it? A: Regardless of the weight of the box, the man does no work on it as he holds it while walking across the room. However, he does more work when he first lifts a heavier box to chest height. Question: you do more work playing basketball than you do studying for a test. Options:(A) true (B) false Answer: [/INST] A </s>
Is it correct that I put the correct answer after [/INST]?

**Comment by Sosycs** [comment]
Also, can you please advice me on the way I need to evaluate the model with?
Do I send the quesries in this form in order to evaluate?
`<s>[INST] <<SYS>> Please select the correct answer from the given multiple Options based on the given Context: <</SYS>> Context: Work is defined differently in physics than in everyday language. In physics, work means the use of force to move an object. The teens who are playing basketball in the picture above are using force to move their bodies and the basketball, so they are doing work. The teen who is studying isnt moving anything, so she isnt doing work. Not all force that is used to move an object does work. For work to be done, the force must be applied in the same direction that the object moves. If a force is applied in a different direction than the object moves, no work is done. The Figure 1.1 illustrates this point. Q: If the box the man is carrying is very heavy, does he do any work as he walks across the room with it? A: Regardless of the weight of the box, the man does no work on it as he holds it while walking across the room. However, he does more work when he first lifts a heavier box to chest height. Question: you do more work playing basketball than you do studying for a test. Options:(A) true (B) false Answer: [/INST]  </s>`

by sending the the same structure of the instruction when training with correct answer being empty?

**Comment by JhonDan1999** [comment]
> Hi @Sosycs, on your first question: It is correct, you send the system prompt and the user question inside the `[INST]` tags, and the complete sentence, with the correct answer, is enclosed by the `<s>` tags. You can see a simplified example of this in the [tokenization function](https://github.com/facebookresearch/llama-recipes/blob/main/examples/custom_dataset.py#L14) for the custom dataset (OpenAssist) from the llama-recipes, as well as in the HF blog. On the second question, if you are implementing your own generation script, then you need to take care of these tags as well, but if you are using the [generation.py](https://github.com/facebookresearch/llama/blob/main/llama/generation.py) present in this repo, it's already handled in it, and you only need to send in the prompt text.

Hi @albertodepaola 

Are you sure about the correctness of the prompt provided by @Sosycs  for the evaluation?
I believe in the evaluation we should not end the prompt with ```</s>```
right?
