### ISSUE TITLE
it always report error when using llama2 model on mac

### ISSUE THREAD

**Issue by liumilan** [facebookresearch/llama#883]
i just follow this link to install llama2 model on mac m1,but it always report Errors:
https://simonwillison.net/2023/Aug/1/llama-2-mac/
brew install llm
llm install llm-llama-cpp
llm install llama-cpp-python
llm llama-cpp download-model \
  https://huggingface.co/TheBloke/Llama-2-7B-Chat-GGML/resolve/main/llama-2-7b-chat.ggmlv3.q8_0.bin \
  --alias llama2-chat --alias l2c --llama2-chat
llm -m l2c 'Tell me a joke about a llama'
and result is Error:
Could u helpe to find out why?

**Comment by subramen** [comment]
Please share more information about the error, it is imposssible to diagnose what is wrong without any details about the error.

Feel free to reopen the issue when you have more information!
