### ISSUE TITLE
Click on "Accept and Continue" does NOTHING

### ISSUE THREAD

**Issue by Abdelkrim** [facebookresearch/llama#885]
## Describe the bug

1. I am about to accept the terms of conditions to download the Llama2 model
2. the process worked in the past AND I have received an email containing the link to download the model

![image](https://github.com/facebookresearch/llama/assets/791663/198c9ef8-0840-44cb-87ea-e88a93eaf2db)

### Minimal reproducible example

1. Click on [](https://ai.meta.com/resources/models-and-libraries/llama-downloads/)
4. Fill the required contact details
5. Check "Llama 2 & Llama Chat"
6. Check "Code Llama"
7. Check "I accept the terms and conditions"
8. Click on "Accept and Continue"

![image](https://github.com/facebookresearch/llama/assets/791663/e4e9d12b-0705-40ea-b384-df90636a1578)

### Output

* **NOTHING**, the browser DOES NOT load a new page indicating the success of the operation

## Runtime Environment
- Windows 11 - Browser : Chrome, Firefox, Bing
- Mobile phone : OnePlus - Browser : Chrome

**Comment by samuelselvan** [comment]
@Abdelkrim  - could you please retry?

**Comment by Abdelkrim** [comment]
> @Abdelkrim - could you please retry?

I have found the issue. **The form DOES NOT accept a '+' inside the email address**
