### ISSUE TITLE
 Llama-2-70b Model: Challenges with Long Token Sequences

### ISSUE THREAD

**Issue by Zuhashaik** [facebookresearch/llama#887]
As the open-source Llama-2-70b model gains popularity within the community, questions arise about its performance on longer token sequences, potentially exceeding 2500 tokens. In my case, it seems to struggle after 500 tokens. Specifically, I'm referring to the Llama-2-70b model.

**Comment by Zuhashaik** [comment]
May be after finetuning with the data (simulated with gpt-3.5 or 4).what does the community thinks about working on 2500 tokens and higher or any suggetions on some other models?

**Comment by Zuhashaik** [comment]
No no you're getting me wrong, as the max_input_tokens are 4096 for the model llama-2-70b. But the efficiency of the model is limited to 500 tokens(in my experience of usage). When tokens exceed 500 the model started giving garbage.
Even you all guys experienced the same ?
If so what if we fine-tune the model will it increase the performance when the tokens are more than 500 ?
If not suggest me any other models which are good at handling more input tokens my use case have more than 2500 tokens.

**Comment by HongheZ** [comment]
> No no you're getting me wrong, as the max_input_tokens are 4096 for the model llama-2-70b. But the efficiency of the model is limited to 500 tokens(in my experience of usage). When tokens exceed 500 the model started giving garbage. Even you all guys experienced the same ? If so what if we fine-tune the model will it increase the performance when the tokens are more than 500 ? If not suggest me any other models which are good at handling more input tokens my use case have more than 2500 tokens.

Oh, got it. It seems that my problem is different. The output of the model I used will interrupt suddenly. But the output is logically. Maybe you can have a try the model I used: Llama-2-13b-chat?

**Comment by ejsd1989** [comment]
@Zuhashaik thanks for submitting the question for the community. Overall, you should be able to generate more than 500 tokens using all of the Llama models. Based on your comments above, am I correct to interpret that you are seeing a lot of hallucination with larger generations of 500+ tokens? This could be related to the prompt itself and could also be affected by the temperature used in your hyperparameters. 

Could you please provide some more info about your configuration? i.e.- 

model: 
input size:
output size:
parameters:
example input/prompts:

**Comment by ejsd1989** [comment]
@HongheZ 

It may be good to know more about your setup. It sounds like you may be running into resource constraints with the larger generations. As the generation size increases, I definitely see latency increase significantly and I'm wondering if your system hanging. Do you have more details around your system specs, gpu, memory, etc.

**Comment by Sanchit-404** [comment]
How does the system specs have influence on the quality of outputs? there can be latency but the quality of output should remain consistent regardless of specs.

**Comment by Zuhashaik** [comment]
> @Zuhashaik thanks for submitting the question for the community. Overall, you should be able to generate more than 500 tokens using all of the Llama models. Based on your comments above, am I correct to interpret that you are seeing a lot of hallucination with larger generations of 500+ tokens? This could be related to the prompt itself and could also be affected by the temperature used in your hyperparameters.
> 
> Could you please provide some more info about your configuration? i.e.-
> 
> model: input size: output size: parameters: example input/prompts:

The model ive used is llama-70b-chat-hf
input size would be more than 2000 tokens for sure and go upto 3500 and also max_tokens limit
output will be less than 500 tokens
as i need the ground truth about the conversations i am giving as input and also it should'nt halucinate so temp should be between 0.2-0.5
Functionality is, i am sending a conversation as an input to this llm and asked to analyse(something complex, which gpt-3.5 has done well on this task) and give some outputs on the questions ive aksed.

And i dont think so my hardware matters but as you've asked, i am using 3 cards of tesla-v100 and 32gib of vram each which makes 96gib of vram total to load a 5 bit quantized version of this llm.

**Comment by Zuhashaik** [comment]
The only thing i wanted to know is, whether this llm performs well on more input tokens or not?
if not i can still fine-tune it by taking aws sagemaker instances, even this doesn't work, it will be a waste of money, that why to save this i am asking suggetions to community. if the ans is no to the both questions, then can any one suggest me a good alternative that can handle more number of tokens with better performance.

I want to make clear about my problem, there is a difference between max_tokens and tokens that can be handled with a good performance. I get all of you guys got this!
Thank you.

**Comment by ejsd1989** [comment]
Hey @Zuhashaik - It's been a while and I wanted to get back to you on this. 

Llama-2 works fine with up to the 4k context limit. I've run to around 3k in and 500+ out and it worked fine running on a P4D instance with SageMaker. Curious if you've had time to test a bit more? Please feel free to reopen this thread if you have some more info, otherwise I'll close it for now because it's been silent.
