### ISSUE TITLE
Unable to download Llama 2 models

### ISSUE THREAD

**Issue by anirudhv** [facebookresearch/llama#888]
I opened up conda. I created a new folder and cloned the llama github repository into it. 

In the llama repository, I first ran the command - `pip install -e .`

I installed pytorch with this command -

`conda install -c pytorch pytorch`

I then ran download.sh. When prompted to enter the URL from my email, I did. Note that I got the URL in my email inbox less than 24 hours ago (around 5-6 hours ago).  Once I entered the link, I was asked to select which models I wanted to install. I pressed the enter key to install all models. The pop-up window that asked me to enter the URL closed automatically as soon as I chose which models I wanted to install. I had no sort of indication that the models were installing/installed. 

I've followed the instructions in the Quick Start section of the README file - https://github.com/facebookresearch/llama - so I'm not sure where I've went wrong.

Advice/help would be appreciated!

I have a WIndows 11 laptop with the NVIDIA GeForce RTX 3070 laptop GPU, 16GB of RAM. If there is a text/video tutorial I should follow, please share them with me. I haven't found anything concrete yet. The README file is a bit vague.

**Comment by fbnav** [comment]
Hi, please make sure you've installed wget in your working environment. You can do that by downloading Windows binaries of GNU Wget (wget.exe) from [https://eternallybored.org/misc/wget/](https://github.com/facebookresearch/llama/issues/873), and add the wget.exe file to your PATH.

Once you have wget, please retry running the ./download.sh script to download the models. You might need to request a new URL link from [https://ai.meta.com/resources/models-and-libraries/llama-downloads/](https://github.com/facebookresearch/llama/issues/873).

If you'd like to run the download script using Windows CMD, try changing the line-endings from CRLF to LF then run it using bash download.sh.

**Comment by fbnav** [comment]
Closing this issue for now, please reopen if you need to follow-up.
