### ISSUE TITLE
Unable to run example.py

### ISSUE THREAD

**Issue by kalloud** [facebookresearch/llama#89]
Hi, 

I was trying to run the example.py for a first try but I got the following error: 

![image](https://user-images.githubusercontent.com/49025724/222783473-63d4561f-d398-4231-9106-32121b50ff37.png)

Can someone please help me with this issue? 

Thanks!

**Comment by Inserian** [comment]
Try modifying the --nproc_per_node flag to match the number of processes used during training. For example, if the checkpoint was trained with 2 model parallel processes, you can run the following command: torchrun --nproc_per_node 2 example.py --ckpt_dir $TARGET_FOLDER/7B --tokenizer path $TARGET_FOLDER/tokenizer.mode
This will launch the example.py script with 2 model parallel processes, which should be compatible with the checkpoint trained with 2 processes. If the number of processes used during training is different, you should adjust the --nproc_per_node flag accordingly.
If you don't know the number of processes used during training, you can try using the auto option for the --nproc_per_node flag, which will automatically detect the optimal number of processes based on the available hardware resources.
torchrun --nproc_per_node auto example.py --ckpt_dir $TARGET_FOLDER/7B --tokenizer path $TARGET_FOLDER/tokenizer.mode

If neither works try the alternative to torchrun    python -m torch.distributed.run --nproc_per_node MP example.py --ckpt_dir $TARGET_FOLDER/model_size --tokenizer_path $TARGET_FOLDER/tokenizer.model
(Changing the MP value of course).

**Comment by amirzamli** [comment]
Seems to me that its not resolving the correct directory. Check that the $TARGET_FOLDER is set and pointing to the correct directory.
