### ISSUE TITLE
release of LLAMA-I

### ISSUE THREAD

**Issue by bino282** [facebookresearch/llama#9]
Do you have plan to release instruction model  LLAMA-I?

**Comment by glample** [comment]
LLAMA-I was only a very experimental model and we barely started working on the instruction fine-tuning, so it will not be released in the short term. We will consider it in the future when we have made more progress in this direction.

**Comment by Franck-Dernoncourt** [comment]
https://crfm.stanford.edu/2023/03/13/alpaca.html :
> *We introduce [Alpaca 7B](https://crfm.stanford.edu/alpaca/), a model fine-tuned from the LLaMA 7B model on 52K instruction-following demonstrations. Alpaca behaves similarly to OpenAI’s text-davinci-003, while being surprisingly small and easy/cheap to reproduce (<$600).*  
[Web Demo](https://crfm.stanford.edu/alpaca/)   [GitHub](https://github.com/tatsu-lab/stanford_alpaca)

Weights aren't released yet either though.
