### ISSUE TITLE
PaddlePaddle implementation of LLaMA

### ISSUE THREAD

**Issue by jiaohuix** [facebookresearch/llama#90]
I have reimplemented llama with the paddlepaddle framework and provided an example of running 7b using aistudio
free computing power, feel free to test and suggest improvements.
repo:  [ppllama](https://github.com/MiuGod0126/ppllama)

**Comment by HelixNGC7293** [comment]
This is awesome!

**Comment by jspisak** [comment]
thank you for your contribution! @subramen - should we do a blog post on this?

**Comment by subramen** [comment]
@jiaohuix - thanks for your work! i can help you write a blog about this for the wider community to learn. please email me subramen <at> meta <dot> com if you're interested!
