### ISSUE TITLE
ERROR:  OSError:lama-2-7b-chat does not appear to have a file named config.json. 

### ISSUE THREAD

**Issue by Yarmohamadshr** [facebookresearch/llama#904]
Hi,
I am trying to run the Llama-7b chat that I already downloaded from Meta locally. I got this configuration error because I am using Transformers. I do not know how to run or change the code to be able to run with Transformers. Also, my local system is a remote GPU server, which does not have permission to connect to the internet.

```python
'''
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer, AutoConfig

# Define the model name or directory path
model_name_or_path = ".../llama-2-7b-chat"  # Replace with the actual model name or path

# Load the configuration
config = AutoConfig.from_pretrained(model_name_or_path)

# Check if a GPU is available, and if so, use it
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Load the model
model = AutoModelForCausalLM.from_pretrained(model_name_or_path, config=config).to(device)

# Load the tokenizer
tokenizer = AutoTokenizer.from_pretrained(model_name_or_path)

print("Model loaded.")

'''
```

### Output
OSError:lama-2-7b-chat does not appear to have a file named config.json. 

```

**Comment by EmanuelaBoros** [comment]
Hello @Yarmohamadshr, the local downloaded model can only be loaded with their code (found in the same repo). If you want to use the HuggingFace code, you need to use the model from HuggingFace https://huggingface.co/meta-llama/Llama-2-70b-chat-hf

**Comment by Yarmohamadshr** [comment]
My server does not have the permission to connect to the internet for Hugging Face log in, do you know how to use this hugging Face version without connection and offline?

**Comment by subramen** [comment]
@Yarmohamadshr You should be able to use the downloaded checkpoint files on your server without the HF login. You will have to convert those checkpoints to th HF format as mentioned here https://github.com/facebookresearch/llama/issues/875#issuecomment-1779647981

**Comment by Yarmohamadshr** [comment]
@subramen I am trying to use the conversion code in the Conda virtual environment, I get the error for GitHub, I am sorry, I am not that familiar with this terminal code, Should I run it on cmd calling Python or in my Conda prompt, Below is the screen shot of the error for git clone
![Screenshot 2023-11-08 113309](https://github.com/facebookresearch/llama/assets/73134971/0a753900-18a5-4ed3-9b64-0ef32ed38e14)

**Comment by EmanuelaBoros** [comment]
@Yarmohamadshr It’s unclear why you’re trying to clone the transformers repo, you should clone this one https://github.com/facebookresearch/llama.

Second, you need to add your SSH key to GitHub to be able to clone repos:

https://docs.github.com/en/authentication/connecting-to-github-with-ssh/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent?platform=linux

https://docs.github.com/en/authentication/connecting-to-github-with-ssh/adding-a-new-ssh-key-to-your-github-account

**Comment by EmanuelaBoros** [comment]
@Yarmohamadshr for installing transformers, you can just do: pip install transformers —upgrade

**Comment by Vatsal1106Virani** [comment]
You can manually download form below link and put at that folder.

https://huggingface.co/meta-llama/Llama-2-7b-chat-hf/tree/main

**Comment by Yarmohamadshr** [comment]
Good morning,
Actually the model needed to be converted to HuggingFace friendly format, I did convert it and now all Files and Cards are available, thank you!
