### ISSUE TITLE
License of Llama2 derivative model

### ISSUE THREAD

**Issue by icoxfog417** [facebookresearch/llama#907]
Our customers are interested in training a model using Llama2 as a starting point. Before investing significant time and compute resources into this work, I wanted to request clarification on how derivative models should be licensed. 

Based on my reading of the [Llama2 license](https://ai.meta.com/llama/license/) especially section `1-b-i` , my understanding is that any model derived from Llama2 - whether by fine-tuning the weights or training from scratch using the codebase - would need to be released under the LLAMA 2 Community License. These derivative models could not be released under a more permissive license like MIT or Apache 2.0.

The key points are:

- Models fine-tuned from Llama2 weights need the LLAMA 2 Community License.
- New models trained from scratch using the Llama2 codebase also need the LLAMA 2 Community License. 
- The LLAMA 2 Community License does not allow derivative works to be re-licensed under permissive licenses like MIT or Apache 2.0 that were not written for AI systems.
  - If codebase is implemetend from scratch by referring [Llama2 paper](https://arxiv.org/abs/2302.13971), it does not need to inherit license because paper itself is not included to the "Llama Materilas"

Please let me know if this interpretation is accurate. I want to be certain I understand the obligations for derivative works before proceeding with model development using Llama2. Thank you again for the clarification.

## Related issues

* https://github.com/facebookresearch/llama/issues/240
* https://github.com/facebookresearch/llama/issues/226

**Comment by jspisak** [comment]
i am not a lawyer so I would advocate that you check with your legal team for any clarification. But generally yes, the license requires that it is redistributed for any derivative models.

**Comment by icoxfog417** [comment]
OK, thank you for your reply!
