### ISSUE TITLE
Script download 65B reported no MD5 error

### ISSUE THREAD

**Issue by haxx12113** [facebookresearch/llama#91]
HTTP request sent, awaiting response... 200 OK
Length: 478 [binary/octet-stream]
Saving to: ‘~/llama//65B/checklist.chk’

~/llama//65B/checkl   0%[                    ]       0  --.-KB/s    in 0s

Cannot write to ‘~/llama//65B/checklist.chk’ (Success).
Checking checksums
md5sum: checklist.chk: no properly formatted MD5 checksum lines found

**Comment by Inserian** [comment]
You need to ensure you have permission to write and that the folder exists (use * ls -ld ~/llama//65B/ * to check permission settings). If it doesn't exist, open with admin mode and try with the  * mkdir -p ~/llama//65B/  *
The other thing I noticed is your double slash after llama, this should most likely be a value.

**Comment by Jainam213** [comment]
Can you please upload 65b to a google drive/dropbox/make a pull request?
