### ISSUE TITLE
Seed LLAMA weights

### ISSUE THREAD

**Issue by Jainam2130** [facebookresearch/llama#92]
Can someone please seed the llama weights at
magnet:?xt=urn:btih:b8287ebfa04f879b048d4d4404108cf3e8014352&dn=LLaMA&tr=udp%3a%2f%2ftracker.opentrackr.org%3a1337%2fannounce

Or make them availabe at google drive? There are 0 seeders not sure how long they will stay

**Comment by Justin-Time-Coder** [comment]
I don't think this is allowed? 😯

**Comment by shankarsivarajan** [comment]
All digital files are just lists of numbers.
