### ISSUE TITLE
I've been thinking about how to obtain the hidden state of the last layer of Llama2 after calling the chat_completion method, but I'm not sure how to implement it. I hope to get some answers.

### ISSUE THREAD

**Issue by Eyryu** [facebookresearch/llama#920]
I've been thinking about how to obtain the hidden state of the last layer of Llama2 after calling the chat_completion method, but I'm not sure how to implement it. I hope to get some answers.

_オリジナルは @jjkk123456 が https://github.com/facebookresearch/llama/issues/909 にポスト_

**Comment by fbnav** [comment]
Duplicate of https://github.com/facebookresearch/llama/issues/921. Closing.

**Comment by tanshuai0219** [comment]
any answer? I meet the same question.
