### ISSUE TITLE
Hi,

### ISSUE THREAD

**Issue by Eyryu** [facebookresearch/llama#922]
Hi, 

I have downloaded Llama 2 and quantized it MacOs (llama.cpp). In the terminal, I am able to run the model with following command: 
`./main -m ./models/7B/ggml-model-q4_0.bin -n 1024 --repeat_penalty 1.0 --color -i -r "User:" -f ./prompts/chat-with-bob.txt
`
However I am confused how to load the model as well as the tokenizer in a Python script? In all tutorial I only see how the model is downloaded with Transformers like here: 
`from torch import cuda, bfloat16
import transformers

model_id = 'meta-llama/Llama-2-13b-chat-hf'

bnb_config = transformers.BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type='nf4',
    bnb_4bit_use_double_quant=True,
    bnb_4bit_compute_dtype=bfloat16
)

hf_auth = 'AUTH_TOKEN'
model_config = transformers.AutoConfig.from_pretrained(
    model_id,
    use_auth_token=hf_auth
)

model = transformers.AutoModelForCausalLM.from_pretrained(
    model_id,
    trust_remote_code=True,
    config=model_config,
    quantization_config=bnb_config,
    device_map='auto',
    use_auth_token=hf_auth
)
model.eval()
print(f"Model loaded on {device}")

tokenizer = transformers.AutoTokenizer.from_pretrained(
    model_id,
    use_auth_token=hf_auth
)
`

Do I only need to replace the "model_id" with my path?

_オリジナルは @weissenbacherpwc が https://github.com/facebookresearch/llama/issues/875 にポスト_

**Comment by WuhanMonkey** [comment]
@Eyryu Hi, I am not sure what exactly what you wanna do but since you are using HF frameworks in Python, the answer is yes. Refer to [here](https://huggingface.co/docs/transformers/model_doc/auto#transformers.AutoTokenizer.from_pretrained.pretrained_model_name_or_path)

**Comment by WuhanMonkey** [comment]
Please close this issue if that resolves your question
