### ISSUE TITLE
Files disappeared after download is finished

### ISSUE THREAD

**Issue by DanielKim15** [facebookresearch/llama#940]
## Describe the bug
Hi everyone, I've tried to downloading the 7b and 13b models into my MacBook Pro m2 max computer and everything was working well. However once I finished downloading the models, the files that were supposed to contain them disappeared and I can't find them anywhere on the computer. When I looked at my computer storage, it appears that no space was taken, and yet it seemed the download was successful. What happened?

### Minimal reproducible example
<Remember to wrap the code in ```` ```triple-quotes blocks``` ````>

```python
2023-11-24 19:48:47 (2.32 MB/s) - ‘./llama-2-13b-chat/params.json’ saved [102/102]

--2023-11-24 19:48:47--  
Resolving download.llamameta.net (download.llamameta.net)... 18.244.202.48, 18.244.202.69, 18.244.202.122, ...
Connecting to download.llamameta.net (download.llamameta.net)|18.244.202.48|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 154 [binary/octet-stream]
Saving to: ‘./llama-2-13b-chat/checklist.chk’

./llama-2-13b-chat/ 100%[===================>]     154  --.-KB/s    in 0s      

2023-11-24 19:48:47 (8.64 MB/s) - ‘./llama-2-13b-chat/checklist.chk’ saved [154/154]

Checking checksums
MD5 (checklist.chk) = 49c4cebd5ce83915f26ccd5f80d17bea
```

### Output
<Remember to wrap the output in ```` ```triple-quotes blocks``` ````>

```
<paste stacktrace and other outputs here>
```

## Runtime Environment
- Model: [eg: `llama-2-7b-chat`]
- Using via huggingface?: [no]
- OS: [eg. MacOS]

**Comment by subramen** [comment]
Hi, the script should be downloading the files. Can you verify if you are following all the steps correctly in the instructions? How long did the model checkpoints download take (it should be much more than a few seconds)?
