### ISSUE TITLE
Llama 2 Access on Hugging Face

### ISSUE THREAD

**Issue by rosieyzh** [facebookresearch/llama#942]
Hello,

I have received an email for access to the Llama-2 models but am still waiting on access through HuggingFace. This is my mistake, I believe I submitted the request on HuggingFace prior to submitting on the Meta website; is there a way to gain access on HF? My email is rosiezhao@g.harvard.edu. Sorry for the inconvenience, I appreciate the help!

<img width="906" alt="Screenshot 2023-11-28 at 2 21 07 AM" src="https://github.com/facebookresearch/llama/assets/43302868/34cb6347-d408-434a-a670-7e88a829bcc9">

**Comment by tranlm** [comment]
Apologies. I did the same thing (accidentally filled out the form before getting approved). Is it possible to add my account as well? It’s link.m.tran@gmail.com

thanks!
