### ISSUE TITLE
download.sh not working

### ISSUE THREAD

**Issue by qsimeon** [facebookresearch/llama#95]
```
(pytorch) user@computer llama % bash download.sh       
download.sh: line 8: declare: -A: invalid option
declare: usage: declare [-afFirtx] [-p] [name[=value] ...]
download.sh: line 10: 7B: value too great for base (error token is "7B")
download.sh: line 11: 13B: value too great for base (error token is "13B")
download.sh: line 12: 30B: value too great for base (error token is "30B")
download.sh: line 13: 65B: value too great for base (error token is "65B")
Downloading tokenizer
download.sh: line 16: wget: command not found
download.sh: line 17: wget: command not found
parseopts.c:76: setup_check: fopen 'tokenizer_checklist.chk': No such file or directory
Downloading 7BB
download.sh: line 21: 7B: value too great for base (error token is "7B")
download.sh: line 30: wget: command not found
download.sh: line 31: wget: command not found
Checking checksums
parseopts.c:76: setup_check: fopen 'checklist.chk': No such file or directory
```

`pytorch` is a conda environment I created with Pytorch installed. `wget` is installed.

Below is the content of my download.sh, with my PRESIGNED_URL redacted:
```
# Copyright (c) Meta Platforms, Inc. and affiliates.
# This software may be used and distributed according to the terms of the GNU General Public License version 3.

PRESIGNED_URL=""             # replace with presigned url from email
MODEL_SIZE="7B"  # edit this list with the model sizes you wish to download
TARGET_FOLDER="download"             # where all files should end up

declare -A N_SHARD_DICT

N_SHARD_DICT["7B"]="0"
N_SHARD_DICT["13B"]="1"
N_SHARD_DICT["30B"]="3"
N_SHARD_DICT["65B"]="7"

echo "Downloading tokenizer"
wget ${PRESIGNED_URL/'*'/"tokenizer.model"} -O ${TARGET_FOLDER}"/tokenizer.model"
wget ${PRESIGNED_URL/'*'/"tokenizer_checklist.chk"} -O ${TARGET_FOLDER}"/tokenizer_checklist.chk"

(cd ${TARGET_FOLDER} && md5sum -c tokenizer_checklist.chk)

for i in ${MODEL_SIZE//,/ }
do
    echo "Downloading ${i}B"
    mkdir -p ${TARGET_FOLDER}"/${i}B"
    for s in $(seq -f "0%g" 0 ${N_SHARD_DICT[$i]})
    do
        echo "Downloading shard ${s}B"
        wget ${PRESIGNED_URL/'*'/"${i}B/consolidated.${s}.pth"} -O ${TARGET_FOLDER}"/${i}B/consolidated.${s}.pth"
    done
    wget ${PRESIGNED_URL/'*'/"${i}B/params.json"} -O ${TARGET_FOLDER}"/${i}B/params.json"
    wget ${PRESIGNED_URL/'*'/"${i}B/checklist.chk"} -O ${TARGET_FOLDER}"/${i}B/checklist.chk"
    echo "Checking checksums"
    (cd ${TARGET_FOLDER}"/${i}B" && md5sum -c checklist.chk)
done
```

**Comment by soheilAppear** [comment]
First, you need to get your unique URL to download these files and second you need to provide the destination file to download pre-trained models .pth files

**Comment by qsimeon** [comment]
@soheilAppear yes I have both of those, please see my updated Issue.

**Comment by qsimeon** [comment]
Below are some of the errors from my Terminal output after trying to run the example from the README ```torchrun --nproc_per_node 1 example.py --ckpt_dir "download/model_size" --tokenizer_path "download/tokenizer.model"```

```
RuntimeError: Distributed package doesn't have NCCL built in
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 0 (pid: 35752) of binary: 
...
...
line 246, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
example.py FAILED
------------------------------------------------------------
Failures:
  <NO_OTHER_FAILURES>
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2023-03-03_19:12:57
  host      : computer.tld
  rank      : 0 (local_rank: 0)
  exitcode  : 1 (pid: 35752)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================
```

**Comment by soheilAppear** [comment]
Apparently, this is only working on Linux. make sure to use that only.

**Comment by qsimeon** [comment]
> You'll need to run this in the right terminal type. This script is meant for bash.
> 
> What OS are you on?

I'm on MacOS Monterey

This is what I get when I switch to the bash mode my Terminal. 
```
bash-3.2$ bash download.sh
Downloading tokenizer
download.sh: line 16: wget: command not found
download.sh: line 17: wget: command not found
parseopts.c:76: setup_check: fopen 'tokenizer_checklist.chk': No such file or directory
Downloading 7B
Downloading shard 01B
download.sh: line 28: wget: command not found
Downloading shard 00B
download.sh: line 28: wget: command not found
download.sh: line 30: wget: command not found
download.sh: line 31: wget: command not found
Checking checksums
parseopts.c:76: setup_check: fopen 'checklist.chk': No such file or directory
```

**Comment by qsimeon** [comment]
> Apparently, this is only working on Linux. make sure to use that only.

I don't think that's true. I have seen other issues (different problem) where people were able to download on Mac.

**Comment by rpforrest1** [comment]
The readme has an FAQ section now. I was ultimately able to download on mac after modifying the download.sh file.

**Comment by qsimeon** [comment]
> The readme has an FAQ section now. I was ultimately able to download on mac after modifying the download.sh file.

Can you share here what modifications you made? I have seen the FAQ and done almost everything on there but perhaps I am doing something wrong.

**Comment by rpforrest1** [comment]
> 

You need to remove all the "B" characters here:
N_SHARD_DICT["7B"]="0"
N_SHARD_DICT["13B"]="1"
N_SHARD_DICT["30B"]="3"
N_SHARD_DICT["65B"]="7"

Since you have this error "wget: command not found" you may not have wget? You could try to use wget alone without using a script. Maybe just try typing this in the terminal: `wget --spider www.google.com`

**Comment by qsimeon** [comment]
> > 
> 
> You need to remove all the "B" characters here: MODEL_SIZE="7B"
> 
> N_SHARD_DICT["7B"]="0" N_SHARD_DICT["13B"]="1" N_SHARD_DICT["30B"]="3" N_SHARD_DICT["65B"]="7"
> 
> There were some other modifications after that, but overall just copy the download.sh file from this comment: [#41 (comment)](https://github.com/facebookresearch/llama/issues/41#issuecomment-1451290160)
> 
> Since you have this error "wget: command not found" you may not have wget? You could try to use wget alone without using a script. Maybe just try typing this in the terminal: `wget --spider www.google.com`

This looks like it worked (currently downloading @ 2%)! Thank you!

**Comment by zhongtao93** [comment]
I found download failed for 65B params.json, anyone can kindly provide it.
Thank you very much!!!

**Comment by abalhomaid** [comment]
I added #!/bin/bash at the first line and chmod +x download.sh for it to work. Also, make sure your shell window can call wget command

**Comment by awelshds** [comment]
In case anyone is trying to do this on Windows without using WSL, I had to modify the download.sh to remove the two calls to md5sums to get it to work. Theoretically, you could also download md5sums from pc-tools, save the exe in the clone repo directory, and add a ./ in front of the md5sums call in the script, or go through the bother of adding it to the path so gitbash or whatever bash program you're using can call md5sums.

**Comment by anilraj1980** [comment]
I am unbale get proper output from download.sh. I got below error "Downloading tokenizer
--2023-10-04 12:24:18--  https://download2.llamameta.net/tokenizer.model?Policy=eyJTdGF0ZW1lbnQiOlt7InVuaXF1ZV9oYXNoIjoiaWxsa3RtcmZucW40ejRndjNjeGp2c3o5IiwiUmVzb3VyY2UiOiJodHRwczpcL1wvZG93bmxvYWQyLmxsYW1hbWV0YS5uZXRcLyoiLCJDb25kaXRpb24iOnsiRGF0ZUxlc3NUaGFuIjp7IkFXUzpFcG9jaFRpbWUiOjE2OTY0MTQ1OTV9fX1dfQ__&Signature=Ns5b9pgkK5uAlWqYxQYxjTj%7EPrXYYQQljhUwC7s3gctn1lTBSsPHPalnu5YxOQIqjFn2aGA1%7Ed5-ecHeHtgFa5p2Ba5FDEVaN6QTIyGmjqeTei-oCTaPRtqRVH-9%7EZaWxEQFWbTwO-0bmXBK5kCm9JCOfhnSzMQXAZHqscnXQuefHIEF9WB4wqHi3XfQ68a2axfU5TIa2DY3ko8W7TFISEyCSm8E1Ijt5SwnVclwDCFAsqQqUO1gu7ZBpWXfj7KBARn3EM9LUN-oGUzXxItVtf77ES-ERxclov7j8F1pcXhrLybLu7dTKBT7uXuEM%7EKpWWkj7pM6N%7EgvN5ik8zoIeA__&Key-Pair-Id=K15QRJLYKIFSLZ&Download-Request-ID=836982628430044
Resolving download2.llamameta.net (download2.llamameta.net)... 13.225.78.5, 13.225.78.2, 13.225.78.16, ...
Connecting to download2.llamameta.net (download2.llamameta.net)|13.225.78.5|:443... connected.
HTTP request sent, awaiting response... 403 Forbidden
2023-10-04 12:24:19 ERROR 403: Forbidden." 

wget is also good, Can anyone suggest me. anilkumar@LAPTOP-4VOO0U1G:~$ wget --spider www.google.com
Spider mode enabled. Check if remote file exists.
--2023-10-04 12:24:57--  http://www.google.com/
Resolving www.google.com (www.google.com)... 216.58.206.36, 2a00:1450:4001:81c::2004
Connecting to www.google.com (www.google.com)|216.58.206.36|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Remote file exists and could contain further links,
but recursion is disabled -- not retrieving.

anilkumar@LAPTOP-4VOO0U1G:~$
