### ISSUE TITLE
training loss curve of llama 1 and 2

### ISSUE THREAD

**Issue by bpwl0121** [facebookresearch/llama#950]
thanks for your awesome work！
I have a question about the training curve of llama 1 and 2.
in the training of llama 1, some loss spikes ocurred, but it is not the case for llama2.
why did these spikes occur? because of datasets?
![image](https://github.com/facebookresearch/llama/assets/38959389/a1826cf4-2d08-4d55-b344-4bd2d07f8292)
![image](https://github.com/facebookresearch/llama/assets/38959389/a0f78c63-31a2-4cac-b2ea-8658d247191f)

**Comment by subramen** [comment]
Closing this issue, please reopen if you need to follow-up
