### ISSUE TITLE
Embed size disparity

### ISSUE THREAD

**Issue by EdwinMeriaux** [facebookresearch/llama#951]
Hello,

I have been passing texts into llama2 7B to embed them and then use that data for a different DRL algorithm. 

I am trying to figure out what the different values of the embed tensors are?

for example if i just pass a prompt of "h" for the 7B model in user mode:

{"role": "user", "content": "h"}

I then get a tensor of this size in model.py forward function of the transformer class :

h = self.tok_embeddings(tokens)
h.shape = torch.Size([1, 9, 4096])

What are the different values in the tensor? 
Is the second value (9 in this case) variable based on the size of the tokens?

**Comment by subramen** [comment]
Yes, 9 refers to the sequence length aka number of tokens forming the prompt. You can see how your prompt is turned into tokens here : https://github.com/facebookresearch/llama/blob/ef351e9cd9496c579bf9f2bb036ef11bdc5ca3d2/llama/generation.py#L320

**Comment by EdwinMeriaux** [comment]
@subramen Perfect thank you! 

How does the model take inputs of different sizes? This would be an issue right?
