### ISSUE TITLE
Cuda OutOfMemoryError [Nvidia GeForce GTX 1080 Ti (11 GB )+ 24GB Ram] 

### ISSUE THREAD

**Issue by jaykeerti** [facebookresearch/llama#954]
I am trying to run the llama-2-7b out of the box with the following command
```torchrun --nproc_per_node 1 example_text_completion.py --ckpt_dir llama-2-7b/ --tokenizer_path tokenizer.model --max_seq_len 128 --max_batch_size 1```

```
torch.cuda.OutOfMemoryError: CUDA out of memory. Tried to allocate 86.00 MiB. GPU 0 has a total capacty of 4.00 GiB of which 0 bytes is free. Of the allocated memory 3.49 GiB is allocated by PyTorch, and 1.88 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting max_split_size_mb to avoid fragmentation.  See documentation for Memory Management and PYTORCH_CUDA_ALLOC_CONF
[2023-12-07 22:47:46,411] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: 1) local_rank: 0 (pid: 6760) of binary: C:\<path_to_python>
```

## Runtime Environment
- Model: llama-2-7b
- Using via huggingface?: no
- OS: Windows
- GPU VRAM: 11 GB
- Number of GPUs: 1 
- GPU Make: Nvidia
- RAM: 24GB

Disclaimer: I am an application engineer and not much into data science :-)
just wanted to ask following questions

1. is it really possible to run the pyTorch model with these specs above? or going to a quantized model is better?
2. Why can't I increase the CUDA memory to use complete GPU (11Gb in my case, but it only allocates 4GB as per error)

PS: i have changed the following nccl -> gloo based on some recommendations to make it work till here
```
 if not torch.distributed.is_initialized():
    torch.distributed.init_process_group("nccl") 
```

**Comment by subramen** [comment]
You need around 14GB GPU VRAM to run the 7B model. I suggest you check out quantized models like llama.cpp that can run with smaller GPU VRAM requirements.

**Comment by Jaswir** [comment]
@subramen How is one supposed to use quantized models like llama.cpp. I see TheBloke has quantized versions for llama-2 models like: https://huggingface.co/TheBloke/Llama-2-7B-Chat-GPTQ

Or quantize it yourself?

**Comment by jaykeerti** [comment]
@Jaswir i think you can directly use models from bloke

**Comment by subramen** [comment]
@jaswir Using llama.cpp: https://github.com/ggerganov/llama.cpp?tab=readme-ov-file#usage
And yeah, like @jaykeerti  says the GPTQ models should work with the HF API. 

Closing this thread, please open a new one for separate queries!
