### ISSUE TITLE
SafetensorError: Error while deserializing header: HeaderTooLarge  

### ISSUE THREAD

**Issue by KyrieCui** [facebookresearch/llama#959]
## Describe the bug
I tried to load llama-2-70b-chat-hf with transformers, but I got an error: SafetensorError: Error while deserializing header: HeaderTooLarge

### Below is the code to execute

```python
base_model = '/llm/llama-2-70b-chat-hf'
model = AutoModelForCausalLM.from_pretrained(
    base_model,
    load_8_bit = True,
    device_map = {"":0},
    use_safetensors = True
)


```

### Output
Some error msg below

```
in load_state_dict (checkpoint_file)
      462 """
      463 Reads a Pytorch checkpoint file, returning properly formatted errors if they arise.   
      464 """
      465 if checkpoint_file.endswith(".safetensors") and is_safetensors_available():
-->466     with safe_open(checkpoint_file,framework="pt") as f:
      467     metadata=f.metadate()
SafetensorError: Error while deserializing header: HeaderTooLarge    
```

## Runtime Environment
- Model: [llama-2-70b-chat-hf]
- Using via huggingface?: [yes]
- OS: [Linux/Ubuntu]
- GPU VRAM:  81 G
- Number of GPUs: 1
- GPU Make: [eg: Nvidia]

I re-downloaded the safetensors file but could not solve it. Look forward to your reply ASAP.

**Comment by subramen** [comment]
Paging @osanseviero for HF / safetensors expertise!

**Comment by osanseviero** [comment]
This was closed via https://github.com/huggingface/transformers/issues/27923
