### ISSUE TITLE
403 Permission denied only on 7B/consolidated.01.pth

### ISSUE THREAD

**Issue by paulutsch** [facebookresearch/llama#96]
<img width="1342" alt="Bildschirmfoto 2023-03-04 um 01 11 53" src="https://user-images.githubusercontent.com/76492498/222858129-c9577335-1b1b-4e26-b0bf-ac9d781b4404.png">

I get a status code 403 (Forbidden) response on trying to download the consolidated.01.pth file for the 7B model. For all other files, I get 200 (OK).

**Comment by danielraffel** [comment]
I got the same error. I think it's OK tho `checklist.chk` indicates there are only two files in that directory. Likely an unrelated issue.

**Comment by paulutsch** [comment]
> > <img alt="Bildschirmfoto 2023-03-04 um 01 11 53" width="1342" src="https://user-images.githubusercontent.com/76492498/222858129-c9577335-1b1b-4e26-b0bf-ac9d781b4404.png">
> > I get a status code 403 (Forbidden) response on trying to download the consolidated.01.pth file for the 7B model. For all other files, I get 200 (OK).
> 
> Read macOS download.sh fix in the FAQ. I think it should solve your issue.

Thanks! That did it.
