### ISSUE TITLE
Wrong pending for approval for LLama-2 message

### ISSUE THREAD

**Issue by usrikanth** [facebookresearch/llama#962]
Even though I am approved and received an email from Meta, I get the following message: **Your request to access this repo has been successfully submitted, and is pending a review from the repo's authors.**

History: The request was pending, so I went to the Meta site and re-registered. I got an immediate email. Perhaps when I registered from Hugging face, the emails were not identical. Would appreciate if you can help fix the issue.

**Comment by samuelselvan** [comment]
@usrikanth for HF access the request email should match with your HF account email.

**Comment by usrikanth** [comment]
Thanks Sam. It was approved when I used the same email.
Regards,
Srikanth

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
