### ISSUE TITLE
Able to run 70B 4Q Llama2 on MacBook -- but unexpectedly not 2Q version 

### ISSUE THREAD

**Issue by FrankSandqvist** [facebookresearch/llama#964]
## Describe the bug

I am trying to run the 70B Llama model thru Ollama on my M3 Pro macbook with 36 gb of RAM.

I'm informed that this is likely too little RAM for this model, however I am able to run the 4Q version just fine - although extremely slowly.  

So I thought I'd try the 2Q (chat) variant instead - but this version consistently fails with this output:
```
ggml_metal_init: GPU name:   Apple M3 Pro
ggml_metal_init: GPU family: MTLGPUFamilyApple9 (1009)
ggml_metal_init: hasUnifiedMemory              = true
ggml_metal_init: recommendedMaxWorkingSetSize  = 27648.00 MiB
ggml_metal_init: maxTransferRate               = built-in GPU
llama_new_context_with_model: compute buffer total size = 571.07 MiB
llama_new_context_with_model: max tensor size =   205.08 MiB
ggml_metal_add_buffer: allocated 'data            ' buffer, size = 20736.00 MiB, offs =            0
ggml_metal_add_buffer: allocated 'data            ' buffer, size =  7391.97 MiB, offs =  21528215552, (28133.67 / 27648.00)ggml_metal_add_buffer: warning: current allocated size is greater than the recommended max working set size
ggml_metal_add_buffer: allocated 'kv              ' buffer, size =  1280.02 MiB, (29413.69 / 27648.00)ggml_metal_add_buffer: warning: current allocated size is greater than the recommended max working set size
ggml_metal_add_buffer: allocated 'alloc           ' buffer, size =   568.02 MiB, (29981.70 / 27648.00)ggml_metal_add_buffer: warning: current allocated size is greater than the recommended max working set size
ggml_metal_graph_compute: command buffer 4 failed with status 5
GGML_ASSERT: /Users/jmorgan/workspace/ollama/llm/llama.cpp/gguf/ggml-metal.m:1623: false
```

Attaching the memory usage graph for both.  The 3Q version also fails. 4Q version (standard) consistently works every time (although slow as syrup)

I'm a bit of a newbie - but I thought this was interesting, and I was wondering of ways of how I could go about using the more quantized versions for faster performance. Perhaps there is an implementation issue between the standard model and the different quantization versions?

### Minimal reproducible example
Run 70B 4Q - then run 70B 2Q on a M3 Pro 36gb

### Output
Running 70B 4Q
![Screenshot 2023-12-14 at 12 12 39](https://github.com/facebookresearch/llama/assets/32358133/a861fa23-c466-4809-8c89-4984e3a02ecc)

Failing to run 70B 2Q
![Screenshot 2023-12-14 at 12 15 16](https://github.com/facebookresearch/llama/assets/32358133/b0c7a04a-04ef-41f1-8046-cd0facbf93d4)

## Runtime Environment
- Model: [eg: `llama-2-70b-chat`]
- Using via huggingface? no, ollama
- OS: Mac
- GPU VRAM: 36gb
- Number of GPUs:
- GPU Make: Apple

**Comment by FrankSandqvist** [comment]
Just noticed this in the logs, which looks a bit suspish:
`GGML_ASSERT: /Users/jmorgan/workspace/ollama/llm/llama.cpp/gguf/ggml-metal.m:1623: false`

Who is this jmorgan guy? 😄

**Comment by albertodepaola** [comment]
Hi @FrankSandqvist, thanks for the interest in Llama 2! You'll need to follow up this issue on the ollama repo, as you've done already. We currently don't support mac natively, but if you can get a linux machine with a GPU, you can use [llama-recipes](https://github.com/facebookresearch/llama-recipes) to run the hugging face version of the models quantized as well.
Feel free to open a new issue with additional questions as well!
