### ISSUE TITLE
Are meta-llama/Llama-2 models Quantized by default?

### ISSUE THREAD

**Issue by Jaswir** [facebookresearch/llama#965]
I looked for information about this here: https://huggingface.co/meta-llama/Llama-2-7b-chat-hf
But couldn't find any. 

Are meta-llama/Llama-2 models Quantized by default?

How are we supposed to use quantized models like llama.cpp. I see TheBloke has quantized versions for llama-2 models like: https://huggingface.co/TheBloke/Llama-2-7B-Chat-GPTQ

Or quantize it yourself?

**Comment by subramen** [comment]
No the code here is in fp16 precision by default

Please refer to the llama.cpp repo (https://github.com/ggerganov/llama.cpp) for usage instructions. Briefly, those models are quantized with various schemes and the llama.cpp command-line utility is used to generate responses and embeddings.
