### ISSUE TITLE
Neural Network Weights are not Copyrightable! 🥳🎉

### ISSUE THREAD

**Issue by ghost** [facebookresearch/llama#97]
Good news people. 

Neural Network Weights are not copyrightable by US law. 

`"that material from a non-human entity is not copyrightable"`

Also, since the model itself is open-source, this means that we are free to use this model and the weights for commercial purposes!

We're home free boyz.

I'm off to start my rival to Bing.

Great news.

Disclaimer - I am not a lawyer.

**Comment by BetaDoggo** [comment]
There are a lot of arguments to be made and I don't think there will be any legal consensus until it is brought before a judge. The quote you included has nothing to do with the model itself, only the things it generates. The creation of the model requires quite a lot of human effort so I think it would still qualify. 

Open-source does not equal free labor.

**Comment by Jainam213** [comment]
How do they plan to track use?
We need someone to take it to court to test the copyright

**Comment by pauldog** [comment]
> How do they plan to track use? We need someone to take it to court to test the copyright

I double dare you to do it 😎

**Comment by Jainam213** [comment]
Would do it but I'm not in the us of a since meta is based in us would be best to test there

**Comment by albertodepaola** [comment]
Thanks for the question! 

With Llama 2 available for comercial use, this has changed since it was originally posted. Feel free to open new issues with further questions or feedback as well!
