### ISSUE TITLE
How can I give different prompts in batched.cpp ?

### ISSUE THREAD

**Issue by Tr-buaa** [facebookresearch/llama#970]
Recently I have seen the example/batched.cpp which can run the llama with multiple batch, but this project only give one prompt then output different results. I want to give different prompts as input and test the multiple batch output, How can I do this?

**Comment by albertodepaola** [comment]
Hi @Tr-buaa, thanks for the interest in Llama 2! Are you referring to llama.cpp? I see a file called [batched.cpp](https://github.com/ggerganov/llama.cpp/blob/799fc2268989482054944c902874cca76337580f/examples/batched/batched.cpp) there. If that's the issue, please open an issue in that repo, thanks! If not, feel free to reopen with more context.
