### ISSUE TITLE
Time to fine-tune on 1m samples(13b)

### ISSUE THREAD

**Issue by sr5434** [facebookresearch/llama#973]
Hello! I have a chat dataset with about 1 million samples. On an H100, how long will fine-tuning llama 2 13b for one epoch take?

**Comment by subramen** [comment]
Difficult to answer this, as it depends on your sample length as well. We haven't published any benchmarks for finetuning yet, but stay tuned!

**Comment by sr5434** [comment]
My sample size is probably 5-6 hundred tokens

**Comment by subramen** [comment]
@sr5434 Closing this issue for now, but if you end up running any benchmarks, feel free to reopen the issue and share your findings!
