### ISSUE TITLE
How to use low amount of memory and high concurrent users when using LLAMA-2-7b-chat model for Inference?

### ISSUE THREAD

**Issue by harkishankhuva** [facebookresearch/llama#975]
Hello,
First I used the LLAMA-2-7b-chat with flask and gunicorn. I tried it with single worker and used F16 torch dtype. Model itself was consuming about 14GB of memory on GPU(using  NVIDIA A10G) and later for model inference it was taking about 3+GB. with that I cannot continue as It will need more memory for inference for new requests and the GPU has only 24GB.

I also have to add a system prompt in it at the time of inference only at first when user requested api first time.

Later I searched for quantized model and I used `TheBloke/llama2-7b-chat-codeCherryPop-qLoRA-AWQ` quantized model and it's taking only 4328MB on GPU, the main problem is of inference, it takes 1500MB(start of using) to 5038MB(with previous data) of memory on GPU.
When I used multiple workers the model was loaded multiple times and with `--preload`, an error raised to use spawn with start_method, so after a long google search I found a stackoverflow answer and I used it to use low memory for multiple workers and yes with `zeromq` the model loaded only once and then I was sharing with all workers, the main problem still exists the inference when requests number increases.

Do I have to limit the users for the input or is there any other configuration with that I can handle more concurrent users.

The main goal is to handle/serve large number of concurrent requests with low latency, the main use is Inference only.

**Comment by WuhanMonkey** [comment]
Hi @harkishankhuva, I would recommend you take a look at vLLM or TGI as a serving solution. These frameworks had integrated tools to serve concurrent requests with low latency and high throughput. It also provides nice features for memory management that you can configure for you situation. We have some examples [here](https://github.com/facebookresearch/llama-recipes/blob/main/demo_apps/llama-on-prem.md). AWQ is a good solution for quantization and vLLM is in progress to integrate it.
