### ISSUE TITLE
how was the base model created?

### ISSUE THREAD

**Issue by sartimo** [facebookresearch/llama#979]
hi

i am wondering myself as a ML/ai noob... how was the base model and the model files created when you pre-trained llama2-7b for example? As far as I see, this repo just contains code for inference and not for the pre-training process. can you give a short exmplaining how you created the model files initially?

Thanks and BR

Timo

**Comment by subramen** [comment]
Hi @sartimo, the methodology of creating the llama models has been shared on the research paper: https://arxiv.org/abs/2307.09288 Currently there are no plans to release pretraining code. Thanks for your interest!
