### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by minh282906** [facebookresearch/llama#983]
![Screenshot 2023-12-26 061457](https://github.com/facebookresearch/llama/assets/96937594/f1c5ae29-6eb0-4125-b1ab-8b567ff41339)

after run
torchrun --nproc_per_node 1 example_text_completion.py
--ckpt_dir llama-2-7b/
--tokenizer_path tokenizer.model
--max_seq_len 128 --max_batch_size 4

I got an error "[2023-12-26 06:14:09,399] torch.distributed.elastic.multiprocessing.api: [ERROR] failed (exitcode: -9) local_rank: 0 (pid: 963) of binary: /home/minhnguyen/anaconda3/envs/llama/bin/python" like in image

How to fix this issue

**Comment by minh282906** [comment]
anyone?

**Comment by subramen** [comment]
Your actual error would be lower in the stacktrace, please share that. 
Also, please follow the issue template and share all the details asked on it, as that will help us diagnose your problem.

**Comment by subramen** [comment]
Closing this for now, but feel free to reopen when you have more information to share
