### ISSUE TITLE
download stops when it reached to ~1.16G

### ISSUE THREAD

**Issue by garychl** [facebookresearch/llama#99]
Hi all, I tried to download the 7B version on my mac M2. Yet the download stopped when it reached to 9% (~1.16G)...What are some possible causes to this and are there any solutions...?
![image](https://user-images.githubusercontent.com/25881099/222875745-fef9e064-87e3-4d3b-b7c8-6402a2601f8b.png)
Thanks.

**Comment by pauldog** [comment]
Torrent it?

**Comment by garychl** [comment]
> Torrent it?

Thanks for your reply.
I am using VPN. Do you think it is related?

**Comment by garychl** [comment]
I tried to download it on my another computer and it works... that's strange...
Thanks for your reply @pauldog and I will close it.

**Comment by BITKarBo** [comment]
![image](https://github.com/facebookresearch/llama/assets/39126085/69261117-aafb-45c9-84bf-35d003ab01ad)
add this so it continues
