### ISSUE TITLE
which model to use for what's the root of 256256?

### ISSUE THREAD

**Issue by dcasota** [facebookresearch/llama#995]
Please, see https://github.com/jmorganca/ollama/issues/1805.
Thank you for a curated answer.

**Comment by subramen** [comment]
Models like llama aren't equipped by default to solve arithmetic operations, as they are trained on predicting next words based on the previous words. You'd likely need to train a model like llama on a massive trove of arithmetic sequences which is obviously very inefficient and still won't guarantee the model to have math expertise.

I think the closest model you can try is codellama. Use it to generate a function that returns the answer to your math question, and run that function with your inputs  OR use llama to derive the inputs and arithmetic operation from your prompt, and pass that on to a calculator API like [wolfram](https://developer.wolframalpha.com/)

**Comment by dcasota** [comment]
@subramen thank you for your answer. With respect to precision and root mean squared error, there are few llms which respect math functions by default, e.g. wizardcoder:34b-python delivers 50.199, which is good enough.
```
>>> what's the root of 256256?
The root of 256256 can be found by taking the square root of both sides of the equation:
x^2 = 256256
which gives us:
x = sqrt(256256)
= 50.199 (approximately)
Therefore, the square root of 256256 is approximately 50.19.
```
