### ISSUE TITLE
Directory incorrect for params.json

### ISSUE THREAD

**Issue by dongzizhu** [facebookresearch/llama#999]
## Describe the bug
I followed this blog to install the llama 2. https://ai.meta.com/blog/5-steps-to-getting-started-with-llama-2/
In step 2, running this code 

`python $TRANSFORM --input_dir ./llama-2-7b-chat --model_size 7B --output_dir ./llama-2-7b-chat-hf`

would return with an error

_no such file or directory: ./llama-2-7b-chat/7B/params.json'._

Apparently, there's no directory named 7B in llama-2-7b-chat. But there is indeed a params.json in llama-2-7b-chat. How do I fix this?

### Minimal reproducible example
Just follow the blog step by step.

Thanks in advance!

**Comment by fbnav** [comment]
Hi @dongzizhu, what version of transformers library are you using? You can check your version using `python -c "import transformers; print(transformers.__version__)"`. Could you please try to update the version to the latest and re-try?

**Comment by dongzizhu** [comment]
Sorry, I already deleted the conda environment since it was not working. But I found the HF version of llama weight somewhere else and it is working. So everything is good now. Thanks!
